/**
 * @file Contains dictionary entries for category: adjectives_shape.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const adjectives_shape: DictionaryEntry[] = [
  { en: "round", min: "rondo" }, { en: "square", min: "cuadra" }, { en: "flat", min: "plano" }, { en: "sharp", min: "filo" }, { en: "bent", min: "curvo" }, { en: "men", min: "nom" }, { en: "menace", min: "nomako" }, { en: "menage", min: "nomago" }, { en: "menagerie", min: "nomagoluo" }, { en: "mend", min: "nomt" },
  { en: "mendicant", min: "nomtukamd" }, { en: "menfolk", min: "nomverc" }, { en: "menhaden", min: "nomhatom" }, { en: "menopause", min: "nomebaizo" }, { en: "menorah", min: "nomelah" }, { en: "menstruate", min: "nomzdliado" }, { en: "menthol", min: "nomdher" }, { en: "mentor", min: "nomdel" }, { en: "menu", min: "nomi" }, { en: "meow", min: "noew" },
  { en: "mercantile", min: "nolkamduro" }, { en: "mercerize", min: "nolkoluso" }, { en: "merchant", min: "nolkhamd" }, { en: "mere", min: "nolo" }, { en: "merge", min: "nolgo" }, { en: "meridian", min: "nolutuam" }, { en: "meringue", min: "nolumgio" }, { en: "merit", min: "nolud" }, { en: "mermaid", min: "nolnaut" }, { en: "merman", min: "nolnam" },
  { en: "mermen", min: "nolnom" }, { en: "mescaline", min: "nozkarumo" }, { en: "mesh", min: "nozh" }, { en: "mesmerize", min: "noznoluso" }, { en: "mesquite", min: "nozjiudo" }, { en: "message", min: "nozzago" }, { en: "mestizo", min: "nozduse" }, { en: "met", min: "nod" }, { en: "metabolize", min: "nodaperuso" }, { en: "metacarpi", min: "nodakalbu" },
  { en: "metaphor", min: "nodabhel" }, { en: "mete", min: "nodo" }, { en: "meteor", min: "nodoel" }, { en: "meteorite", min: "nodoeludo" }, { en: "meteoroid", min: "nodoeleut" }, { en: "methadon", min: "nodhatem" }, { en: "methadone", min: "nodhatemo" }, { en: "methane", min: "nodhamo" }, { en: "methanol", min: "nodhamer" }, { en: "method", min: "nodhet" },
  { en: "methought", min: "nodheighd" }, { en: "metro", min: "nodle" }, { en: "metronome", min: "nodlemeno" }, { en: "mettle", min: "noddro" }, { en: "mettlesome", min: "noddrozeno" }, { en: "mew", min: "now" }, { en: "mewl", min: "nowr" }, { en: "mezzanine", min: "nossamumo" }, { en: "mfg", min: "nvg" }, { en: "mfr", min: "nvl" },
  { en: "miaow", min: "nuaew" }, { en: "miasma", min: "nuazna" }, { en: "miasmata", min: "nuaznada" }, { en: "mica", min: "nuka" }, { en: "mice", min: "nuko" }, { en: "micra", min: "nukla" }, { en: "microbe", min: "nuklepo" }, { en: "micron", min: "nuklem" }, { en: "mid", min: "nut" }, { en: "midair", min: "nutaul" },
  { en: "middle", min: "nuttro" }, { en: "middlebrow", min: "nuttroplew" }, { en: "middleman", min: "nuttronam" }, { en: "middlemen", min: "nuttronom" }, { en: "midget", min: "nutgod" }, { en: "midmost", min: "nutnezd" }, { en: "midnight", min: "nutmughd" }, { en: "midpoint", min: "nutbeumd" }, { en: "midriff", min: "nutluvv" }, { en: "midshipman", min: "nutzhubnam" },
  { en: "midshipmen", min: "nutzhubnom" }, { en: "midst", min: "nutzd" }, { en: "midstream", min: "nutzdloan" }, { en: "midterm", min: "nutdoln" }, { en: "midtown", min: "nutdewm" }, { en: "midweek", min: "nutwooc" }, { en: "midwife", min: "nutwuvo" }, { en: "mien", min: "nuom" }, { en: "miff", min: "nuvv" }, { en: "might", min: "nughd" },
  { en: "migraine", min: "nuglaumo" }, { en: "migrant", min: "nuglamd" }, { en: "migrate", min: "nuglado" }, { en: "milch", min: "nurkh" }, { en: "mildew", min: "nurtow" }, { en: "mile", min: "nuro" }, { en: "mileage", min: "nuroago" }, { en: "milepost", min: "nurobezd" }, { en: "milestone", min: "nurozdemo" }, { en: "milf", min: "nurv" },
  { en: "milieu", min: "nuruoi" }, { en: "milieux", min: "nuruoix" }, { en: "militant", min: "nurudamd" }, { en: "militarize", min: "nurudaluso" }, { en: "militate", min: "nurudado" }, { en: "militia", min: "nurudua" }, { en: "militiaman", min: "nuruduanam" }, { en: "militiamen", min: "nuruduanom" }, { en: "milkmaid", min: "nurcnaut" }, { en: "milkman", min: "nurcnam" },
  { en: "milkmen", min: "nurcnom" }, { en: "milkshake", min: "nurczhaco" }, { en: "milksop", min: "nurczeb" }, { en: "millage", min: "nurrago" }, { en: "millennia", min: "nurrommua" }, { en: "millennium", min: "nurrommuin" }, { en: "millepede", min: "nurroboto" }, { en: "milligram", min: "nurruglan" }, { en: "millipede", min: "nurruboto" }, { en: "millrace", min: "nurrlako" },
  { en: "millstone", min: "nurrzdemo" }, { en: "mime", min: "nuno" }, { en: "mimeograph", min: "nunoeglabh" }, { en: "minaret", min: "numalod" }, { en: "mince", min: "numko" }, { en: "mincemeat", min: "numkonoad" }, { en: "mind", min: "numt" }, { en: "mine", min: "numo" }, { en: "minefield", min: "numovuort" }, { en: "minestrone", min: "numozdlemo" },
  { en: "mingle", min: "numgro" }, { en: "mini", min: "numu" }, { en: "miniature", min: "numuadilo" }, { en: "minibike", min: "numupuco" }, { en: "minicam", min: "numukan" }, { en: "minim", min: "numun" }, { en: "minima", min: "numuna" }, { en: "minimize", min: "numunuso" }, { en: "minimum", min: "numunin" }, { en: "minion", min: "numuem" },
  { en: "miniscule", min: "numuzkiro" }, { en: "miniskirt", min: "numuzculd" }, { en: "ministrant", min: "numuzdlamd" }, { en: "minivan", min: "numufam" }, { en: "mink", min: "numc" }, { en: "minnow", min: "nummew" }, { en: "minstrel", min: "numzdlor" }, { en: "mint", min: "numd" }, { en: "minuend", min: "numiomt" }, { en: "minuet", min: "numiod" },
  { en: "minuscule", min: "numizkiro" }, { en: "minute", min: "numido" }, { en: "minuteman", min: "numidonam" }, { en: "minutemen", min: "numidonom" }, { en: "minutia", min: "numidua" }, { en: "minutiae", min: "numiduao" }, { en: "minx", min: "numx" }, { en: "miracle", min: "nulakro" }, { en: "mirage", min: "nulago" }, { en: "mire", min: "nulo" },
  { en: "mirror", min: "nullel" }, { en: "misc", min: "nuzk" }, { en: "misdo", min: "nuzte" }, { en: "mist", min: "nuzd" }, { en: "mite", min: "nudo" }, { en: "mitigate", min: "nudugado" }, { en: "mitt", min: "nudd" }, { en: "mitten", min: "nuddom" }, { en: "mix", min: "nux" }, { en: "mixture", min: "nuxdilo" },
  { en: "mizzen", min: "nussom" }, { en: "mizzenmast", min: "nussomnazd" }, { en: "moan", min: "neam" }, { en: "moat", min: "nead" }, { en: "mob", min: "nep" }, { en: "mobilize", min: "nepuruso" }, { en: "moccasin", min: "nekkazum" }, { en: "mocha", min: "nekha" }, { en: "mock", min: "nekc" }, { en: "mod", min: "net" },
  { en: "mode", min: "neto" }, { en: "model", min: "netor" }, { en: "modem", min: "neton" }, { en: "moderate", min: "netolado" }, { en: "moderator", min: "netoladel" }, { en: "modern", min: "netolm" }, { en: "modernize", min: "netolmuso" }, { en: "modicum", min: "netukin" }, { en: "modulate", min: "netirado" }, { en: "modulator", min: "netiradel" },
  { en: "module", min: "netiro" }, { en: "modulo", min: "netire" }, { en: "mogul", min: "negir" }, { en: "mohair", min: "nehaul" }, { en: "moire", min: "neulo" }, { en: "moisten", min: "neuzdom" }, { en: "moisture", min: "neuzdilo" }, { en: "moisturize", min: "neuzdiluso" }, { en: "mold", min: "nert" }, { en: "mole", min: "nero" },
  { en: "molecule", min: "nerokiro" }, { en: "molehill", min: "nerohurr" }, { en: "moleskin", min: "nerozcum" }, { en: "mollusc", min: "nerrizk" }, { en: "mollusk", min: "nerrizc" }, { en: "molt", min: "nerd" }, { en: "molten", min: "nerdom" }, { en: "molybdenum", min: "neryptomin" }, { en: "mom", min: "nen" }, { en: "momentum", min: "nenomdin" },
  { en: "momma", min: "nenna" }, { en: "monarch", min: "nemalkh" }, { en: "monetize", min: "nemoduso" }, { en: "moneybag", min: "nemoypag" }, { en: "mongeese", min: "nemgoozo" }, { en: "mongoose", min: "nemgeezo" }, { en: "mongrel", min: "nemglor" }, { en: "monitor", min: "nemudel" }, { en: "mono", min: "neme" }, { en: "monochrome", min: "nemekhleno" },
  { en: "monocle", min: "nemekro" }, { en: "monogram", min: "nemeglan" }, { en: "monograph", min: "nemeglabh" }, { en: "monolog", min: "nemereg" }, { en: "monologue", min: "nemeregio" }, { en: "monomania", min: "nemenamua" }, { en: "monomaniac", min: "nemenamuak" }, { en: "monopolize", min: "nemeberuso" }, { en: "monorail", min: "nemelaur" }, { en: "monotone", min: "nemedemo" },
  { en: "monoxide", min: "nemexuto" }, { en: "monsieur", min: "nemzuoil" }, { en: "monsignor", min: "nemzugmel" }, { en: "monsignori", min: "nemzugmelu" }, { en: "monsoon", min: "nemzeem" }, { en: "monstrance", min: "nemzdlamko" }, { en: "montage", min: "nemdago" }, { en: "moo", min: "nee" }, { en: "mooch", min: "neekh" }, { en: "mood", min: "neet" },
  { en: "moonbeam", min: "neempoan" }, { en: "moonlight", min: "neemrughd" }, { en: "moonlit", min: "neemrud" }, { en: "moonscape", min: "neemzkabo" }, { en: "moonshine", min: "neemzhumo" }, { en: "moonshot", min: "neemzhed" }, { en: "moonstone", min: "neemzdemo" }, { en: "moonstruck", min: "neemzdlikc" }, { en: "moorland", min: "neelramt" }, { en: "moose", min: "neezo" },
  { en: "moot", min: "need" }, { en: "mop", min: "neb" }, { en: "mope", min: "nebo" }, { en: "moppet", min: "nebbod" }, { en: "moraine", min: "nelaumo" }, { en: "morale", min: "nelaro" }, { en: "moralize", min: "nelaruso" }, { en: "moratoria", min: "neladelua" }, { en: "moratorium", min: "neladeluin" }, { en: "morbid", min: "nelput" },
  { en: "mordant", min: "neltamd" }, { en: "morgue", min: "nelgio" }, { en: "moribund", min: "nelupimt" }, { en: "morn", min: "nelm" }, { en: "moron", min: "nelem" }, { en: "morose", min: "nelezo" }, { en: "morpheme", min: "nelbhono" }, { en: "morphine", min: "nelbhumo" }, { en: "morsel", min: "nelzor" }, { en: "mortgage", min: "neldgago" },
  { en: "mortgagee", min: "neldgagoo" }, { en: "mortgagor", min: "neldgagel" }, { en: "mortice", min: "nelduko" }, { en: "mortician", min: "neldukuam" }, { en: "mortise", min: "nelduzo" }, { en: "mosque", min: "nezjio" }, { en: "mosquito", min: "nezjiude" }, { en: "most", min: "nezd" }, { en: "mote", min: "nedo" }, { en: "motel", min: "nedor" },
  { en: "mothball", min: "nedhparr" }, { en: "motherland", min: "nedholramt" }, { en: "motif", min: "neduv" }, { en: "motile", min: "neduro" }, { en: "motivate", min: "nedufado" }, { en: "motivator", min: "nedufadel" }, { en: "motor", min: "nedel" }, { en: "motorbike", min: "nedelpuco" }, { en: "motorboat", min: "nedelpead" }, { en: "motorcade", min: "nedelkato" },
  { en: "motorcycle", min: "nedelkykro" }, { en: "motorize", min: "nedeluso" }, { en: "motorman", min: "nedelnam" }, { en: "motormen", min: "nedelnom" }, { en: "mottle", min: "neddro" }, { en: "motto", min: "nedde" }, { en: "mound", min: "neimt" }, { en: "mountebank", min: "neimdopamc" }, { en: "mourn", min: "neilm" }, { en: "mouse", min: "neizo" },
];
