/**
 * @file Contains dictionary entries for category: adjectives_speed.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const adjectives_speed: DictionaryEntry[] = [
  { en: "fast", min: "rapido" }, { en: "slow", min: "lento" }, { en: "quick", min: "veloz" }, { en: "rapid", min: "pronto" }, { en: "steady", min: "firme" }, { en: "padlock", min: "batrekc" }, { en: "padre", min: "batlo" }, { en: "paean", min: "baoam" }, { en: "pagan", min: "bagam" }, { en: "pageant", min: "bagoamd" },
  { en: "paginate", min: "bagumado" }, { en: "pagoda", min: "bageta" }, { en: "paid", min: "baut" }, { en: "pail", min: "baur" }, { en: "pain", min: "baum" }, { en: "paint", min: "baumd" }, { en: "paintbrush", min: "baumdplizh" }, { en: "paintwork", min: "baumdwelc" }, { en: "pair", min: "baul" }, { en: "pal", min: "bar" },
  { en: "palace", min: "barako" }, { en: "palate", min: "barado" }, { en: "palazzi", min: "barassu" }, { en: "palazzo", min: "barasse" }, { en: "pale", min: "baro" }, { en: "paleface", min: "barovako" }, { en: "palette", min: "baroddo" }, { en: "palindrome", min: "barumtleno" }, { en: "palisade", min: "baruzato" }, { en: "pall", min: "barr" },
  { en: "palladium", min: "barratuin" }, { en: "pallet", min: "barrod" }, { en: "palliate", min: "barruado" }, { en: "pallid", min: "barrut" }, { en: "pallor", min: "barrel" }, { en: "palm", min: "barn" }, { en: "palmetto", min: "barnodde" }, { en: "palomino", min: "barenume" }, { en: "palpate", min: "barbado" }, { en: "palpitate", min: "barbudado" },
  { en: "pamphlet", min: "banbhrod" }, { en: "panacea", min: "bamakoa" }, { en: "panache", min: "bamakho" }, { en: "pancake", min: "bamkaco" }, { en: "panda", min: "bamta" }, { en: "pane", min: "bamo" }, { en: "panel", min: "bamor" }, { en: "pang", min: "bamg" }, { en: "panhandle", min: "bamhamtro" }, { en: "panorama", min: "bamelana" },
  { en: "pant", min: "bamd" }, { en: "pantie", min: "bamduo" }, { en: "pantomime", min: "bamdenuno" }, { en: "pantsuit", min: "bamdziud" }, { en: "pantyhose", min: "bamdyhezo" }, { en: "pap", min: "bab" }, { en: "papa", min: "baba" }, { en: "papaw", min: "babaw" }, { en: "papaya", min: "babaya" }, { en: "paperback", min: "babolpakc" },
  { en: "papergirl", min: "babolgulr" }, { en: "paperwork", min: "babolwelc" }, { en: "papilla", min: "baburra" }, { en: "papillae", min: "baburrao" }, { en: "papoose", min: "babeezo" }, { en: "paprika", min: "babluca" }, { en: "papyri", min: "babylu" }, { en: "par", min: "bal" }, { en: "parabola", min: "balapera" }, { en: "parachute", min: "balakhido" },
  { en: "parade", min: "balato" }, { en: "paradigm", min: "balatugn" }, { en: "paradox", min: "balatex" }, { en: "paraffin", min: "balavvum" }, { en: "paragon", min: "balagem" }, { en: "paragraph", min: "balaglabh" }, { en: "parakeet", min: "balacood" }, { en: "parallax", min: "balarrax" }, { en: "parallel", min: "balarror" }, { en: "paralyze", min: "balaryso" },
  { en: "paramecia", min: "balanokua" }, { en: "paramecium", min: "balanokuin" }, { en: "paramour", min: "balaneil" }, { en: "paranoia", min: "balameua" }, { en: "paranoid", min: "balameut" }, { en: "parapet", min: "balabod" }, { en: "paraphrase", min: "balabhlazo" }, { en: "paraplegia", min: "balabrogua" }, { en: "parasite", min: "balazudo" }, { en: "parasol", min: "balazer" },
  { en: "parboil", min: "balpeur" }, { en: "parcel", min: "balkor" }, { en: "parch", min: "balkh" }, { en: "pardon", min: "baltem" }, { en: "pare", min: "balo" }, { en: "parent", min: "balomd" }, { en: "parentage", min: "balomdago" }, { en: "parfait", min: "balvaud" }, { en: "pariah", min: "baluah" }, { en: "parka", min: "balca" },
  { en: "parkour", min: "balceil" }, { en: "parlance", min: "balramko" }, { en: "parlor", min: "balrel" }, { en: "parole", min: "balero" }, { en: "parolee", min: "baleroo" }, { en: "paroxysm", min: "balexyzn" }, { en: "parquet", min: "baljiod" }, { en: "parrakeet", min: "ballacood" }, { en: "parricide", min: "ballukuto" }, { en: "parrot", min: "balled" },
  { en: "parse", min: "balzo" }, { en: "parsec", min: "balzok" }, { en: "parsnip", min: "balzmub" }, { en: "parson", min: "balzem" }, { en: "parsonage", min: "balzemago" }, { en: "part", min: "bald" }, { en: "partake", min: "baldaco" }, { en: "partaken", min: "baldacom" }, { en: "parterre", min: "baldollo" }, { en: "participle", min: "baldukubro" },
  { en: "particle", min: "baldukro" }, { en: "partisan", min: "balduzam" }, { en: "partizan", min: "baldusam" }, { en: "partook", min: "baldeec" }, { en: "partridge", min: "baldlutgo" }, { en: "parvenu", min: "balfomi" }, { en: "pasha", min: "bazha" }, { en: "passage", min: "bazzago" }, { en: "passbook", min: "bazzpeec" }, { en: "passel", min: "bazzor" },
  { en: "passionate", min: "bazzuemado" }, { en: "passport", min: "bazzbeld" }, { en: "password", min: "bazzwelt" }, { en: "past", min: "bazd" }, { en: "pasta", min: "bazda" }, { en: "paste", min: "bazdo" }, { en: "pasteboard", min: "bazdopealt" }, { en: "pastel", min: "bazdor" }, { en: "pastern", min: "bazdolm" }, { en: "pasteurize", min: "bazdoiluso" },
  { en: "pastiche", min: "bazdukho" }, { en: "pastie", min: "bazduo" }, { en: "pastime", min: "bazduno" }, { en: "pastor", min: "bazdel" }, { en: "pastorate", min: "bazdelado" }, { en: "pastrami", min: "bazdlanu" }, { en: "pasturage", min: "bazdilago" }, { en: "pasture", min: "bazdilo" }, { en: "patch", min: "badkh" }, { en: "patchwork", min: "badkhwelc" },
  { en: "patella", min: "badorra" }, { en: "patellae", min: "badorrao" }, { en: "patent", min: "badomd" }, { en: "pathogen", min: "badhegom" }, { en: "patient", min: "baduomd" }, { en: "patina", min: "baduma" }, { en: "patinae", min: "badumao" }, { en: "patine", min: "badumo" }, { en: "patio", min: "badue" }, { en: "patriarch", min: "badlualkh" },
  { en: "patrician", min: "badlukuam" }, { en: "patricide", min: "badlukuto" }, { en: "patriot", min: "badlued" }, { en: "patrol", min: "badler" }, { en: "patrolman", min: "badlernam" }, { en: "patrolmen", min: "badlernom" }, { en: "patron", min: "badlem" }, { en: "patronage", min: "badlemago" }, { en: "patronize", min: "badlemuso" }, { en: "pattern", min: "baddolm" },
  { en: "paunch", min: "baimkh" }, { en: "pauperize", min: "baiboluso" }, { en: "pause", min: "baizo" }, { en: "pave", min: "bafo" }, { en: "pavilion", min: "bafuruem" }, { en: "paw", min: "baw" }, { en: "pawl", min: "bawr" }, { en: "pawn", min: "bawm" }, { en: "pawnshop", min: "bawmzheb" }, { en: "pawpaw", min: "bawbaw" },
  { en: "paycheck", min: "baykhokc" }, { en: "payee", min: "bayoo" }, { en: "payload", min: "bayreat" }, { en: "payoff", min: "bayevv" }, { en: "payroll", min: "baylerr" }, { en: "paywall", min: "baywarr" }, { en: "payware", min: "baywalo" }, { en: "pct", min: "bkd" }, { en: "pea", min: "boa" }, { en: "peacetime", min: "boakoduno" },
  { en: "peach", min: "boakh" }, { en: "peacock", min: "boakekc" }, { en: "peafowl", min: "boavewr" }, { en: "peahen", min: "boahom" }, { en: "peak", min: "boac" }, { en: "peanut", min: "boamid" }, { en: "peasant", min: "boazamd" }, { en: "pease", min: "boazo" }, { en: "peat", min: "boad" }, { en: "pebble", min: "boppro" },
  { en: "pecan", min: "bokam" }, { en: "peccadillo", min: "bokkaturre" }, { en: "pectin", min: "bokdum" }, { en: "pedagog", min: "botageg" }, { en: "pedagogue", min: "botagegio" }, { en: "pedant", min: "botamd" }, { en: "peddle", min: "bottro" }, { en: "pederast", min: "botolazd" }, { en: "pedestrian", min: "botozdluam" }, { en: "pedicure", min: "botukilo" },
  { en: "pedigree", min: "botugloo" }, { en: "pee", min: "boo" }, { en: "peek", min: "booc" }, { en: "peekaboo", min: "boocapee" }, { en: "peep", min: "boob" }, { en: "peephole", min: "boobhero" }, { en: "peerage", min: "boolago" }, { en: "peeve", min: "boofo" }, { en: "peewee", min: "boowoo" }, { en: "pekoe", min: "boceo" },
  { en: "pelican", min: "borukam" }, { en: "pellagra", min: "borragla" }, { en: "pellet", min: "borrod" }, { en: "pellucid", min: "borrikut" }, { en: "pelt", min: "bord" }, { en: "penalize", min: "bomaruso" }, { en: "penance", min: "bomamko" }, { en: "pence", min: "bomko" }, { en: "penchant", min: "bomkhamd" }, { en: "pencil", min: "bomkur" },
  { en: "pend", min: "bomt" }, { en: "pendant", min: "bomtamd" }, { en: "pendent", min: "bomtomd" }, { en: "pendulum", min: "bomtirin" }, { en: "penetrate", min: "bomodlado" }, { en: "penguin", min: "bomgium" }, { en: "penicillin", min: "bomukurrum" }, { en: "penile", min: "bomuro" }, { en: "peninsula", min: "bomumzira" }, { en: "penitence", min: "bomudomko" },
  { en: "penitent", min: "bomudomd" }, { en: "penknife", min: "bomcmuvo" }, { en: "penlight", min: "bomrughd" }, { en: "penlite", min: "bomrudo" }, { en: "pennant", min: "bommamd" }, { en: "pennon", min: "bommem" }, { en: "pension", min: "bomzuem" }, { en: "pent", min: "bomd" }, { en: "pentathlon", min: "bomdadhrem" }, { en: "penthouse", min: "bomdheizo" },
  { en: "peon", min: "boem" }, { en: "peonage", min: "boemago" }, { en: "people", min: "boebro" }, { en: "pep", min: "bob" }, { en: "peppercorn", min: "bobbolkelm" }, { en: "peppermint", min: "bobbolnumd" }, { en: "pepperoni", min: "bobbolemu" }, { en: "pepsin", min: "bobzum" }, { en: "per", min: "bol" }, { en: "percale", min: "bolkaro" },
  { en: "percent", min: "bolkomd" }, { en: "percentage", min: "bolkomdago" }, { en: "percentile", min: "bolkomduro" }, { en: "perch", min: "bolkh" }, { en: "perchance", min: "bolkhamko" }, { en: "percolate", min: "bolkerado" }, { en: "percolator", min: "bolkeradel" }, { en: "percussion", min: "bolkizzuem" }, { en: "perfect", min: "bolvokd" }, { en: "perforate", min: "bolvelado" },
  { en: "perforce", min: "bolvelko" }, { en: "perform", min: "bolveln" }, { en: "perfume", min: "bolvino" }, { en: "pericardia", min: "bolukaltua" }, { en: "perigee", min: "bolugoo" }, { en: "perihelia", min: "boluhorua" }, { en: "perihelion", min: "boluhoruem" }, { en: "peril", min: "bolur" }, { en: "period", min: "boluet" }, { en: "peritonea", min: "boludemoa" },
  { en: "peritoneum", min: "boludemoin" }, { en: "periwig", min: "boluwug" }, { en: "periwinkle", min: "boluwumcro" }, { en: "perjure", min: "bolqilo" }, { en: "perk", min: "bolc" }, { en: "permafrost", min: "bolnavlezd" }, { en: "permanence", min: "bolnamomko" }, { en: "permanent", min: "bolnamomd" }, { en: "permeate", min: "bolnoado" }, { en: "permission", min: "bolnuzzuem" },
  { en: "permit", min: "bolnud" }, { en: "permute", min: "bolnido" }, { en: "peroxide", min: "bolexuto" }, { en: "perpetrate", min: "bolbodlado" }, { en: "perpetuate", min: "bolbodiado" }, { en: "perplex", min: "bolbrox" }, { en: "perquisite", min: "boljiuzudo" }, { en: "persecute", min: "bolzokido" }, { en: "persecutor", min: "bolzokidel" }, { en: "persevere", min: "bolzofolo" },
];
