/**
 * @file Contains dictionary entries for category: adjectives_quality.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const adjectives_quality: DictionaryEntry[] = [
  { en: "good", min: "bueno" }, { en: "bad", min: "malo" }, { en: "great", min: "superbello" }, { en: "nice", min: "lindo" }, { en: "fine", min: "sano" }, { en: "persiflage", min: "bolzuvrago" }, { en: "persimmon", min: "bolzunnem" }, { en: "persistent", min: "bolzuzdomd" }, { en: "person", min: "bolzem" }, { en: "persona", min: "bolzema" },
  { en: "personae", min: "bolzemao" }, { en: "personage", min: "bolzemago" }, { en: "personnel", min: "bolzemmor" }, { en: "perspire", min: "bolzbulo" }, { en: "persuade", min: "bolziato" }, { en: "persuasion", min: "bolziazuem" }, { en: "pert", min: "bold" }, { en: "pertain", min: "boldaum" }, { en: "pertinence", min: "boldumomko" }, { en: "pertinent", min: "boldumomd" },
  { en: "perturb", min: "boldilp" }, { en: "peruse", min: "bolizo" }, { en: "pervade", min: "bolfato" }, { en: "perverse", min: "bolfolzo" }, { en: "perversion", min: "bolfolzuem" }, { en: "pervert", min: "bolfold" }, { en: "peseta", min: "bozoda" }, { en: "peso", min: "boze" }, { en: "pest", min: "bozd" }, { en: "pesticide", min: "bozdukuto" },
  { en: "pestilence", min: "bozduromko" }, { en: "pestilent", min: "bozduromd" }, { en: "pestle", min: "bozdro" }, { en: "petard", min: "bodalt" }, { en: "petiole", min: "boduero" }, { en: "petite", min: "bodudo" }, { en: "petrel", min: "bodlor" }, { en: "petrol", min: "bodler" }, { en: "petrolatum", min: "bodleradin" }, { en: "petroleum", min: "bodleroin" },
  { en: "petticoat", min: "boddukead" }, { en: "pettifog", min: "bodduveg" }, { en: "petulance", min: "bodiramko" }, { en: "petulant", min: "bodiramd" }, { en: "pew", min: "bow" }, { en: "pewee", min: "bowoo" }, { en: "peyote", min: "boyedo" }, { en: "phage", min: "bhago" }, { en: "phalanx", min: "bharamx" }, { en: "phalli", min: "bharru" },
  { en: "phantasm", min: "bhamdazn" }, { en: "phantom", min: "bhamden" }, { en: "pharynx", min: "bhalymx" }, { en: "phase", min: "bhazo" }, { en: "pheasant", min: "bhoazamd" }, { en: "phenomena", min: "bhomenoma" }, { en: "phenomenon", min: "bhomenomem" }, { en: "phenotype", min: "bhomedybo" }, { en: "pheromone", min: "bholenemo" }, { en: "phlegm", min: "bhrogn" },
  { en: "phloem", min: "bhreon" }, { en: "phlox", min: "bhrex" }, { en: "phobia", min: "bhepua" }, { en: "phone", min: "bhemo" }, { en: "phoneme", min: "bhemono" }, { en: "phonograph", min: "bhemeglabh" }, { en: "phosphate", min: "bhezbhado" }, { en: "phosphor", min: "bhezbhel" }, { en: "photo", min: "bhede" }, { en: "photograph", min: "bhedeglabh" },
  { en: "photon", min: "bhedem" }, { en: "phrase", min: "bhlazo" }, { en: "phyla", min: "bhyra" }, { en: "phylum", min: "bhyrin" }, { en: "physician", min: "bhyzukuam" }, { en: "physique", min: "bhyzujio" }, { en: "pianissimi", min: "buamuzzunu" }, { en: "pianissimo", min: "buamuzzune" }, { en: "piano", min: "buame" }, { en: "pianoforte", min: "buameveldo" },
  { en: "piazza", min: "buassa" }, { en: "piazze", min: "buasso" }, { en: "pica", min: "buka" }, { en: "picante", min: "bukamdo" }, { en: "picaresque", min: "bukalozjio" }, { en: "picayune", min: "bukayimo" }, { en: "piccalilli", min: "bukkarurru" }, { en: "piccolo", min: "bukkere" }, { en: "pick", min: "bukc" }, { en: "pickaback", min: "bukcapakc" },
  { en: "pickax", min: "bukcax" }, { en: "pickaxe", min: "bukcaxo" }, { en: "pickerel", min: "bukcolor" }, { en: "picket", min: "bukcod" }, { en: "pickle", min: "bukcro" }, { en: "pickpocket", min: "bukcbekcod" }, { en: "pickup", min: "bukcib" }, { en: "pictograph", min: "bukdeglabh" }, { en: "picture", min: "bukdilo" }, { en: "piddle", min: "buttro" },
  { en: "pidgin", min: "butgum" }, { en: "pie", min: "buo" }, { en: "piebald", min: "buopart" }, { en: "piece", min: "buoko" }, { en: "piecework", min: "buokowelc" }, { en: "piffle", min: "buvvro" }, { en: "pig", min: "bug" }, { en: "pigeon", min: "bugoem" }, { en: "pigeonhole", min: "bugoemhero" }, { en: "piggyback", min: "buggypakc" },
  { en: "piglet", min: "bugrod" }, { en: "pigpen", min: "bugbom" }, { en: "pigskin", min: "bugzcum" }, { en: "pigtail", min: "bugdaur" }, { en: "pilaf", min: "burav" }, { en: "pilaff", min: "buravv" }, { en: "pilau", min: "burai" }, { en: "pilaw", min: "buraw" }, { en: "pilchard", min: "burkhalt" }, { en: "pile", min: "buro" },
  { en: "pileup", min: "buroib" }, { en: "pilgrimage", min: "burglunago" }, { en: "pill", min: "burr" }, { en: "pillage", min: "burrago" }, { en: "pillbox", min: "burrpex" }, { en: "pillion", min: "burruem" }, { en: "pillow", min: "burrew" }, { en: "pillowcase", min: "burrewkazo" }, { en: "pilot", min: "bured" }, { en: "pilothouse", min: "buredheizo" },
  { en: "pimento", min: "bunomde" }, { en: "pimiento", min: "bunuomde" }, { en: "pimp", min: "bunb" }, { en: "pimpernel", min: "bunbolmor" }, { en: "pimple", min: "bunbro" }, { en: "pinafore", min: "bumavelo" }, { en: "pinball", min: "bumparr" }, { en: "pinch", min: "bumkh" }, { en: "pincushion", min: "bumkizhuem" }, { en: "pine", min: "bumo" },
  { en: "pineapple", min: "bumoabbro" }, { en: "ping", min: "bumg" }, { en: "pinhead", min: "bumhoat" }, { en: "pinhole", min: "bumhero" }, { en: "pinion", min: "bumuem" }, { en: "pink", min: "bumc" }, { en: "pinkeye", min: "bumcoyo" }, { en: "pinkie", min: "bumcuo" }, { en: "pinnacle", min: "bummakro" }, { en: "pinnate", min: "bummado" },
  { en: "pinochle", min: "bumekhro" }, { en: "pinpoint", min: "bumbeumd" }, { en: "pinprick", min: "bumblukc" }, { en: "pinstripe", min: "bumzdlubo" }, { en: "pint", min: "bumd" }, { en: "pinto", min: "bumde" }, { en: "pinup", min: "bumib" }, { en: "pinwheel", min: "bumwhoor" }, { en: "pip", min: "bub" }, { en: "pipe", min: "bubo" },
  { en: "pipeline", min: "buborumo" }, { en: "pipit", min: "bubud" }, { en: "pipsqueak", min: "bubzjioac" }, { en: "piquant", min: "bujiamd" }, { en: "pique", min: "bujio" }, { en: "piranha", min: "bulamha" }, { en: "pirate", min: "bulado" }, { en: "pirouette", min: "buleioddo" }, { en: "pistachio", min: "buzdakhue" }, { en: "pistil", min: "buzdur" },
  { en: "pistillate", min: "buzdurrado" }, { en: "pistol", min: "buzder" }, { en: "piston", min: "buzdem" }, { en: "pit", min: "bud" }, { en: "pita", min: "buda" }, { en: "pitch", min: "budkh" }, { en: "pitchfork", min: "budkhvelc" }, { en: "pitchman", min: "budkhnam" }, { en: "pitchmen", min: "budkhnom" }, { en: "pitfall", min: "budvarr" },
  { en: "piton", min: "budem" }, { en: "pittance", min: "buddamko" }, { en: "pivot", min: "bufed" }, { en: "pixel", min: "buxor" }, { en: "pixie", min: "buxuo" }, { en: "pizazz", min: "busass" }, { en: "pizza", min: "bussa" }, { en: "pizzazz", min: "bussass" }, { en: "pizzeria", min: "bussolua" }, { en: "pizzicati", min: "bussukadu" },
  { en: "pizzicato", min: "bussukade" }, { en: "pkg", min: "bcg" }, { en: "placard", min: "brakalt" }, { en: "placate", min: "brakado" }, { en: "place", min: "brako" }, { en: "placebo", min: "brakope" }, { en: "placenta", min: "brakomda" }, { en: "placentae", min: "brakomdao" }, { en: "placid", min: "brakut" }, { en: "placket", min: "brakcod" },
  { en: "plagiarize", min: "bragualuso" }, { en: "plague", min: "bragio" }, { en: "plaice", min: "brauko" }, { en: "plaid", min: "braut" }, { en: "plain", min: "braum" }, { en: "plaint", min: "braumd" }, { en: "plaintiff", min: "braumduvv" }, { en: "plait", min: "braud" }, { en: "plan", min: "bram" }, { en: "plane", min: "bramo" },
  { en: "planet", min: "bramod" }, { en: "planetaria", min: "bramodalua" }, { en: "plangent", min: "bramgomd" }, { en: "plank", min: "bramc" }, { en: "plankton", min: "bramcdem" }, { en: "plant", min: "bramd" }, { en: "plantain", min: "bramdaum" }, { en: "plaque", min: "brajio" }, { en: "plasma", min: "brazna" }, { en: "plastique", min: "brazdujio" },
  { en: "plate", min: "brado" }, { en: "plateau", min: "bradoai" }, { en: "plateaux", min: "bradoaix" }, { en: "platelet", min: "bradorod" }, { en: "platen", min: "bradom" }, { en: "platform", min: "bradveln" }, { en: "platinum", min: "bradumin" }, { en: "platitude", min: "bradudito" }, { en: "platoon", min: "bradeem" }, { en: "platypi", min: "bradybu" },
  { en: "plaudit", min: "braitud" }, { en: "playact", min: "brayakd" }, { en: "playback", min: "braypakc" }, { en: "playbill", min: "braypurr" }, { en: "playground", min: "braygleimt" }, { en: "playhouse", min: "brayheizo" }, { en: "playmate", min: "braynado" }, { en: "playoff", min: "brayevv" }, { en: "playpen", min: "braybom" }, { en: "playroom", min: "brayleen" },
  { en: "playwright", min: "braywlughd" }, { en: "plaza", min: "brasa" }, { en: "plea", min: "broa" }, { en: "plead", min: "broat" }, { en: "pleasant", min: "broazamd" }, { en: "please", min: "broazo" }, { en: "pleasure", min: "broazilo" }, { en: "pleat", min: "broad" }, { en: "plebeian", min: "bropouam" }, { en: "plebiscite", min: "bropuzkudo" },
  { en: "plectra", min: "brokdla" }, { en: "plectrum", min: "brokdlin" }, { en: "pledge", min: "brotgo" }, { en: "plenitude", min: "bromudito" }, { en: "plethora", min: "brodhela" }, { en: "pliant", min: "bruamd" }, { en: "plight", min: "brughd" }, { en: "plod", min: "bret" }, { en: "plonk", min: "bremc" }, { en: "plop", min: "breb" },
  { en: "plot", min: "bred" }, { en: "plough", min: "breigh" }, { en: "plow", min: "brew" }, { en: "plowman", min: "brewnam" }, { en: "plowmen", min: "brewnom" }, { en: "plowshare", min: "brewzhalo" }, { en: "pluck", min: "brikc" }, { en: "plug", min: "brig" }, { en: "plugin", min: "brigum" }, { en: "plum", min: "brin" },
  { en: "plumage", min: "brinago" }, { en: "plumb", min: "brinp" }, { en: "plume", min: "brino" }, { en: "plummet", min: "brinnod" }, { en: "plump", min: "brinb" }, { en: "plunge", min: "brimgo" }, { en: "plunk", min: "brimc" }, { en: "pluperfect", min: "bribolvokd" }, { en: "pluralize", min: "brilaruso" }, { en: "plush", min: "brizh" },
  { en: "plutocrat", min: "brideklad" }, { en: "plutonium", min: "bridemuin" }, { en: "plywood", min: "bryweet" }, { en: "pneumonia", min: "bmoinemua" }, { en: "poach", min: "beakh" }, { en: "pock", min: "bekc" }, { en: "pocket", min: "bekcod" }, { en: "pocketbook", min: "bekcodpeec" }, { en: "pockmark", min: "bekcnalc" }, { en: "pod", min: "bet" },
  { en: "podcast", min: "betkazd" }, { en: "podia", min: "betua" }, { en: "podium", min: "betuin" }, { en: "poem", min: "beon" }, { en: "poet", min: "beod" }, { en: "pogrom", min: "beglen" }, { en: "poi", min: "beu" }, { en: "poignant", min: "beugmamd" }, { en: "poinsettia", min: "beumzoddua" }, { en: "point", min: "beumd" },
];
