/**
 * @file Contains dictionary entries for category: adjectives_temp.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const adjectives_temp: DictionaryEntry[] = [
  { en: "hot", min: "caliente" }, { en: "cold", min: "frio" }, { en: "warm", min: "tibio" }, { en: "cool", min: "fresco" }, { en: "mild", min: "suave" }, { en: "mousetrap", min: "neizodlab" }, { en: "mousse", min: "neizzo" }, { en: "moustache", min: "neizdakho" }, { en: "mouthpiece", min: "neidhbuoko" }, { en: "mouthwash", min: "neidhwazh" },
  { en: "move", min: "nefo" }, { en: "movie", min: "nefuo" }, { en: "mow", min: "new" }, { en: "mown", min: "newm" }, { en: "mozzarella", min: "nessalorra" }, { en: "mpg", min: "nbg" }, { en: "mph", min: "nbh" }, { en: "much", min: "nikh" }, { en: "mucilage", min: "nikurago" }, { en: "muck", min: "nikc" },
  { en: "muckrake", min: "nikclaco" }, { en: "mud", min: "nit" }, { en: "muddle", min: "nittro" }, { en: "mudguard", min: "nitgialt" }, { en: "mudslide", min: "nitzruto" }, { en: "muesli", min: "niozru" }, { en: "muezzin", min: "niossum" }, { en: "muff", min: "nivv" }, { en: "muffle", min: "nivvro" }, { en: "mufti", min: "nivdu" },
  { en: "mug", min: "nig" }, { en: "muggle", min: "niggro" }, { en: "mukluk", min: "nicric" }, { en: "mulatto", min: "niradde" }, { en: "mulch", min: "nirkh" }, { en: "mule", min: "niro" }, { en: "mull", min: "nirr" }, { en: "mullah", min: "nirrah" }, { en: "mullet", min: "nirrod" }, { en: "mullion", min: "nirruem" },
  { en: "multi", min: "nirdu" }, { en: "mum", min: "nin" }, { en: "mumble", min: "ninpro" }, { en: "munchkin", min: "nimkhcum" }, { en: "mundane", min: "nimtamo" }, { en: "mung", min: "nimg" }, { en: "munificent", min: "nimuvukomd" }, { en: "murk", min: "nilc" }, { en: "murmur", min: "nilnil" }, { en: "muscatel", min: "nizkador" },
  { en: "muscle", min: "nizkro" }, { en: "mush", min: "nizh" }, { en: "mushroom", min: "nizhleen" }, { en: "musicale", min: "nizukaro" }, { en: "musician", min: "nizukuam" }, { en: "musk", min: "nizc" }, { en: "musket", min: "nizcod" }, { en: "muskmelon", min: "nizcnorem" }, { en: "muskrat", min: "nizclad" }, { en: "muslin", min: "nizrum" },
  { en: "mussel", min: "nizzor" }, { en: "must", min: "nizd" }, { en: "mustache", min: "nizdakho" }, { en: "mustang", min: "nizdamg" }, { en: "mustard", min: "nizdalt" }, { en: "mutant", min: "nidamd" }, { en: "mutate", min: "nidado" }, { en: "mute", min: "nido" }, { en: "mutilate", min: "nidurado" }, { en: "mutt", min: "nidd" },
  { en: "mutton", min: "niddem" }, { en: "muumuu", min: "niinii" }, { en: "muzzle", min: "nissro" }, { en: "myna", min: "nyma" }, { en: "mynah", min: "nymah" }, { en: "myopia", min: "nyebua" }, { en: "myriad", min: "nyluat" }, { en: "myrrh", min: "nyllh" }, { en: "myself", min: "nyzorv" }, { en: "mystique", min: "nyzdujio" },
  { en: "nab", min: "map" }, { en: "nabob", min: "mapep" }, { en: "nacho", min: "makhe" }, { en: "nacre", min: "maklo" }, { en: "nadir", min: "matul" }, { en: "nag", min: "mag" }, { en: "nagware", min: "magwalo" }, { en: "naiad", min: "mauat" }, { en: "nail", min: "maur" }, { en: "nailbrush", min: "maurplizh" },
  { en: "namesake", min: "manozaco" }, { en: "nanobot", min: "mameped" }, { en: "nanosecond", min: "mamezokemt" }, { en: "nap", min: "mab" }, { en: "napalm", min: "mabarn" }, { en: "nape", min: "mabo" }, { en: "naphtha", min: "mabhdha" }, { en: "napkin", min: "mabcum" }, { en: "narc", min: "malk" }, { en: "narcissi", min: "malkuzzu" },
  { en: "nark", min: "malc" }, { en: "narrate", min: "mallado" }, { en: "narrator", min: "malladel" }, { en: "narrow", min: "mallew" }, { en: "nasalize", min: "mazaruso" }, { en: "nascent", min: "mazkomd" }, { en: "nasturtium", min: "mazdilduin" }, { en: "natl", min: "madr" }, { en: "naturalize", min: "madilaruso" }, { en: "nature", min: "madilo" },
  { en: "naught", min: "maighd" }, { en: "nausea", min: "maizoa" }, { en: "nauseam", min: "maizoan" }, { en: "nauseate", min: "maizoado" }, { en: "nautili", min: "maiduru" }, { en: "nave", min: "mafo" }, { en: "navel", min: "mafor" }, { en: "navigate", min: "mafugado" }, { en: "navigator", min: "mafugadel" }, { en: "neat", min: "moad" },
  { en: "nebula", min: "mopira" }, { en: "nebulae", min: "mopirao" }, { en: "neck", min: "mokc" }, { en: "necklace", min: "mokcrako" }, { en: "neckline", min: "mokcrumo" }, { en: "necktie", min: "mokcduo" }, { en: "nectarine", min: "mokdalumo" }, { en: "needle", min: "mootro" }, { en: "needlework", min: "mootrowelc" }, { en: "neg", min: "mog" },
  { en: "negate", min: "mogado" }, { en: "neglect", min: "mogrokd" }, { en: "neglig", min: "mogrug" }, { en: "negligee", min: "mogrugoo" }, { en: "negligence", min: "mogrugomko" }, { en: "negligent", min: "mogrugomd" }, { en: "negotiate", min: "mogeduado" }, { en: "negotiator", min: "mogeduadel" }, { en: "neigh", min: "mough" }, { en: "neighbor", min: "moughpel" },
  { en: "nematode", min: "monadeto" }, { en: "neocon", min: "moekem" }, { en: "neodymium", min: "moetynuin" }, { en: "neon", min: "moem" }, { en: "neonate", min: "moemado" }, { en: "neophilia", min: "moebhurua" }, { en: "neophyte", min: "moebhydo" }, { en: "neoprene", min: "moeblomo" }, { en: "nephew", min: "mobhow" }, { en: "neptunium", min: "mobdimuin" },
  { en: "nerd", min: "molt" }, { en: "nerve", min: "molfo" }, { en: "nest", min: "mozd" }, { en: "net", min: "mod" }, { en: "netbook", min: "modpeec" }, { en: "nethermost", min: "modholnezd" }, { en: "netiquette", min: "modujioddo" }, { en: "nettlesome", min: "moddrozeno" }, { en: "network", min: "modwelc" }, { en: "neuralgia", min: "moilargua" },
  { en: "neuron", min: "moilem" }, { en: "neutralize", min: "moidlaruso" }, { en: "neutrino", min: "moidlume" }, { en: "neutron", min: "moidlem" }, { en: "nevermore", min: "mofolnelo" }, { en: "newbie", min: "mowpuo" }, { en: "newborn", min: "mowpelm" }, { en: "newel", min: "mowor" }, { en: "newline", min: "mowrumo" }, { en: "newscast", min: "mowzkazd" },
  { en: "newsflash", min: "mowzvrazh" }, { en: "newsgroup", min: "mowzgleib" }, { en: "newsman", min: "mowznam" }, { en: "newsmen", min: "mowznom" }, { en: "newsprint", min: "mowzblumd" }, { en: "newsreel", min: "mowzloor" }, { en: "newsstand", min: "mowzzdamt" }, { en: "newt", min: "mowd" }, { en: "next", min: "moxd" }, { en: "niacin", min: "muakum" },
  { en: "nib", min: "mup" }, { en: "nibble", min: "muppro" }, { en: "niche", min: "mukho" }, { en: "nickel", min: "mukcor" }, { en: "nickle", min: "mukcro" }, { en: "nicknack", min: "mukcmakc" }, { en: "nickname", min: "mukcmano" }, { en: "nicotine", min: "mukedumo" }, { en: "niece", min: "muoko" }, { en: "nigga", min: "mugga" },
  { en: "niggard", min: "muggalt" }, { en: "niggaz", min: "muggas" }, { en: "niggle", min: "muggro" }, { en: "nigh", min: "mugh" }, { en: "nightcap", min: "mughdkab" }, { en: "nightclub", min: "mughdkrip" }, { en: "nightfall", min: "mughdvarr" }, { en: "nightgown", min: "mughdgewm" }, { en: "nighthawk", min: "mughdhawc" }, { en: "nightie", min: "mughduo" },
  { en: "nightlife", min: "mughdruvo" }, { en: "nightmare", min: "mughdnalo" }, { en: "nightshade", min: "mughdzhato" }, { en: "nightshirt", min: "mughdzhuld" }, { en: "nightstick", min: "mughdzdukc" }, { en: "nighttime", min: "mughdduno" }, { en: "nil", min: "mur" }, { en: "nimbi", min: "munpu" }, { en: "nimble", min: "munpro" }, { en: "nincompoop", min: "mumkenbeeb" },
  { en: "nine", min: "mumo" }, { en: "ninepin", min: "mumobum" }, { en: "nineteen", min: "mumodoom" }, { en: "ninja", min: "mumqa" }, { en: "nip", min: "mub" }, { en: "nipple", min: "mubbro" }, { en: "nit", min: "mud" }, { en: "nite", min: "mudo" }, { en: "nitpick", min: "mudbukc" }, { en: "nitrate", min: "mudlado" },
  { en: "nitrogen", min: "mudlegom" }, { en: "nitwit", min: "mudwud" }, { en: "nix", min: "mux" }, { en: "nobleman", min: "mepronam" }, { en: "noblemen", min: "mepronom" }, { en: "noblewoman", min: "meprowenam" }, { en: "noblewomen", min: "meprowenom" }, { en: "nocturne", min: "mekdilmo" }, { en: "nod", min: "met" }, { en: "node", min: "meto" },
  { en: "nodule", min: "metiro" }, { en: "noggin", min: "meggum" }, { en: "noise", min: "meuzo" }, { en: "noisome", min: "meuzeno" }, { en: "nomad", min: "menat" }, { en: "nominate", min: "menumado" }, { en: "nominee", min: "menumoo" }, { en: "non", min: "mem" }, { en: "nonce", min: "memko" }, { en: "none", min: "memo" },
  { en: "noodle", min: "meetro" }, { en: "nook", min: "meec" }, { en: "noon", min: "meem" }, { en: "noontime", min: "meemduno" }, { en: "noose", min: "meezo" }, { en: "nope", min: "mebo" }, { en: "nor", min: "mel" }, { en: "norm", min: "meln" }, { en: "normalize", min: "melnaruso" }, { en: "northbound", min: "meldhpeimt" },
  { en: "nosedove", min: "mezotefo" }, { en: "nosh", min: "mezh" }, { en: "nostalgia", min: "mezdargua" }, { en: "nostril", min: "mezdlur" }, { en: "nostrum", min: "mezdlin" }, { en: "not", min: "med" }, { en: "notarize", min: "medaluso" }, { en: "notch", min: "medkh" }, { en: "note", min: "medo" }, { en: "notebook", min: "medopeec" },
  { en: "notepad", min: "medobat" }, { en: "notice", min: "meduko" }, { en: "notwork", min: "medwelc" }, { en: "nougat", min: "meigad" }, { en: "nought", min: "meighd" }, { en: "noun", min: "meim" }, { en: "novae", min: "mefao" }, { en: "novel", min: "mefor" }, { en: "novelette", min: "meforoddo" }, { en: "novella", min: "meforra" },
  { en: "novelle", min: "meforro" }, { en: "novice", min: "mefuko" }, { en: "novitiate", min: "mefuduado" }, { en: "nowhere", min: "mewholo" }, { en: "nozzle", min: "messro" }, { en: "nth", min: "mdh" }, { en: "nuance", min: "miamko" }, { en: "nub", min: "mip" }, { en: "nubile", min: "mipuro" }, { en: "nuclei", min: "mikrou" },
  { en: "nude", min: "mito" }, { en: "nudge", min: "mitgo" }, { en: "nugget", min: "miggod" }, { en: "nuisance", min: "miuzamko" }, { en: "nuke", min: "mico" }, { en: "null", min: "mirr" }, { en: "numb", min: "minp" }, { en: "numbskull", min: "minpzcirr" }, { en: "numerate", min: "minolado" }, { en: "numerator", min: "minoladel" },
  { en: "numskull", min: "minzcirr" }, { en: "nun", min: "mim" }, { en: "nuncio", min: "mimkue" }, { en: "nurse", min: "milzo" }, { en: "nursemaid", min: "milzonaut" }, { en: "nurseryman", min: "milzolynam" }, { en: "nurserymen", min: "milzolynom" }, { en: "nurture", min: "mildilo" }, { en: "nut", min: "mid" }, { en: "nuthatch", min: "midhadkh" },
];
