/**
 * @file Contains dictionary entries for category: adjectives_size.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const adjectives_size: DictionaryEntry[] = [
  { en: "big", min: "bango" }, { en: "small", min: "pika" }, { en: "tall", min: "alto" }, { en: "short", min: "bajito" }, { en: "wide", min: "ancho" }, { en: "lymphomata", min: "rynbhenada" }, { en: "lynchpin", min: "rymkhbum" }, { en: "lynx", min: "rymx" }, { en: "lyre", min: "rylo" }, { en: "macabre", min: "nakaplo" },
  { en: "macadam", min: "nakatan" }, { en: "macaroni", min: "nakalemu" }, { en: "macaroon", min: "nakaleem" }, { en: "macaw", min: "nakaw" }, { en: "macerate", min: "nakolado" }, { en: "machete", min: "nakhodo" }, { en: "machine", min: "nakhumo" }, { en: "machismo", min: "nakhuzne" }, { en: "macho", min: "nakhe" }, { en: "mackerel", min: "nakcolor" },
  { en: "mackintosh", min: "nakcumdezh" }, { en: "macro", min: "nakle" }, { en: "macron", min: "naklem" }, { en: "mad", min: "nat" }, { en: "madam", min: "natan" }, { en: "madame", min: "natano" }, { en: "madcap", min: "natkab" }, { en: "made", min: "nato" }, { en: "madhouse", min: "natheizo" }, { en: "madman", min: "natnam" },
  { en: "madmen", min: "natnom" }, { en: "madrasa", min: "natlaza" }, { en: "madrasah", min: "natlazah" }, { en: "madrassa", min: "natlazza" }, { en: "madwoman", min: "natwenam" }, { en: "madwomen", min: "natwenom" }, { en: "maelstrom", min: "naorzdlen" }, { en: "maestri", min: "naozdlu" }, { en: "maestro", min: "naozdle" }, { en: "magazine", min: "nagasumo" },
  { en: "magenta", min: "nagomda" }, { en: "maggot", min: "nagged" }, { en: "magician", min: "nagukuam" }, { en: "magistrate", min: "naguzdlado" }, { en: "magma", min: "nagna" }, { en: "magnate", min: "nagmado" }, { en: "magnesia", min: "nagmozua" }, { en: "magnesium", min: "nagmozuin" }, { en: "magnet", min: "nagmod" }, { en: "magnetize", min: "nagmoduso" },
  { en: "magneto", min: "nagmode" }, { en: "magnitude", min: "nagmudito" }, { en: "magnolia", min: "nagmerua" }, { en: "magnum", min: "nagmin" }, { en: "magpie", min: "nagbuo" }, { en: "maharaja", min: "nahalaqa" }, { en: "maharajah", min: "nahalaqah" }, { en: "maharanee", min: "nahalamoo" }, { en: "maharani", min: "nahalamu" }, { en: "maharishi", min: "nahaluzhu" },
  { en: "mahatma", min: "nahadna" }, { en: "mahjong", min: "nahqemg" }, { en: "maid", min: "naut" }, { en: "maiden", min: "nautom" }, { en: "maidenhair", min: "nautomhaul" }, { en: "maidenhead", min: "nautomhoat" }, { en: "mail", min: "naur" }, { en: "mailbomb", min: "naurpenp" }, { en: "mailbox", min: "naurpex" }, { en: "mailman", min: "naurnam" },
  { en: "mailmen", min: "naurnom" }, { en: "maim", min: "naun" }, { en: "main", min: "naum" }, { en: "mainframe", min: "naumvlano" }, { en: "mainland", min: "naumramt" }, { en: "mainline", min: "naumrumo" }, { en: "mainmast", min: "naumnazd" }, { en: "mainsail", min: "naumzaur" }, { en: "mainstream", min: "naumzdloan" }, { en: "maintain", min: "naumdaum" },
  { en: "maize", min: "nauso" }, { en: "majorette", min: "naqeloddo" }, { en: "makeshift", min: "nacozhuvd" }, { en: "makeup", min: "nacoib" }, { en: "maladroit", min: "naratleud" }, { en: "malaise", min: "narauzo" }, { en: "malaria", min: "naralua" }, { en: "malcontent", min: "narkemdomd" }, { en: "malefactor", min: "narovakdel" }, { en: "malevolent", min: "naroferomd" },
  { en: "malice", min: "naruko" }, { en: "malign", min: "narugm" }, { en: "malignant", min: "narugmamd" }, { en: "mall", min: "narr" }, { en: "mallard", min: "narralt" }, { en: "mallet", min: "narrod" }, { en: "mallow", min: "narrew" }, { en: "malt", min: "nard" }, { en: "maltreat", min: "nardload" }, { en: "malware", min: "narwalo" },
  { en: "mama", min: "nana" }, { en: "mambo", min: "nanpe" }, { en: "mamma", min: "nanna" }, { en: "mammalian", min: "nannaruam" }, { en: "mammogram", min: "nanneglan" }, { en: "manacle", min: "namakro" }, { en: "manage", min: "namago" }, { en: "manatee", min: "namadoo" }, { en: "mandate", min: "namtado" }, { en: "mandolin", min: "namterum" },
  { en: "mandrake", min: "namtlaco" }, { en: "mandrill", min: "namtlurr" }, { en: "mane", min: "namo" }, { en: "manga", min: "namga" }, { en: "manganese", min: "namgamozo" }, { en: "mange", min: "namgo" }, { en: "mangle", min: "namgro" }, { en: "mango", min: "namge" }, { en: "mangrove", min: "namglefo" }, { en: "manhandle", min: "namhamtro" },
  { en: "manhole", min: "namhero" }, { en: "manhunt", min: "namhimd" }, { en: "mania", min: "namua" }, { en: "maniac", min: "namuak" }, { en: "manicure", min: "namukilo" }, { en: "manifesto", min: "namuvozde" }, { en: "manifold", min: "namuvert" }, { en: "manikin", min: "namucum" }, { en: "manipulate", min: "namubirado" }, { en: "mankind", min: "namcumt" },
  { en: "manna", min: "namma" }, { en: "mannequin", min: "nammojium" }, { en: "mannikin", min: "nammucum" }, { en: "manor", min: "namel" }, { en: "mansard", min: "namzalt" }, { en: "manse", min: "namzo" }, { en: "manservant", min: "namzolfamd" }, { en: "mansion", min: "namzuem" }, { en: "mantel", min: "namdor" }, { en: "mantilla", min: "namdurra" },
  { en: "mantissa", min: "namduzza" }, { en: "mantra", min: "namdla" }, { en: "manumit", min: "naminud" }, { en: "manure", min: "namilo" }, { en: "manuscript", min: "namizklubd" }, { en: "map", min: "nab" }, { en: "maple", min: "nabro" }, { en: "marabou", min: "nalapei" }, { en: "maraca", min: "nalaka" }, { en: "maraud", min: "nalait" },
  { en: "marble", min: "nalpro" }, { en: "mare", min: "nalo" }, { en: "margarine", min: "nalgalumo" }, { en: "margin", min: "nalgum" }, { en: "marginalia", min: "nalgumarua" }, { en: "mariachi", min: "naluakhu" }, { en: "marihuana", min: "naluhiama" }, { en: "marijuana", min: "naluqiama" }, { en: "marimba", min: "nalunpa" }, { en: "marinade", min: "nalumato" },
  { en: "marinate", min: "nalumado" }, { en: "marionette", min: "naluemoddo" }, { en: "maritime", min: "naluduno" }, { en: "marjoram", min: "nalqelan" }, { en: "markdown", min: "nalctewm" }, { en: "market", min: "nalcod" }, { en: "marksman", min: "nalcznam" }, { en: "marksmen", min: "nalcznom" }, { en: "markup", min: "nalcib" }, { en: "marmalade", min: "nalnarato" },
  { en: "marmoset", min: "nalnezod" }, { en: "marmot", min: "nalned" }, { en: "maroon", min: "naleem" }, { en: "marquee", min: "naljioo" }, { en: "marquise", min: "naljiuzo" }, { en: "marriage", min: "nalluago" }, { en: "marrow", min: "nallew" }, { en: "mart", min: "nald" }, { en: "marten", min: "naldom" }, { en: "martinet", min: "naldumod" },
  { en: "martini", min: "naldumu" }, { en: "martyr", min: "naldyl" }, { en: "martyrdom", min: "naldylten" }, { en: "marvel", min: "nalfor" }, { en: "marzipan", min: "nalsubam" }, { en: "masc", min: "nazk" }, { en: "mascara", min: "nazkala" }, { en: "mascot", min: "nazked" }, { en: "masculine", min: "nazkirumo" }, { en: "mash", min: "nazh" },
  { en: "mashup", min: "nazhib" }, { en: "mask", min: "nazc" }, { en: "masque", min: "nazjio" }, { en: "masquerade", min: "nazjiolato" }, { en: "massacre", min: "nazzaklo" }, { en: "massage", min: "nazzago" }, { en: "masseur", min: "nazzoil" }, { en: "masseuse", min: "nazzoizo" }, { en: "mast", min: "nazd" }, { en: "mastermind", min: "nazdolnumt" },
  { en: "masterwork", min: "nazdolwelc" }, { en: "masthead", min: "nazdhoat" }, { en: "masticate", min: "nazdukado" }, { en: "mastiff", min: "nazduvv" }, { en: "mastodon", min: "nazdetem" }, { en: "mastoid", min: "nazdeut" }, { en: "masturbate", min: "nazdilpado" }, { en: "mat", min: "nad" }, { en: "matador", min: "nadatel" }, { en: "match", min: "nadkh" },
  { en: "matchbook", min: "nadkhpeec" }, { en: "matchbox", min: "nadkhpex" }, { en: "matchstick", min: "nadkhzdukc" }, { en: "mate", min: "nado" }, { en: "matriarch", min: "nadlualkh" }, { en: "matricide", min: "nadlukuto" }, { en: "matrix", min: "nadlux" }, { en: "matron", min: "nadlem" }, { en: "matte", min: "naddo" }, { en: "mattock", min: "naddekc" },
  { en: "mature", min: "nadilo" }, { en: "matzo", min: "nadse" }, { en: "matzoh", min: "nadseh" }, { en: "matzot", min: "nadsed" }, { en: "maudlin", min: "naitrum" }, { en: "maul", min: "nair" }, { en: "mausolea", min: "naizeroa" }, { en: "mausoleum", min: "naizeroin" }, { en: "mauve", min: "naifo" }, { en: "maven", min: "nafom" },
  { en: "maverick", min: "nafolukc" }, { en: "mavin", min: "nafum" }, { en: "maw", min: "naw" }, { en: "maxilla", min: "naxurra" }, { en: "maxillae", min: "naxurrao" }, { en: "maxim", min: "naxun" }, { en: "maxima", min: "naxuna" }, { en: "maximize", min: "naxunuso" }, { en: "maximum", min: "naxunin" }, { en: "maybe", min: "naypo" },
  { en: "mayhem", min: "nayhon" }, { en: "mayonnaise", min: "nayemmauzo" }, { en: "mayor", min: "nayel" }, { en: "maypole", min: "naybero" }, { en: "maze", min: "naso" }, { en: "mazourka", min: "naseilca" }, { en: "mazurka", min: "nasilca" }, { en: "meadow", min: "noatew" }, { en: "meadowlark", min: "noatewralc" }, { en: "mealtime", min: "noarduno" },
  { en: "mean", min: "noam" }, { en: "meant", min: "noamd" }, { en: "meantime", min: "noamduno" }, { en: "meanwhile", min: "noamwhuro" }, { en: "measure", min: "noazilo" }, { en: "meat", min: "noad" }, { en: "meatball", min: "noadparr" }, { en: "meatloaf", min: "noadreav" }, { en: "mechanize", min: "nokhamuso" }, { en: "med", min: "not" },
  { en: "medallion", min: "notarruem" }, { en: "meddle", min: "nottro" }, { en: "meddlesome", min: "nottrozeno" }, { en: "median", min: "notuam" }, { en: "mediate", min: "notuado" }, { en: "mediator", min: "notuadel" }, { en: "medicate", min: "notukado" }, { en: "medicine", min: "notukumo" }, { en: "mediocre", min: "notueklo" }, { en: "meditate", min: "notudado" },
  { en: "medium", min: "notuin" }, { en: "medulla", min: "notirra" }, { en: "medullae", min: "notirrao" }, { en: "meek", min: "nooc" }, { en: "meet", min: "nood" }, { en: "megabyte", min: "nogapydo" }, { en: "megachurch", min: "nogakhilkh" }, { en: "megacycle", min: "nogakykro" }, { en: "megahertz", min: "nogaholds" }, { en: "megaphone", min: "nogabhemo" },
  { en: "megapixel", min: "nogabuxor" }, { en: "megaton", min: "nogadem" }, { en: "meh", min: "noh" }, { en: "melange", min: "noramgo" }, { en: "melanin", min: "noramum" }, { en: "melanoma", min: "noramena" }, { en: "melanomata", min: "noramenada" }, { en: "meld", min: "nort" }, { en: "mellow", min: "norrew" }, { en: "melodrama", min: "noretlana" },
  { en: "melt", min: "nord" }, { en: "meltdown", min: "nordtewm" }, { en: "membrane", min: "nonplamo" }, { en: "meme", min: "nono" }, { en: "memento", min: "nonomde" }, { en: "memo", min: "none" }, { en: "memoir", min: "noneul" }, { en: "memoranda", min: "nonelamta" }, { en: "memorandum", min: "nonelamtin" }, { en: "memorize", min: "noneluso" },
];
