/**
 * @file Contains dictionary entries for category: animals_bugs.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const animals_bugs: DictionaryEntry[] = [
  { en: "ant", min: "hormiga" }, { en: "bee", min: "abeja" }, { en: "fly", min: "mosca" }, { en: "spider", min: "arana" }, { en: "worm", min: "gusano" }, { en: "samaritan", min: "zanaludam" }, { en: "samarkand", min: "zanalcamt" }, { en: "sammie", min: "zannuo" }, { en: "samoan", min: "zaneam" }, { en: "samoset", min: "zanezod" },
  { en: "sampson", min: "zanbzem" }, { en: "samson", min: "zanzem" }, { en: "samsonite", min: "zanzemudo" }, { en: "samuel", min: "zanior" }, { en: "samuelson", min: "zaniorzem" }, { en: "sana", min: "zama" }, { en: "sanchez", min: "zamkhos" }, { en: "sancho", min: "zamkhe" }, { en: "sand", min: "zamt" }, { en: "sandburg", min: "zamtpilg" },
  { en: "sandinista", min: "zamtumuzda" }, { en: "sanford", min: "zamvelt" }, { en: "sang", min: "zamg" }, { en: "sanhedrin", min: "zamhotlum" }, { en: "sanka", min: "zamca" }, { en: "sankara", min: "zamcala" }, { en: "sanskrit", min: "zamzclud" }, { en: "santa", min: "zamda" }, { en: "santana", min: "zamdama" }, { en: "santayana", min: "zamdayama" },
  { en: "santeria", min: "zamdolua" }, { en: "sappho", min: "zabbhe" }, { en: "sapporo", min: "zabbele" }, { en: "saracen", min: "zalakom" }, { en: "saragossa", min: "zalagezza" }, { en: "saran", min: "zalam" }, { en: "sarasota", min: "zalazeda" }, { en: "saratov", min: "zaladef" }, { en: "sarawak", min: "zalawac" }, { en: "sardinia", min: "zaltumua" },
  { en: "sargasso", min: "zalgazze" }, { en: "sargent", min: "zalgomd" }, { en: "sargon", min: "zalgem" }, { en: "sarnoff", min: "zalmevv" }, { en: "saroyan", min: "zaleyam" }, { en: "sarto", min: "zalde" }, { en: "sartre", min: "zaldlo" }, { en: "saskatoon", min: "zazcadeem" }, { en: "sasquatch", min: "zazjiadkh" }, { en: "sassanian", min: "zazzamuam" },
  { en: "sassoon", min: "zazzeem" }, { en: "satan", min: "zadam" }, { en: "saturn", min: "zadilm" }, { en: "saturnalia", min: "zadilmarua" }, { en: "saul", min: "zair" }, { en: "saussure", min: "zaizzilo" }, { en: "sauterne", min: "zaidolmo" }, { en: "savage", min: "zafago" }, { en: "savannah", min: "zafammah" }, { en: "savior", min: "zafuel" },
  { en: "savonarola", min: "zafemalera" }, { en: "savoyard", min: "zafeyalt" }, { en: "saxon", min: "zaxem" }, { en: "scala", min: "zkara" }, { en: "scaramouch", min: "zkalaneikh" }, { en: "scarlatti", min: "zkalraddu" }, { en: "scheat", min: "zkhoad" }, { en: "schick", min: "zkhukc" }, { en: "schliemann", min: "zkhruonamm" }, { en: "schlitz", min: "zkhruds" },
  { en: "schmidt", min: "zkhnutd" }, { en: "schnabel", min: "zkhmapor" }, { en: "schoenberg", min: "zkheompolg" }, { en: "schubert", min: "zkhipold" }, { en: "schultz", min: "zkhirds" }, { en: "schulz", min: "zkhirs" }, { en: "schumann", min: "zkhinamm" }, { en: "schuylkill", min: "zkhiyrcurr" }, { en: "schwartz", min: "zkhwalds" }, { en: "schwinn", min: "zkhwumm" },
  { en: "scipio", min: "zkubue" }, { en: "scorpio", min: "zkelbue" }, { en: "scorsese", min: "zkelzozo" }, { en: "scot", min: "zked" }, { en: "scotch", min: "zkedkh" }, { en: "scotchman", min: "zkedkhnam" }, { en: "scotchmen", min: "zkedkhnom" }, { en: "scotia", min: "zkedua" }, { en: "scotsman", min: "zkedznam" }, { en: "scotsmen", min: "zkedznom" },
  { en: "scotswoman", min: "zkedzwenam" }, { en: "scotswomen", min: "zkedzwenom" }, { en: "scott", min: "zkedd" }, { en: "scottie", min: "zkedduo" }, { en: "scottsdale", min: "zkeddztaro" }, { en: "scout", min: "zkeid" }, { en: "scrabble", min: "zklappro" }, { en: "scranton", min: "zklamdem" }, { en: "scriabin", min: "zkluapum" }, { en: "scripture", min: "zklubdilo" },
  { en: "scrooge", min: "zkleego" }, { en: "scud", min: "zkit" }, { en: "scylla", min: "zkyrra" }, { en: "scythia", min: "zkydhua" }, { en: "scythian", min: "zkydhuam" }, { en: "seaborg", min: "zoapelg" }, { en: "seagram", min: "zoaglan" }, { en: "seaside", min: "zoazuto" }, { en: "seattle", min: "zoaddro" }, { en: "sebastian", min: "zopazduam" },
  { en: "sedna", min: "zotma" }, { en: "seebeck", min: "zoopokc" }, { en: "sega", min: "zoga" }, { en: "segovia", min: "zogefua" }, { en: "segre", min: "zoglo" }, { en: "segundo", min: "zogimte" }, { en: "seiko", min: "zouce" }, { en: "seine", min: "zoumo" }, { en: "seinfeld", min: "zoumvort" }, { en: "sejong", min: "zoqemg" },
  { en: "selassie", min: "zorazzuo" }, { en: "seleucid", min: "zoroikut" }, { en: "selim", min: "zorun" }, { en: "seljuk", min: "zorqic" }, { en: "selkirk", min: "zorculc" }, { en: "selznick", min: "zorsmukc" }, { en: "semarang", min: "zonalamg" }, { en: "semite", min: "zonudo" }, { en: "semtex", min: "zondox" }, { en: "sen", min: "zom" },
  { en: "senate", min: "zomado" }, { en: "senator", min: "zomadel" }, { en: "sendai", min: "zomtau" }, { en: "seneca", min: "zomoka" }, { en: "senegalese", min: "zomogarozo" }, { en: "senghor", min: "zomghel" }, { en: "senior", min: "zomuel" }, { en: "sennett", min: "zommodd" }, { en: "sep", min: "zob" }, { en: "sephardi", min: "zobhaltu" },
  { en: "sept", min: "zobd" }, { en: "septuagint", min: "zobdiagumd" }, { en: "sequoya", min: "zojieya" }, { en: "serb", min: "zolp" }, { en: "serbian", min: "zolpuam" }, { en: "serengeti", min: "zolomgodu" }, { en: "sergei", min: "zolgou" }, { en: "sergio", min: "zolgue" }, { en: "serra", min: "zolla" }, { en: "serrano", min: "zollame" },
  { en: "set", min: "zod" }, { en: "seton", min: "zodem" }, { en: "seurat", min: "zoilad" }, { en: "sevastopol", min: "zofazdeber" }, { en: "severn", min: "zofolm" }, { en: "seville", min: "zofurro" }, { en: "sexton", min: "zoxdem" }, { en: "seyfert", min: "zoyvold" }, { en: "seymour", min: "zoyneil" }, { en: "sgt", min: "zgd" },
  { en: "shackleton", min: "zhakcrodem" }, { en: "shaka", min: "zhaca" }, { en: "shanghai", min: "zhamghau" }, { en: "shankara", min: "zhamcala" }, { en: "shantung", min: "zhamdimg" }, { en: "shapiro", min: "zhabule" }, { en: "sharepoint", min: "zhalobeumd" }, { en: "sharif", min: "zhaluv" }, { en: "sharpe", min: "zhalbo" }, { en: "shasta", min: "zhazda" },
  { en: "shaula", min: "zhaira" }, { en: "shavian", min: "zhafuam" }, { en: "shavuot", min: "zhafied" }, { en: "shaw", min: "zhaw" }, { en: "shebeli", min: "zhoporu" }, { en: "sheboygan", min: "zhopeygam" }, { en: "sheetrock", min: "zhoodlekc" }, { en: "sheffield", min: "zhovvuort" }, { en: "sheldon", min: "zhortem" }, { en: "shelton", min: "zhordem" },
  { en: "shenandoah", min: "zhomamteah" }, { en: "shenyang", min: "zhomyamg" }, { en: "sheol", min: "zhoer" }, { en: "shepard", min: "zhobalt" }, { en: "shepherd", min: "zhobholt" }, { en: "sheppard", min: "zhobbalt" }, { en: "sheratan", min: "zholadam" }, { en: "sheraton", min: "zholadem" }, { en: "sheridan", min: "zholutam" }, { en: "sherlock", min: "zholrekc" },
  { en: "sherman", min: "zholnam" }, { en: "sherpa", min: "zholba" }, { en: "sherwood", min: "zholweet" }, { en: "shetland", min: "zhodramt" }, { en: "shevat", min: "zhofad" }, { en: "shikoku", min: "zhuceci" }, { en: "shillong", min: "zhurremg" }, { en: "shiloh", min: "zhureh" }, { en: "shinto", min: "zhumde" }, { en: "shiraz", min: "zhulas" },
  { en: "shiva", min: "zhufa" }, { en: "shorthorn", min: "zheldhelm" }, { en: "shoshone", min: "zhezhemo" }, { en: "shrek", min: "zhloc" }, { en: "shreveport", min: "zhlofobeld" }, { en: "shropshire", min: "zhlebzhulo" }, { en: "shula", min: "zhira" }, { en: "shylock", min: "zhyrekc" }, { en: "shylockian", min: "zhyrekcuam" }, { en: "siam", min: "zuan" },
  { en: "siamese", min: "zuanozo" }, { en: "sian", min: "zuam" }, { en: "siberian", min: "zupoluam" }, { en: "sicilian", min: "zukuruam" }, { en: "sid", min: "zut" }, { en: "siddhartha", min: "zutthaldha" }, { en: "sierpinski", min: "zuolbumzcu" }, { en: "sigismund", min: "zuguznimt" }, { en: "sigmund", min: "zugnimt" }, { en: "sigurd", min: "zugilt" },
  { en: "sihanouk", min: "zuhameic" }, { en: "sikh", min: "zuch" }, { en: "sikkim", min: "zuccun" }, { en: "sikkimese", min: "zuccunozo" }, { en: "silurian", min: "zuriluam" }, { en: "simenon", min: "zunomem" }, { en: "simon", min: "zunem" }, { en: "simpson", min: "zunbzem" }, { en: "sinai", min: "zumau" }, { en: "sinatra", min: "zumadla" },
  { en: "sinclair", min: "zumkraul" }, { en: "sindbad", min: "zumtpat" }, { en: "sindhi", min: "zumthu" }, { en: "singh", min: "zumgh" }, { en: "singleton", min: "zumgrodem" }, { en: "sinhalese", min: "zumharozo" }, { en: "sinkiang", min: "zumcuamg" }, { en: "sistine", min: "zuzdumo" }, { en: "sisyphean", min: "zuzybhoam" }, { en: "siva", min: "zufa" },
  { en: "sivan", min: "zufam" }, { en: "sjaelland", min: "zqaorramt" }, { en: "skye", min: "zcyo" }, { en: "skylab", min: "zcyrap" }, { en: "skype", min: "zcybo" }, { en: "slackware", min: "zrakcwalo" }, { en: "slashdot", min: "zrazhted" }, { en: "slav", min: "zraf" }, { en: "slidell", min: "zrutorr" }, { en: "sloan", min: "zream" },
  { en: "sloane", min: "zreamo" }, { en: "slocum", min: "zrekin" }, { en: "slovak", min: "zrefac" }, { en: "slovakian", min: "zrefacuam" }, { en: "slovenian", min: "zrefomuam" }, { en: "slurpee", min: "zrilboo" }, { en: "smetana", min: "znodama" }, { en: "smirnoff", min: "znulmevv" }, { en: "smithson", min: "znudhzem" }, { en: "smolensk", min: "zneromzc" },
  { en: "smollett", min: "znerrodd" }, { en: "snake", min: "zmaco" }, { en: "snapple", min: "zmabbro" }, { en: "snead", min: "zmoat" }, { en: "snell", min: "zmorr" }, { en: "snowbelt", min: "zmewpord" }, { en: "soave", min: "zeafo" }, { en: "socastee", min: "zekazdoo" }, { en: "socorro", min: "zekelle" }, { en: "sodom", min: "zeten" },
  { en: "soho", min: "zehe" }, { en: "sol", min: "zer" }, { en: "solon", min: "zerem" }, { en: "somali", min: "zenaru" }, { en: "somalian", min: "zenaruam" }, { en: "somme", min: "zenno" }, { en: "somoza", min: "zenesa" }, { en: "son", min: "zem" }, { en: "sondheim", min: "zemthoun" }, { en: "songhai", min: "zemghau" },
  { en: "songhua", min: "zemghia" }, { en: "sontag", min: "zemdag" }, { en: "sophoclean", min: "zebhekroam" }, { en: "sorbonne", min: "zelpemmo" }, { en: "sosa", min: "zeza" }, { en: "soto", min: "zede" }, { en: "sousa", min: "zeiza" }, { en: "southeast", min: "zeidhoazd" }, { en: "soviet", min: "zefuod" }, { en: "soweto", min: "zewode" },
  { en: "soyinka", min: "zeyumca" }, { en: "soyuz", min: "zeyis" }, { en: "spaatz", min: "zbaads" }, { en: "spackle", min: "zbakcro" }, { en: "spahn", min: "zbahm" }, { en: "spam", min: "zban" }, { en: "spaniard", min: "zbamualt" }, { en: "sparta", min: "zbalda" }, { en: "spartan", min: "zbaldam" }, { en: "spence", min: "zbomko" },
];
