/**
 * @file Contains dictionary entries for category: animals_wild.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const animals_wild: DictionaryEntry[] = [
  { en: "lion", min: "leo" }, { en: "tiger", min: "tigre" }, { en: "bear", min: "oso" }, { en: "monkey", min: "mono" }, { en: "deer", min: "venado" }, { en: "oshawa", min: "ezhawa" }, { en: "oshkosh", min: "ezhcezh" }, { en: "osman", min: "eznam" }, { en: "ostwald", min: "ezdwart" }, { en: "osvaldo", min: "ezfarte" },
  { en: "oswald", min: "ezwart" }, { en: "othello", min: "edhorre" }, { en: "otto", min: "edde" }, { en: "ottoman", min: "eddenam" }, { en: "ouija", min: "eiuqa" }, { en: "ovid", min: "efut" }, { en: "owen", min: "ewom" }, { en: "owensboro", min: "ewomzpele" }, { en: "oxford", min: "exvelt" }, { en: "oxnard", min: "exmalt" },
  { en: "oxonian", min: "exemuam" }, { en: "oxycontin", min: "exykemdum" }, { en: "ozark", min: "esalc" }, { en: "ozzie", min: "essuo" }, { en: "pac", min: "bak" }, { en: "parc", min: "balk" }, { en: "pbx", min: "bpx" }, { en: "pcb", min: "bkp" }, { en: "pcmcia", min: "bknkua" }, { en: "pdf", min: "btv" },
  { en: "pdq", min: "btj" }, { en: "pfc", min: "bvk" }, { en: "pgp", min: "bgb" }, { en: "php", min: "bhb" }, { en: "pin", min: "bum" }, { en: "plo", min: "bre" }, { en: "pow", min: "bew" }, { en: "pst", min: "bzd" }, { en: "pta", min: "bda" }, { en: "pvc", min: "bfk" },
  { en: "pablo", min: "bapre" }, { en: "pablum", min: "baprin" }, { en: "pabst", min: "bapzd" }, { en: "pace", min: "bako" }, { en: "pacheco", min: "bakhoke" }, { en: "pacino", min: "bakume" }, { en: "packard", min: "bakcalt" }, { en: "paderewski", min: "batolowzcu" }, { en: "padilla", min: "baturra" }, { en: "paganini", min: "bagamumu" },
  { en: "paglia", min: "bagrua" }, { en: "pahlavi", min: "bahrafu" }, { en: "paine", min: "baumo" }, { en: "pakistani", min: "bacuzdamu" }, { en: "palembang", min: "baronpamg" }, { en: "paleocene", min: "baroekomo" }, { en: "paleogene", min: "baroegomo" }, { en: "palermo", min: "barolne" }, { en: "palestrina", min: "barozdluma" }, { en: "palladio", min: "barratue" },
  { en: "palmdale", min: "barntaro" }, { en: "palmerston", min: "barnolzdem" }, { en: "palmyra", min: "barnyla" }, { en: "pan", min: "bam" }, { en: "panamanian", min: "bamanamuam" }, { en: "pangaea", min: "bamgaoa" }, { en: "pankhurst", min: "bamchilzd" }, { en: "panmunjom", min: "bamnimqen" }, { en: "pantagruel", min: "bamdaglior" }, { en: "pantaloon", min: "bamdareem" },
  { en: "pantheon", min: "bamdhoem" }, { en: "panza", min: "bamsa" }, { en: "paraclete", min: "balakrodo" }, { en: "paradise", min: "balatuzo" }, { en: "paraguayan", min: "balagiayam" }, { en: "paramount", min: "balaneimd" }, { en: "parcheesi", min: "balkhoozu" }, { en: "pareto", min: "balode" }, { en: "parisian", min: "baluzuam" }, { en: "parkinson", min: "balcumzem" },
  { en: "parkman", min: "balcnam" }, { en: "parmesan", min: "balnozam" }, { en: "parnell", min: "balmorr" }, { en: "parr", min: "ball" }, { en: "parsi", min: "balzu" }, { en: "parthenon", min: "baldhomem" }, { en: "parthia", min: "baldhua" }, { en: "pasadena", min: "bazatoma" }, { en: "pascagoula", min: "bazkageira" }, { en: "pasco", min: "bazke" },
  { en: "pasquale", min: "bazjiaro" }, { en: "passion", min: "bazzuem" }, { en: "pasternak", min: "bazdolmac" }, { en: "pasteur", min: "bazdoil" }, { en: "patagonia", min: "badagemua" }, { en: "patagonian", min: "badagemuam" }, { en: "pate", min: "bado" }, { en: "patel", min: "bador" }, { en: "paterson", min: "badolzem" }, { en: "patna", min: "badma" },
  { en: "patrick", min: "badlukc" }, { en: "patterson", min: "baddolzem" }, { en: "patton", min: "baddem" }, { en: "paul", min: "bair" }, { en: "pavarotti", min: "bafaleddu" }, { en: "pavlov", min: "bafref" }, { en: "pavlova", min: "bafrefa" }, { en: "pavlovian", min: "bafrefuam" }, { en: "pawnee", min: "bawmoo" }, { en: "payne", min: "baymo" },
  { en: "peace", min: "boako" }, { en: "peale", min: "boaro" }, { en: "pearlie", min: "boalruo" }, { en: "pearson", min: "boalzem" }, { en: "pechora", min: "bokhela" }, { en: "peck", min: "bokc" }, { en: "peckinpah", min: "bokcumbah" }, { en: "pedro", min: "botle" }, { en: "peel", min: "boor" }, { en: "pei", min: "bou" },
  { en: "pekinese", min: "bocumozo" }, { en: "pekingese", min: "bocumgozo" }, { en: "pele", min: "boro" }, { en: "pelee", min: "boroo" }, { en: "pembroke", min: "bonpleco" }, { en: "pena", min: "boma" }, { en: "penderecki", min: "bomtolokcu" }, { en: "penn", min: "bomm" }, { en: "pennington", min: "bommumgdem" }, { en: "pennzoil", min: "bommseur" },
  { en: "pensacola", min: "bomzakera" }, { en: "pentagon", min: "bomdagem" }, { en: "pentateuch", min: "bomdadoikh" }, { en: "pentax", min: "bomdax" }, { en: "pentecost", min: "bomdokezd" }, { en: "pentium", min: "bomduin" }, { en: "peoria", min: "boelua" }, { en: "pepin", min: "bobum" }, { en: "pequot", min: "bojied" }, { en: "percheron", min: "bolkholem" },
  { en: "perelman", min: "bolornam" }, { en: "perez", min: "bolos" }, { en: "periclean", min: "bolukroam" }, { en: "perm", min: "boln" }, { en: "permian", min: "bolnuam" }, { en: "pernod", min: "bolmet" }, { en: "peron", min: "bolem" }, { en: "perot", min: "boled" }, { en: "perseid", min: "bolzout" }, { en: "persephone", min: "bolzobhemo" },
  { en: "persia", min: "bolzua" }, { en: "persian", min: "bolzuam" }, { en: "peruvian", min: "bolifuam" }, { en: "petaluma", min: "bodarina" }, { en: "pete", min: "bodo" }, { en: "petersen", min: "bodolzom" }, { en: "peterson", min: "bodolzem" }, { en: "petrarch", min: "bodlalkh" }, { en: "peugeot", min: "boigoed" }, { en: "phd", min: "bht" },
  { en: "phaethon", min: "bhaodhem" }, { en: "pharaoh", min: "bhalaeh" }, { en: "pharisee", min: "bhaluzoo" }, { en: "phekda", min: "bhocta" }, { en: "philip", min: "bhurub" }, { en: "philistine", min: "bhuruzdumo" }, { en: "phillip", min: "bhurrub" }, { en: "phillipa", min: "bhurruba" }, { en: "phoenicia", min: "bheomukua" }, { en: "phoenix", min: "bheomux" },
  { en: "photostat", min: "bhedezdad" }, { en: "phrygia", min: "bhlygua" }, { en: "piaf", min: "buav" }, { en: "piaget", min: "buagod" }, { en: "pianola", min: "buamera" }, { en: "picasso", min: "bukazze" }, { en: "pickett", min: "bukcodd" }, { en: "pickford", min: "bukcvelt" }, { en: "pickwick", min: "bukcwukc" }, { en: "pict", min: "bukd" },
  { en: "piedmont", min: "buotnemd" }, { en: "pierce", min: "buolko" }, { en: "pierrot", min: "buolled" }, { en: "pike", min: "buco" }, { en: "pilate", min: "burado" }, { en: "pilcomayo", min: "burkenaye" }, { en: "pilgrim", min: "burglun" }, { en: "pinatubo", min: "bumadipe" }, { en: "pinkerton", min: "bumcoldem" }, { en: "pinocchio", min: "bumekkhue" },
  { en: "pinochet", min: "bumekhod" }, { en: "pippin", min: "bubbum" }, { en: "pirandello", min: "bulamtorre" }, { en: "pisa", min: "buza" }, { en: "pissaro", min: "buzzale" }, { en: "pitt", min: "budd" }, { en: "pittman", min: "buddnam" }, { en: "pittsburgh", min: "buddzpilgh" }, { en: "pittsfield", min: "buddzvuort" }, { en: "pizarro", min: "busalle" },
  { en: "planck", min: "bramkc" }, { en: "plasticine", min: "brazdukumo" }, { en: "plataea", min: "bradaoa" }, { en: "plato", min: "brade" }, { en: "platte", min: "braddo" }, { en: "playtex", min: "braydox" }, { en: "pliocene", min: "bruekomo" }, { en: "plutarch", min: "bridalkh" }, { en: "pluto", min: "bride" }, { en: "pocatello", min: "bekadorre" },
  { en: "pocono", min: "bekeme" }, { en: "podhoretz", min: "bethelods" }, { en: "podunk", min: "betimc" }, { en: "poe", min: "beo" }, { en: "pogo", min: "bege" }, { en: "poiret", min: "beulod" }, { en: "poirot", min: "beuled" }, { en: "poisson", min: "beuzzem" }, { en: "polanski", min: "beramzcu" }, { en: "polaroid", min: "beraleut" },
  { en: "pole", min: "bero" }, { en: "politburo", min: "berudpile" }, { en: "polk", min: "berc" }, { en: "pollard", min: "berralt" }, { en: "pollock", min: "berrekc" }, { en: "pollux", min: "berrix" }, { en: "polo", min: "bere" }, { en: "poltava", min: "berdafa" }, { en: "polyhymnia", min: "beryhynmua" }, { en: "polynesian", min: "berymozuam" },
  { en: "pomerania", min: "benolamua" }, { en: "pomeranian", min: "benolamuam" }, { en: "pomona", min: "benema" }, { en: "pompadour", min: "benbateil" }, { en: "pompeii", min: "benbouu" }, { en: "ponce", min: "bemko" }, { en: "pontiac", min: "bemduak" }, { en: "pontianak", min: "bemduamac" }, { en: "poole", min: "beero" }, { en: "poona", min: "beema" },
  { en: "pope", min: "bebo" }, { en: "popeye", min: "beboyo" }, { en: "popsicle", min: "bebzukro" }, { en: "porfirio", min: "belvulue" }, { en: "porrima", min: "belluna" }, { en: "porsche", min: "belzkho" }, { en: "portland", min: "beldramt" }, { en: "poseidon", min: "bezoutem" }, { en: "post", min: "bezd" }, { en: "potemkin", min: "bedoncum" },
  { en: "potomac", min: "bedenak" }, { en: "potsdam", min: "bedztan" }, { en: "pottstown", min: "beddzdewm" }, { en: "pound", min: "beimt" }, { en: "poussin", min: "beizzum" }, { en: "powell", min: "beworr" }, { en: "powerpc", min: "bewolbk" }, { en: "powerpoint", min: "bewolbeumd" }, { en: "powhatan", min: "bewhadam" }, { en: "poznan", min: "besmam" },
  { en: "prada", min: "blata" }, { en: "prado", min: "blate" }, { en: "praetorian", min: "blaodeluam" }, { en: "prague", min: "blagio" }, { en: "prakrit", min: "blaclud" }, { en: "pratchett", min: "bladkhodd" }, { en: "pratt", min: "bladd" }, { en: "pravda", min: "blafta" }, { en: "priam", min: "bluan" }, { en: "pribilof", min: "blupurev" },
  { en: "price", min: "bluko" }, { en: "priceline", min: "blukorumo" }, { en: "prince", min: "blumko" }, { en: "princeton", min: "blumkodem" }, { en: "prof", min: "blev" }, { en: "provo", min: "blefe" }, { en: "pruitt", min: "bliudd" }, { en: "prussia", min: "blizzua" }, { en: "prussian", min: "blizzuam" }, { en: "prut", min: "blid" },
  { en: "pryor", min: "blyel" }, { en: "psyche", min: "bzykho" }, { en: "ptah", min: "bdah" }, { en: "puccini", min: "bikkumu" }, { en: "puck", min: "bikc" }, { en: "puckett", min: "bikcodd" }, { en: "puebla", min: "biopra" }, { en: "pueblo", min: "biopre" }, { en: "puget", min: "bigod" }, { en: "pugh", min: "bigh" },
  { en: "pulaski", min: "birazcu" }, { en: "pullman", min: "birrnam" }, { en: "punch", min: "bimkh" }, { en: "punjab", min: "bimqap" }, { en: "purana", min: "bilama" }, { en: "purcell", min: "bilkorr" }, { en: "purdue", min: "biltio" }, { en: "purim", min: "bilun" }, { en: "purina", min: "biluma" }, { en: "puritan", min: "biludam" },
];
