/**
 * @file Contains dictionary entries for category: animals_sea.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const animals_sea: DictionaryEntry[] = [
  { en: "whale", min: "ballena" }, { en: "shark", min: "tiburo" }, { en: "crab", min: "cangre" }, { en: "octopus", min: "pulpo" }, { en: "seal", min: "foca" }, { en: "pusan", min: "bizam" }, { en: "pushkin", min: "bizhcum" }, { en: "pushtu", min: "bizhdi" }, { en: "putin", min: "bidum" }, { en: "putnam", min: "bidman" },
  { en: "puzo", min: "bise" }, { en: "pytorch", min: "bydelkh" }, { en: "pygmalion", min: "bygnaruem" }, { en: "pyle", min: "byro" }, { en: "pym", min: "byn" }, { en: "pynchon", min: "bymkhem" }, { en: "pyotr", min: "byedl" }, { en: "pyrex", min: "bylox" }, { en: "python", min: "bydhem" }, { en: "qaddafi", min: "jattavu" },
  { en: "qingdao", min: "jumgtae" }, { en: "qom", min: "jen" }, { en: "quaalude", min: "jiaarito" }, { en: "qualcomm", min: "jiarkenn" }, { en: "quasimodo", min: "jiazunete" }, { en: "quayle", min: "jiayro" }, { en: "quebec", min: "jiopok" }, { en: "quechua", min: "jiokhia" }, { en: "queen", min: "jioom" }, { en: "queensland", min: "jioomzramt" },
  { en: "quezon", min: "jiosem" }, { en: "quintilian", min: "jiumduruam" }, { en: "quinton", min: "jiumdem" }, { en: "quixote", min: "jiuxedo" }, { en: "qumran", min: "jinlam" }, { en: "quonset", min: "jiemzod" }, { en: "quran", min: "jilam" }, { en: "ram", min: "lan" }, { en: "rbi", min: "lpu" }, { en: "rca", min: "lka" },
  { en: "rda", min: "lta" }, { en: "rem", min: "lon" }, { en: "rfc", min: "lvk" }, { en: "rfd", min: "lvt" }, { en: "rip", min: "lub" }, { en: "rna", min: "lma" }, { en: "rofl", min: "levr" }, { en: "rom", min: "len" }, { en: "rotc", min: "ledk" }, { en: "rsv", min: "lzf" },
  { en: "rsvp", min: "lzfb" }, { en: "rtfm", min: "ldvn" }, { en: "rabin", min: "lapum" }, { en: "racine", min: "lakumo" }, { en: "radcliff", min: "latkruvv" }, { en: "radcliffe", min: "latkruvvo" }, { en: "rafael", min: "lavaor" }, { en: "raleigh", min: "larough" }, { en: "ralph", min: "larbh" }, { en: "rama", min: "lana" },
  { en: "ramada", min: "lanata" }, { en: "ramadan", min: "lanatam" }, { en: "ramanujan", min: "lanamiqam" }, { en: "ramayana", min: "lanayama" }, { en: "rambo", min: "lanpe" }, { en: "ramirez", min: "lanulos" }, { en: "ramiro", min: "lanule" }, { en: "ramon", min: "lanem" }, { en: "rand", min: "lamt" }, { en: "randall", min: "lamtarr" },
  { en: "randell", min: "lamtorr" }, { en: "randolph", min: "lamterbh" }, { en: "rangoon", min: "lamgeem" }, { en: "rankin", min: "lamcum" }, { en: "rankine", min: "lamcumo" }, { en: "raoul", min: "laeir" }, { en: "raphael", min: "labhaor" }, { en: "rapunzel", min: "labimsor" }, { en: "rasalgethi", min: "lazargodhu" }, { en: "rasalhague", min: "lazarhagio" },
  { en: "rasmussen", min: "laznizzom" }, { en: "rasputin", min: "lazbidum" }, { en: "rasta", min: "lazda" }, { en: "rastaban", min: "lazdapam" }, { en: "ratliff", min: "ladruvv" }, { en: "raul", min: "lair" }, { en: "ravel", min: "lafor" }, { en: "rawalpindi", min: "lawarbumtu" }, { en: "rayban", min: "laypam" }, { en: "rayburn", min: "laypilm" },
  { en: "rayleigh", min: "layrough" }, { en: "raymond", min: "laynemt" }, { en: "raymundo", min: "laynimte" }, { en: "reid", min: "lout" }, { en: "reno", min: "lome" }, { en: "rep", min: "lob" }, { en: "rev", min: "lof" }, { en: "reva", min: "lofa" }, { en: "rex", min: "lox" }, { en: "rhee", min: "lhoo" },
  { en: "rheingau", min: "lhoumgai" }, { en: "rhiannon", min: "lhuammem" }, { en: "rhine", min: "lhumo" }, { en: "rhineland", min: "lhumoramt" }, { en: "rhode", min: "lheto" }, { en: "rhodesia", min: "lhetozua" }, { en: "rhone", min: "lhemo" }, { en: "ribbentrop", min: "luppomdleb" }, { en: "ricardo", min: "lukalte" }, { en: "rice", min: "luko" },
  { en: "rich", min: "lukh" }, { en: "richard", min: "lukhalt" }, { en: "richardson", min: "lukhaltzem" }, { en: "richelieu", min: "lukhoruoi" }, { en: "richie", min: "lukhuo" }, { en: "richmond", min: "lukhnemt" }, { en: "richthofen", min: "lukhdhevom" }, { en: "rick", min: "lukc" }, { en: "riddle", min: "luttro" }, { en: "ride", min: "luto" },
  { en: "riel", min: "luor" }, { en: "riemann", min: "luonamm" }, { en: "rigel", min: "lugor" }, { en: "rigoberto", min: "lugepolde" }, { en: "rigoletto", min: "lugerodde" }, { en: "rilke", min: "lurco" }, { en: "rimbaud", min: "lunpait" }, { en: "ringo", min: "lumge" }, { en: "rio", min: "lue" }, { en: "ritalin", min: "ludarum" },
  { en: "ritz", min: "luds" }, { en: "rivera", min: "lufola" }, { en: "riverside", min: "lufolzuto" }, { en: "riviera", min: "lufuola" }, { en: "roach", min: "leakh" }, { en: "roanoke", min: "leameco" }, { en: "rob", min: "lep" }, { en: "roberson", min: "lepolzem" }, { en: "robert", min: "lepold" }, { en: "roberto", min: "lepolde" },
  { en: "robertson", min: "lepoldzem" }, { en: "robeson", min: "lepozem" }, { en: "robinson", min: "lepumzem" }, { en: "robitussin", min: "lepudizzum" }, { en: "robson", min: "lepzem" }, { en: "robt", min: "lepd" }, { en: "rocco", min: "lekke" }, { en: "rocha", min: "lekha" }, { en: "rochambeau", min: "lekhanpoai" }, { en: "roche", min: "lekho" },
  { en: "rock", min: "lekc" }, { en: "rockford", min: "lekcvelt" }, { en: "rockne", min: "lekcmo" }, { en: "rockwell", min: "lekcworr" }, { en: "rod", min: "let" }, { en: "roderick", min: "letolukc" }, { en: "rodin", min: "letum" }, { en: "rodolfo", min: "leterve" }, { en: "rodrick", min: "letlukc" }, { en: "rodrigo", min: "letluge" },
  { en: "rodriguez", min: "letlugios" }, { en: "rodriquez", min: "letlujios" }, { en: "roeg", min: "leog" }, { en: "roentgen", min: "leomdgom" }, { en: "rogelio", min: "legorue" }, { en: "roget", min: "legod" }, { en: "roku", min: "leci" }, { en: "roland", min: "leramt" }, { en: "rolando", min: "leramte" }, { en: "rolland", min: "lerramt" },
  { en: "rolodex", min: "leretox" }, { en: "rolvaag", min: "lerfaag" }, { en: "roman", min: "lenam" }, { en: "romanesque", min: "lenamozjio" }, { en: "romanian", min: "lenamuam" }, { en: "romano", min: "lename" }, { en: "romanov", min: "lenamef" }, { en: "romansh", min: "lenamzh" }, { en: "rome", min: "leno" }, { en: "romeo", min: "lenoe" },
  { en: "romero", min: "lenole" }, { en: "rommel", min: "lennor" }, { en: "ron", min: "lem" }, { en: "ronald", min: "lemart" }, { en: "ronstadt", min: "lemzdatd" }, { en: "roosevelt", min: "leezoford" }, { en: "root", min: "leed" }, { en: "roquefort", min: "lejioveld" }, { en: "rorschach", min: "lelzkhakh" }, { en: "rosario", min: "lezalue" },
  { en: "roscoe", min: "lezkeo" }, { en: "rosenberg", min: "lezompolg" }, { en: "rosendo", min: "lezomte" }, { en: "rosenzweig", min: "lezomswoug" }, { en: "rossetti", min: "lezzoddu" }, { en: "rossini", min: "lezzumu" }, { en: "rostand", min: "lezdamt" }, { en: "rostov", min: "lezdef" }, { en: "roswell", min: "lezworr" }, { en: "rotarian", min: "ledaluam" },
  { en: "rothko", min: "ledhce" }, { en: "rothschild", min: "ledhzkhurt" }, { en: "rotterdam", min: "leddoltan" }, { en: "rouault", min: "leiaird" }, { en: "roumania", min: "leinamua" }, { en: "rourke", min: "leilco" }, { en: "rousseau", min: "leizzoai" }, { en: "rove", min: "lefo" }, { en: "rowland", min: "lewramt" }, { en: "royce", min: "leyko" },
  { en: "rte", min: "ldo" }, { en: "rubaiyat", min: "lipauyad" }, { en: "rubbermaid", min: "lippolnaut" }, { en: "ruben", min: "lipom" }, { en: "rubicon", min: "lipukem" }, { en: "rubik", min: "lipuc" }, { en: "rubin", min: "lipum" }, { en: "rubinstein", min: "lipumzdoum" }, { en: "ruchbah", min: "likhpah" }, { en: "rudolf", min: "literv" },
  { en: "rudolph", min: "literbh" }, { en: "rudyard", min: "lityalt" }, { en: "ruhr", min: "lihl" }, { en: "ruiz", min: "lius" }, { en: "rumania", min: "linamua" }, { en: "rumsfeld", min: "linzvort" }, { en: "runnymede", min: "limmynoto" }, { en: "runyon", min: "limyem" }, { en: "rupert", min: "libold" }, { en: "rush", min: "lizh" },
  { en: "rushdie", min: "lizhtuo" }, { en: "rushmore", min: "lizhnelo" }, { en: "ruskin", min: "lizcum" }, { en: "russel", min: "lizzor" }, { en: "russell", min: "lizzorr" }, { en: "russo", min: "lizze" }, { en: "rustbelt", min: "lizdpord" }, { en: "rutan", min: "lidam" }, { en: "rutherford", min: "lidholvelt" }, { en: "rutledge", min: "lidrotgo" },
  { en: "rwandan", min: "lwamtam" }, { en: "ryan", min: "lyam" }, { en: "rydberg", min: "lytpolg" }, { en: "ryukyu", min: "lyicyi" }, { en: "salt", min: "zard" }, { en: "sap", min: "zab" }, { en: "sase", min: "zazo" }, { en: "sat", min: "zad" }, { en: "sec", min: "zok" }, { en: "sjw", min: "zqw" },
  { en: "slr", min: "zrl" }, { en: "sop", min: "zeb" }, { en: "sql", min: "zjr" }, { en: "sqlite", min: "zjrudo" }, { en: "sro", min: "zle" }, { en: "ssa", min: "zza" }, { en: "sst", min: "zzd" }, { en: "std", min: "zdt" }, { en: "stol", min: "zder" }, { en: "suse", min: "zizo" },
  { en: "suv", min: "zif" }, { en: "svn", min: "zfm" }, { en: "swat", min: "zwad" }, { en: "saab", min: "zaap" }, { en: "saarinen", min: "zaalumom" }, { en: "saatchi", min: "zaadkhu" }, { en: "sabik", min: "zapuc" }, { en: "sabin", min: "zapum" }, { en: "sabre", min: "zaplo" }, { en: "sacajawea", min: "zakaqawoa" },
  { en: "sacco", min: "zakke" }, { en: "sacramento", min: "zaklanomde" }, { en: "sadat", min: "zatad" }, { en: "saddam", min: "zattan" }, { en: "sadducee", min: "zattikoo" }, { en: "sade", min: "zato" }, { en: "sadr", min: "zatl" }, { en: "safavid", min: "zavafut" }, { en: "sagan", min: "zagam" }, { en: "saginaw", min: "zagumaw" },
  { en: "sahel", min: "zahor" }, { en: "saigon", min: "zaugem" }, { en: "saiph", min: "zaubh" }, { en: "sakai", min: "zacau" }, { en: "sakha", min: "zacha" }, { en: "sakhalin", min: "zacharum" }, { en: "sakharov", min: "zachalef" }, { en: "saki", min: "zacu" }, { en: "saladin", min: "zaratum" }, { en: "salado", min: "zarate" },
  { en: "salem", min: "zaron" }, { en: "salerno", min: "zarolme" }, { en: "salesforce", min: "zarozvelko" }, { en: "salk", min: "zarc" }, { en: "sallust", min: "zarrizd" }, { en: "salton", min: "zardem" }, { en: "salvadoran", min: "zarfatelam" }, { en: "salvatore", min: "zarfadelo" }, { en: "salween", min: "zarwoom" }, { en: "salyut", min: "zaryid" },
];
