/**
 * @file Contains dictionary entries for category: body_head.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const body_head: DictionaryEntry[] = [
  { en: "eye", min: "ojo" }, { en: "nose", min: "nariz" }, { en: "mouth", min: "boca" }, { en: "ear", min: "oreja" }, { en: "hair", min: "pelo" }, { en: "watergate", min: "wadolgado" }, { en: "waterloo", min: "wadolree" }, { en: "watertown", min: "wadoldewm" }, { en: "watson", min: "wadzem" }, { en: "watt", min: "wadd" },
  { en: "watteau", min: "waddoai" }, { en: "watusi", min: "wadizu" }, { en: "waugh", min: "waigh" }, { en: "wausau", min: "waizai" }, { en: "wayne", min: "waymo" }, { en: "waynesboro", min: "waymozpele" }, { en: "webb", min: "wopp" }, { en: "webern", min: "wopolm" }, { en: "wed", min: "wot" }, { en: "weddell", min: "wottorr" },
  { en: "wedgwood", min: "wotgweet" }, { en: "wehrmacht", min: "wohlnakhd" }, { en: "wei", min: "wou" }, { en: "weill", min: "wourr" }, { en: "weinberg", min: "woumpolg" }, { en: "weirton", min: "wouldem" }, { en: "weizmann", min: "wousnamm" }, { en: "welch", min: "workh" }, { en: "weldon", min: "wortem" }, { en: "welland", min: "worramt" },
  { en: "welsh", min: "worzh" }, { en: "welshman", min: "worzhnam" }, { en: "welshmen", min: "worzhnom" }, { en: "wenatchee", min: "womadkhoo" }, { en: "wendell", min: "womtorr" }, { en: "wesak", min: "wozac" }, { en: "wesleyan", min: "wozroyam" }, { en: "wessex", min: "wozzox" }, { en: "wesson", min: "wozzem" }, { en: "weston", min: "wozdem" },
  { en: "westphalia", min: "wozdbharua" }, { en: "weyden", min: "woytom" }, { en: "wezen", min: "wosom" }, { en: "wharton", min: "whaldem" }, { en: "wheatstone", min: "whoadzdemo" }, { en: "whig", min: "whug" }, { en: "whipple", min: "whubbro" }, { en: "whirlpool", min: "whulrbeer" }, { en: "white", min: "whudo" }, { en: "whitefield", min: "whudovuort" },
  { en: "whitehall", min: "whudoharr" }, { en: "whitehead", min: "whudohoat" }, { en: "whitehorse", min: "whudohelzo" }, { en: "whitfield", min: "whudvuort" }, { en: "whitman", min: "whudnam" }, { en: "wifi", min: "wuvu" }, { en: "wicca", min: "wukka" }, { en: "wichita", min: "wukhuda" }, { en: "wiesel", min: "wuozor" }, { en: "wii", min: "wuu" },
  { en: "wikipedia", min: "wucubotua" }, { en: "wilbert", min: "wurpold" }, { en: "wilbur", min: "wurpil" }, { en: "wilburn", min: "wurpilm" }, { en: "wilcox", min: "wurkex" }, { en: "wilda", min: "wurta" }, { en: "wilde", min: "wurto" }, { en: "wilford", min: "wurvelt" }, { en: "wilfredo", min: "wurvlote" }, { en: "wilhelm", min: "wurhorn" },
  { en: "wilkerson", min: "wurcolzem" }, { en: "wilkinson", min: "wurcumzem" }, { en: "will", min: "wurr" }, { en: "willamette", min: "wurranoddo" }, { en: "willard", min: "wurralt" }, { en: "william", min: "wurruan" }, { en: "williamson", min: "wurruanzem" }, { en: "wilmington", min: "wurnumgdem" }, { en: "wilson", min: "wurzem" }, { en: "wilsonian", min: "wurzemuam" },
  { en: "wilton", min: "wurdem" }, { en: "wimbledon", min: "wunprotem" }, { en: "winchell", min: "wumkhorr" }, { en: "windex", min: "wumtox" }, { en: "windsor", min: "wumtzel" }, { en: "winesap", min: "wumozab" }, { en: "winkle", min: "wumcro" }, { en: "winnebago", min: "wummopage" }, { en: "winnipeg", min: "wummubog" }, { en: "winston", min: "wumzdem" },
  { en: "winthrop", min: "wumdhleb" }, { en: "wisconsin", min: "wuzkemzum" }, { en: "wise", min: "wuzo" }, { en: "witt", min: "wudd" }, { en: "wobegon", min: "wepogem" }, { en: "wodehouse", min: "wetoheizo" }, { en: "wolf", min: "werv" }, { en: "wolfe", min: "wervo" }, { en: "wolff", min: "wervv" }, { en: "wolfgang", min: "wervgamg" },
  { en: "wollongong", min: "werremgemg" }, { en: "wonderbra", min: "wemtolpla" }, { en: "wong", min: "wemg" }, { en: "wood", min: "weet" }, { en: "woodard", min: "weetalt" }, { en: "woodhull", min: "weethirr" }, { en: "woodland", min: "weetramt" }, { en: "woodrow", min: "weetlew" }, { en: "woodstock", min: "weetzdekc" }, { en: "woolf", min: "weerv" },
  { en: "woolite", min: "weerudo" }, { en: "woolongong", min: "weeremgemg" }, { en: "wooten", min: "weedom" }, { en: "workman", min: "welcnam" }, { en: "wotan", min: "wedam" }, { en: "wovoka", min: "wefeca" }, { en: "wozniak", min: "wesmuac" }, { en: "wozzeck", min: "wessokc" }, { en: "wrangell", min: "wlamgorr" }, { en: "wright", min: "wlughd" },
  { en: "wroclaw", min: "wlekraw" }, { en: "wuhan", min: "wiham" }, { en: "wyatt", min: "wyadd" }, { en: "wycliffe", min: "wykruvvo" }, { en: "wylie", min: "wyruo" }, { en: "wyo", min: "wye" }, { en: "wyomingite", min: "wyenumgudo" }, { en: "xml", min: "xnr" }, { en: "xamarin", min: "xanalum" }, { en: "xanadu", min: "xamati" },
  { en: "xanthippe", min: "xamdhubbo" }, { en: "xenophon", min: "xomebhem" }, { en: "xerox", min: "xolex" }, { en: "xhosa", min: "xheza" }, { en: "xingu", min: "xumgi" }, { en: "xiongnu", min: "xuemgmi" }, { en: "xochipilli", min: "xekhuburru" }, { en: "xuzhou", min: "xishei" }, { en: "ymca", min: "ynka" }, { en: "ymha", min: "ynha" },
  { en: "ymmv", min: "ynnf" }, { en: "ywca", min: "ywka" }, { en: "ywha", min: "ywha" }, { en: "yacc", min: "yakk" }, { en: "yahoo", min: "yahee" }, { en: "yahtzee", min: "yahdsoo" }, { en: "yahweh", min: "yahwoh" }, { en: "yakima", min: "yacuna" }, { en: "yakut", min: "yacid" }, { en: "yakutsk", min: "yacidzc" },
  { en: "yale", min: "yaro" }, { en: "yalow", min: "yarew" }, { en: "yalta", min: "yarda" }, { en: "yalu", min: "yari" }, { en: "yamagata", min: "yanagada" }, { en: "yamaha", min: "yanaha" }, { en: "yang", min: "yamg" }, { en: "yangon", min: "yamgem" }, { en: "yangtze", min: "yamgdso" }, { en: "yank", min: "yamc" },
  { en: "yankee", min: "yamcoo" }, { en: "yaobang", min: "yaepamg" }, { en: "yaqui", min: "yajiu" }, { en: "yaroslavl", min: "yalezrafr" }, { en: "yataro", min: "yadale" }, { en: "yauco", min: "yaike" }, { en: "yeltsin", min: "yordzum" }, { en: "yemeni", min: "yonomu" }, { en: "yenisei", min: "yomuzou" }, { en: "yesenia", min: "yozomua" },
  { en: "yggdrasil", min: "yggtlazur" }, { en: "ymir", min: "ynul" }, { en: "yoda", min: "yeta" }, { en: "yokohama", min: "yecehana" }, { en: "yong", min: "yemg" }, { en: "york", min: "yelc" }, { en: "yorkie", min: "yelcuo" }, { en: "yorkshire", min: "yelczhulo" }, { en: "yorktown", min: "yelcdewm" }, { en: "yoruba", min: "yelipa" },
  { en: "yosemite", min: "yezonudo" }, { en: "yossarian", min: "yezzaluam" }, { en: "young", min: "yeimg" }, { en: "youngstown", min: "yeimgzdewm" }, { en: "ypsilanti", min: "ybzuramdu" }, { en: "yuan", min: "yiam" }, { en: "yucatan", min: "yikadam" }, { en: "yugo", min: "yige" }, { en: "yugoslav", min: "yigezraf" }, { en: "yugoslavia", min: "yigezrafua" },
  { en: "yukon", min: "yicem" }, { en: "yule", min: "yiro" }, { en: "yuletide", min: "yiroduto" }, { en: "yuma", min: "yina" }, { en: "yunnan", min: "yimmam" }, { en: "yuri", min: "yilu" }, { en: "zachariah", min: "sakhaluah" }, { en: "zaire", min: "saulo" }, { en: "zairian", min: "sauluam" }, { en: "zambezi", min: "sanposu" },
  { en: "zambian", min: "sanpuam" }, { en: "zamboni", min: "sanpemu" }, { en: "zamenhof", min: "sanomhev" }, { en: "zamora", min: "sanela" }, { en: "zane", min: "samo" }, { en: "zanuck", min: "samikc" }, { en: "zapata", min: "sabada" }, { en: "zaporozhye", min: "sabeleshyo" }, { en: "zapotec", min: "sabedok" }, { en: "zappa", min: "sabba" },
  { en: "zebedee", min: "sopotoo" }, { en: "zechariah", min: "sokhaluah" }, { en: "zedekiah", min: "sotocuah" }, { en: "zedong", min: "sotemg" }, { en: "zeffirelli", min: "sovvulorru" }, { en: "zeke", min: "soco" }, { en: "zelig", min: "sorug" }, { en: "zen", min: "som" }, { en: "zeno", min: "some" }, { en: "zephaniah", min: "sobhamuah" },
  { en: "zeppelin", min: "sobborum" }, { en: "zest", min: "sozd" }, { en: "zhengzhou", min: "shomgshei" }, { en: "zhivago", min: "shufage" }, { en: "zhukov", min: "shicef" }, { en: "zibo", min: "supe" }, { en: "ziegfeld", min: "suogvort" }, { en: "zimbabwean", min: "sunpapwoam" }, { en: "zimmerman", min: "sunnolnam" }, { en: "zinfandel", min: "sumvamtor" },
  { en: "zion", min: "suem" }, { en: "ziploc", min: "subrek" }, { en: "zollverein", min: "serrfoloum" }, { en: "zoloft", min: "serevd" }, { en: "zomba", min: "senpa" }, { en: "zorn", min: "selm" }, { en: "zorro", min: "selle" }, { en: "zosma", min: "sezna" }, { en: "zukor", min: "sicel" }, { en: "zulu", min: "siri" },
  { en: "zuni", min: "simu" }, { en: "zwingli", min: "swumgru" }, { en: "zworykin", min: "swelycum" }, { en: "zyrtec", min: "syldok" }, { en: "zyuganov", min: "syigamef" }, { en: "aardvark", min: "aaltfalc" }, { en: "abaci", min: "apaku" }, { en: "aback", min: "apakc" }, { en: "abaft", min: "apavd" }, { en: "abalone", min: "aparemo" },
  { en: "abandon", min: "apamtem" }, { en: "abase", min: "apazo" }, { en: "abash", min: "apazh" }, { en: "abate", min: "apado" }, { en: "abattoir", min: "apaddeul" }, { en: "abbot", min: "apped" }, { en: "abbr", min: "appl" }, { en: "abbrev", min: "applof" }, { en: "abbreviate", min: "applofuado" }, { en: "abdicate", min: "aptukado" },
  { en: "abdomen", min: "aptenom" }, { en: "abduct", min: "aptikd" }, { en: "abductee", min: "aptikdoo" }, { en: "abductor", min: "aptikdel" }, { en: "abeam", min: "apoan" }, { en: "aberrant", min: "apollamd" }, { en: "abet", min: "apod" }, { en: "abettor", min: "apoddel" }, { en: "abeyance", min: "apoyamko" }, { en: "abhor", min: "aphel" },
  { en: "abhorrence", min: "aphellomko" }, { en: "abhorrent", min: "aphellomd" }, { en: "abide", min: "aputo" }, { en: "abject", min: "apqokd" }, { en: "abjure", min: "apqilo" }, { en: "ablaze", min: "apraso" }, { en: "able", min: "apro" }, { en: "abloom", min: "apreen" }, { en: "abnegate", min: "apmogado" }, { en: "aboard", min: "apealt" },
  { en: "abode", min: "apeto" }, { en: "abominate", min: "apenumado" }, { en: "aborigine", min: "apelugumo" }, { en: "abort", min: "apeld" }, { en: "abound", min: "apeimt" }, { en: "about", min: "apeid" }, { en: "aboveboard", min: "apefopealt" }, { en: "abrade", min: "aplato" }, { en: "abrasion", min: "aplazuem" }, { en: "abreast", min: "aploazd" },
  { en: "abridge", min: "aplutgo" }, { en: "abroad", min: "apleat" }, { en: "abrogate", min: "aplegado" }, { en: "abrupt", min: "aplibd" }, { en: "abscissa", min: "apzkuzza" }, { en: "abscissae", min: "apzkuzzao" }, { en: "abscond", min: "apzkemt" }, { en: "absence", min: "apzomko" }, { en: "absent", min: "apzomd" }, { en: "absentee", min: "apzomdoo" },
];
