/**
 * @file Contains dictionary entries for category: body_limb.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const body_limb: DictionaryEntry[] = [
  { en: "arm", min: "brazo" }, { en: "leg", min: "pierna" }, { en: "hand", min: "mano" }, { en: "foot", min: "pie" }, { en: "finger", min: "dedo" }, { en: "absinthe", min: "apzumdho" }, { en: "absolute", min: "apzerido" }, { en: "absolve", min: "apzerfo" }, { en: "absorb", min: "apzelp" }, { en: "absorbent", min: "apzelpomd" },
  { en: "abstain", min: "apzdaum" }, { en: "abstinence", min: "apzdumomko" }, { en: "abstinent", min: "apzdumomd" }, { en: "abstract", min: "apzdlakd" }, { en: "abstruse", min: "apzdlizo" }, { en: "absurd", min: "apzilt" }, { en: "abundance", min: "apimtamko" }, { en: "abundant", min: "apimtamd" }, { en: "abuse", min: "apizo" }, { en: "abut", min: "apid" },
  { en: "abuzz", min: "apiss" }, { en: "acacia", min: "akakua" }, { en: "academia", min: "akatonua" }, { en: "acanthi", min: "akamdhu" }, { en: "accede", min: "akkoto" }, { en: "accelerate", min: "akkorolado" }, { en: "accent", min: "akkomd" }, { en: "accentuate", min: "akkomdiado" }, { en: "accept", min: "akkobd" }, { en: "acceptance", min: "akkobdamko" },
  { en: "accession", min: "akkozzuem" }, { en: "accident", min: "akkutomd" }, { en: "acclaim", min: "akkraun" }, { en: "acclimate", min: "akkrunado" }, { en: "accolade", min: "akkerato" }, { en: "accomplice", min: "akkenbruko" }, { en: "accord", min: "akkelt" }, { en: "accordance", min: "akkeltamko" }, { en: "accordion", min: "akkeltuem" }, { en: "accost", min: "akkezd" },
  { en: "account", min: "akkeimd" }, { en: "accountant", min: "akkeimdamd" }, { en: "accredit", min: "akklotud" }, { en: "accrue", min: "akklio" }, { en: "acct", min: "akkd" }, { en: "accumulate", min: "akkinirado" }, { en: "accurate", min: "akkilado" }, { en: "accurst", min: "akkilzd" }, { en: "accuse", min: "akkizo" }, { en: "accustom", min: "akkizden" },
  { en: "ace", min: "ako" }, { en: "acetate", min: "akodado" }, { en: "acetone", min: "akodemo" }, { en: "acetylene", min: "akodyromo" }, { en: "ache", min: "akho" }, { en: "achieve", min: "akhuofo" }, { en: "achoo", min: "akhee" }, { en: "acid", min: "akut" }, { en: "acme", min: "akno" }, { en: "acne", min: "akmo" },
  { en: "acolyte", min: "akerydo" }, { en: "aconite", min: "akemudo" }, { en: "acorn", min: "akelm" }, { en: "acquaint", min: "akjiaumd" }, { en: "acquiesce", min: "akjiuozko" }, { en: "acquire", min: "akjiulo" }, { en: "acquit", min: "akjiud" }, { en: "acre", min: "aklo" }, { en: "acreage", min: "akloago" }, { en: "acrid", min: "aklut" },
  { en: "acrobat", min: "aklepad" }, { en: "acronym", min: "aklemyn" }, { en: "actinium", min: "akdumuin" }, { en: "activate", min: "akdufado" }, { en: "actor", min: "akdel" }, { en: "actualize", min: "akdiaruso" }, { en: "actuate", min: "akdiado" }, { en: "actuator", min: "akdiadel" }, { en: "acumen", min: "akinom" }, { en: "acute", min: "akido" },
  { en: "adage", min: "atago" }, { en: "adagio", min: "atague" }, { en: "adamant", min: "atanamd" }, { en: "adapt", min: "atabd" }, { en: "adaptor", min: "atabdel" }, { en: "add", min: "att" }, { en: "addend", min: "attomt" }, { en: "addenda", min: "attomta" }, { en: "addendum", min: "attomtin" }, { en: "addict", min: "attukd" },
  { en: "addle", min: "attro" }, { en: "addressee", min: "attlozzoo" }, { en: "adduce", min: "attiko" }, { en: "adenoid", min: "atomeut" }, { en: "adept", min: "atobd" }, { en: "adequate", min: "atojiado" }, { en: "adhere", min: "atholo" }, { en: "adherence", min: "atholomko" }, { en: "adherent", min: "atholomd" }, { en: "adhesion", min: "athozuem" },
  { en: "adieu", min: "atuoi" }, { en: "adieux", min: "atuoix" }, { en: "adipose", min: "atubezo" }, { en: "adj", min: "atq" }, { en: "adjacent", min: "atqakomd" }, { en: "adjoin", min: "atqeum" }, { en: "adjourn", min: "atqeilm" }, { en: "adjudge", min: "atqitgo" }, { en: "adjudicate", min: "atqitukado" }, { en: "adjunct", min: "atqimkd" },
  { en: "adjure", min: "atqilo" }, { en: "adjust", min: "atqizd" }, { en: "adjustor", min: "atqizdel" }, { en: "adjutant", min: "atqidamd" }, { en: "adman", min: "atnam" }, { en: "admen", min: "atnom" }, { en: "admin", min: "atnum" }, { en: "admire", min: "atnulo" }, { en: "admission", min: "atnuzzuem" }, { en: "admit", min: "atnud" },
  { en: "admittance", min: "atnuddamko" }, { en: "admixture", min: "atnuxdilo" }, { en: "ado", min: "ate" }, { en: "adolescent", min: "aterozkomd" }, { en: "adopt", min: "atebd" }, { en: "adorn", min: "atelm" }, { en: "adrenalin", min: "atlomarum" }, { en: "adrenaline", min: "atlomarumo" }, { en: "adrift", min: "atluvd" }, { en: "adroit", min: "atleud" },
  { en: "adulate", min: "atirado" }, { en: "adult", min: "atird" }, { en: "adulterant", min: "atirdolamd" }, { en: "adulterate", min: "atirdolado" }, { en: "adumbrate", min: "atinplado" }, { en: "adv", min: "atf" }, { en: "advance", min: "atfamko" }, { en: "advantage", min: "atfamdago" }, { en: "adventure", min: "atfomdilo" }, { en: "adverb", min: "atfolp" },
  { en: "adverse", min: "atfolzo" }, { en: "advert", min: "atfold" }, { en: "advertise", min: "atfolduzo" }, { en: "advice", min: "atfuko" }, { en: "advise", min: "atfuzo" }, { en: "advisor", min: "atfuzel" }, { en: "advocate", min: "atfekado" }, { en: "advt", min: "atfd" }, { en: "adware", min: "atwalo" }, { en: "adz", min: "ats" },
  { en: "adze", min: "atso" }, { en: "aeon", min: "aoem" }, { en: "aerate", min: "aolado" }, { en: "aerator", min: "aoladel" }, { en: "aerie", min: "aoluo" }, { en: "aerosol", min: "aolezer" }, { en: "aerospace", min: "aolezbako" }, { en: "aesthete", min: "aozdhodo" }, { en: "affair", min: "avvaul" }, { en: "affect", min: "avvokd" },
  { en: "affidavit", min: "avvutafud" }, { en: "affiliate", min: "avvuruado" }, { en: "affirm", min: "avvuln" }, { en: "affix", min: "avvux" }, { en: "afflict", min: "avvrukd" }, { en: "affluence", min: "avvriomko" }, { en: "affluent", min: "avvriomd" }, { en: "afford", min: "avvelt" }, { en: "affront", min: "avvlemd" }, { en: "aficionado", min: "avukuemate" },
  { en: "afield", min: "avuort" }, { en: "afire", min: "avulo" }, { en: "aflame", min: "avrano" }, { en: "afloat", min: "avread" }, { en: "afoot", min: "aveed" }, { en: "aforesaid", min: "avelozaut" }, { en: "afoul", min: "aveir" }, { en: "afraid", min: "avlaut" }, { en: "afresh", min: "avlozh" }, { en: "aft", min: "avd" },
  { en: "aftercare", min: "avdolkalo" }, { en: "afterglow", min: "avdolgrew" }, { en: "afterlife", min: "avdolruvo" }, { en: "afternoon", min: "avdolmeem" }, { en: "aftershave", min: "avdolzhafo" }, { en: "aftershock", min: "avdolzhekc" }, { en: "aftertaste", min: "avdoldazdo" }, { en: "afterword", min: "avdolwelt" }, { en: "again", min: "agaum" }, { en: "against", min: "agaumzd" },
  { en: "agape", min: "agabo" }, { en: "agate", min: "agado" }, { en: "agave", min: "agafo" }, { en: "age", min: "ago" }, { en: "agenda", min: "agomta" }, { en: "agent", min: "agomd" }, { en: "aggrandize", min: "agglamtuso" }, { en: "aggravate", min: "agglafado" }, { en: "aggregate", min: "agglogado" }, { en: "aggression", min: "agglozzuem" },
  { en: "aggressor", min: "agglozzel" }, { en: "aggrieve", min: "aggluofo" }, { en: "aghast", min: "aghazd" }, { en: "agile", min: "aguro" }, { en: "agitate", min: "agudado" }, { en: "agitator", min: "agudadel" }, { en: "agleam", min: "agroan" }, { en: "aglow", min: "agrew" }, { en: "ago", min: "age" }, { en: "agog", min: "ageg" },
  { en: "agonize", min: "agemuso" }, { en: "agrarian", min: "aglaluam" }, { en: "agree", min: "agloo" }, { en: "aground", min: "agleimt" }, { en: "ague", min: "agio" }, { en: "aha", min: "aha" }, { en: "ahead", min: "ahoat" }, { en: "ahem", min: "ahon" }, { en: "aid", min: "aut" }, { en: "aide", min: "auto" },
  { en: "ail", min: "aur" }, { en: "aileron", min: "aurolem" }, { en: "aim", min: "aun" }, { en: "air", min: "aul" }, { en: "airborne", min: "aulpelmo" }, { en: "airbrush", min: "aulplizh" }, { en: "aircraft", min: "aulklavd" }, { en: "airdrop", min: "aultleb" }, { en: "airfare", min: "aulvalo" }, { en: "airfield", min: "aulvuort" },
  { en: "airfoil", min: "aulveur" }, { en: "airhead", min: "aulhoat" }, { en: "airlift", min: "aulruvd" }, { en: "airline", min: "aulrumo" }, { en: "airmail", min: "aulnaur" }, { en: "airman", min: "aulnam" }, { en: "airmen", min: "aulnom" }, { en: "airplane", min: "aulbramo" }, { en: "airport", min: "aulbeld" }, { en: "airsick", min: "aulzukc" },
  { en: "airspace", min: "aulzbako" }, { en: "airstrip", min: "aulzdlub" }, { en: "airtight", min: "auldughd" }, { en: "aisle", min: "auzro" }, { en: "akimbo", min: "acunpe" }, { en: "akin", min: "acum" }, { en: "alarm", min: "araln" }, { en: "alb", min: "arp" }, { en: "albacore", min: "arpakelo" }, { en: "albeit", min: "arpoud" },
  { en: "albino", min: "arpume" }, { en: "album", min: "arpin" }, { en: "albumen", min: "arpinom" }, { en: "albumin", min: "arpinum" }, { en: "alcohol", min: "arkeher" }, { en: "alcove", min: "arkefo" }, { en: "alderman", min: "artolnam" }, { en: "aldermen", min: "artolnom" }, { en: "alderwoman", min: "artolwenam" }, { en: "alderwomen", min: "artolwenom" },
  { en: "ale", min: "aro" }, { en: "alert", min: "arold" }, { en: "alfalfa", min: "arvarva" }, { en: "alfresco", min: "arvlozke" }, { en: "alga", min: "arga" }, { en: "algae", min: "argao" }, { en: "algebra", min: "argopla" }, { en: "algorithm", min: "argeludhn" }, { en: "alibi", min: "arupu" }, { en: "alien", min: "aruom" },
  { en: "alienate", min: "aruomado" }, { en: "alight", min: "arughd" }, { en: "align", min: "arugm" }, { en: "alike", min: "aruco" }, { en: "alit", min: "arud" }, { en: "alkali", min: "arcaru" }, { en: "alkaline", min: "arcarumo" }, { en: "alkaloid", min: "arcareut" }, { en: "all", min: "arr" }, { en: "allege", min: "arrogo" },
  { en: "allegiance", min: "arroguamko" }, { en: "allegro", min: "arrogle" }, { en: "alleluia", min: "arroriua" }, { en: "allergen", min: "arrolgom" }, { en: "alleviate", min: "arrofuado" }, { en: "alliance", min: "arruamko" }, { en: "alligator", min: "arrugadel" }, { en: "allocate", min: "arrekado" }, { en: "allot", min: "arred" }, { en: "allow", min: "arrew" },
  { en: "allowance", min: "arrewamko" }, { en: "allspice", min: "arrzbuko" }, { en: "allude", min: "arrito" }, { en: "allure", min: "arrilo" }, { en: "allusion", min: "arrizuem" }, { en: "alluvia", min: "arrifua" }, { en: "alluvium", min: "arrifuin" }, { en: "almanac", min: "arnamak" }, { en: "almond", min: "arnemt" }, { en: "almost", min: "arnezd" },
];
