/**
 * @file Contains dictionary entries for category: body_organs.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const body_organs: DictionaryEntry[] = [
  { en: "heart", min: "kokoro" }, { en: "brain", min: "cerebro" }, { en: "blood", min: "sangre" }, { en: "bone", min: "hueso" }, { en: "skin", min: "piel" }, { en: "aloe", min: "areo" }, { en: "aloft", min: "arevd" }, { en: "aloha", min: "areha" }, { en: "alone", min: "aremo" }, { en: "along", min: "aremg" },
  { en: "alongside", min: "aremgzuto" }, { en: "aloof", min: "areev" }, { en: "aloud", min: "areit" }, { en: "alpaca", min: "arbaka" }, { en: "alpha", min: "arbha" }, { en: "alphabet", min: "arbhapod" }, { en: "alright", min: "arlughd" }, { en: "also", min: "arze" }, { en: "alt", min: "ard" }, { en: "alternate", min: "ardolmado" },
  { en: "alternator", min: "ardolmadel" }, { en: "altho", min: "ardhe" }, { en: "although", min: "ardheigh" }, { en: "altitude", min: "ardudito" }, { en: "alto", min: "arde" }, { en: "alum", min: "arin" }, { en: "aluminum", min: "arinumin" }, { en: "alumna", min: "arinma" }, { en: "alumnae", min: "arinmao" }, { en: "alumni", min: "arinmu" },
  { en: "amalgam", min: "anargan" }, { en: "amalgamate", min: "anarganado" }, { en: "amateur", min: "anadoil" }, { en: "amaze", min: "anaso" }, { en: "ambassador", min: "anpazzatel" }, { en: "ambiance", min: "anpuamko" }, { en: "ambience", min: "anpuomko" }, { en: "ambient", min: "anpuomd" }, { en: "ambivalent", min: "anpufaromd" }, { en: "amble", min: "anpro" },
  { en: "ambrosia", min: "anplezua" }, { en: "ambulance", min: "anpiramko" }, { en: "ambush", min: "anpizh" }, { en: "ameba", min: "anopa" }, { en: "amebae", min: "anopao" }, { en: "ameliorate", min: "anoruelado" }, { en: "amen", min: "anom" }, { en: "amend", min: "anomt" }, { en: "amethyst", min: "anodhyzd" }, { en: "amid", min: "anut" },
  { en: "amidst", min: "anutzd" }, { en: "amigo", min: "anuge" }, { en: "amino", min: "anume" }, { en: "amir", min: "anul" }, { en: "ammo", min: "anne" }, { en: "ammonia", min: "annemua" }, { en: "amnesia", min: "anmozua" }, { en: "amnesiac", min: "anmozuak" }, { en: "amoeba", min: "aneopa" }, { en: "amoebae", min: "aneopao" },
  { en: "amok", min: "anec" }, { en: "among", min: "anemg" }, { en: "amongst", min: "anemgzd" }, { en: "amortize", min: "anelduso" }, { en: "amount", min: "aneimd" }, { en: "amour", min: "aneil" }, { en: "amp", min: "anb" }, { en: "amperage", min: "anbolago" }, { en: "ampersand", min: "anbolzamt" }, { en: "amphibian", min: "anbhupuam" },
  { en: "ample", min: "anbro" }, { en: "amplitude", min: "anbrudito" }, { en: "ampoule", min: "anbeiro" }, { en: "ampul", min: "anbir" }, { en: "ampule", min: "anbiro" }, { en: "amputate", min: "anbidado" }, { en: "amputee", min: "anbidoo" }, { en: "amt", min: "and" }, { en: "amuck", min: "anikc" }, { en: "amulet", min: "anirod" },
  { en: "amuse", min: "anizo" }, { en: "anaconda", min: "amakemta" }, { en: "anaemia", min: "amaonua" }, { en: "anagram", min: "amaglan" }, { en: "analgesia", min: "amargozua" }, { en: "analog", min: "amareg" }, { en: "analogue", min: "amaregio" }, { en: "analyst", min: "amaryzd" }, { en: "analyze", min: "amaryso" }, { en: "anathema", min: "amadhona" },
  { en: "ancestor", min: "amkozdel" }, { en: "anchor", min: "amkhel" }, { en: "anchorite", min: "amkheludo" }, { en: "anchorman", min: "amkhelnam" }, { en: "anchormen", min: "amkhelnom" }, { en: "ancient", min: "amkuomd" }, { en: "andante", min: "amtamdo" }, { en: "andiron", min: "amtulem" }, { en: "androgen", min: "amtlegom" }, { en: "anecdota", min: "amokteda" },
  { en: "anecdote", min: "amoktedo" }, { en: "anemia", min: "amonua" }, { en: "anemone", min: "amonemo" }, { en: "anesthesia", min: "amozdhozua" }, { en: "aneurysm", min: "amoilyzn" }, { en: "anew", min: "amow" }, { en: "angina", min: "amguma" }, { en: "angiosperm", min: "amguezboln" }, { en: "angle", min: "amgro" }, { en: "angleworm", min: "amgroweln" },
  { en: "angst", min: "amgzd" }, { en: "angstrom", min: "amgzdlen" }, { en: "ani", min: "amu" }, { en: "animate", min: "amunado" }, { en: "animator", min: "amunadel" }, { en: "anime", min: "amuno" }, { en: "anion", min: "amuem" }, { en: "anise", min: "amuzo" }, { en: "ankh", min: "amch" }, { en: "ankle", min: "amcro" },
  { en: "anklet", min: "amcrod" }, { en: "annex", min: "ammox" }, { en: "annihilate", min: "ammuhurado" }, { en: "annotate", min: "ammedado" }, { en: "announce", min: "ammeimko" }, { en: "annoyance", min: "ammeyamko" }, { en: "annul", min: "ammir" }, { en: "anode", min: "ameto" }, { en: "anodyne", min: "ametymo" }, { en: "anoint", min: "ameumd" },
  { en: "anon", min: "amem" }, { en: "anorak", min: "amelac" }, { en: "anorexia", min: "ameloxua" }, { en: "antacid", min: "amdakut" }, { en: "antagonize", min: "amdagemuso" }, { en: "ante", min: "amdo" }, { en: "antebellum", min: "amdoporrin" }, { en: "antecedent", min: "amdokotomd" }, { en: "antedate", min: "amdotado" }, { en: "antelope", min: "amdorebo" },
  { en: "antenna", min: "amdomma" }, { en: "antennae", min: "amdommao" }, { en: "anterior", min: "amdoluel" }, { en: "anteroom", min: "amdoleen" }, { en: "anthem", min: "amdhon" }, { en: "anthill", min: "amdhurr" }, { en: "anthracite", min: "amdhlakudo" }, { en: "anthrax", min: "amdhlax" }, { en: "anthropoid", min: "amdhlebeut" }, { en: "anti", min: "amdu" },
  { en: "antonym", min: "amdemyn" }, { en: "anvil", min: "amfur" }, { en: "anyhow", min: "amyhew" }, { en: "anymore", min: "amynelo" }, { en: "anyone", min: "amyemo" }, { en: "anyplace", min: "amybrako" }, { en: "anytime", min: "amyduno" }, { en: "anywhere", min: "amywholo" }, { en: "aorta", min: "aelda" }, { en: "aortae", min: "aeldao" },
  { en: "apace", min: "abako" }, { en: "apart", min: "abald" }, { en: "apartheid", min: "abaldhout" }, { en: "ape", min: "abo" }, { en: "aperitif", min: "aboluduv" }, { en: "aperture", min: "aboldilo" }, { en: "apex", min: "abox" }, { en: "aphasia", min: "abhazua" }, { en: "aphelia", min: "abhorua" }, { en: "aphelion", min: "abhoruem" },
  { en: "aphid", min: "abhut" }, { en: "apiece", min: "abuoko" }, { en: "aplomb", min: "abrenp" }, { en: "apocalypse", min: "abekarybzo" }, { en: "apogee", min: "abegoo" }, { en: "apologia", min: "aberegua" }, { en: "apologize", min: "abereguso" }, { en: "apostate", min: "abezdado" }, { en: "apostle", min: "abezdro" }, { en: "apostrophe", min: "abezdlebho" },
  { en: "app", min: "abb" }, { en: "appall", min: "abbarr" }, { en: "apparel", min: "abbalor" }, { en: "apparent", min: "abbalomd" }, { en: "appearance", min: "abboalamko" }, { en: "appease", min: "abboazo" }, { en: "appellant", min: "abborramd" }, { en: "appellate", min: "abborrado" }, { en: "append", min: "abbomt" }, { en: "appendage", min: "abbomtago" },
  { en: "appendix", min: "abbomtux" }, { en: "appertain", min: "abboldaum" }, { en: "appetite", min: "abbodudo" }, { en: "applaud", min: "abbrait" }, { en: "applause", min: "abbraizo" }, { en: "applejack", min: "abbroqakc" }, { en: "applesauce", min: "abbrozaiko" }, { en: "appliance", min: "abbruamko" }, { en: "applicant", min: "abbrukamd" }, { en: "applicator", min: "abbrukadel" },
  { en: "appoint", min: "abbeumd" }, { en: "appointee", min: "abbeumdoo" }, { en: "apposite", min: "abbezudo" }, { en: "appraise", min: "abblauzo" }, { en: "appreciate", min: "abblokuado" }, { en: "apprehend", min: "abblohomt" }, { en: "apprentice", min: "abblomduko" }, { en: "apprise", min: "abbluzo" }, { en: "apprize", min: "abbluso" }, { en: "approach", min: "abbleakh" },
  { en: "approve", min: "abblefo" }, { en: "approx", min: "abblex" }, { en: "apricot", min: "abluked" }, { en: "apron", min: "ablem" }, { en: "apse", min: "abzo" }, { en: "apt", min: "abd" }, { en: "aptitude", min: "abdudito" }, { en: "aqua", min: "ajia" }, { en: "aquae", min: "ajiao" }, { en: "aquamarine", min: "ajianalumo" },
  { en: "aquanaut", min: "ajiamaid" }, { en: "aquaplane", min: "ajiabramo" }, { en: "aquaria", min: "ajialua" }, { en: "aquarium", min: "ajialuin" }, { en: "aquavit", min: "ajiafud" }, { en: "aqueduct", min: "ajiotikd" }, { en: "aquiline", min: "ajiurumo" }, { en: "arabesque", min: "alapozjio" }, { en: "arachnid", min: "alakhmut" }, { en: "arbitrate", min: "alpudlado" },
  { en: "arbitrator", min: "alpudladel" }, { en: "arbor", min: "alpel" }, { en: "arboreta", min: "alpeloda" }, { en: "arboretum", min: "alpelodin" }, { en: "arborvitae", min: "alpelfudao" }, { en: "arc", min: "alk" }, { en: "arcade", min: "alkato" }, { en: "arcane", min: "alkamo" }, { en: "arch", min: "alkh" }, { en: "archangel", min: "alkhamgor" },
  { en: "archbishop", min: "alkhpuzheb" }, { en: "archdeacon", min: "alkhtoakem" }, { en: "archduke", min: "alkhtico" }, { en: "archetype", min: "alkhodybo" }, { en: "architect", min: "alkhudokd" }, { en: "ardent", min: "altomd" }, { en: "ardor", min: "altel" }, { en: "are", min: "alo" }, { en: "area", min: "aloa" }, { en: "arena", min: "aloma" },
  { en: "argon", min: "algem" }, { en: "argot", min: "alged" }, { en: "argue", min: "algio" }, { en: "argyle", min: "algyro" }, { en: "aria", min: "alua" }, { en: "arid", min: "alut" }, { en: "aright", min: "alughd" }, { en: "arise", min: "aluzo" }, { en: "arisen", min: "aluzom" }, { en: "aristocrat", min: "aluzdeklad" },
  { en: "armada", min: "alnata" }, { en: "armadillo", min: "alnaturre" }, { en: "armature", min: "alnadilo" }, { en: "armband", min: "alnpamt" }, { en: "armchair", min: "alnkhaul" }, { en: "armhole", min: "alnhero" }, { en: "armistice", min: "alnuzduko" }, { en: "armlet", min: "alnrod" }, { en: "armor", min: "alnel" }, { en: "armpit", min: "alnbud" },
  { en: "aroma", min: "alena" }, { en: "arose", min: "alezo" }, { en: "around", min: "aleimt" }, { en: "arouse", min: "aleizo" }, { en: "arpeggio", min: "alboggue" }, { en: "arraign", min: "allaugm" }, { en: "arrange", min: "allamgo" }, { en: "arrant", min: "allamd" }, { en: "arrogance", min: "allegamko" }, { en: "arrogant", min: "allegamd" },
  { en: "arrogate", min: "allegado" }, { en: "arrow", min: "allew" }, { en: "arrowhead", min: "allewhoat" }, { en: "arrowroot", min: "allewleed" }, { en: "arroyo", min: "alleye" }, { en: "arson", min: "alzem" }, { en: "artefact", min: "aldovakd" }, { en: "arthropod", min: "aldhlebet" }, { en: "artichoke", min: "aldukheco" }, { en: "article", min: "aldukro" },
  { en: "articulate", min: "aldukirado" }, { en: "artifact", min: "alduvakd" }, { en: "artifice", min: "alduvuko" }, { en: "artisan", min: "alduzam" }, { en: "artiste", min: "alduzdo" }, { en: "artwork", min: "aldwelc" }, { en: "ascend", min: "azkomt" }, { en: "ascendant", min: "azkomtamd" }, { en: "ascendent", min: "azkomtomd" }, { en: "ascension", min: "azkomzuem" },
];
