/**
 * @file Contains dictionary entries for category: clothing_top.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const clothing_top: DictionaryEntry[] = [
  { en: "shirt", min: "camisa" }, { en: "jacket", min: "saco" }, { en: "coat", min: "abrigo" }, { en: "sweater", min: "buzo" }, { en: "vest", min: "chaleco" }, { en: "ascent", min: "azkomd" }, { en: "ascertain", min: "azkoldaum" }, { en: "ascot", min: "azked" }, { en: "ascribe", min: "azklupo" }, { en: "ash", min: "azh" },
  { en: "ashcan", min: "azhkam" }, { en: "ashen", min: "azhom" }, { en: "ashore", min: "azhelo" }, { en: "ashram", min: "azhlan" }, { en: "aside", min: "azuto" }, { en: "asinine", min: "azumumo" }, { en: "askance", min: "azcamko" }, { en: "askew", min: "azcow" }, { en: "aslant", min: "azramd" }, { en: "asleep", min: "azroob" },
  { en: "asp", min: "azb" }, { en: "aspartame", min: "azbaldano" }, { en: "aspect", min: "azbokd" }, { en: "aspersion", min: "azbolzuem" }, { en: "asphalt", min: "azbhard" }, { en: "asphyxia", min: "azbhyxua" }, { en: "asphyxiate", min: "azbhyxuado" }, { en: "aspirant", min: "azbulamd" }, { en: "aspirate", min: "azbulado" }, { en: "aspire", min: "azbulo" },
  { en: "aspirin", min: "azbulum" }, { en: "assail", min: "azzaur" }, { en: "assailant", min: "azzauramd" }, { en: "assassin", min: "azzazzum" }, { en: "assault", min: "azzaird" }, { en: "assemblage", min: "azzonprago" }, { en: "assemble", min: "azzonpro" }, { en: "assent", min: "azzomd" }, { en: "assert", min: "azzold" }, { en: "assessor", min: "azzozzel" },
  { en: "asset", min: "azzod" }, { en: "asseverate", min: "azzofolado" }, { en: "asshole", min: "azzhero" }, { en: "assign", min: "azzugm" }, { en: "assimilate", min: "azzunurado" }, { en: "assistance", min: "azzuzdamko" }, { en: "assistant", min: "azzuzdamd" }, { en: "assize", min: "azzuso" }, { en: "assn", min: "azzm" }, { en: "assoc", min: "azzek" },
  { en: "associate", min: "azzekuado" }, { en: "assonance", min: "azzemamko" }, { en: "assort", min: "azzeld" }, { en: "asst", min: "azzd" }, { en: "assuage", min: "azziago" }, { en: "assume", min: "azzino" }, { en: "assurance", min: "azzilamko" }, { en: "assure", min: "azzilo" }, { en: "asterisk", min: "azdoluzc" }, { en: "astern", min: "azdolm" },
  { en: "asteroid", min: "azdoleut" }, { en: "asthma", min: "azdhna" }, { en: "astir", min: "azdul" }, { en: "astound", min: "azdeimt" }, { en: "astride", min: "azdluto" }, { en: "astringent", min: "azdlumgomd" }, { en: "astronaut", min: "azdlemaid" }, { en: "astute", min: "azdido" }, { en: "asylum", min: "azyrin" }, { en: "ate", min: "ado" },
  { en: "athlete", min: "adhrodo" }, { en: "atmosphere", min: "adnezbholo" }, { en: "atoll", min: "aderr" }, { en: "atom", min: "aden" }, { en: "atone", min: "ademo" }, { en: "atop", min: "adeb" }, { en: "atrium", min: "adluin" }, { en: "attach", min: "addakh" }, { en: "attack", min: "addakc" }, { en: "attain", min: "addaum" },
  { en: "attempt", min: "addonbd" }, { en: "attend", min: "addomt" }, { en: "attendance", min: "addomtamko" }, { en: "attendant", min: "addomtamd" }, { en: "attenuate", min: "addomiado" }, { en: "attire", min: "addulo" }, { en: "attitude", min: "addudito" }, { en: "attract", min: "addlakd" }, { en: "attribute", min: "addlupido" }, { en: "attune", min: "addimo" },
  { en: "audience", min: "aituomko" }, { en: "audio", min: "aitue" }, { en: "audiophile", min: "aituebhuro" }, { en: "audit", min: "aitud" }, { en: "auditor", min: "aitudel" }, { en: "auditoria", min: "aitudelua" }, { en: "auditorium", min: "aitudeluin" }, { en: "aught", min: "aighd" }, { en: "augur", min: "aigil" }, { en: "auk", min: "aic" },
  { en: "aunt", min: "aimd" }, { en: "aurae", min: "ailao" }, { en: "aureola", min: "ailoera" }, { en: "aureole", min: "ailoero" }, { en: "auricle", min: "ailukro" }, { en: "auspice", min: "aizbuko" }, { en: "austere", min: "aizdolo" }, { en: "author", min: "aidhel" }, { en: "authorize", min: "aidheluso" }, { en: "auto", min: "aide" },
  { en: "avail", min: "afaur" }, { en: "avalanche", min: "afaramkho" }, { en: "avarice", min: "afaluko" }, { en: "avast", min: "afazd" }, { en: "avdp", min: "aftb" }, { en: "avenge", min: "afomgo" }, { en: "avenue", min: "afomio" }, { en: "average", min: "afolago" }, { en: "averse", min: "afolzo" }, { en: "aversion", min: "afolzuem" },
  { en: "avert", min: "afold" }, { en: "avg", min: "afg" }, { en: "avian", min: "afuam" }, { en: "aviator", min: "afuadel" }, { en: "aviatrix", min: "afuadlux" }, { en: "avid", min: "afut" }, { en: "avocado", min: "afekate" }, { en: "avoid", min: "afeut" }, { en: "avoidance", min: "afeutamko" }, { en: "avow", min: "afew" },
  { en: "await", min: "awaud" }, { en: "awake", min: "awaco" }, { en: "awaken", min: "awacom" }, { en: "award", min: "awalt" }, { en: "aware", min: "awalo" }, { en: "awash", min: "awazh" }, { en: "awe", min: "awo" }, { en: "aweigh", min: "awough" }, { en: "awesome", min: "awozeno" }, { en: "awestruck", min: "awozdlikc" },
  { en: "awhile", min: "awhuro" }, { en: "awl", min: "awr" }, { en: "awoke", min: "aweco" }, { en: "awoken", min: "awecom" }, { en: "axe", min: "axo" }, { en: "axiom", min: "axuen" }, { en: "axle", min: "axro" }, { en: "axon", min: "axem" }, { en: "ayatollah", min: "ayaderrah" }, { en: "aye", min: "ayo" },
  { en: "azalea", min: "asaroa" }, { en: "azure", min: "asilo" }, { en: "baa", min: "paa" }, { en: "babble", min: "pappro" }, { en: "babe", min: "papo" }, { en: "baboon", min: "papeem" }, { en: "babushka", min: "papizhca" }, { en: "babysat", min: "papyzad" }, { en: "babysit", min: "papyzud" }, { en: "bachelor", min: "pakhorel" },
  { en: "bacilli", min: "pakurru" }, { en: "back", min: "pakc" }, { en: "backache", min: "pakcakho" }, { en: "backbit", min: "pakcpud" }, { en: "backbite", min: "pakcpudo" }, { en: "backbitten", min: "pakcpuddom" }, { en: "backboard", min: "pakcpealt" }, { en: "backbone", min: "pakcpemo" }, { en: "backdate", min: "pakctado" }, { en: "backdrop", min: "pakctleb" },
  { en: "backfield", min: "pakcvuort" }, { en: "backfire", min: "pakcvulo" }, { en: "backgammon", min: "pakcgannem" }, { en: "background", min: "pakcgleimt" }, { en: "backhand", min: "pakchamt" }, { en: "backhoe", min: "pakcheo" }, { en: "backlash", min: "pakcrazh" }, { en: "backlog", min: "pakcreg" }, { en: "backpack", min: "pakcbakc" }, { en: "backside", min: "pakczuto" },
  { en: "backslash", min: "pakczrazh" }, { en: "backslid", min: "pakczrut" }, { en: "backslide", min: "pakczruto" }, { en: "backspace", min: "pakczbako" }, { en: "backspin", min: "pakczbum" }, { en: "backstage", min: "pakczdago" }, { en: "backstop", min: "pakczdeb" }, { en: "backstroke", min: "pakczdleco" }, { en: "backtrack", min: "pakcdlakc" }, { en: "backup", min: "pakcib" },
  { en: "backwash", min: "pakcwazh" }, { en: "backyard", min: "pakcyalt" }, { en: "bacteria", min: "pakdolua" }, { en: "bacterium", min: "pakdoluin" }, { en: "bade", min: "pato" }, { en: "badge", min: "patgo" }, { en: "badinage", min: "patumago" }, { en: "badminton", min: "patnumdem" }, { en: "baffle", min: "pavvro" }, { en: "bag", min: "pag" },
  { en: "bagatelle", min: "pagadorro" }, { en: "bagel", min: "pagor" }, { en: "baggage", min: "paggago" }, { en: "bagpipe", min: "pagbubo" }, { en: "bah", min: "pah" }, { en: "bail", min: "paur" }, { en: "bailiff", min: "pauruvv" }, { en: "bailiwick", min: "pauruwukc" }, { en: "bailout", min: "paureid" }, { en: "bait", min: "paud" },
  { en: "baize", min: "pauso" }, { en: "bake", min: "paco" }, { en: "balalaika", min: "pararauca" }, { en: "balance", min: "paramko" }, { en: "bald", min: "part" }, { en: "balderdash", min: "partoltazh" }, { en: "bale", min: "paro" }, { en: "baleen", min: "paroom" }, { en: "balk", min: "parc" }, { en: "ballad", min: "parrat" },
  { en: "ballast", min: "parrazd" }, { en: "ballerina", min: "parroluma" }, { en: "ballet", min: "parrod" }, { en: "balloon", min: "parreem" }, { en: "ballot", min: "parred" }, { en: "ballpark", min: "parrbalc" }, { en: "ballpoint", min: "parrbeumd" }, { en: "ballroom", min: "parrleen" }, { en: "ballyhoo", min: "parryhee" }, { en: "balm", min: "parn" },
  { en: "balsa", min: "parza" }, { en: "balsam", min: "parzan" }, { en: "balustrade", min: "parizdlato" }, { en: "bamboo", min: "panpee" }, { en: "bamboozle", min: "panpeesro" }, { en: "ban", min: "pam" }, { en: "band", min: "pamt" }, { en: "bandage", min: "pamtago" }, { en: "bandana", min: "pamtama" }, { en: "bandanna", min: "pamtamma" },
  { en: "bandit", min: "pamtud" }, { en: "banditti", min: "pamtuddu" }, { en: "bandstand", min: "pamtzdamt" }, { en: "bandwagon", min: "pamtwagem" }, { en: "bane", min: "pamo" }, { en: "bang", min: "pamg" }, { en: "bangle", min: "pamgro" }, { en: "bani", min: "pamu" }, { en: "banjo", min: "pamqe" }, { en: "bankbook", min: "pamcpeec" },
  { en: "banknote", min: "pamcmedo" }, { en: "bankroll", min: "pamclerr" }, { en: "bankrupt", min: "pamclibd" }, { en: "banquet", min: "pamjiod" }, { en: "banshee", min: "pamzhoo" }, { en: "bantam", min: "pamdan" }, { en: "banyan", min: "pamyam" }, { en: "baobab", min: "paepap" }, { en: "baptize", min: "pabduso" }, { en: "bar", min: "pal" },
  { en: "barbacoa", min: "palpakea" }, { en: "barbarian", min: "palpaluam" }, { en: "barbecue", min: "palpokio" }, { en: "barbell", min: "palporr" }, { en: "barbeque", min: "palpojio" }, { en: "barbershop", min: "palpolzheb" }, { en: "bard", min: "palt" }, { en: "bare", min: "palo" }, { en: "bareback", min: "palopakc" }, { en: "barefoot", min: "paloveed" },
  { en: "barf", min: "palv" }, { en: "bargain", min: "palgaum" }, { en: "barge", min: "palgo" }, { en: "barista", min: "paluzda" }, { en: "baritone", min: "paludemo" }, { en: "barium", min: "paluin" }, { en: "bark", min: "palc" }, { en: "barmaid", min: "palnaut" }, { en: "barman", min: "palnam" }, { en: "barn", min: "palm" },
  { en: "barnacle", min: "palmakro" }, { en: "barnstorm", min: "palmzdeln" }, { en: "barnyard", min: "palmyalt" }, { en: "baron", min: "palem" }, { en: "baronet", min: "palemod" }, { en: "baroque", min: "palejio" }, { en: "barrack", min: "pallakc" }, { en: "barracuda", min: "pallakita" }, { en: "barrage", min: "pallago" }, { en: "barrel", min: "pallor" },
  { en: "barren", min: "pallom" }, { en: "barrette", min: "palloddo" }, { en: "barricade", min: "pallukato" }, { en: "barrio", min: "pallue" }, { en: "barroom", min: "palleen" }, { en: "barrow", min: "pallew" }, { en: "basalt", min: "pazard" }, { en: "base", min: "pazo" }, { en: "baseball", min: "pazoparr" }, { en: "baseboard", min: "pazopealt" },
];
