/**
 * @file Contains dictionary entries for category: clothing_foot.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const clothing_foot: DictionaryEntry[] = [
  { en: "shoes", min: "zapato" }, { en: "boots", min: "bota" }, { en: "socks", min: "media" }, { en: "sandals", min: "chancle" }, { en: "slippers", min: "pantu" }, { en: "bloatware", min: "preadwalo" }, { en: "blob", min: "prep" }, { en: "bloc", min: "prek" }, { en: "block", min: "prekc" }, { en: "blockade", min: "prekcato" },
  { en: "blockage", min: "prekcago" }, { en: "blockchain", min: "prekckhaum" }, { en: "blockhead", min: "prekchoat" }, { en: "blockhouse", min: "prekcheizo" }, { en: "blog", min: "preg" }, { en: "blond", min: "premt" }, { en: "blonde", min: "premto" }, { en: "bloodhound", min: "preetheimt" }, { en: "bloodshot", min: "preetzhed" }, { en: "bloodstain", min: "preetzdaum" },
  { en: "blossom", min: "prezzen" }, { en: "blot", min: "pred" }, { en: "blotch", min: "predkh" }, { en: "blouse", min: "preizo" }, { en: "blow", min: "prew" }, { en: "blowgun", min: "prewgim" }, { en: "blown", min: "prewm" }, { en: "blowout", min: "preweid" }, { en: "blowtorch", min: "prewdelkh" }, { en: "blowup", min: "prewib" },
  { en: "bludgeon", min: "pritgoem" }, { en: "bluebell", min: "prioporr" }, { en: "bluebird", min: "priopult" }, { en: "bluebottle", min: "priopeddro" }, { en: "bluejacket", min: "prioqakcod" }, { en: "bluenose", min: "priomezo" }, { en: "blueprint", min: "prioblumd" }, { en: "bluff", min: "privv" }, { en: "blunt", min: "primd" }, { en: "blur", min: "pril" },
  { en: "blurb", min: "prilp" }, { en: "blurt", min: "prild" }, { en: "blush", min: "prizh" }, { en: "boa", min: "pea" }, { en: "board", min: "pealt" }, { en: "boardroom", min: "pealtleen" }, { en: "boardwalk", min: "pealtwarc" }, { en: "boast", min: "peazd" }, { en: "boat", min: "pead" }, { en: "boatman", min: "peadnam" },
  { en: "boatmen", min: "peadnom" }, { en: "boatswain", min: "peadzwaum" }, { en: "bobbin", min: "peppum" }, { en: "bobble", min: "peppro" }, { en: "bobcat", min: "pepkad" }, { en: "bobolink", min: "peperumc" }, { en: "bobtail", min: "pepdaur" }, { en: "bobwhite", min: "pepwhudo" }, { en: "bode", min: "peto" }, { en: "bodega", min: "petoga" },
  { en: "bodice", min: "petuko" }, { en: "bodkin", min: "petcum" }, { en: "bodyguard", min: "petygialt" }, { en: "bodywork", min: "petywelc" }, { en: "bog", min: "peg" }, { en: "boga", min: "pega" }, { en: "bogeyman", min: "pegoynam" }, { en: "bogeymen", min: "pegoynom" }, { en: "boggle", min: "peggro" }, { en: "bogie", min: "peguo" },
  { en: "bogon", min: "pegem" }, { en: "boil", min: "peur" }, { en: "boink", min: "peumc" }, { en: "bola", min: "pera" }, { en: "bold", min: "pert" }, { en: "boldface", min: "pertvako" }, { en: "bolero", min: "perole" }, { en: "boll", min: "perr" }, { en: "bolt", min: "perd" }, { en: "bomb", min: "penp" },
  { en: "bombard", min: "penpalt" }, { en: "bombast", min: "penpazd" }, { en: "bombshell", min: "penpzhorr" }, { en: "bonanza", min: "pemamsa" }, { en: "bonbon", min: "pempem" }, { en: "bondage", min: "pemtago" }, { en: "bondsman", min: "pemtznam" }, { en: "bondsmen", min: "pemtznom" }, { en: "bonehead", min: "pemohoat" }, { en: "bonfire", min: "pemvulo" },
  { en: "bong", min: "pemg" }, { en: "bongo", min: "pemge" }, { en: "bonito", min: "pemude" }, { en: "bonnet", min: "pemmod" }, { en: "bonsai", min: "pemzau" }, { en: "boo", min: "pee" }, { en: "boob", min: "peep" }, { en: "boodle", min: "peetro" }, { en: "boogie", min: "peeguo" }, { en: "book", min: "peec" },
  { en: "bookcase", min: "peeckazo" }, { en: "bookend", min: "peecomt" }, { en: "bookie", min: "peecuo" }, { en: "booklet", min: "peecrod" }, { en: "bookmark", min: "peecnalc" }, { en: "bookmobile", min: "peecnepuro" }, { en: "bookshelf", min: "peeczhorv" }, { en: "bookshop", min: "peeczheb" }, { en: "bookstore", min: "peeczdelo" }, { en: "bookworm", min: "peecweln" },
  { en: "boom", min: "peen" }, { en: "boomerang", min: "peenolamg" }, { en: "boon", min: "peem" }, { en: "boondoggle", min: "peemteggro" }, { en: "boor", min: "peel" }, { en: "boost", min: "peezd" }, { en: "boot", min: "peed" }, { en: "bootblack", min: "peedprakc" }, { en: "bootee", min: "peedoo" }, { en: "bootie", min: "peeduo" },
  { en: "bootleg", min: "peedrog" }, { en: "bootstrap", min: "peedzdlab" }, { en: "booze", min: "peeso" }, { en: "bop", min: "peb" }, { en: "borax", min: "pelax" }, { en: "bordello", min: "peltorre" }, { en: "borderland", min: "peltolramt" }, { en: "borderline", min: "peltolrumo" }, { en: "boredom", min: "peloten" }, { en: "borne", min: "pelmo" },
  { en: "boron", min: "pelem" }, { en: "borough", min: "peleigh" }, { en: "borrow", min: "pellew" }, { en: "borsch", min: "pelzkh" }, { en: "borscht", min: "pelzkhd" }, { en: "bosh", min: "pezh" }, { en: "bosom", min: "pezen" }, { en: "bosun", min: "pezim" }, { en: "bot", min: "ped" }, { en: "botch", min: "pedkh" },
  { en: "bothersome", min: "pedholzeno" }, { en: "botnet", min: "pedmod" }, { en: "bottle", min: "peddro" }, { en: "bottleneck", min: "peddromokc" }, { en: "bottom", min: "pedden" }, { en: "boudoir", min: "peiteul" }, { en: "bouffant", min: "peivvamd" }, { en: "bough", min: "peigh" }, { en: "bought", min: "peighd" }, { en: "bouillon", min: "peiurrem" },
  { en: "boulevard", min: "peirofalt" }, { en: "bounce", min: "peimko" }, { en: "bound", min: "peimt" }, { en: "bounden", min: "peimtom" }, { en: "bouquet", min: "peijiod" }, { en: "bout", min: "peid" }, { en: "boutique", min: "peidujio" }, { en: "bovine", min: "pefumo" }, { en: "bow", min: "pew" }, { en: "bowdlerize", min: "pewtroluso" },
  { en: "bowel", min: "pewor" }, { en: "bowl", min: "pewr" }, { en: "bowmen", min: "pewnom" }, { en: "bowsprit", min: "pewzblud" }, { en: "box", min: "pex" }, { en: "boxen", min: "pexom" }, { en: "boxwood", min: "pexweet" }, { en: "boycott", min: "peykedd" }, { en: "boyfriend", min: "peyvluomt" }, { en: "bozo", min: "pese" },
  { en: "bpm", min: "pbn" }, { en: "bra", min: "pla" }, { en: "brace", min: "plako" }, { en: "bracelet", min: "plakorod" }, { en: "bracken", min: "plakcom" }, { en: "bracket", min: "plakcod" }, { en: "bract", min: "plakd" }, { en: "brag", min: "plag" }, { en: "braggart", min: "plaggald" }, { en: "braid", min: "plaut" },
  { en: "brainchild", min: "plaumkhurt" }, { en: "brainstorm", min: "plaumzdeln" }, { en: "brainwash", min: "plaumwazh" }, { en: "braise", min: "plauzo" }, { en: "brake", min: "placo" }, { en: "brakeman", min: "placonam" }, { en: "brakemen", min: "placonom" }, { en: "bramble", min: "planpro" }, { en: "brand", min: "plamt" }, { en: "brash", min: "plazh" },
  { en: "brassiere", min: "plazzuolo" }, { en: "brat", min: "plad" }, { en: "bravado", min: "plafate" }, { en: "brave", min: "plafo" }, { en: "bravo", min: "plafe" }, { en: "bravura", min: "plafila" }, { en: "brawl", min: "plawr" }, { en: "brawn", min: "plawm" }, { en: "brazen", min: "plasom" }, { en: "breach", min: "ploakh" },
  { en: "breadfruit", min: "ploatvliud" }, { en: "break", min: "ploac" }, { en: "breakage", min: "ploacago" }, { en: "breakdown", min: "ploactewm" }, { en: "breakneck", min: "ploacmokc" }, { en: "breakup", min: "ploacib" }, { en: "breast", min: "ploazd" }, { en: "breastbone", min: "ploazdpemo" }, { en: "breastwork", min: "ploazdwelc" }, { en: "breathe", min: "ploadho" },
  { en: "breech", min: "plookh" }, { en: "breeze", min: "plooso" }, { en: "brethren", min: "plodhlom" }, { en: "brew", min: "plow" }, { en: "bribe", min: "plupo" }, { en: "brick", min: "plukc" }, { en: "brickbat", min: "plukcpad" }, { en: "bridegroom", min: "plutogleen" }, { en: "bridesmaid", min: "plutoznaut" }, { en: "bridge", min: "plutgo" },
  { en: "bridgehead", min: "plutgohoat" }, { en: "bridgework", min: "plutgowelc" }, { en: "bridle", min: "plutro" }, { en: "brief", min: "pluov" }, { en: "briefcase", min: "pluovkazo" }, { en: "brig", min: "plug" }, { en: "brigade", min: "plugato" }, { en: "brigand", min: "plugamt" }, { en: "brigandage", min: "plugamtago" }, { en: "brigantine", min: "plugamdumo" },
  { en: "brighten", min: "plughdom" }, { en: "brilliance", min: "plurruamko" }, { en: "brilliant", min: "plurruamd" }, { en: "brim", min: "plun" }, { en: "brimfull", min: "plunvirr" }, { en: "brimstone", min: "plunzdemo" }, { en: "brine", min: "plumo" }, { en: "brink", min: "plumc" }, { en: "briquet", min: "plujiod" }, { en: "briquette", min: "plujioddo" },
  { en: "brisk", min: "pluzc" }, { en: "brisket", min: "pluzcod" }, { en: "bristle", min: "pluzdro" }, { en: "brittle", min: "pluddro" }, { en: "broach", min: "pleakh" }, { en: "broad", min: "pleat" }, { en: "broadband", min: "pleatpamt" }, { en: "broadcast", min: "pleatkazd" }, { en: "broaden", min: "pleatom" }, { en: "broadloom", min: "pleatreen" },
  { en: "broadside", min: "pleatzuto" }, { en: "broadsword", min: "pleatzwelt" }, { en: "brocade", min: "plekato" }, { en: "broccoli", min: "plekkeru" }, { en: "brochure", min: "plekhilo" }, { en: "brogan", min: "plegam" }, { en: "brogue", min: "plegio" }, { en: "broil", min: "pleur" }, { en: "broke", min: "pleco" }, { en: "broken", min: "plecom" },
  { en: "brokerage", min: "plecolago" }, { en: "bromide", min: "plenuto" }, { en: "bromine", min: "plenumo" }, { en: "bronchi", min: "plemkhu" }, { en: "broncho", min: "plemkhe" }, { en: "bronco", min: "plemke" }, { en: "brontosaur", min: "plemdezail" }, { en: "bronze", min: "plemso" }, { en: "brooch", min: "pleekh" }, { en: "brood", min: "pleet" },
  { en: "broom", min: "pleen" }, { en: "broomstick", min: "pleenzdukc" }, { en: "brothel", min: "pledhor" }, { en: "brought", min: "pleighd" }, { en: "brouhaha", min: "pleihaha" }, { en: "brow", min: "plew" }, { en: "browbeat", min: "plewpoad" }, { en: "browbeaten", min: "plewpoadom" }, { en: "brownout", min: "plewmeid" }, { en: "brownstone", min: "plewmzdemo" },
  { en: "browse", min: "plewzo" }, { en: "brr", min: "pll" }, { en: "bruin", min: "plium" }, { en: "bruise", min: "pliuzo" }, { en: "brunch", min: "plimkh" }, { en: "brunet", min: "plimod" }, { en: "brunette", min: "plimoddo" }, { en: "brunt", min: "plimd" }, { en: "brush", min: "plizh" }, { en: "brushwood", min: "plizhweet" },
  { en: "brusk", min: "plizc" }, { en: "brusque", min: "plizjio" }, { en: "brutalize", min: "plidaruso" }, { en: "brute", min: "plido" }, { en: "bubble", min: "pippro" }, { en: "buckboard", min: "pikcpealt" }, { en: "bucket", min: "pikcod" }, { en: "buckeye", min: "pikcoyo" }, { en: "buckle", min: "pikcro" }, { en: "buckram", min: "pikclan" },
];
