/**
 * @file Contains dictionary entries for category: family.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const family: DictionaryEntry[] = [
  { en: "father", min: "papa" }, { en: "mother", min: "mama" }, { en: "brother", min: "hermano" }, { en: "sister", min: "hermana" }, { en: "friend", min: "buddha" }, { en: "tosca", min: "dezka" }, { en: "toscanini", min: "dezkamumu" }, { en: "toshiba", min: "dezhupa" }, { en: "toto", min: "dede" }, { en: "toulouse", min: "deireizo" },
  { en: "townsend", min: "dewmzomt" }, { en: "toynbee", min: "deympoo" }, { en: "toyoda", min: "deyeta" }, { en: "trajan", min: "dlaqam" }, { en: "tran", min: "dlam" }, { en: "travolta", min: "dlaferda" }, { en: "treblinka", min: "dloprumca" }, { en: "trekkie", min: "dloccuo" }, { en: "trent", min: "dlomd" }, { en: "trenton", min: "dlomdem" },
  { en: "trevelyan", min: "dloforyam" }, { en: "trevino", min: "dlofume" }, { en: "trevor", min: "dlofel" }, { en: "triangulum", min: "dluamgirin" }, { en: "trident", min: "dlutomd" }, { en: "trieste", min: "dluozdo" }, { en: "trimurti", min: "dlunildu" }, { en: "tripitaka", min: "dlubudaca" }, { en: "trippe", min: "dlubbo" }, { en: "tristan", min: "dluzdam" },
  { en: "triton", min: "dludem" }, { en: "trobriand", min: "dlepluamt" }, { en: "trojan", min: "dleqam" }, { en: "trollope", min: "dlerrebo" }, { en: "trondheim", min: "dlemthoun" }, { en: "tropicana", min: "dlebukama" }, { en: "truckee", min: "dlikcoo" }, { en: "trudeau", min: "dlitoai" }, { en: "truffaut", min: "dlivvaid" }, { en: "trujillo", min: "dliqurre" },
  { en: "truman", min: "dlinam" }, { en: "trumbull", min: "dlinpirr" }, { en: "trump", min: "dlinb" }, { en: "tsimshian", min: "dzunzhuam" }, { en: "tsingtao", min: "dzumgdae" }, { en: "tsongkhapa", min: "dzemgchaba" }, { en: "tswana", min: "dzwama" }, { en: "tuamotu", min: "dianedi" }, { en: "tuareg", min: "dialog" }, { en: "tubman", min: "dipnam" },
  { en: "tucson", min: "dikzem" }, { en: "tucuman", min: "dikinam" }, { en: "tudor", min: "ditel" }, { en: "tulane", min: "diramo" }, { en: "tull", min: "dirr" }, { en: "tulsa", min: "dirza" }, { en: "tunguska", min: "dimgizca" }, { en: "tunisian", min: "dimuzuam" }, { en: "tupi", min: "dibu" }, { en: "tupperware", min: "dibbolwalo" },
  { en: "tupungato", min: "dibimgade" }, { en: "turgenev", min: "dilgomof" }, { en: "turin", min: "dilum" }, { en: "turk", min: "dilc" }, { en: "turkestan", min: "dilcozdam" }, { en: "turlock", min: "dilrekc" }, { en: "turpin", min: "dilbum" }, { en: "tuscaloosa", min: "dizkareeza" }, { en: "tuscan", min: "dizkam" }, { en: "tuscarora", min: "dizkalela" },
  { en: "tuscon", min: "dizkem" }, { en: "tuskegee", min: "dizcogoo" }, { en: "tussaud", min: "dizzait" }, { en: "tut", min: "did" }, { en: "tutsi", min: "didzu" }, { en: "tutu", min: "didi" }, { en: "twain", min: "dwaum" }, { en: "tweedledee", min: "dwootrotoo" }, { en: "tweedledum", min: "dwootrotin" }, { en: "tycho", min: "dykhe" },
  { en: "tylenol", min: "dyromer" }, { en: "tyndale", min: "dymtaro" }, { en: "tyndall", min: "dymtarr" }, { en: "tyre", min: "dylo" }, { en: "tyree", min: "dyloo" }, { en: "tyrone", min: "dylemo" }, { en: "tyson", min: "dyzem" }, { en: "uaw", min: "iaw" }, { en: "ucla", min: "ikra" }, { en: "ufo", min: "ive" },
  { en: "uhf", min: "ihv" }, { en: "unix", min: "imux" }, { en: "upc", min: "ibk" }, { en: "upi", min: "ibu" }, { en: "url", min: "ilr" }, { en: "usa", min: "iza" }, { en: "usaf", min: "izav" }, { en: "usb", min: "izp" }, { en: "usda", min: "izta" }, { en: "usmc", min: "iznk" },
  { en: "usn", min: "izm" }, { en: "uso", min: "ize" }, { en: "ussr", min: "izzl" }, { en: "utc", min: "idk" }, { en: "ubangi", min: "ipamgu" }, { en: "ubuntu", min: "ipimdi" }, { en: "ucayali", min: "ikayaru" }, { en: "uccello", min: "ikkorre" }, { en: "udall", min: "itarr" }, { en: "ufa", min: "iva" },
  { en: "ugandan", min: "igamtam" }, { en: "uighur", min: "iughil" }, { en: "ukrainian", min: "iclaumuam" }, { en: "ultrasuede", min: "irdlazioto" }, { en: "ulyanovsk", min: "iryamefzc" }, { en: "umbriel", min: "inpluor" }, { en: "updike", min: "ibtuco" }, { en: "upjohn", min: "ibqehm" }, { en: "upton", min: "ibdem" }, { en: "urania", min: "ilamua" },
  { en: "urban", min: "ilpam" }, { en: "urdu", min: "ilti" }, { en: "uriah", min: "iluah" }, { en: "uriel", min: "iluor" }, { en: "urquhart", min: "iljihald" }, { en: "uruguayan", min: "iligiayam" }, { en: "urumqi", min: "ilinju" }, { en: "usenet", min: "izomod" }, { en: "ustinov", min: "izdumef" }, { en: "utah", min: "idah" },
  { en: "ute", min: "ido" }, { en: "utica", min: "iduka" }, { en: "utopia", min: "idebua" }, { en: "utopian", min: "idebuam" }, { en: "utrecht", min: "idlokhd" }, { en: "utrillo", min: "idlurre" }, { en: "uzbek", min: "ispoc" }, { en: "uzi", min: "isu" }, { en: "vat", min: "fad" }, { en: "vax", min: "fax" },
  { en: "vba", min: "fpa" }, { en: "vcr", min: "fkl" }, { en: "vdt", min: "ftd" }, { en: "vhf", min: "fhv" }, { en: "vip", min: "fub" }, { en: "vlf", min: "frv" }, { en: "vtol", min: "fder" }, { en: "vacaville", min: "fakafurro" }, { en: "valarie", min: "faraluo" }, { en: "valdez", min: "fartos" },
  { en: "valdosta", min: "fartezda" }, { en: "valenti", min: "faromdu" }, { en: "valentin", min: "faromdum" }, { en: "valentino", min: "faromdume" }, { en: "valenzuela", min: "faromsiora" }, { en: "valerian", min: "faroluam" }, { en: "valhalla", min: "farharra" }, { en: "valium", min: "faruin" }, { en: "valkyrie", min: "farcyluo" }, { en: "vallejo", min: "farroqe" },
  { en: "valparaiso", min: "farbalauze" }, { en: "valvoline", min: "farferumo" }, { en: "vance", min: "famko" }, { en: "vanderbilt", min: "famtolpurd" }, { en: "vandyke", min: "famtyco" }, { en: "vang", min: "famg" }, { en: "vanzetti", min: "famsoddu" }, { en: "varanasi", min: "falamazu" }, { en: "varese", min: "falozo" }, { en: "vaseline", min: "fazorumo" },
  { en: "vasquez", min: "fazjios" }, { en: "vatican", min: "fadukam" }, { en: "vauban", min: "faipam" }, { en: "vaughan", min: "faigham" }, { en: "vaughn", min: "faighm" }, { en: "vazquez", min: "fasjios" }, { en: "veblen", min: "foprom" }, { en: "vedanta", min: "fotamda" }, { en: "vega", min: "foga" }, { en: "vegemite", min: "fogonudo" },
  { en: "vela", min: "fora" }, { en: "velcro", min: "forkle" }, { en: "velez", min: "foros" }, { en: "velveeta", min: "forfooda" }, { en: "venetian", min: "fomoduam" }, { en: "venezuelan", min: "fomosioram" }, { en: "venice", min: "fomuko" }, { en: "venn", min: "fomm" }, { en: "ventolin", min: "fomderum" }, { en: "venusian", min: "fomizuam" },
  { en: "veracruz", min: "folaklis" }, { en: "verdi", min: "foltu" }, { en: "verdun", min: "foltim" }, { en: "vergil", min: "folgur" }, { en: "verizon", min: "folusem" }, { en: "verlaine", min: "folraumo" }, { en: "vermont", min: "folnemd" }, { en: "vern", min: "folm" }, { en: "verne", min: "folmo" }, { en: "vernon", min: "folmem" },
  { en: "verona", min: "folema" }, { en: "veronese", min: "folemozo" }, { en: "vespasian", min: "fozbazuam" }, { en: "vespucci", min: "fozbikku" }, { en: "vesta", min: "fozda" }, { en: "viacom", min: "fuaken" }, { en: "viagra", min: "fuagla" }, { en: "vic", min: "fuk" }, { en: "vicente", min: "fukomdo" }, { en: "vicksburg", min: "fukczpilg" },
  { en: "victor", min: "fukdel" }, { en: "victorian", min: "fukdeluam" }, { en: "victrola", min: "fukdlera" }, { en: "vienna", min: "fuomma" }, { en: "viennese", min: "fuommozo" }, { en: "vietcong", min: "fuodkemg" }, { en: "vietminh", min: "fuodnumh" }, { en: "vijayawada", min: "fuqayawata" }, { en: "vila", min: "fura" }, { en: "villa", min: "furra" },
  { en: "villon", min: "furrem" }, { en: "vilyui", min: "furyiu" }, { en: "vince", min: "fumko" }, { en: "vineland", min: "fumoramt" }, { en: "vinson", min: "fumzem" }, { en: "virgil", min: "fulgur" }, { en: "virginian", min: "fulgumuam" }, { en: "virgo", min: "fulge" }, { en: "visa", min: "fuza" }, { en: "visalia", min: "fuzarua" },
  { en: "vishnu", min: "fuzhmi" }, { en: "vistula", min: "fuzdira" }, { en: "vitim", min: "fudun" }, { en: "vito", min: "fude" }, { en: "vivaldi", min: "fufartu" }, { en: "vlad", min: "frat" }, { en: "vladimir", min: "fratunul" }, { en: "vlaminck", min: "franumkc" }, { en: "voip", min: "feub" }, { en: "vogue", min: "fegio" },
  { en: "voldemort", min: "fertoneld" }, { en: "volga", min: "ferga" }, { en: "volgograd", min: "fergeglat" }, { en: "volkswagen", min: "ferczwagom" }, { en: "volstead", min: "ferzdoat" }, { en: "volta", min: "ferda" }, { en: "voltaire", min: "ferdaulo" }, { en: "volvo", min: "ferfe" }, { en: "vonda", min: "femta" }, { en: "vonnegut", min: "femmogid" },
  { en: "voronezh", min: "felemosh" }, { en: "vuitton", min: "fiuddem" }, { en: "vulcan", min: "firkam" }, { en: "vulgate", min: "firgado" }, { en: "wasp", min: "wazb" }, { en: "who", min: "whe" }, { en: "wmd", min: "wnt" }, { en: "wto", min: "wde" }, { en: "wwi", min: "wwu" }, { en: "wwii", min: "wwuu" },
  { en: "www", min: "www" }, { en: "wysiwyg", min: "wyzuwyg" }, { en: "wabash", min: "wapazh" }, { en: "wac", min: "wak" }, { en: "waco", min: "wake" }, { en: "wade", min: "wato" }, { en: "wagnerian", min: "wagmoluam" }, { en: "wahhabi", min: "wahhapu" }, { en: "waikiki", min: "waucucu" }, { en: "waite", min: "waudo" },
  { en: "wake", min: "waco" }, { en: "waksman", min: "wacznam" }, { en: "wald", min: "wart" }, { en: "walden", min: "wartom" }, { en: "waldensian", min: "wartomzuam" }, { en: "waldheim", min: "warthoun" }, { en: "waldo", min: "warte" }, { en: "waldorf", min: "wartelv" }, { en: "walesa", min: "waroza" }, { en: "walgreen", min: "wargloom" },
  { en: "walkman", min: "warcnam" }, { en: "wall", min: "warr" }, { en: "wallace", min: "warrako" }, { en: "walloon", min: "warreem" }, { en: "walpole", min: "warbero" }, { en: "walsh", min: "warzh" }, { en: "walt", min: "ward" }, { en: "walton", min: "wardem" }, { en: "wang", min: "wamg" }, { en: "wankel", min: "wamcor" },
  { en: "ward", min: "walt" }, { en: "ware", min: "walo" }, { en: "warhol", min: "walher" }, { en: "warren", min: "wallom" }, { en: "warsaw", min: "walzaw" }, { en: "warwick", min: "walwukc" }, { en: "wasatch", min: "wazadkh" }, { en: "wash", min: "wazh" }, { en: "wassermann", min: "wazzolnamm" }, { en: "waterford", min: "wadolvelt" },
];
