/**
 * @file Contains dictionary entries for category: food_meal.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const food_meal: DictionaryEntry[] = [
  { en: "breakfast", min: "desayu" }, { en: "lunch", min: "almu" }, { en: "dinner", min: "cena" }, { en: "soup", min: "sopa" }, { en: "bread", min: "pan" }, { en: "maurice", min: "nailuko" }, { en: "mauricio", min: "nailukue" }, { en: "mauro", min: "naile" }, { en: "mauryan", min: "nailyam" }, { en: "maximilian", min: "naxunuruam" },
  { en: "maxwell", min: "naxworr" }, { en: "maya", min: "naya" }, { en: "mayan", min: "nayam" }, { en: "mayfair", min: "nayvaul" }, { en: "maynard", min: "naymalt" }, { en: "mayo", min: "naye" }, { en: "mayra", min: "nayla" }, { en: "maytag", min: "naydag" }, { en: "mazama", min: "nasana" }, { en: "mazarin", min: "nasalum" },
  { en: "mazatlan", min: "nasadram" }, { en: "mazda", min: "nasta" }, { en: "mazola", min: "nasera" }, { en: "mazzini", min: "nassumu" }, { en: "mbini", min: "npumu" }, { en: "mcadam", min: "nkatan" }, { en: "mcallen", min: "nkarrom" }, { en: "mcbride", min: "nkpluto" }, { en: "mccain", min: "nkkaum" }, { en: "mccall", min: "nkkarr" },
  { en: "mcclain", min: "nkkraum" }, { en: "mcclellan", min: "nkkrorram" }, { en: "mcclure", min: "nkkrilo" }, { en: "mcconnell", min: "nkkemmorr" }, { en: "mccormick", min: "nkkelnukc" }, { en: "mccullough", min: "nkkirreigh" }, { en: "mcdaniel", min: "nktamuor" }, { en: "mcdonnell", min: "nktemmorr" }, { en: "mcdowell", min: "nkteworr" }, { en: "mcenroe", min: "nkomleo" },
  { en: "mcfadden", min: "nkvattom" }, { en: "mcfarland", min: "nkvalramt" }, { en: "mcgee", min: "nkgoo" }, { en: "mcgovern", min: "nkgefolm" }, { en: "mcgowan", min: "nkgewam" }, { en: "mcguire", min: "nkgiulo" }, { en: "mcintosh", min: "nkumdezh" }, { en: "mcintyre", min: "nkumdylo" }, { en: "mckee", min: "nkcoo" }, { en: "mckenzie", min: "nkcomsuo" },
  { en: "mcknight", min: "nkcmughd" }, { en: "mclaughlin", min: "nkraighrum" }, { en: "mclean", min: "nkroam" }, { en: "mcleod", min: "nkroet" }, { en: "mcluhan", min: "nkriham" }, { en: "mcmahon", min: "nknahem" }, { en: "mcmillan", min: "nknurram" }, { en: "mcnamara", min: "nkmanala" }, { en: "mcnaughton", min: "nkmaighdem" }, { en: "mcneil", min: "nkmour" },
  { en: "mcpherson", min: "nkbholzem" }, { en: "mcqueen", min: "nkjioom" }, { en: "mcveigh", min: "nkfough" }, { en: "mecca", min: "nokka" }, { en: "medan", min: "notam" }, { en: "medea", min: "notoa" }, { en: "medellin", min: "notorrum" }, { en: "medford", min: "notvelt" }, { en: "media", min: "notua" }, { en: "medicaid", min: "notukaut" },
  { en: "medicare", min: "notukalo" }, { en: "medici", min: "notuku" }, { en: "medina", min: "notuma" }, { en: "medusa", min: "notiza" }, { en: "meighen", min: "noughom" }, { en: "meiji", min: "nouqu" }, { en: "meir", min: "noul" }, { en: "mejia", min: "noqua" }, { en: "mekong", min: "nocemg" }, { en: "melanesia", min: "noramozua" },
  { en: "melanesian", min: "noramozuam" }, { en: "melbourne", min: "norpeilmo" }, { en: "melchior", min: "norkhuel" }, { en: "melendez", min: "noromtos" }, { en: "mellon", min: "norrem" }, { en: "melpomene", min: "norbenomo" }, { en: "melton", min: "nordem" }, { en: "melville", min: "norfurro" }, { en: "melvin", min: "norfum" }, { en: "mencken", min: "nomkcom" },
  { en: "mendel", min: "nomtor" }, { en: "mendeleev", min: "nomtoroof" }, { en: "mendelian", min: "nomtoruam" }, { en: "mendez", min: "nomtos" }, { en: "mendocino", min: "nomtekume" }, { en: "mendoza", min: "nomtesa" }, { en: "menelik", min: "nomoruc" }, { en: "menifee", min: "nomuvoo" }, { en: "menkalinan", min: "nomcarumam" }, { en: "menkent", min: "nomcomd" },
  { en: "mennen", min: "nommom" }, { en: "mennonite", min: "nommemudo" }, { en: "menominee", min: "nomenumoo" }, { en: "menotti", min: "nomeddu" }, { en: "mensa", min: "nomza" }, { en: "menuhin", min: "nomihum" }, { en: "merak", min: "nolac" }, { en: "mercado", min: "nolkate" }, { en: "mercator", min: "nolkadel" }, { en: "mercia", min: "nolkua" },
  { en: "merck", min: "nolkc" }, { en: "merino", min: "nolume" }, { en: "merlin", min: "nolrum" }, { en: "merlot", min: "nolred" }, { en: "merriam", min: "nolluan" }, { en: "merrick", min: "nollukc" }, { en: "merrimack", min: "nollunakc" }, { en: "merritt", min: "nolludd" }, { en: "merton", min: "noldem" }, { en: "mervin", min: "nolfum" },
  { en: "mesa", min: "noza" }, { en: "mesabi", min: "nozapu" }, { en: "messiaen", min: "nozzuaom" }, { en: "messiah", min: "nozzuah" }, { en: "metallica", min: "nodarruka" }, { en: "metamucil", min: "nodanikur" }, { en: "methuselah", min: "nodhizorah" }, { en: "metternich", min: "noddolmukh" }, { en: "meuse", min: "noizo" }, { en: "mexicali", min: "noxukaru" },
  { en: "mexican", min: "noxukam" }, { en: "mfume", min: "nvino" }, { en: "mig", min: "nug" }, { en: "miami", min: "nuanu" }, { en: "micah", min: "nukah" }, { en: "mich", min: "nukh" }, { en: "michael", min: "nukhaor" }, { en: "michelob", min: "nukhorep" }, { en: "michelson", min: "nukhorzem" }, { en: "michigan", min: "nukhugam" },
  { en: "mick", min: "nukc" }, { en: "micmac", min: "nuknak" }, { en: "middleton", min: "nuttrodem" }, { en: "middletown", min: "nuttrodewm" }, { en: "midland", min: "nutramt" }, { en: "midwestern", min: "nutwozdolm" }, { en: "miguel", min: "nugior" }, { en: "mike", min: "nuco" }, { en: "mikhail", min: "nuchaur" }, { en: "mikoyan", min: "nuceyam" },
  { en: "milan", min: "nuram" }, { en: "milford", min: "nurvelt" }, { en: "milken", min: "nurcom" }, { en: "mill", min: "nurr" }, { en: "millard", min: "nurralt" }, { en: "millet", min: "nurrod" }, { en: "millikan", min: "nurrucam" }, { en: "milne", min: "nurmo" }, { en: "milo", min: "nure" }, { en: "milton", min: "nurdem" },
  { en: "miltown", min: "nurdewm" }, { en: "milwaukee", min: "nurwaicoo" }, { en: "mimosa", min: "nuneza" }, { en: "minamoto", min: "numanede" }, { en: "mindanao", min: "numtamae" }, { en: "mindoro", min: "numtele" }, { en: "ming", min: "numg" }, { en: "minn", min: "numm" }, { en: "minnelli", min: "nummorru" }, { en: "minnesota", min: "nummozeda" },
  { en: "minnesotan", min: "nummozedam" }, { en: "minoan", min: "numeam" }, { en: "minolta", min: "numerda" }, { en: "minot", min: "numed" }, { en: "minotaur", min: "numedail" }, { en: "mintaka", min: "numdaca" }, { en: "minuit", min: "numiud" }, { en: "miocene", min: "nuekomo" }, { en: "mir", min: "nul" }, { en: "mirabeau", min: "nulapoai" },
  { en: "mirach", min: "nulakh" }, { en: "mirfak", min: "nulvac" }, { en: "miro", min: "nule" }, { en: "mirzam", min: "nulsan" }, { en: "mitch", min: "nudkh" }, { en: "mitchel", min: "nudkhor" }, { en: "mitchell", min: "nudkhorr" }, { en: "mitford", min: "nudvelt" }, { en: "mithra", min: "nudhla" }, { en: "mitsubishi", min: "nudzipuzhu" },
  { en: "mitterrand", min: "nuddollamt" }, { en: "mixtec", min: "nuxdok" }, { en: "mnemosyne", min: "nmonezymo" }, { en: "mobil", min: "nepur" }, { en: "mobile", min: "nepuro" }, { en: "mobutu", min: "nepidi" }, { en: "modesto", min: "netozde" }, { en: "modigliani", min: "netugruamu" }, { en: "moe", min: "neo" }, { en: "moet", min: "neod" },
  { en: "mohammad", min: "nehannat" }, { en: "mohammedan", min: "nehannotam" }, { en: "mohawk", min: "nehawc" }, { en: "mohican", min: "nehukam" }, { en: "moho", min: "nehe" }, { en: "moiseyev", min: "neuzoyof" }, { en: "mojave", min: "neqafo" }, { en: "moldavia", min: "nertafua" }, { en: "moliere", min: "neruolo" }, { en: "molina", min: "neruma" },
  { en: "moloch", min: "nerekh" }, { en: "molokai", min: "nerecau" }, { en: "molotov", min: "neredef" }, { en: "mombasa", min: "nenpaza" }, { en: "mon", min: "nem" }, { en: "mondale", min: "nemtaro" }, { en: "mondrian", min: "nemtluam" }, { en: "monera", min: "nemola" }, { en: "monessen", min: "nemozzom" }, { en: "monet", min: "nemod" },
  { en: "mongodb", min: "nemgetp" }, { en: "mongol", min: "nemger" }, { en: "mongolian", min: "nemgeruam" }, { en: "mongoloid", min: "nemgereut" }, { en: "monk", min: "nemc" }, { en: "monroe", min: "nemleo" }, { en: "monsanto", min: "nemzamde" }, { en: "mont", min: "nemd" }, { en: "montague", min: "nemdagio" }, { en: "montaigne", min: "nemdaugmo" },
  { en: "montana", min: "nemdama" }, { en: "montanan", min: "nemdamam" }, { en: "montcalm", min: "nemdkarn" }, { en: "monte", min: "nemdo" }, { en: "montessori", min: "nemdozzelu" }, { en: "monteverdi", min: "nemdofoltu" }, { en: "montezuma", min: "nemdosina" }, { en: "monticello", min: "nemdukorre" }, { en: "montoya", min: "nemdeya" }, { en: "montrachet", min: "nemdlakhod" },
  { en: "moog", min: "neeg" }, { en: "moor", min: "neel" }, { en: "moore", min: "neelo" }, { en: "moran", min: "nelam" }, { en: "moravia", min: "nelafua" }, { en: "moravian", min: "nelafuam" }, { en: "more", min: "nelo" }, { en: "moreno", min: "nelome" }, { en: "morgantown", min: "nelgamdewm" }, { en: "morin", min: "nelum" },
  { en: "morison", min: "neluzem" }, { en: "morita", min: "neluda" }, { en: "mormon", min: "nelnem" }, { en: "moro", min: "nele" }, { en: "moroccan", min: "nelekkam" }, { en: "morrison", min: "nelluzem" }, { en: "morristown", min: "nelluzdewm" }, { en: "morrow", min: "nellew" }, { en: "morse", min: "nelzo" }, { en: "mort", min: "neld" },
  { en: "morton", min: "neldem" }, { en: "moslem", min: "nezron" }, { en: "mosul", min: "nezir" }, { en: "motorola", min: "nedelera" }, { en: "motown", min: "nedewm" }, { en: "motrin", min: "nedlum" }, { en: "mott", min: "nedd" }, { en: "mount", min: "neimd" }, { en: "mountie", min: "neimduo" }, { en: "mouthe", min: "neidho" },
  { en: "mouton", min: "neidem" }, { en: "mowgli", min: "newgru" }, { en: "mozambican", min: "nesanpukam" }, { en: "mozart", min: "nesald" }, { en: "mozilla", min: "nesurra" }, { en: "muawiya", min: "niawuya" }, { en: "mubarak", min: "nipalac" }, { en: "mugabe", min: "nigapo" }, { en: "muhammad", min: "nihannat" }, { en: "muhammadan", min: "nihannatam" },
  { en: "muir", min: "niul" }, { en: "mujib", min: "niqup" }, { en: "mullen", min: "nirrom" }, { en: "mulligan", min: "nirrugam" }, { en: "mullikan", min: "nirrucam" }, { en: "multan", min: "nirdam" }, { en: "mumbai", min: "ninpau" }, { en: "mumford", min: "ninvelt" }, { en: "munch", min: "nimkh" }, { en: "muncie", min: "nimkuo" },
  { en: "munich", min: "nimukh" }, { en: "munoz", min: "nimes" }, { en: "munro", min: "nimle" }, { en: "muppet", min: "nibbod" }, { en: "murasaki", min: "nilazacu" }, { en: "murat", min: "nilad" }, { en: "murchison", min: "nilkhuzem" }, { en: "murdoch", min: "niltekh" }, { en: "murillo", min: "nilurre" }, { en: "murine", min: "nilumo" },
];
