/**
 * @file Contains dictionary entries for category: food_veg.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const food_veg: DictionaryEntry[] = [
  { en: "potato", min: "patata" }, { en: "tomato", min: "tomate" }, { en: "carrot", min: "zanahoria" }, { en: "onion", min: "cebolla" }, { en: "garlic", min: "ajo" }, { en: "ipa", min: "uba" }, { en: "ipo", min: "ube" }, { en: "irc", min: "ulk" }, { en: "iso", min: "uze" }, { en: "isp", min: "uzb" },
  { en: "iud", min: "uit" }, { en: "ivf", min: "ufv" }, { en: "iaccoca", min: "uakkeka" }, { en: "iago", min: "uage" }, { en: "ian", min: "uam" }, { en: "ibadan", min: "upatam" }, { en: "iberia", min: "upolua" }, { en: "iberian", min: "upoluam" }, { en: "ibiza", min: "upusa" }, { en: "ibo", min: "upe" },
  { en: "ibsen", min: "upzom" }, { en: "icahn", min: "ukahm" }, { en: "idaho", min: "utahe" }, { en: "idahoan", min: "utaheam" }, { en: "ieyasu", min: "uoyazi" }, { en: "ignacio", min: "ugmakue" }, { en: "igor", min: "ugel" }, { en: "iguassu", min: "ugiazzi" }, { en: "ijssel", min: "uqzzor" }, { en: "ike", min: "uco" },
  { en: "ikhnaton", min: "uchmadem" }, { en: "ila", min: "ura" }, { en: "iliad", min: "uruat" }, { en: "ill", min: "urr" }, { en: "illuminati", min: "urrinumadu" }, { en: "ilyushin", min: "uryizhum" }, { en: "imhotep", min: "unhedob" }, { en: "imodium", min: "unetuin" }, { en: "inc", min: "umk" }, { en: "inca", min: "umka" },
  { en: "inchon", min: "umkhem" }, { en: "ind", min: "umt" }, { en: "indiana", min: "umtuama" }, { en: "indianan", min: "umtuamam" }, { en: "indio", min: "umtue" }, { en: "indochina", min: "umtekhuma" }, { en: "indonesian", min: "umtemozuam" }, { en: "indore", min: "umtelo" }, { en: "indra", min: "umtla" }, { en: "inglewood", min: "umgroweet" },
  { en: "ingram", min: "umglan" }, { en: "innocent", min: "ummekomd" }, { en: "inonu", min: "umemi" }, { en: "intelsat", min: "umdorzad" }, { en: "inuit", min: "umiud" }, { en: "inuktitut", min: "umicdudid" }, { en: "ionesco", min: "uemozke" }, { en: "ionian", min: "uemuam" }, { en: "iowa", min: "uewa" }, { en: "iowan", min: "uewam" },
  { en: "iphigenia", min: "ubhugomua" }, { en: "iqaluit", min: "ujariud" }, { en: "iranian", min: "ulamuam" }, { en: "iraqi", min: "ulaju" }, { en: "irishman", min: "uluzhnam" }, { en: "irishmen", min: "uluzhnom" }, { en: "irishwoman", min: "uluzhwenam" }, { en: "irishwomen", min: "uluzhwenom" }, { en: "irkutsk", min: "ulcidzc" }, { en: "iroquoian", min: "ulejieuam" },
  { en: "irvin", min: "ulfum" }, { en: "irwin", min: "ulwum" }, { en: "isaac", min: "uzaak" }, { en: "isabela", min: "uzapora" }, { en: "isaiah", min: "uzauah" }, { en: "iscariot", min: "uzkalued" }, { en: "isfahan", min: "uzvaham" }, { en: "isherwood", min: "uzholweet" }, { en: "ishim", min: "uzhun" }, { en: "ishmael", min: "uzhnaor" },
  { en: "isiah", min: "uzuah" }, { en: "isidro", min: "uzutle" }, { en: "islam", min: "uzran" }, { en: "ismael", min: "uznaor" }, { en: "ismail", min: "uznaur" }, { en: "isolde", min: "uzerto" }, { en: "ispell", min: "uzborr" }, { en: "israeli", min: "uzlaoru" }, { en: "israelite", min: "uzlaorudo" }, { en: "issac", min: "uzzak" },
  { en: "istanbul", min: "uzdampir" }, { en: "isuzu", min: "uzisi" }, { en: "itaipu", min: "udaubi" }, { en: "itasca", min: "udazka" }, { en: "ithaca", min: "udhaka" }, { en: "ithacan", min: "udhakam" }, { en: "ito", min: "ude" }, { en: "iva", min: "ufa" }, { en: "ivan", min: "ufam" }, { en: "ivanhoe", min: "ufamheo" },
  { en: "izaak", min: "usaac" }, { en: "izanagi", min: "usamagu" }, { en: "izanami", min: "usamanu" }, { en: "izhevsk", min: "ushofzc" }, { en: "izmir", min: "usnul" }, { en: "izod", min: "uset" }, { en: "izvestia", min: "usfozdua" }, { en: "jfk", min: "qvc" }, { en: "jpeg", min: "qbog" }, { en: "jack", min: "qakc" },
  { en: "jackson", min: "qakczem" }, { en: "jacksonian", min: "qakczemuam" }, { en: "jacob", min: "qakep" }, { en: "jacobean", min: "qakepoam" }, { en: "jacobi", min: "qakepu" }, { en: "jacobin", min: "qakepum" }, { en: "jacobite", min: "qakepudo" }, { en: "jacobson", min: "qakepzem" }, { en: "jacquard", min: "qakjialt" }, { en: "jacuzzi", min: "qakissu" },
  { en: "jagiellon", min: "qaguorrem" }, { en: "jahangir", min: "qahamgul" }, { en: "jain", min: "qaum" }, { en: "jaipur", min: "qaubil" }, { en: "jake", min: "qaco" }, { en: "jamaican", min: "qanaukam" }, { en: "jame", min: "qano" }, { en: "jamel", min: "qanor" }, { en: "janacek", min: "qamakoc" }, { en: "janell", min: "qamorr" },
  { en: "janesville", min: "qamozfurro" }, { en: "jannie", min: "qammuo" }, { en: "jansen", min: "qamzom" }, { en: "japura", min: "qabila" }, { en: "jarlsberg", min: "qalrzpolg" }, { en: "jarrett", min: "qallodd" }, { en: "jarrod", min: "qallet" }, { en: "jason", min: "qazem" }, { en: "jataka", min: "qadaca" }, { en: "java", min: "qafa" },
  { en: "javascript", min: "qafazklubd" }, { en: "jayapura", min: "qayabila" }, { en: "jaycee", min: "qaykoo" }, { en: "jayson", min: "qayzem" }, { en: "jed", min: "qot" }, { en: "jedi", min: "qotu" }, { en: "jeep", min: "qoob" }, { en: "jeff", min: "qovv" }, { en: "jefferson", min: "qovvolzem" }, { en: "jehovah", min: "qohefah" },
  { en: "jekyll", min: "qocyrr" }, { en: "jensen", min: "qomzom" }, { en: "jephthah", min: "qobhdhah" }, { en: "jerald", min: "qolart" }, { en: "jeremiah", min: "qolonuah" }, { en: "jericho", min: "qolukhe" }, { en: "jeroboam", min: "qolepean" }, { en: "jerold", min: "qolert" }, { en: "jerome", min: "qoleno" }, { en: "jerri", min: "qollu" },
  { en: "jerrod", min: "qollet" }, { en: "jerrold", min: "qollert" }, { en: "jesuit", min: "qoziud" }, { en: "jew", min: "qow" }, { en: "jezebel", min: "qosopor" }, { en: "jidda", min: "qutta" }, { en: "jilin", min: "qurum" }, { en: "jim", min: "qun" }, { en: "jimenez", min: "qunomos" }, { en: "jimmie", min: "qunnuo" },
  { en: "jinan", min: "qumam" }, { en: "jinnah", min: "qummah" }, { en: "jivaro", min: "qufale" }, { en: "joaquin", min: "qeajium" }, { en: "job", min: "qep" }, { en: "jocasta", min: "qekazda" }, { en: "jock", min: "qekc" }, { en: "joe", min: "qeo" }, { en: "joel", min: "qeor" }, { en: "jogjakarta", min: "qegqacalda" },
  { en: "johann", min: "qehamm" }, { en: "johnathan", min: "qehmadham" }, { en: "johnathon", min: "qehmadhem" }, { en: "johnie", min: "qehmuo" }, { en: "johnnie", min: "qehmmuo" }, { en: "johnson", min: "qehmzem" }, { en: "johnston", min: "qehmzdem" }, { en: "johnstown", min: "qehmzdewm" }, { en: "joliet", min: "qeruod" }, { en: "jolson", min: "qerzem" },
  { en: "jon", min: "qem" }, { en: "jonah", min: "qemah" }, { en: "jonathan", min: "qemadham" }, { en: "jonathon", min: "qemadhem" }, { en: "jonesboro", min: "qemozpele" }, { en: "jonson", min: "qemzem" }, { en: "joplin", min: "qebrum" }, { en: "jordanian", min: "qeltamuam" }, { en: "jorge", min: "qelgo" }, { en: "jose", min: "qezo" },
  { en: "josef", min: "qezov" }, { en: "joseph", min: "qezobh" }, { en: "josephson", min: "qezobhzem" }, { en: "josh", min: "qezh" }, { en: "joshua", min: "qezhia" }, { en: "josiah", min: "qezuah" }, { en: "josue", min: "qezio" }, { en: "joule", min: "qeiro" }, { en: "jove", min: "qefo" }, { en: "jovian", min: "qefuam" },
  { en: "joycean", min: "qeykoam" }, { en: "juarez", min: "qialos" }, { en: "judaeo", min: "qitaoe" }, { en: "judah", min: "qitah" }, { en: "judd", min: "qitt" }, { en: "jude", min: "qito" }, { en: "judea", min: "qitoa" }, { en: "judson", min: "qitzem" }, { en: "juggernaut", min: "qiggolmaid" }, { en: "jul", min: "qir" },
  { en: "julian", min: "qiruam" }, { en: "julio", min: "qirue" }, { en: "julliard", min: "qirrualt" }, { en: "jun", min: "qim" }, { en: "juneau", min: "qimoai" }, { en: "jung", min: "qimg" }, { en: "jungfrau", min: "qimgvlai" }, { en: "jungian", min: "qimguam" }, { en: "junior", min: "qimuel" }, { en: "juno", min: "qime" },
  { en: "jurua", min: "qilia" }, { en: "justice", min: "qizduko" }, { en: "justin", min: "qizdum" }, { en: "justinian", min: "qizdumuam" }, { en: "jutland", min: "qidramt" }, { en: "kfc", min: "cvk" }, { en: "kgb", min: "cgp" }, { en: "kia", min: "cua" }, { en: "kkk", min: "ccc" }, { en: "kaaba", min: "caapa" },
  { en: "kafka", min: "cavca" }, { en: "kafkaesque", min: "cavcaozjio" }, { en: "kagoshima", min: "cagezhuna" }, { en: "kahlua", min: "cahria" }, { en: "kahului", min: "cahiriu" }, { en: "kaifeng", min: "cauvomg" }, { en: "kailua", min: "cauria" }, { en: "kalahari", min: "carahalu" }, { en: "kalamazoo", min: "caranasee" }, { en: "kalb", min: "carp" },
  { en: "kalevala", min: "carofara" }, { en: "kalgoorlie", min: "cargeelruo" }, { en: "kalmyk", min: "carnyc" }, { en: "kama", min: "cana" }, { en: "kamchatka", min: "cankhadca" }, { en: "kamehameha", min: "canohanoha" }, { en: "kampuchea", min: "canbikhoa" }, { en: "kane", min: "camo" }, { en: "kaneohe", min: "camoeho" }, { en: "kankakee", min: "camcacoo" },
  { en: "kannada", min: "cammata" }, { en: "kano", min: "came" }, { en: "kanpur", min: "cambil" }, { en: "kansan", min: "camzam" }, { en: "kant", min: "camd" }, { en: "kantian", min: "camduam" }, { en: "kaohsiung", min: "caehzuimg" }, { en: "kaposi", min: "cabezu" }, { en: "karachi", min: "calakhu" }, { en: "karaganda", min: "calagamta" },
  { en: "karakorum", min: "calacelin" }, { en: "karamazov", min: "calanasef" }, { en: "kareem", min: "caloon" }, { en: "karenina", min: "calomuma" }, { en: "karl", min: "calr" }, { en: "karloff", min: "calrevv" }, { en: "karo", min: "cale" }, { en: "karroo", min: "callee" }, { en: "kasai", min: "cazau" }, { en: "kashmir", min: "cazhnul" },
  { en: "kasparov", min: "cazbalef" }, { en: "katelyn", min: "cadorym" }, { en: "katmai", min: "cadnau" }, { en: "katmandu", min: "cadnamti" }, { en: "katowice", min: "cadewuko" }, { en: "kauai", min: "caiau" }, { en: "kaufman", min: "caivnam" }, { en: "kaunda", min: "caimta" }, { en: "kawabata", min: "cawapada" }, { en: "kawasaki", min: "cawazacu" },
  { en: "kazakh", min: "casach" }, { en: "kazan", min: "casam" }, { en: "keaton", min: "coadem" }, { en: "keck", min: "cokc" }, { en: "keenan", min: "coomam" }, { en: "keewatin", min: "coowadum" }, { en: "keillor", min: "courrel" }, { en: "keisha", min: "couzha" }, { en: "kellogg", min: "corregg" }, { en: "kelvin", min: "corfum" },
];
