/**
 * @file Contains dictionary entries for category: grammar_con.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const grammar_con: DictionaryEntry[] = [
  { en: "and", min: "na" }, { en: "but", min: "pero" }, { en: "or", min: "ka" }, { en: "so", min: "entonces" }, { en: "because", min: "porque" }, { en: "poise", min: "beuzo" }, { en: "poison", min: "beuzem" }, { en: "poke", min: "beco" }, { en: "pol", min: "ber" }, { en: "polarize", min: "beraluso" },
  { en: "polecat", min: "berokad" }, { en: "police", min: "beruko" }, { en: "policeman", min: "berukonam" }, { en: "policemen", min: "berukonom" }, { en: "polio", min: "berue" }, { en: "polite", min: "berudo" }, { en: "politesse", min: "berudozzo" }, { en: "politician", min: "berudukuam" }, { en: "politicize", min: "berudukuso" }, { en: "politico", min: "beruduke" },
  { en: "polka", min: "berca" }, { en: "poll", min: "berr" }, { en: "pollen", min: "berrom" }, { en: "pollinate", min: "berrumado" }, { en: "polliwog", min: "berruweg" }, { en: "pollutant", min: "berridamd" }, { en: "pollute", min: "berrido" }, { en: "pollywog", min: "berryweg" }, { en: "polonaise", min: "beremauzo" }, { en: "polonium", min: "beremuin" },
  { en: "poltroon", min: "berdleem" }, { en: "polyglot", min: "berygred" }, { en: "polygon", min: "berygem" }, { en: "polygraph", min: "beryglabh" }, { en: "polyhedra", min: "beryhotla" }, { en: "polyhedron", min: "beryhotlem" }, { en: "polyp", min: "beryb" }, { en: "polythene", min: "berydhomo" }, { en: "pomade", min: "benato" }, { en: "pommel", min: "bennor" },
  { en: "pomp", min: "benb" }, { en: "pompom", min: "benben" }, { en: "pompon", min: "benbem" }, { en: "poncho", min: "bemkhe" }, { en: "pond", min: "bemt" }, { en: "pone", min: "bemo" }, { en: "poniard", min: "bemualt" }, { en: "pontiff", min: "bemduvv" }, { en: "pontoon", min: "bemdeem" }, { en: "ponytail", min: "bemydaur" },
  { en: "pooch", min: "beekh" }, { en: "poodle", min: "beetro" }, { en: "pool", min: "beer" }, { en: "poop", min: "beeb" }, { en: "poor", min: "beel" }, { en: "poorhouse", min: "beelheizo" }, { en: "pop", min: "beb" }, { en: "popcorn", min: "bebkelm" }, { en: "popgun", min: "bebgim" }, { en: "poplin", min: "bebrum" },
  { en: "poppa", min: "bebba" }, { en: "poppycock", min: "bebbykekc" }, { en: "populace", min: "bebirako" }, { en: "popularize", min: "bebiraluso" }, { en: "populate", min: "bebirado" }, { en: "porcelain", min: "belkoraum" }, { en: "porch", min: "belkh" }, { en: "porcine", min: "belkumo" }, { en: "porcupine", min: "belkibumo" }, { en: "pore", min: "belo" },
  { en: "pork", min: "belc" }, { en: "porn", min: "belm" }, { en: "porno", min: "belme" }, { en: "porpoise", min: "belbeuzo" }, { en: "porridge", min: "bellutgo" }, { en: "portage", min: "beldago" }, { en: "portend", min: "beldomt" }, { en: "portent", min: "beldomd" }, { en: "portfolio", min: "beldverue" }, { en: "porthole", min: "beldhero" },
  { en: "portico", min: "belduke" }, { en: "portrait", min: "beldlaud" }, { en: "pose", min: "bezo" }, { en: "poseur", min: "bezoil" }, { en: "posh", min: "bezh" }, { en: "posit", min: "bezud" }, { en: "positron", min: "bezudlem" }, { en: "posse", min: "bezzo" }, { en: "possession", min: "bezzozzuem" }, { en: "possessor", min: "bezzozzel" },
  { en: "possum", min: "bezzin" }, { en: "pot", min: "bed" }, { en: "potash", min: "bedazh" }, { en: "potassium", min: "bedazzuin" }, { en: "potent", min: "bedomd" }, { en: "potentate", min: "bedomdado" }, { en: "pothole", min: "bedhero" }, { en: "pothook", min: "bedheec" }, { en: "potluck", min: "bedrikc" }, { en: "potpie", min: "bedbuo" },
  { en: "potpourri", min: "bedbeillu" }, { en: "potsherd", min: "bedzholt" }, { en: "potshot", min: "bedzhed" }, { en: "pottage", min: "beddago" }, { en: "pouch", min: "beikh" }, { en: "poultice", min: "beirduko" }, { en: "pounce", min: "beimko" }, { en: "pour", min: "beil" }, { en: "pout", min: "beid" }, { en: "powerboat", min: "bewolpead" },
  { en: "powerhouse", min: "bewolheizo" }, { en: "powwow", min: "bewwew" }, { en: "pox", min: "bex" }, { en: "practice", min: "blakduko" }, { en: "practise", min: "blakduzo" }, { en: "prairie", min: "blauluo" }, { en: "praise", min: "blauzo" }, { en: "praline", min: "blarumo" }, { en: "pram", min: "blan" }, { en: "prance", min: "blamko" },
  { en: "prank", min: "blamc" }, { en: "prate", min: "blado" }, { en: "pratfall", min: "bladvarr" }, { en: "prattle", min: "bladdro" }, { en: "prawn", min: "blawm" }, { en: "preen", min: "bloom" }, { en: "prep", min: "blob" }, { en: "prick", min: "blukc" }, { en: "prickle", min: "blukcro" }, { en: "pride", min: "bluto" },
  { en: "prig", min: "blug" }, { en: "prim", min: "blun" }, { en: "primate", min: "blunado" }, { en: "prime", min: "bluno" }, { en: "primp", min: "blunb" }, { en: "primrose", min: "blunlezo" }, { en: "principle", min: "blumkubro" }, { en: "print", min: "blumd" }, { en: "printout", min: "blumdeid" }, { en: "prior", min: "bluel" },
  { en: "prioritize", min: "blueluduso" }, { en: "prison", min: "bluzem" }, { en: "pristine", min: "bluzdumo" }, { en: "prithee", min: "bludhoo" }, { en: "private", min: "blufado" }, { en: "privatize", min: "blufaduso" }, { en: "privet", min: "blufod" }, { en: "privilege", min: "blufurogo" }, { en: "prize", min: "bluso" }, { en: "prizefight", min: "blusovughd" },
  { en: "pro", min: "ble" }, { en: "probe", min: "blepo" }, { en: "prod", min: "blet" }, { en: "prom", min: "blen" }, { en: "promo", min: "blene" }, { en: "pron", min: "blem" }, { en: "prone", min: "blemo" }, { en: "prong", min: "blemg" }, { en: "proof", min: "bleev" }, { en: "prop", min: "bleb" },
  { en: "prose", min: "blezo" }, { en: "proud", min: "bleit" }, { en: "prove", min: "blefo" }, { en: "prow", min: "blew" }, { en: "prowl", min: "blewr" }, { en: "prude", min: "blito" }, { en: "prudent", min: "blitomd" }, { en: "prune", min: "blimo" }, { en: "prurience", min: "bliluomko" }, { en: "prurient", min: "bliluomd" },
  { en: "psalm", min: "bzarn" }, { en: "pseudo", min: "bzoite" }, { en: "pseudonym", min: "bzoitemyn" }, { en: "pshaw", min: "bzhaw" }, { en: "psst", min: "bzzd" }, { en: "psych", min: "bzykh" }, { en: "psycho", min: "bzykhe" }, { en: "ptarmigan", min: "bdalnugam" }, { en: "ptomaine", min: "bdenaumo" }, { en: "pub", min: "bip" },
  { en: "pubescence", min: "bipozkomko" }, { en: "pubescent", min: "bipozkomd" }, { en: "publican", min: "biprukam" }, { en: "publicize", min: "biprukuso" }, { en: "puddle", min: "bittro" }, { en: "puerile", min: "bioluro" }, { en: "puff", min: "bivv" }, { en: "puffball", min: "bivvparr" }, { en: "puffin", min: "bivvum" }, { en: "pug", min: "big" },
  { en: "puke", min: "bico" }, { en: "pull", min: "birr" }, { en: "pullback", min: "birrpakc" }, { en: "pullet", min: "birrod" }, { en: "pullout", min: "birreid" }, { en: "pulp", min: "birb" }, { en: "pulpit", min: "birbud" }, { en: "pulsate", min: "birzado" }, { en: "pulse", min: "birzo" }, { en: "pulverize", min: "birfoluso" },
  { en: "puma", min: "bina" }, { en: "pumice", min: "binuko" }, { en: "pummel", min: "binnor" }, { en: "pump", min: "binb" }, { en: "pumpkin", min: "binbcum" }, { en: "pun", min: "bim" }, { en: "punchline", min: "bimkhrumo" }, { en: "punctuate", min: "bimkdiado" }, { en: "puncture", min: "bimkdilo" }, { en: "pundit", min: "bimtud" },
  { en: "pungent", min: "bimgomd" }, { en: "punk", min: "bimc" }, { en: "punt", min: "bimd" }, { en: "pup", min: "bib" }, { en: "pupa", min: "biba" }, { en: "pupae", min: "bibao" }, { en: "pupil", min: "bibur" }, { en: "puppet", min: "bibbod" }, { en: "purblind", min: "bilprumt" }, { en: "purchase", min: "bilkhazo" },
  { en: "pure", min: "bilo" }, { en: "puree", min: "biloo" }, { en: "purge", min: "bilgo" }, { en: "purl", min: "bilr" }, { en: "purloin", min: "bilreum" }, { en: "purple", min: "bilbro" }, { en: "purport", min: "bilbeld" }, { en: "purpose", min: "bilbezo" }, { en: "purr", min: "bill" }, { en: "purse", min: "bilzo" },
  { en: "pursuance", min: "bilziamko" }, { en: "pursuant", min: "bilziamd" }, { en: "pursue", min: "bilzio" }, { en: "pursuit", min: "bilziud" }, { en: "purulence", min: "biliromko" }, { en: "purulent", min: "biliromd" }, { en: "purveyor", min: "bilfoyel" }, { en: "purview", min: "bilfuow" }, { en: "push", min: "bizh" }, { en: "pushcart", min: "bizhkald" },
  { en: "pushup", min: "bizhib" }, { en: "pussycat", min: "bizzykad" }, { en: "pussyfoot", min: "bizzyveed" }, { en: "pustule", min: "bizdiro" }, { en: "put", min: "bid" }, { en: "putrescent", min: "bidlozkomd" }, { en: "putrid", min: "bidlut" }, { en: "putsch", min: "bidzkh" }, { en: "putt", min: "bidd" }, { en: "puzzle", min: "bissro" },
  { en: "pwn", min: "bwm" }, { en: "pylon", min: "byrem" }, { en: "pyorrhea", min: "byellhoa" }, { en: "pyramid", min: "bylanut" }, { en: "pyre", min: "bylo" }, { en: "pyrite", min: "byludo" }, { en: "pyromania", min: "bylenamua" }, { en: "pyromaniac", min: "bylenamuak" }, { en: "pyx", min: "byx" }, { en: "qua", min: "jia" },
  { en: "quack", min: "jiakc" }, { en: "quad", min: "jiat" }, { en: "quadrangle", min: "jiatlamgro" }, { en: "quadrant", min: "jiatlamd" }, { en: "quadrature", min: "jiatladilo" }, { en: "quadrille", min: "jiatlurro" }, { en: "quadruple", min: "jiatlibro" }, { en: "quadruplet", min: "jiatlibrod" }, { en: "quaff", min: "jiavv" }, { en: "quagmire", min: "jiagnulo" },
  { en: "quahaug", min: "jiahaig" }, { en: "quahog", min: "jiaheg" }, { en: "quail", min: "jiaur" }, { en: "quaint", min: "jiaumd" }, { en: "quake", min: "jiaco" }, { en: "qualm", min: "jiarn" }, { en: "quanta", min: "jiamda" }, { en: "quantum", min: "jiamdin" }, { en: "quarantine", min: "jialamdumo" }, { en: "quark", min: "jialc" },
  { en: "quarrel", min: "jiallor" }, { en: "quart", min: "jiald" }, { en: "quartet", min: "jialdod" }, { en: "quartette", min: "jialdoddo" }, { en: "quarto", min: "jialde" }, { en: "quartz", min: "jialds" }, { en: "quash", min: "jiazh" }, { en: "quasi", min: "jiazu" }, { en: "quatrain", min: "jiadlaum" }, { en: "quell", min: "jiorr" },
  { en: "quench", min: "jiomkh" }, { en: "quesadilla", min: "jiozaturra" }, { en: "queue", min: "jioio" }, { en: "quibble", min: "jiuppro" }, { en: "quiche", min: "jiukho" }, { en: "quicken", min: "jiukcom" }, { en: "quickie", min: "jiukcuo" }, { en: "quicklime", min: "jiukcruno" }, { en: "quicksand", min: "jiukczamt" }, { en: "quid", min: "jiut" },
];
