/**
 * @file Contains dictionary entries for category: grammar_prep.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const grammar_prep: DictionaryEntry[] = [
  { en: "on", min: "ba" }, { en: "in", min: "con" }, { en: "under", min: "pajo" }, { en: "above", min: "arriba" }, { en: "behind", min: "atras" }, { en: "quiescence", min: "jiuozkomko" }, { en: "quiescent", min: "jiuozkomd" }, { en: "quiet", min: "jiuod" }, { en: "quietude", min: "jiuodito" }, { en: "quill", min: "jiurr" },
  { en: "quilt", min: "jiurd" }, { en: "quince", min: "jiumko" }, { en: "quine", min: "jiumo" }, { en: "quinine", min: "jiumumo" }, { en: "quintet", min: "jiumdod" }, { en: "quintuple", min: "jiumdibro" }, { en: "quintuplet", min: "jiumdibrod" }, { en: "quip", min: "jiub" }, { en: "quire", min: "jiulo" }, { en: "quirk", min: "jiulc" },
  { en: "quit", min: "jiud" }, { en: "quite", min: "jiudo" }, { en: "quiz", min: "jius" }, { en: "quoit", min: "jieud" }, { en: "quondam", min: "jiemtan" }, { en: "quorum", min: "jielin" }, { en: "quota", min: "jieda" }, { en: "quote", min: "jiedo" }, { en: "quotidian", min: "jiedutuam" }, { en: "quotient", min: "jieduomd" },
  { en: "rabbi", min: "lappu" }, { en: "rabbinate", min: "lappumado" }, { en: "rabble", min: "lappro" }, { en: "rabid", min: "laput" }, { en: "raccoon", min: "lakkeem" }, { en: "race", min: "lako" }, { en: "racecourse", min: "lakokeilzo" }, { en: "racehorse", min: "lakohelzo" }, { en: "raceme", min: "lakono" }, { en: "racetrack", min: "lakodlakc" },
  { en: "rack", min: "lakc" }, { en: "racket", min: "lakcod" }, { en: "raconteur", min: "lakemdoil" }, { en: "racoon", min: "lakeem" }, { en: "racquet", min: "lakjiod" }, { en: "radiance", min: "latuamko" }, { en: "radiant", min: "latuamd" }, { en: "radiate", min: "latuado" }, { en: "radiator", min: "latuadel" }, { en: "radii", min: "latuu" },
  { en: "radio", min: "latue" }, { en: "radiogram", min: "latueglan" }, { en: "radium", min: "latuin" }, { en: "radon", min: "latem" }, { en: "raffia", min: "lavvua" }, { en: "raffle", min: "lavvro" }, { en: "raft", min: "lavd" }, { en: "rag", min: "lag" }, { en: "raga", min: "laga" }, { en: "ragamuffin", min: "laganivvum" },
  { en: "rage", min: "lago" }, { en: "raglan", min: "lagram" }, { en: "ragout", min: "lageid" }, { en: "ragtag", min: "lagdag" }, { en: "ragtime", min: "lagduno" }, { en: "raid", min: "laut" }, { en: "rail", min: "laur" }, { en: "railroad", min: "laurleat" }, { en: "rainbow", min: "laumpew" }, { en: "raincoat", min: "laumkead" },
  { en: "raindrop", min: "laumtleb" }, { en: "rainfall", min: "laumvarr" }, { en: "rainstorm", min: "laumzdeln" }, { en: "raise", min: "lauzo" }, { en: "raisin", min: "lauzum" }, { en: "raja", min: "laqa" }, { en: "rajah", min: "laqah" }, { en: "rake", min: "laco" }, { en: "ramble", min: "lanpro" }, { en: "ramp", min: "lanb" },
  { en: "rampage", min: "lanbago" }, { en: "rampant", min: "lanbamd" }, { en: "rampart", min: "lanbald" }, { en: "ramrod", min: "lanlet" }, { en: "ramshackle", min: "lanzhakcro" }, { en: "ran", min: "lam" }, { en: "ranch", min: "lamkh" }, { en: "rancid", min: "lamkut" }, { en: "rancor", min: "lamkel" }, { en: "random", min: "lamten" },
  { en: "randomize", min: "lamtenuso" }, { en: "rang", min: "lamg" }, { en: "range", min: "lamgo" }, { en: "rank", min: "lamc" }, { en: "rankle", min: "lamcro" }, { en: "ransack", min: "lamzakc" }, { en: "ransom", min: "lamzen" }, { en: "rant", min: "lamd" }, { en: "rap", min: "lab" }, { en: "rape", min: "labo" },
  { en: "rapine", min: "labumo" }, { en: "rapport", min: "labbeld" }, { en: "rapt", min: "labd" }, { en: "rapture", min: "labdilo" }, { en: "rare", min: "lalo" }, { en: "rash", min: "lazh" }, { en: "rasp", min: "lazb" }, { en: "rat", min: "lad" }, { en: "ratchet", min: "ladkhod" }, { en: "rate", min: "lado" },
  { en: "ratio", min: "ladue" }, { en: "rationale", min: "laduemaro" }, { en: "rattan", min: "laddam" }, { en: "rattle", min: "laddro" }, { en: "rattletrap", min: "laddrodlab" }, { en: "rattrap", min: "laddlab" }, { en: "ravage", min: "lafago" }, { en: "rave", min: "lafo" }, { en: "ravine", min: "lafumo" }, { en: "ravioli", min: "lafueru" },
  { en: "raw", min: "law" }, { en: "rawhide", min: "lawhuto" }, { en: "rayon", min: "layem" }, { en: "raze", min: "laso" }, { en: "razor", min: "lasel" }, { en: "razz", min: "lass" }, { en: "read", min: "loat" }, { en: "ream", min: "loan" }, { en: "reap", min: "loab" }, { en: "recd", min: "lokt" },
  { en: "redo", min: "lote" }, { en: "reef", min: "loov" }, { en: "reek", min: "looc" }, { en: "reel", min: "loor" }, { en: "ref", min: "lov" }, { en: "rehi", min: "lohu" }, { en: "rein", min: "loum" }, { en: "rend", min: "lomt" }, { en: "rent", min: "lomd" }, { en: "resp", min: "lozb" },
  { en: "rest", min: "lozd" }, { en: "rhapsodize", min: "lhabzetuso" }, { en: "rheostat", min: "lhoezdad" }, { en: "rheum", min: "lhoin" }, { en: "rhinestone", min: "lhumozdemo" }, { en: "rhino", min: "lhume" }, { en: "rhinoceri", min: "lhumekolu" }, { en: "rhizome", min: "lhuseno" }, { en: "rho", min: "lhe" }, { en: "rhodium", min: "lhetuin" },
  { en: "rhombi", min: "lhenpu" }, { en: "rhomboid", min: "lhenpeut" }, { en: "rhubarb", min: "lhipalp" }, { en: "rhyme", min: "lhyno" }, { en: "rhythm", min: "lhydhn" }, { en: "rib", min: "lup" }, { en: "ribald", min: "lupart" }, { en: "ribbon", min: "luppem" }, { en: "riboflavin", min: "lupevrafum" }, { en: "ricksha", min: "lukczha" },
  { en: "rickshaw", min: "lukczhaw" }, { en: "ricochet", min: "lukekhod" }, { en: "ricotta", min: "lukedda" }, { en: "rid", min: "lut" }, { en: "riddance", min: "luttamko" }, { en: "ridden", min: "luttom" }, { en: "ridge", min: "lutgo" }, { en: "ridgepole", min: "lutgobero" }, { en: "ridicule", min: "lutukiro" }, { en: "rife", min: "luvo" },
  { en: "riff", min: "luvv" }, { en: "riffle", min: "luvvro" }, { en: "riffraff", min: "luvvlavv" }, { en: "rifle", min: "luvro" }, { en: "rifleman", min: "luvronam" }, { en: "riflemen", min: "luvronom" }, { en: "rift", min: "luvd" }, { en: "rig", min: "lug" }, { en: "rigamarole", min: "luganalero" }, { en: "right", min: "lughd" },
  { en: "rightmost", min: "lughdnezd" }, { en: "rigid", min: "lugut" }, { en: "rigmarole", min: "lugnalero" }, { en: "rigor", min: "lugel" }, { en: "rile", min: "luro" }, { en: "rill", min: "lurr" }, { en: "rim", min: "lun" }, { en: "rime", min: "luno" }, { en: "rind", min: "lumt" }, { en: "ringlet", min: "lumgrod" },
  { en: "ringside", min: "lumgzuto" }, { en: "ringtone", min: "lumgdemo" }, { en: "ringworm", min: "lumgweln" }, { en: "rink", min: "lumc" }, { en: "rinse", min: "lumzo" }, { en: "riot", min: "lued" }, { en: "ripe", min: "lubo" }, { en: "ripen", min: "lubom" }, { en: "ripoff", min: "lubevv" }, { en: "riposte", min: "lubezdo" },
  { en: "ripple", min: "lubbro" }, { en: "ripsaw", min: "lubzaw" }, { en: "rise", min: "luzo" }, { en: "risen", min: "luzom" }, { en: "risk", min: "luzc" }, { en: "rite", min: "ludo" }, { en: "riven", min: "lufom" }, { en: "riverfront", min: "lufolvlemd" }, { en: "rivet", min: "lufod" }, { en: "rivulet", min: "lufirod" },
  { en: "roadblock", min: "leatprekc" }, { en: "roadhouse", min: "leatheizo" }, { en: "roadkill", min: "leatcurr" }, { en: "roadshow", min: "leatzhew" }, { en: "roadside", min: "leatzuto" }, { en: "roadwork", min: "leatwelc" }, { en: "roam", min: "lean" }, { en: "roan", min: "leam" }, { en: "roast", min: "leazd" }, { en: "robe", min: "lepo" },
  { en: "robocall", min: "lepekarr" }, { en: "robot", min: "leped" }, { en: "robust", min: "lepizd" }, { en: "rocket", min: "lekcod" }, { en: "rococo", min: "lekeke" }, { en: "rode", min: "leto" }, { en: "rodent", min: "letomd" }, { en: "rodeo", min: "letoe" }, { en: "roebuck", min: "leopikc" }, { en: "rogue", min: "legio" },
  { en: "roil", min: "leur" }, { en: "role", min: "lero" }, { en: "roll", min: "lerr" }, { en: "rollback", min: "lerrpakc" }, { en: "rollick", min: "lerrukc" }, { en: "romaine", min: "lenaumo" }, { en: "romance", min: "lenamko" }, { en: "romp", min: "lenb" }, { en: "rood", min: "leet" }, { en: "roof", min: "leev" },
  { en: "rooftop", min: "leevdeb" }, { en: "rook", min: "leec" }, { en: "rookie", min: "leecuo" }, { en: "room", min: "leen" }, { en: "roommate", min: "leennado" }, { en: "roost", min: "leezd" }, { en: "rope", min: "lebo" }, { en: "roseate", min: "lezoado" }, { en: "rosebud", min: "lezopit" }, { en: "rosebush", min: "lezopizh" },
  { en: "rosewood", min: "lezoweet" }, { en: "rosin", min: "lezum" }, { en: "rostra", min: "lezdla" }, { en: "rostrum", min: "lezdlin" }, { en: "rot", min: "led" }, { en: "rotate", min: "ledado" }, { en: "rote", min: "ledo" }, { en: "rotisserie", min: "leduzzoluo" }, { en: "rotor", min: "ledel" }, { en: "rotten", min: "leddom" },
  { en: "rotund", min: "ledimt" }, { en: "rotunda", min: "ledimta" }, { en: "rouge", min: "leigo" }, { en: "rough", min: "leigh" }, { en: "roughage", min: "leighago" }, { en: "roughen", min: "leighom" }, { en: "roughhouse", min: "leighheizo" }, { en: "roughneck", min: "leighmokc" }, { en: "roughshod", min: "leighzhet" }, { en: "roulette", min: "leiroddo" },
  { en: "roundabout", min: "leimtapeid" }, { en: "roundhouse", min: "leimtheizo" }, { en: "roundup", min: "leimtib" }, { en: "roundworm", min: "leimtweln" }, { en: "rouse", min: "leizo" }, { en: "roustabout", min: "leizdapeid" }, { en: "rout", min: "leid" }, { en: "route", min: "leido" }, { en: "routine", min: "leidumo" }, { en: "routinize", min: "leidumuso" },
  { en: "rowboat", min: "lewpead" }, { en: "rowel", min: "lewor" }, { en: "rpm", min: "lbn" }, { en: "rub", min: "lip" }, { en: "rubberize", min: "lippoluso" }, { en: "rubberneck", min: "lippolmokc" }, { en: "rubble", min: "lippro" }, { en: "rubdown", min: "liptewm" }, { en: "rube", min: "lipo" }, { en: "rubella", min: "liporra" },
  { en: "rubicund", min: "lipukimt" }, { en: "ruble", min: "lipro" }, { en: "rucksack", min: "likczakc" }, { en: "rude", min: "lito" }, { en: "rue", min: "lio" }, { en: "ruff", min: "livv" }, { en: "ruffian", min: "livvuam" }, { en: "ruffle", min: "livvro" }, { en: "rug", min: "lig" }, { en: "rugrat", min: "liglad" },
];
