/**
 * @file Contains dictionary entries for category: home_tools.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const home_tools: DictionaryEntry[] = [
  { en: "hammer", min: "palu" }, { en: "saw", min: "sierra" }, { en: "key", min: "llave" }, { en: "drill", min: "perfo" }, { en: "screw", min: "tuerca" }, { en: "cram", min: "klan" }, { en: "cramp", min: "klanb" }, { en: "crania", min: "klamua" }, { en: "cranium", min: "klamuin" }, { en: "crank", min: "klamc" },
  { en: "crankcase", min: "klamckazo" }, { en: "crankshaft", min: "klamczhavd" }, { en: "crap", min: "klab" }, { en: "crape", min: "klabo" }, { en: "crash", min: "klazh" }, { en: "crate", min: "klado" }, { en: "cravat", min: "klafad" }, { en: "crave", min: "klafo" }, { en: "craven", min: "klafom" }, { en: "craw", min: "klaw" },
  { en: "crawl", min: "klawr" }, { en: "crawlspace", min: "klawrzbako" }, { en: "crayon", min: "klayem" }, { en: "craze", min: "klaso" }, { en: "creak", min: "kloac" }, { en: "cream", min: "kloan" }, { en: "crease", min: "kloazo" }, { en: "creature", min: "kloadilo" }, { en: "credence", min: "klotomko" }, { en: "credenza", min: "klotomsa" },
  { en: "credit", min: "klotud" }, { en: "creditor", min: "klotudel" }, { en: "credo", min: "klote" }, { en: "creel", min: "kloor" }, { en: "creep", min: "kloob" }, { en: "cremate", min: "klonado" }, { en: "crematoria", min: "klonadelua" }, { en: "creosote", min: "kloezedo" }, { en: "crepe", min: "klobo" }, { en: "crept", min: "klobd" },
  { en: "crescendi", min: "klozkomtu" }, { en: "crescendo", min: "klozkomte" }, { en: "crescent", min: "klozkomd" }, { en: "cretin", min: "klodum" }, { en: "crevasse", min: "klofazzo" }, { en: "crevice", min: "klofuko" }, { en: "crew", min: "klow" }, { en: "crewman", min: "klownam" }, { en: "crewmen", min: "klownom" }, { en: "crib", min: "klup" },
  { en: "cribbage", min: "kluppago" }, { en: "cricket", min: "klukcod" }, { en: "crime", min: "kluno" }, { en: "crimp", min: "klunb" }, { en: "crimson", min: "klunzem" }, { en: "cringe", min: "klumgo" }, { en: "crinkle", min: "klumcro" }, { en: "crinoline", min: "klumerumo" }, { en: "cripple", min: "klubbro" }, { en: "crisp", min: "kluzb" },
  { en: "criteria", min: "kludolua" }, { en: "criterion", min: "kludoluem" }, { en: "criticize", min: "kludukuso" }, { en: "critique", min: "kludujio" }, { en: "croak", min: "kleac" }, { en: "crochet", min: "klekhod" }, { en: "croci", min: "kleku" }, { en: "crock", min: "klekc" }, { en: "crocodile", min: "kleketuro" }, { en: "croissant", min: "kleuzzamd" },
  { en: "crone", min: "klemo" }, { en: "crook", min: "kleec" }, { en: "croon", min: "kleem" }, { en: "crop", min: "kleb" }, { en: "croquet", min: "klejiod" }, { en: "croquette", min: "klejioddo" }, { en: "crossbeam", min: "klezzpoan" }, { en: "crossbow", min: "klezzpew" }, { en: "crosscheck", min: "klezzkhokc" }, { en: "crossfire", min: "klezzvulo" },
  { en: "crosspiece", min: "klezzbuoko" }, { en: "crossroad", min: "klezzleat" }, { en: "crosstown", min: "klezzdewm" }, { en: "crosswalk", min: "klezzwarc" }, { en: "crossword", min: "klezzwelt" }, { en: "crotch", min: "kledkh" }, { en: "crotchet", min: "kledkhod" }, { en: "crouch", min: "kleikh" }, { en: "croup", min: "kleib" }, { en: "crow", min: "klew" },
  { en: "crowd", min: "klewt" }, { en: "crowdfund", min: "klewtvimt" }, { en: "crown", min: "klewm" }, { en: "crucifix", min: "klikuvux" }, { en: "cruciform", min: "klikuveln" }, { en: "crud", min: "klit" }, { en: "crude", min: "klito" }, { en: "cruel", min: "klior" }, { en: "cruet", min: "kliod" }, { en: "cruft", min: "klivd" },
  { en: "crumb", min: "klinp" }, { en: "crumble", min: "klinpro" }, { en: "crumpet", min: "klinbod" }, { en: "crumple", min: "klinbro" }, { en: "crunch", min: "klimkh" }, { en: "crusade", min: "klizato" }, { en: "crush", min: "klizh" }, { en: "crust", min: "klizd" }, { en: "crustacean", min: "klizdakoam" }, { en: "crutch", min: "klidkh" },
  { en: "crypt", min: "klybd" }, { en: "cryptogram", min: "klybdeglan" }, { en: "crystalize", min: "klyzdaruso" }, { en: "cub", min: "kip" }, { en: "cubbyhole", min: "kippyhero" }, { en: "cube", min: "kipo" }, { en: "cubicle", min: "kipukro" }, { en: "cubit", min: "kipud" }, { en: "cuckold", min: "kikcert" }, { en: "cuckoo", min: "kikcee" },
  { en: "cud", min: "kit" }, { en: "cuddle", min: "kittro" }, { en: "cudgel", min: "kitgor" }, { en: "cue", min: "kio" }, { en: "cuff", min: "kivv" }, { en: "cuisine", min: "kiuzumo" }, { en: "cull", min: "kirr" }, { en: "culminate", min: "kirnumado" }, { en: "culotte", min: "kireddo" }, { en: "culprit", min: "kirblud" },
  { en: "cult", min: "kird" }, { en: "cultivate", min: "kirdufado" }, { en: "cultivator", min: "kirdufadel" }, { en: "culture", min: "kirdilo" }, { en: "culvert", min: "kirfold" }, { en: "cum", min: "kin" }, { en: "cumbersome", min: "kinpolzeno" }, { en: "cumin", min: "kinum" }, { en: "cummerbund", min: "kinnolpimt" }, { en: "cumquat", min: "kinjiad" },
  { en: "cumuli", min: "kiniru" }, { en: "cuneiform", min: "kimouveln" }, { en: "cunt", min: "kimd" }, { en: "cup", min: "kib" }, { en: "cupboard", min: "kibpealt" }, { en: "cupcake", min: "kibkaco" }, { en: "cupola", min: "kibera" }, { en: "cur", min: "kil" }, { en: "curate", min: "kilado" }, { en: "curator", min: "kiladel" },
  { en: "curb", min: "kilp" }, { en: "curd", min: "kilt" }, { en: "curdle", min: "kiltro" }, { en: "cure", min: "kilo" }, { en: "curfew", min: "kilvow" }, { en: "curio", min: "kilue" }, { en: "curl", min: "kilr" }, { en: "curlew", min: "kilrow" }, { en: "curlicue", min: "kilrukio" }, { en: "curlycue", min: "kilrykio" },
  { en: "curmudgeon", min: "kilnitgoem" }, { en: "currant", min: "killamd" }, { en: "current", min: "killomd" }, { en: "curricula", min: "killukira" }, { en: "curriculum", min: "killukirin" }, { en: "currycomb", min: "killykenp" }, { en: "curse", min: "kilzo" }, { en: "cursor", min: "kilzel" }, { en: "curst", min: "kilzd" }, { en: "curtail", min: "kildaur" },
  { en: "curtain", min: "kildaum" }, { en: "curvature", min: "kilfadilo" }, { en: "curve", min: "kilfo" }, { en: "cushion", min: "kizhuem" }, { en: "cusp", min: "kizb" }, { en: "cuspid", min: "kizbut" }, { en: "custard", min: "kizdalt" }, { en: "custodian", min: "kizdetuam" }, { en: "custom", min: "kizden" }, { en: "customize", min: "kizdenuso" },
  { en: "cut", min: "kid" }, { en: "cutback", min: "kidpakc" }, { en: "cute", min: "kido" }, { en: "cuticle", min: "kidukro" }, { en: "cutlet", min: "kidrod" }, { en: "cutoff", min: "kidevv" }, { en: "cutout", min: "kideid" }, { en: "cutthroat", min: "kiddhlead" }, { en: "cutup", min: "kidib" }, { en: "cyanide", min: "kyamuto" },
  { en: "cyberpunk", min: "kypolbimc" }, { en: "cybersex", min: "kypolzox" }, { en: "cyberspace", min: "kypolzbako" }, { en: "cyclamen", min: "kykranom" }, { en: "cycle", min: "kykro" }, { en: "cyclone", min: "kykremo" }, { en: "cyclotron", min: "kykredlem" }, { en: "cygnet", min: "kygmod" }, { en: "cynosure", min: "kymezilo" }, { en: "cyst", min: "kyzd" },
  { en: "cytoplasm", min: "kydebrazn" }, { en: "czarina", min: "ksaluma" }, { en: "dab", min: "tap" }, { en: "dabble", min: "tappro" }, { en: "dacha", min: "takha" }, { en: "dachshund", min: "takhzhimt" }, { en: "dactyl", min: "takdyr" }, { en: "dad", min: "tat" }, { en: "dado", min: "tate" }, { en: "daemon", min: "taonem" },
  { en: "daffodil", min: "tavvetur" }, { en: "daft", min: "tavd" }, { en: "daiquiri", min: "taujiulu" }, { en: "dairymaid", min: "taulynaut" }, { en: "dairyman", min: "taulynam" }, { en: "dairymen", min: "taulynom" }, { en: "dalliance", min: "tarruamko" }, { en: "dam", min: "tan" }, { en: "damage", min: "tanago" }, { en: "damask", min: "tanazc" },
  { en: "dame", min: "tano" }, { en: "damn", min: "tanm" }, { en: "damp", min: "tanb" }, { en: "dampen", min: "tanbom" }, { en: "damsel", min: "tanzor" }, { en: "damson", min: "tanzem" }, { en: "dandelion", min: "tamtoruem" }, { en: "dandle", min: "tamtro" }, { en: "dandruff", min: "tamtlivv" }, { en: "dangle", min: "tamgro" },
  { en: "dank", min: "tamc" }, { en: "dapple", min: "tabbro" }, { en: "daredevil", min: "talotofur" }, { en: "dark", min: "talc" }, { en: "darken", min: "talcom" }, { en: "darkroom", min: "talcleen" }, { en: "darn", min: "talm" }, { en: "dart", min: "tald" }, { en: "dartboard", min: "taldpealt" }, { en: "dash", min: "tazh" },
  { en: "dashboard", min: "tazhpealt" }, { en: "dashiki", min: "tazhucu" }, { en: "data", min: "tada" }, { en: "database", min: "tadapazo" }, { en: "datatype", min: "tadadybo" }, { en: "date", min: "tado" }, { en: "dateline", min: "tadorumo" }, { en: "datum", min: "tadin" }, { en: "daub", min: "taip" }, { en: "daunt", min: "taimd" },
  { en: "dauphin", min: "taibhum" }, { en: "davit", min: "tafud" }, { en: "dawdle", min: "tawtro" }, { en: "daybreak", min: "tayploac" }, { en: "daydream", min: "taytloan" }, { en: "daydreamt", min: "taytloand" }, { en: "daylight", min: "tayrughd" }, { en: "daytime", min: "tayduno" }, { en: "daze", min: "taso" }, { en: "dazzle", min: "tassro" },
  { en: "dead", min: "toat" }, { en: "deaf", min: "toav" }, { en: "debt", min: "topd" }, { en: "deck", min: "tokc" }, { en: "deem", min: "toon" }, { en: "deep", min: "toob" }, { en: "deft", min: "tovd" }, { en: "deli", min: "toru" }, { en: "demo", min: "tone" }, { en: "den", min: "tom" },
  { en: "dent", min: "tomd" }, { en: "dept", min: "tobd" }, { en: "dew", min: "tow" }, { en: "dharma", min: "thalna" }, { en: "dhoti", min: "thedu" }, { en: "diadem", min: "tuaton" }, { en: "diagnose", min: "tuagmezo" }, { en: "diagram", min: "tuaglan" }, { en: "dialect", min: "tuarokd" }, { en: "dialog", min: "tuareg" },
  { en: "dialogue", min: "tuaregio" }, { en: "diamond", min: "tuanemt" }, { en: "diaphragm", min: "tuabhlagn" }, { en: "diarrhea", min: "tuallhoa" }, { en: "diarrhoea", min: "tuallheoa" }, { en: "diatom", min: "tuaden" }, { en: "diatribe", min: "tuadlupo" }, { en: "dibble", min: "tuppro" }, { en: "dice", min: "tuko" }, { en: "dickie", min: "tukcuo" },
  { en: "dicta", min: "tukda" }, { en: "dictate", min: "tukdado" }, { en: "dictator", min: "tukdadel" }, { en: "dictum", min: "tukdin" }, { en: "did", min: "tut" }, { en: "diddle", min: "tuttro" }, { en: "die", min: "tuo" }, { en: "diehard", min: "tuohalt" }, { en: "diet", min: "tuod" }, { en: "dietician", min: "tuodukuam" },
];
