/**
 * @file Contains dictionary entries for category: home_furniture.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const home_furniture: DictionaryEntry[] = [
  { en: "chair", min: "silya" }, { en: "table", min: "mesa" }, { en: "bed", min: "kamita" }, { en: "couch", min: "sillon" }, { en: "desk", min: "pupitre" }, { en: "circadian", min: "kulkatuam" }, { en: "circle", min: "kulkro" }, { en: "circlet", min: "kulkrod" }, { en: "circuit", min: "kulkiud" }, { en: "circulate", min: "kulkirado" },
  { en: "circumcise", min: "kulkinkuzo" }, { en: "circumflex", min: "kulkinvrox" }, { en: "circumvent", min: "kulkinfomd" }, { en: "cistern", min: "kuzdolm" }, { en: "citadel", min: "kudator" }, { en: "cite", min: "kudo" }, { en: "citizen", min: "kudusom" }, { en: "citron", min: "kudlem" }, { en: "citronella", min: "kudlemorra" }, { en: "civet", min: "kufod" },
  { en: "civil", min: "kufur" }, { en: "civilian", min: "kufuruam" }, { en: "civilize", min: "kufuruso" }, { en: "clack", min: "krakc" }, { en: "clad", min: "krat" }, { en: "claim", min: "kraun" }, { en: "claimant", min: "kraunamd" }, { en: "clam", min: "kran" }, { en: "clambake", min: "kranpaco" }, { en: "clamor", min: "kranel" },
  { en: "clamp", min: "kranb" }, { en: "clampdown", min: "kranbtewm" }, { en: "clan", min: "kram" }, { en: "clang", min: "kramg" }, { en: "clangor", min: "kramgel" }, { en: "clank", min: "kramc" }, { en: "clap", min: "krab" }, { en: "clapboard", min: "krabpealt" }, { en: "claptrap", min: "krabdlab" }, { en: "claret", min: "kralod" },
  { en: "clarinet", min: "kralumod" }, { en: "clarion", min: "kraluem" }, { en: "clash", min: "krazh" }, { en: "clasp", min: "krazb" }, { en: "classmate", min: "krazznado" }, { en: "classroom", min: "krazzleen" }, { en: "clause", min: "kraizo" }, { en: "clavichord", min: "krafukhelt" }, { en: "clavicle", min: "krafukro" }, { en: "claw", min: "kraw" },
  { en: "clean", min: "kroam" }, { en: "cleanse", min: "kroamzo" }, { en: "cleanup", min: "kroamib" }, { en: "clearance", min: "kroalamko" }, { en: "cleat", min: "kroad" }, { en: "cleavage", min: "kroafago" }, { en: "cleave", min: "kroafo" }, { en: "clef", min: "krov" }, { en: "cleft", min: "krovd" }, { en: "clench", min: "kromkh" },
  { en: "clergyman", min: "krolgynam" }, { en: "clergymen", min: "krolgynom" }, { en: "clerk", min: "krolc" }, { en: "clew", min: "krow" }, { en: "click", min: "krukc" }, { en: "clickbait", min: "krukcpaud" }, { en: "client", min: "kruomd" }, { en: "clii", min: "kruu" }, { en: "climate", min: "krunado" }, { en: "climax", min: "krunax" },
  { en: "climb", min: "krunp" }, { en: "clime", min: "kruno" }, { en: "clinch", min: "krumkh" }, { en: "clinician", min: "krumukuam" }, { en: "clink", min: "krumc" }, { en: "clip", min: "krub" }, { en: "clipboard", min: "krubpealt" }, { en: "clipt", min: "krubd" }, { en: "clique", min: "krujio" }, { en: "clit", min: "krud" },
  { en: "clix", min: "krux" }, { en: "cloak", min: "kreac" }, { en: "cloakroom", min: "kreacleen" }, { en: "cloche", min: "krekho" }, { en: "clockwork", min: "krekcwelc" }, { en: "clod", min: "kret" }, { en: "clog", min: "kreg" }, { en: "clomp", min: "krenb" }, { en: "clone", min: "kremo" }, { en: "clop", min: "kreb" },
  { en: "close", min: "krezo" }, { en: "closeout", min: "krezoeid" }, { en: "closet", min: "krezod" }, { en: "clot", min: "kred" }, { en: "clothe", min: "kredho" }, { en: "clothespin", min: "kredhozbum" }, { en: "cloture", min: "kredilo" }, { en: "cloudburst", min: "kreitpilzd" }, { en: "clout", min: "kreid" }, { en: "clove", min: "krefo" },
  { en: "cloven", min: "krefom" }, { en: "cloverleaf", min: "krefolroav" }, { en: "clown", min: "krewm" }, { en: "club", min: "krip" }, { en: "clubfeet", min: "kripvood" }, { en: "clubfoot", min: "kripveed" }, { en: "clubhouse", min: "kripheizo" }, { en: "cluck", min: "krikc" }, { en: "clue", min: "krio" }, { en: "clump", min: "krinb" },
  { en: "clung", min: "krimg" }, { en: "clunk", min: "krimc" }, { en: "clutch", min: "kridkh" }, { en: "clvi", min: "krfu" }, { en: "clvii", min: "krfuu" }, { en: "clxi", min: "krxu" }, { en: "clxii", min: "krxuu" }, { en: "clxiv", min: "krxuf" }, { en: "clxix", min: "krxux" }, { en: "clxvi", min: "krxfu" },
  { en: "clxvii", min: "krxfuu" }, { en: "coach", min: "keakh" }, { en: "coachman", min: "keakhnam" }, { en: "coachmen", min: "keakhnom" }, { en: "coagulant", min: "keagiramd" }, { en: "coagulate", min: "keagirado" }, { en: "coalesce", min: "kearozko" }, { en: "coarse", min: "kealzo" }, { en: "coarsen", min: "kealzom" }, { en: "coastline", min: "keazdrumo" },
  { en: "coauthor", min: "keaidhel" }, { en: "coax", min: "keax" }, { en: "cob", min: "kep" }, { en: "cobalt", min: "kepard" }, { en: "cobble", min: "keppro" }, { en: "cobra", min: "kepla" }, { en: "cobweb", min: "kepwop" }, { en: "cocaine", min: "kekaumo" }, { en: "cocci", min: "kekku" }, { en: "coccyx", min: "kekkyx" },
  { en: "cochlea", min: "kekhroa" }, { en: "cochleae", min: "kekhroao" }, { en: "cock", min: "kekc" }, { en: "cockade", min: "kekcato" }, { en: "cockamamie", min: "kekcananuo" }, { en: "cockatoo", min: "kekcadee" }, { en: "cockerel", min: "kekcolor" }, { en: "cockfight", min: "kekcvughd" }, { en: "cockle", min: "kekcro" }, { en: "cockpit", min: "kekcbud" },
  { en: "cockroach", min: "kekcleakh" }, { en: "cockscomb", min: "kekczkenp" }, { en: "cocksure", min: "kekczilo" }, { en: "cocktail", min: "kekcdaur" }, { en: "cocoa", min: "kekea" }, { en: "cocoanut", min: "kekeamid" }, { en: "coconut", min: "kekemid" }, { en: "cocoon", min: "kekeem" }, { en: "coda", min: "keta" }, { en: "coddle", min: "kettro" },
  { en: "code", min: "keto" }, { en: "codeine", min: "ketoumo" }, { en: "codex", min: "ketox" }, { en: "codicil", min: "ketukur" }, { en: "coerce", min: "keolko" }, { en: "coercion", min: "keolkuem" }, { en: "coffeecake", min: "kevvookaco" }, { en: "coffeepot", min: "kevvoobed" }, { en: "coffin", min: "kevvum" }, { en: "cog", min: "keg" },
  { en: "cogent", min: "kegomd" }, { en: "cogitate", min: "kegudado" }, { en: "cognate", min: "kegmado" }, { en: "cognizance", min: "kegmusamko" }, { en: "cognizant", min: "kegmusamd" }, { en: "cognomen", min: "kegmenom" }, { en: "cognomina", min: "kegmenuma" }, { en: "cogwheel", min: "kegwhoor" }, { en: "cohabit", min: "kehapud" }, { en: "cohere", min: "keholo" },
  { en: "coherence", min: "keholomko" }, { en: "coherent", min: "keholomd" }, { en: "cohesion", min: "kehozuem" }, { en: "cohort", min: "keheld" }, { en: "coif", min: "keuv" }, { en: "coiffure", min: "keuvvilo" }, { en: "coil", min: "keur" }, { en: "coin", min: "keum" }, { en: "coinage", min: "keumago" }, { en: "coincide", min: "keumkuto" },
  { en: "coincident", min: "keumkutomd" }, { en: "coleslaw", min: "kerozraw" }, { en: "coliseum", min: "keruzoin" }, { en: "collage", min: "kerrago" }, { en: "collapse", min: "kerrabzo" }, { en: "collarbone", min: "kerralpemo" }, { en: "collate", min: "kerrado" }, { en: "colleague", min: "kerroagio" }, { en: "collect", min: "kerrokd" }, { en: "collector", min: "kerrokdel" },
  { en: "college", min: "kerrogo" }, { en: "collegian", min: "kerroguam" }, { en: "collegiate", min: "kerroguado" }, { en: "collide", min: "kerruto" }, { en: "collision", min: "kerruzuem" }, { en: "collocate", min: "kerrekado" }, { en: "colloid", min: "kerreut" }, { en: "colloquia", min: "kerrejiua" }, { en: "colloquium", min: "kerrejiuin" }, { en: "collude", min: "kerrito" },
  { en: "collusion", min: "kerrizuem" }, { en: "colonel", min: "keremor" }, { en: "colonize", min: "keremuso" }, { en: "colonnade", min: "keremmato" }, { en: "color", min: "kerel" }, { en: "coloratura", min: "kereladila" }, { en: "colorblind", min: "kerelprumt" }, { en: "colorfast", min: "kerelvazd" }, { en: "colossi", min: "kerezzu" }, { en: "column", min: "kerinm" },
  { en: "coma", min: "kena" }, { en: "comatose", min: "kenadezo" }, { en: "comb", min: "kenp" }, { en: "combat", min: "kenpad" }, { en: "combatant", min: "kenpadamd" }, { en: "combine", min: "kenpumo" }, { en: "combo", min: "kenpe" }, { en: "come", min: "keno" }, { en: "comeback", min: "kenopakc" }, { en: "comedian", min: "kenotuam" },
  { en: "comedienne", min: "kenotuommo" }, { en: "comedown", min: "kenotewm" }, { en: "comet", min: "kenod" }, { en: "comfort", min: "kenveld" }, { en: "comm", min: "kenn" }, { en: "comma", min: "kenna" }, { en: "command", min: "kennamt" }, { en: "commandant", min: "kennamtamd" }, { en: "commando", min: "kennamte" }, { en: "commence", min: "kennomko" },
  { en: "commend", min: "kennomt" }, { en: "commentate", min: "kennomdado" }, { en: "commerce", min: "kennolko" }, { en: "commingle", min: "kennumgro" }, { en: "commission", min: "kennuzzuem" }, { en: "commit", min: "kennud" }, { en: "committee", min: "kennuddoo" }, { en: "commode", min: "kenneto" }, { en: "commodore", min: "kennetelo" }, { en: "common", min: "kennem" },
  { en: "commune", min: "kennimo" }, { en: "communique", min: "kennimujio" }, { en: "commute", min: "kennido" }, { en: "compact", min: "kenbakd" }, { en: "compactor", min: "kenbakdel" }, { en: "companion", min: "kenbamuem" }, { en: "compare", min: "kenbalo" }, { en: "comparison", min: "kenbaluzem" }, { en: "compassion", min: "kenbazzuem" }, { en: "compatriot", min: "kenbadlued" },
  { en: "compel", min: "kenbor" }, { en: "compendia", min: "kenbomtua" }, { en: "compendium", min: "kenbomtuin" }, { en: "compensate", min: "kenbomzado" }, { en: "compete", min: "kenbodo" }, { en: "competence", min: "kenbodomko" }, { en: "competent", min: "kenbodomd" }, { en: "competitor", min: "kenbodudel" }, { en: "compile", min: "kenburo" }, { en: "complacent", min: "kenbrakomd" },
  { en: "complain", min: "kenbraum" }, { en: "complaint", min: "kenbraumd" }, { en: "complete", min: "kenbrodo" }, { en: "complex", min: "kenbrox" }, { en: "complexion", min: "kenbroxuem" }, { en: "compliance", min: "kenbruamko" }, { en: "compliant", min: "kenbruamd" }, { en: "complicate", min: "kenbrukado" }, { en: "compo", min: "kenbe" }, { en: "component", min: "kenbemomd" },
  { en: "comport", min: "kenbeld" }, { en: "compose", min: "kenbezo" }, { en: "composite", min: "kenbezudo" }, { en: "compositor", min: "kenbezudel" }, { en: "compost", min: "kenbezd" }, { en: "composure", min: "kenbezilo" }, { en: "compote", min: "kenbedo" }, { en: "compound", min: "kenbeimt" }, { en: "comprehend", min: "kenblohomt" }, { en: "compressor", min: "kenblozzel" },
  { en: "comprise", min: "kenbluzo" }, { en: "compromise", min: "kenblenuzo" }, { en: "compulsion", min: "kenbirzuem" }, { en: "compute", min: "kenbido" }, { en: "comrade", min: "kenlato" }, { en: "concave", min: "kemkafo" }, { en: "concede", min: "kemkoto" }, { en: "conceit", min: "kemkoud" }, { en: "concept", min: "kemkobd" }, { en: "concern", min: "kemkolm" },
];
