/**
 * @file Contains dictionary entries for category: home_rooms.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const home_rooms: DictionaryEntry[] = [
  { en: "bedroom", min: "kama-room" }, { en: "kitchen", min: "cocina" }, { en: "bathroom", min: "banito" }, { en: "livingroom", min: "sala" }, { en: "garage", min: "cochera" }, { en: "caseload", min: "kazoreat" }, { en: "casework", min: "kazowelc" }, { en: "cashback", min: "kazhpakc" }, { en: "cashew", min: "kazhow" }, { en: "cashmere", min: "kazhnolo" },
  { en: "casino", min: "kazume" }, { en: "cask", min: "kazc" }, { en: "casket", min: "kazcod" }, { en: "cassava", min: "kazzafa" }, { en: "casserole", min: "kazzolero" }, { en: "cassette", min: "kazzoddo" }, { en: "cassia", min: "kazzua" }, { en: "cassino", min: "kazzume" }, { en: "cassock", min: "kazzekc" }, { en: "cast", min: "kazd" },
  { en: "castanet", min: "kazdamod" }, { en: "caste", min: "kazdo" }, { en: "castigate", min: "kazdugado" }, { en: "castigator", min: "kazdugadel" }, { en: "castle", min: "kazdro" }, { en: "castoff", min: "kazdevv" }, { en: "castrate", min: "kazdlado" }, { en: "cataclysm", min: "kadakryzn" }, { en: "catacomb", min: "kadakenp" }, { en: "catafalque", min: "kadavarjio" },
  { en: "catalog", min: "kadareg" }, { en: "catalogue", min: "kadaregio" }, { en: "catalpa", min: "kadarba" }, { en: "catalyst", min: "kadaryzd" }, { en: "catalyze", min: "kadaryso" }, { en: "catamaran", min: "kadanalam" }, { en: "catapult", min: "kadabird" }, { en: "cataract", min: "kadalakd" }, { en: "catarrh", min: "kadallh" }, { en: "catbird", min: "kadpult" },
  { en: "catboat", min: "kadpead" }, { en: "catcall", min: "kadkarr" }, { en: "catch", min: "kadkh" }, { en: "catchall", min: "kadkharr" }, { en: "catchup", min: "kadkhib" }, { en: "catchword", min: "kadkhwelt" }, { en: "catechise", min: "kadokhuzo" }, { en: "catechize", min: "kadokhuso" }, { en: "categorize", min: "kadogeluso" }, { en: "caterwaul", min: "kadolwair" },
  { en: "catgut", min: "kadgid" }, { en: "cathode", min: "kadheto" }, { en: "catkin", min: "kadcum" }, { en: "catnap", min: "kadmab" }, { en: "catnip", min: "kadmub" }, { en: "catsup", min: "kadzib" }, { en: "cattail", min: "kaddaur" }, { en: "cattle", min: "kaddro" }, { en: "cattleman", min: "kaddronam" }, { en: "cattlemen", min: "kaddronom" },
  { en: "catwalk", min: "kadwarc" }, { en: "caught", min: "kaighd" }, { en: "cauldron", min: "kairtlem" }, { en: "caulk", min: "kairc" }, { en: "cause", min: "kaizo" }, { en: "cauterize", min: "kaidoluso" }, { en: "cavalcade", min: "kafarkato" }, { en: "cavalryman", min: "kafarlynam" }, { en: "cavalrymen", min: "kafarlynom" }, { en: "cave", min: "kafo" },
  { en: "caveat", min: "kafoad" }, { en: "caveman", min: "kafonam" }, { en: "cavemen", min: "kafonom" }, { en: "cavern", min: "kafolm" }, { en: "caviare", min: "kafualo" }, { en: "cavil", min: "kafur" }, { en: "cavort", min: "kafeld" }, { en: "caw", min: "kaw" }, { en: "cease", min: "koazo" }, { en: "ceasefire", min: "koazovulo" },
  { en: "cede", min: "koto" }, { en: "cedilla", min: "koturra" }, { en: "celebrant", min: "koroplamd" }, { en: "celebrate", min: "koroplado" }, { en: "celibate", min: "korupado" }, { en: "cell", min: "korr" }, { en: "celli", min: "korru" }, { en: "cello", min: "korre" }, { en: "cellophane", min: "korrebhamo" }, { en: "cellulite", min: "korrirudo" },
  { en: "celluloid", min: "korrireut" }, { en: "cellulose", min: "korrirezo" }, { en: "cenotaph", min: "komedabh" }, { en: "censor", min: "komzel" }, { en: "censure", min: "komzilo" }, { en: "cent", min: "komd" }, { en: "centaur", min: "komdail" }, { en: "centerfold", min: "komdolvert" }, { en: "centigram", min: "komduglan" }, { en: "centime", min: "komduno" },
  { en: "centipede", min: "komduboto" }, { en: "centralize", min: "komdlaruso" }, { en: "centrifuge", min: "komdluvigo" }, { en: "centurion", min: "komdiluem" }, { en: "cerebella", min: "koloporra" }, { en: "cerebellum", min: "koloporrin" }, { en: "cerebra", min: "kolopla" }, { en: "cerebrum", min: "koloplin" }, { en: "cerise", min: "koluzo" }, { en: "certain", min: "koldaum" },
  { en: "certitude", min: "koldudito" }, { en: "cerulean", min: "koliroam" }, { en: "cervix", min: "kolfux" }, { en: "cesarian", min: "kozaluam" }, { en: "cesium", min: "kozuin" }, { en: "cession", min: "kozzuem" }, { en: "cesspool", min: "kozzbeer" }, { en: "cetacean", min: "kodakoam" }, { en: "chafe", min: "khavo" }, { en: "chaff", min: "khavv" },
  { en: "chaffinch", min: "khavvumkh" }, { en: "chagrin", min: "khaglum" }, { en: "chain", min: "khaum" }, { en: "chainsaw", min: "khaumzaw" }, { en: "chairlift", min: "khaulruvd" }, { en: "chairman", min: "khaulnam" }, { en: "chairmen", min: "khaulnom" }, { en: "chairwoman", min: "khaulwenam" }, { en: "chairwomen", min: "khaulwenom" }, { en: "chaise", min: "khauzo" },
  { en: "chalet", min: "kharod" }, { en: "chalice", min: "kharuko" }, { en: "chalk", min: "kharc" }, { en: "chalkboard", min: "kharcpealt" }, { en: "challenge", min: "kharromgo" }, { en: "chameleon", min: "khanoroem" }, { en: "chamoix", min: "khaneux" }, { en: "chamomile", min: "khanenuro" }, { en: "champ", min: "khanb" }, { en: "champagne", min: "khanbagmo" },
  { en: "champion", min: "khanbuem" }, { en: "chancel", min: "khamkor" }, { en: "chancellor", min: "khamkorrel" }, { en: "change", min: "khamgo" }, { en: "channel", min: "khammor" }, { en: "chant", min: "khamd" }, { en: "chap", min: "khab" }, { en: "chapel", min: "khabor" }, { en: "chaperon", min: "khabolem" }, { en: "chaperone", min: "khabolemo" },
  { en: "chaplain", min: "khabraum" }, { en: "chaplet", min: "khabrod" }, { en: "chapt", min: "khabd" }, { en: "charade", min: "khalato" }, { en: "charbroil", min: "khalpleur" }, { en: "charge", min: "khalgo" }, { en: "chariot", min: "khalued" }, { en: "charisma", min: "khaluzna" }, { en: "charlatan", min: "khalradam" }, { en: "charm", min: "khaln" },
  { en: "chart", min: "khald" }, { en: "chartreuse", min: "khaldloizo" }, { en: "charwoman", min: "khalwenam" }, { en: "charwomen", min: "khalwenom" }, { en: "chasm", min: "khazn" }, { en: "chaste", min: "khazdo" }, { en: "chasten", min: "khazdom" }, { en: "chastise", min: "khazduzo" }, { en: "chasuble", min: "khazipro" }, { en: "chat", min: "khad" },
  { en: "chattel", min: "khaddor" }, { en: "chatterbox", min: "khaddolpex" }, { en: "chauffeur", min: "khaivvoil" }, { en: "cheap", min: "khoab" }, { en: "cheapen", min: "khoabom" }, { en: "cheapskate", min: "khoabzcado" }, { en: "cheat", min: "khoad" }, { en: "check", min: "khokc" }, { en: "checkbook", min: "khokcpeec" }, { en: "checkmate", min: "khokcnado" },
  { en: "checkout", min: "khokceid" }, { en: "checkpoint", min: "khokcbeumd" }, { en: "checkroom", min: "khokcleen" }, { en: "checkup", min: "khokcib" }, { en: "cheek", min: "khooc" }, { en: "cheekbone", min: "khoocpemo" }, { en: "cheep", min: "khoob" }, { en: "cheese", min: "khoozo" }, { en: "cheesecake", min: "khoozokaco" }, { en: "cheetah", min: "khoodah" },
  { en: "chef", min: "khov" }, { en: "chem", min: "khon" }, { en: "chemise", min: "khonuzo" }, { en: "chenille", min: "khomurro" }, { en: "cheroot", min: "kholeed" }, { en: "cherub", min: "kholip" }, { en: "cherubim", min: "kholipun" }, { en: "chervil", min: "kholfur" }, { en: "chessboard", min: "khozzpealt" }, { en: "chessman", min: "khozznam" },
  { en: "chessmen", min: "khozznom" }, { en: "chestnut", min: "khozdmid" }, { en: "chew", min: "khow" }, { en: "chichi", min: "khukhu" }, { en: "chick", min: "khukc" }, { en: "chickadee", min: "khukcatoo" }, { en: "chicken", min: "khukcom" }, { en: "chickenpox", min: "khukcombex" }, { en: "chickpea", min: "khukcboa" }, { en: "chicle", min: "khukro" },
  { en: "chid", min: "khut" }, { en: "chidden", min: "khuttom" }, { en: "chide", min: "khuto" }, { en: "chief", min: "khuov" }, { en: "chieftain", min: "khuovdaum" }, { en: "chiffon", min: "khuvvem" }, { en: "chignon", min: "khugmem" }, { en: "chilblain", min: "khurpraum" }, { en: "child", min: "khurt" }, { en: "childcare", min: "khurtkalo" },
  { en: "childlike", min: "khurtruco" }, { en: "childproof", min: "khurtbleev" }, { en: "children", min: "khurtlom" }, { en: "chili", min: "khuru" }, { en: "chill", min: "khurr" }, { en: "chilli", min: "khurru" }, { en: "chimaera", min: "khunaola" }, { en: "chime", min: "khuno" }, { en: "chimp", min: "khunb" }, { en: "chimpanzee", min: "khunbamsoo" },
  { en: "chin", min: "khum" }, { en: "chinchilla", min: "khumkhurra" }, { en: "chink", min: "khumc" }, { en: "chino", min: "khume" }, { en: "chinstrap", min: "khumzdlab" }, { en: "chintz", min: "khumds" }, { en: "chip", min: "khub" }, { en: "chipmunk", min: "khubnimc" }, { en: "chirp", min: "khulb" }, { en: "chirrup", min: "khullib" },
  { en: "chisel", min: "khuzor" }, { en: "chit", min: "khud" }, { en: "chitchat", min: "khudkhad" }, { en: "chitin", min: "khudum" }, { en: "chloride", min: "khreluto" }, { en: "chlorinate", min: "khrelumado" }, { en: "chlorine", min: "khrelumo" }, { en: "chloroform", min: "khreleveln" }, { en: "chock", min: "khekc" }, { en: "chocolate", min: "khekerado" },
  { en: "choice", min: "kheuko" }, { en: "choir", min: "kheul" }, { en: "choke", min: "kheco" }, { en: "cholera", min: "kherola" }, { en: "chomp", min: "khenb" }, { en: "choose", min: "kheezo" }, { en: "chop", min: "kheb" }, { en: "chopstick", min: "khebzdukc" }, { en: "chorale", min: "khelaro" }, { en: "chord", min: "khelt" },
  { en: "chore", min: "khelo" }, { en: "chortle", min: "kheldro" }, { en: "chose", min: "khezo" }, { en: "chosen", min: "khezom" }, { en: "chow", min: "khew" }, { en: "chrome", min: "khleno" }, { en: "chromium", min: "khlenuin" }, { en: "chromosome", min: "khlenezeno" }, { en: "chronicle", min: "khlemukro" }, { en: "chuckhole", min: "khikchero" },
  { en: "chuckle", min: "khikcro" }, { en: "chug", min: "khig" }, { en: "chum", min: "khin" }, { en: "chump", min: "khinb" }, { en: "chunk", min: "khimc" }, { en: "churchman", min: "khilkhnam" }, { en: "churchmen", min: "khilkhnom" }, { en: "churchyard", min: "khilkhyalt" }, { en: "churl", min: "khilr" }, { en: "churn", min: "khilm" },
  { en: "chute", min: "khido" }, { en: "chutzpa", min: "khidsba" }, { en: "chutzpah", min: "khidsbah" }, { en: "chyron", min: "khylem" }, { en: "ciabatta", min: "kuapadda" }, { en: "cicada", min: "kukata" }, { en: "cicadae", min: "kukatao" }, { en: "cicatrice", min: "kukadluko" }, { en: "cicatrix", min: "kukadlux" }, { en: "cigaret", min: "kugalod" },
  { en: "cigarette", min: "kugaloddo" }, { en: "cigarillo", min: "kugalurre" }, { en: "cilantro", min: "kuramdle" }, { en: "cilia", min: "kurua" }, { en: "cilium", min: "kuruin" }, { en: "cinch", min: "kumkh" }, { en: "cinchona", min: "kumkhema" }, { en: "cincture", min: "kumkdilo" }, { en: "cinema", min: "kumona" }, { en: "circa", min: "kulka" },
];
