/**
 * @file Contains dictionary entries for category: nature_weather.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const nature_weather: DictionaryEntry[] = [
  { en: "rain", min: "lluvia" }, { en: "snow", min: "nieve" }, { en: "wind", min: "viento" }, { en: "sunshine", min: "solana" }, { en: "storm", min: "tormenta" }, { en: "dyestuff", min: "tyozdivv" }, { en: "dyke", min: "tyco" }, { en: "dynamite", min: "tymanudo" }, { en: "dynamo", min: "tymane" }, { en: "dyslexia", min: "tyzroxua" },
  { en: "dyspepsia", min: "tyzbobzua" }, { en: "each", min: "oakh" }, { en: "eagle", min: "oagro" }, { en: "eaglet", min: "oagrod" }, { en: "earache", min: "oalakho" }, { en: "earbud", min: "oalpit" }, { en: "eardrum", min: "oaltlin" }, { en: "earldom", min: "oalrten" }, { en: "earlobe", min: "oalrepo" }, { en: "earmark", min: "oalnalc" },
  { en: "earmuff", min: "oalnivv" }, { en: "earn", min: "oalm" }, { en: "earphone", min: "oalbhemo" }, { en: "earplug", min: "oalbrig" }, { en: "earshot", min: "oalzhed" }, { en: "earthen", min: "oaldhom" }, { en: "earthquake", min: "oaldhjiaco" }, { en: "earthwork", min: "oaldhwelc" }, { en: "earthworm", min: "oaldhweln" }, { en: "earwax", min: "oalwax" },
  { en: "earwig", min: "oalwug" }, { en: "ease", min: "oazo" }, { en: "easel", min: "oazor" }, { en: "eastbound", min: "oazdpeimt" }, { en: "eat", min: "oad" }, { en: "eaten", min: "oadom" }, { en: "eave", min: "oafo" }, { en: "eavesdrop", min: "oafoztleb" }, { en: "ebb", min: "opp" }, { en: "ebullience", min: "opirruomko" },
  { en: "ebullient", min: "opirruomd" }, { en: "echelon", min: "okhorem" }, { en: "echo", min: "okhe" }, { en: "eclipse", min: "okrubzo" }, { en: "economize", min: "okemenuso" }, { en: "ecosystem", min: "okezyzdon" }, { en: "ecru", min: "okli" }, { en: "eczema", min: "oksona" }, { en: "edamame", min: "otanano" }, { en: "edema", min: "otona" },
  { en: "edge", min: "otgo" }, { en: "edict", min: "otukd" }, { en: "edifice", min: "otuvuko" }, { en: "edit", min: "otud" }, { en: "editor", min: "otudel" }, { en: "educate", min: "otikado" }, { en: "educator", min: "otikadel" }, { en: "eel", min: "oor" }, { en: "eerie", min: "ooluo" }, { en: "efface", min: "ovvako" },
  { en: "effect", min: "ovvokd" }, { en: "effectuate", min: "ovvokdiado" }, { en: "effeminate", min: "ovvonumado" }, { en: "effervesce", min: "ovvolfozko" }, { en: "effete", min: "ovvodo" }, { en: "efficient", min: "ovvukuomd" }, { en: "effluent", min: "ovvriomd" }, { en: "effort", min: "ovveld" }, { en: "effulgence", min: "ovvirgomko" }, { en: "effulgent", min: "ovvirgomd" },
  { en: "effusion", min: "ovvizuem" }, { en: "egg", min: "ogg" }, { en: "egghead", min: "ogghoat" }, { en: "eggnog", min: "oggmeg" }, { en: "eggplant", min: "oggbramd" }, { en: "eggshell", min: "oggzhorr" }, { en: "eglantine", min: "ogramdumo" }, { en: "ego", min: "oge" }, { en: "egret", min: "oglod" }, { en: "eiderdown", min: "outoltewm" },
  { en: "eigenvalue", min: "ougomfario" }, { en: "eight", min: "oughd" }, { en: "eighteen", min: "oughdoom" }, { en: "ejaculate", min: "oqakirado" }, { en: "eject", min: "oqokd" }, { en: "eke", min: "oco" }, { en: "elaborate", min: "orapelado" }, { en: "elapse", min: "orabzo" }, { en: "elate", min: "orado" }, { en: "elbow", min: "orpew" },
  { en: "elbowroom", min: "orpewleen" }, { en: "eldercare", min: "ortolkalo" }, { en: "elect", min: "orokd" }, { en: "elector", min: "orokdel" }, { en: "electorate", min: "orokdelado" }, { en: "electrode", min: "orokdleto" }, { en: "electron", min: "orokdlem" }, { en: "elegance", min: "orogamko" }, { en: "elegant", min: "orogamd" }, { en: "elegiac", min: "oroguak" },
  { en: "elephant", min: "orobhamd" }, { en: "elevate", min: "orofado" }, { en: "elevator", min: "orofadel" }, { en: "eleven", min: "orofom" }, { en: "elf", min: "orv" }, { en: "elfin", min: "orvum" }, { en: "elicit", min: "orukud" }, { en: "elide", min: "oruto" }, { en: "eliminate", min: "orunumado" }, { en: "elision", min: "oruzuem" },
  { en: "elite", min: "orudo" }, { en: "elixir", min: "oruxul" }, { en: "elk", min: "orc" }, { en: "ell", min: "orr" }, { en: "ellipse", min: "orrubzo" }, { en: "elm", min: "orn" }, { en: "elongate", min: "oremgado" }, { en: "elope", min: "orebo" }, { en: "eloquence", min: "orejiomko" }, { en: "eloquent", min: "orejiomd" },
  { en: "elsewhere", min: "orzowholo" }, { en: "elucidate", min: "orikutado" }, { en: "elude", min: "orito" }, { en: "emaciate", min: "onakuado" }, { en: "email", min: "onaur" }, { en: "emanate", min: "onamado" }, { en: "emancipate", min: "onamkubado" }, { en: "emasculate", min: "onazkirado" }, { en: "embalm", min: "onparn" }, { en: "embargo", min: "onpalge" },
  { en: "embark", min: "onpalc" }, { en: "embezzle", min: "onpossro" }, { en: "emblazon", min: "onprasem" }, { en: "emblem", min: "onpron" }, { en: "embolden", min: "onpertom" }, { en: "embrace", min: "onplako" }, { en: "embroil", min: "onpleur" }, { en: "embryo", min: "onplye" }, { en: "emcee", min: "onkoo" }, { en: "emend", min: "onomt" },
  { en: "emerald", min: "onolart" }, { en: "emerge", min: "onolgo" }, { en: "emergence", min: "onolgomko" }, { en: "emergent", min: "onolgomd" }, { en: "emigrant", min: "onuglamd" }, { en: "emigrate", min: "onuglado" }, { en: "eminence", min: "onumomko" }, { en: "eminent", min: "onumomd" }, { en: "emir", min: "onul" }, { en: "emirate", min: "onulado" },
  { en: "emission", min: "onuzzuem" }, { en: "emit", min: "onud" }, { en: "emo", min: "one" }, { en: "emoji", min: "onequ" }, { en: "emollient", min: "onerruomd" }, { en: "emote", min: "onedo" }, { en: "emoticon", min: "onedukem" }, { en: "empanel", min: "onbamor" }, { en: "empathize", min: "onbadhuso" }, { en: "emperor", min: "onbolel" },
  { en: "emphasize", min: "onbhazuso" }, { en: "emphysema", min: "onbhyzona" }, { en: "empire", min: "onbulo" }, { en: "employe", min: "onbreyo" }, { en: "employee", min: "onbreyoo" }, { en: "emporia", min: "onbelua" }, { en: "emporium", min: "onbeluin" }, { en: "emu", min: "oni" }, { en: "emulate", min: "onirado" }, { en: "emulator", min: "oniradel" },
  { en: "emulsion", min: "onirzuem" }, { en: "enact", min: "omakd" }, { en: "enamel", min: "omanor" }, { en: "enamor", min: "omanel" }, { en: "encamp", min: "omkanb" }, { en: "encase", min: "omkazo" }, { en: "enchant", min: "omkhamd" }, { en: "enchilada", min: "omkhurata" }, { en: "encircle", min: "omkulkro" }, { en: "enclave", min: "omkrafo" },
  { en: "enclose", min: "omkrezo" }, { en: "enclosure", min: "omkrezilo" }, { en: "encode", min: "omketo" }, { en: "encore", min: "omkelo" }, { en: "encourage", min: "omkeilago" }, { en: "encroach", min: "omkleakh" }, { en: "encrust", min: "omklizd" }, { en: "encrypt", min: "omklybd" }, { en: "end", min: "omt" }, { en: "endeavor", min: "omtoafel" },
  { en: "endocrine", min: "omteklumo" }, { en: "endorse", min: "omtelzo" }, { en: "endow", min: "omtew" }, { en: "endue", min: "omtio" }, { en: "endurance", min: "omtilamko" }, { en: "endure", min: "omtilo" }, { en: "enema", min: "omona" }, { en: "enemata", min: "omonada" }, { en: "energize", min: "omolguso" }, { en: "enervate", min: "omolfado" },
  { en: "enfeeble", min: "omvoopro" }, { en: "enfold", min: "omvert" }, { en: "enforce", min: "omvelko" }, { en: "engage", min: "omgago" }, { en: "engine", min: "omgumo" }, { en: "engorge", min: "omgelgo" }, { en: "engrave", min: "omglafo" }, { en: "engulf", min: "omgirv" }, { en: "enhance", min: "omhamko" }, { en: "enigma", min: "omugna" },
  { en: "enjoin", min: "omqeum" }, { en: "enlarge", min: "omralgo" }, { en: "enlighten", min: "omrughdom" }, { en: "enlistee", min: "omruzdoo" }, { en: "enliven", min: "omrufom" }, { en: "enmesh", min: "omnozh" }, { en: "ennoble", min: "ommepro" }, { en: "ennui", min: "ommiu" }, { en: "enough", min: "omeigh" }, { en: "enquire", min: "omjiulo" },
  { en: "enrage", min: "omlago" }, { en: "enrapture", min: "omlabdilo" }, { en: "enrich", min: "omlukh" }, { en: "enrol", min: "omler" }, { en: "enroll", min: "omlerr" }, { en: "ensconce", min: "omzkemko" }, { en: "ensemble", min: "omzonpro" }, { en: "enshrine", min: "omzhlumo" }, { en: "enshroud", min: "omzhleit" }, { en: "ensign", min: "omzugm" },
  { en: "enslave", min: "omzrafo" }, { en: "ensnare", min: "omzmalo" }, { en: "ensue", min: "omzio" }, { en: "ensure", min: "omzilo" }, { en: "entail", min: "omdaur" }, { en: "entangle", min: "omdamgro" }, { en: "entente", min: "omdomdo" }, { en: "entertain", min: "omdoldaum" }, { en: "enthrall", min: "omdhlarr" }, { en: "enthrone", min: "omdhlemo" },
  { en: "enthuse", min: "omdhizo" }, { en: "enthusiasm", min: "omdhizuazn" }, { en: "enthusiast", min: "omdhizuazd" }, { en: "entice", min: "omduko" }, { en: "entire", min: "omdulo" }, { en: "entitle", min: "omdudro" }, { en: "entomb", min: "omdenp" }, { en: "entourage", min: "omdeilago" }, { en: "entrance", min: "omdlamko" }, { en: "entrant", min: "omdlamd" },
  { en: "entrap", min: "omdlab" }, { en: "entreat", min: "omdload" }, { en: "entrench", min: "omdlomkh" }, { en: "entrust", min: "omdlizd" }, { en: "entwine", min: "omdwumo" }, { en: "enumerate", min: "ominolado" }, { en: "enunciate", min: "omimkuado" }, { en: "enure", min: "omilo" }, { en: "envelop", min: "omforeb" }, { en: "envelope", min: "omforebo" },
  { en: "envisage", min: "omfuzago" }, { en: "envision", min: "omfuzuem" }, { en: "enzyme", min: "omsyno" }, { en: "eon", min: "oem" }, { en: "epaulet", min: "obairod" }, { en: "epaulette", min: "obairoddo" }, { en: "epicure", min: "obukilo" }, { en: "epigram", min: "obuglan" }, { en: "epilog", min: "obureg" }, { en: "epilogue", min: "oburegio" },
  { en: "episcopate", min: "obuzkebado" }, { en: "episode", min: "obuzeto" }, { en: "epistle", min: "obuzdro" }, { en: "epitaph", min: "obudabh" }, { en: "epithet", min: "obudhod" }, { en: "epitome", min: "obudeno" }, { en: "epitomize", min: "obudenuso" }, { en: "epoch", min: "obekh" }, { en: "epsilon", min: "obzurem" }, { en: "equalize", min: "ojiaruso" },
  { en: "equate", min: "ojiado" }, { en: "equator", min: "ojiadel" }, { en: "equestrian", min: "ojiozdluam" }, { en: "equine", min: "ojiumo" }, { en: "equinox", min: "ojiumex" }, { en: "equip", min: "ojiub" }, { en: "equipage", min: "ojiubago" }, { en: "equipoise", min: "ojiubeuzo" }, { en: "equivalent", min: "ojiufaromd" }, { en: "equivocate", min: "ojiufekado" },
  { en: "eradicate", min: "olatukado" }, { en: "erase", min: "olazo" }, { en: "erasure", min: "olazilo" }, { en: "ere", min: "olo" }, { en: "erect", min: "olokd" }, { en: "erectile", min: "olokduro" }, { en: "erg", min: "olg" }, { en: "ergo", min: "olge" }, { en: "ermine", min: "olnumo" }, { en: "erode", min: "oleto" },
];
