/**
 * @file Contains dictionary entries for category: numbers_units.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const numbers_units: DictionaryEntry[] = [
  { en: "one", min: "uno" }, { en: "two", min: "dos" }, { en: "three", min: "tres" }, { en: "four", min: "cuatro" }, { en: "five", min: "cinco" }, { en: "heft", min: "hovd" }, { en: "height", min: "houghd" }, { en: "heighten", min: "houghdom" }, { en: "heir", min: "houl" }, { en: "heirloom", min: "houlreen" },
  { en: "held", min: "hort" }, { en: "heliotrope", min: "horuedlebo" }, { en: "heliport", min: "horubeld" }, { en: "helium", min: "horuin" }, { en: "helix", min: "horux" }, { en: "hellebore", min: "horropelo" }, { en: "hellhole", min: "horrhero" }, { en: "hellion", min: "horruem" }, { en: "helm", min: "horn" }, { en: "helmet", min: "hornod" },
  { en: "helmsman", min: "hornznam" }, { en: "helmsmen", min: "hornznom" }, { en: "helot", min: "hored" }, { en: "help", min: "horb" }, { en: "helpline", min: "horbrumo" }, { en: "helpmate", min: "horbnado" }, { en: "helpmeet", min: "horbnood" }, { en: "hem", min: "hon" }, { en: "hemisphere", min: "honuzbholo" }, { en: "hemline", min: "honrumo" },
  { en: "hemlock", min: "honrekc" }, { en: "hemoglobin", min: "honegrepum" }, { en: "hemophilia", min: "honebhurua" }, { en: "hemorrhage", min: "honellhago" }, { en: "hemorrhoid", min: "honellheut" }, { en: "hemp", min: "honb" }, { en: "hempen", min: "honbom" }, { en: "hemstitch", min: "honzdudkh" }, { en: "hen", min: "hom" }, { en: "hence", min: "homko" },
  { en: "henchman", min: "homkhnam" }, { en: "henchmen", min: "homkhnom" }, { en: "henna", min: "homma" }, { en: "henpeck", min: "hombokc" }, { en: "hep", min: "hob" }, { en: "heptagon", min: "hobdagem" }, { en: "her", min: "hol" }, { en: "herald", min: "holart" }, { en: "herb", min: "holp" }, { en: "herbage", min: "holpago" },
  { en: "herbicide", min: "holpukuto" }, { en: "herbivore", min: "holpufelo" }, { en: "herculean", min: "holkiroam" }, { en: "herd", min: "holt" }, { en: "herdsman", min: "holtznam" }, { en: "herdsmen", min: "holtznom" }, { en: "here", min: "holo" }, { en: "hereabout", min: "holoapeid" }, { en: "herein", min: "holoum" }, { en: "hereof", min: "holoev" },
  { en: "hereto", min: "holode" }, { en: "heretofore", min: "holodevelo" }, { en: "hereupon", min: "holoibem" }, { en: "heritage", min: "holudago" }, { en: "hermit", min: "holnud" }, { en: "hernia", min: "holmua" }, { en: "herniae", min: "holmuao" }, { en: "hero", min: "hole" }, { en: "heroin", min: "holeum" }, { en: "heroine", min: "holeumo" },
  { en: "heron", min: "holem" }, { en: "herself", min: "holzorv" }, { en: "hesitant", min: "hozudamd" }, { en: "hesitate", min: "hozudado" }, { en: "heterodox", min: "hodoletex" }, { en: "hew", min: "how" }, { en: "hewn", min: "howm" }, { en: "hex", min: "hox" }, { en: "hexagon", min: "hoxagem" }, { en: "hgt", min: "hgd" },
  { en: "hibachi", min: "hupakhu" }, { en: "hibernate", min: "hupolmado" }, { en: "hiccough", min: "hukkeigh" }, { en: "hiccup", min: "hukkib" }, { en: "hick", min: "hukc" }, { en: "hid", min: "hut" }, { en: "hidden", min: "huttom" }, { en: "hide", min: "huto" }, { en: "hidebound", min: "hutopeimt" }, { en: "hideout", min: "hutoeid" },
  { en: "hie", min: "huo" }, { en: "hifalutin", min: "huvaridum" }, { en: "high", min: "hugh" }, { en: "highball", min: "hughparr" }, { en: "highborn", min: "hughpelm" }, { en: "highbrow", min: "hughplew" }, { en: "highchair", min: "hughkhaul" }, { en: "highjack", min: "hughqakc" }, { en: "highland", min: "hughramt" }, { en: "highlight", min: "hughrughd" },
  { en: "hightail", min: "hughdaur" }, { en: "highwayman", min: "hughwaynam" }, { en: "highwaymen", min: "hughwaynom" }, { en: "hijack", min: "huqakc" }, { en: "hike", min: "huco" }, { en: "hillock", min: "hurrekc" }, { en: "hillside", min: "hurrzuto" }, { en: "hilltop", min: "hurrdeb" }, { en: "hilt", min: "hurd" }, { en: "him", min: "hun" },
  { en: "himself", min: "hunzorv" }, { en: "hind", min: "humt" }, { en: "hindmost", min: "humtnezd" }, { en: "hindrance", min: "humtlamko" }, { en: "hindsight", min: "humtzughd" }, { en: "hing", min: "humg" }, { en: "hinge", min: "humgo" }, { en: "hint", min: "humd" }, { en: "hinterland", min: "humdolramt" }, { en: "hip", min: "hub" },
  { en: "hippie", min: "hubbuo" }, { en: "hippo", min: "hubbe" }, { en: "hire", min: "hulo" }, { en: "hirsute", min: "hulzido" }, { en: "histamine", min: "huzdanumo" }, { en: "histogram", min: "huzdeglan" }, { en: "historian", min: "huzdeluam" }, { en: "hit", min: "hud" }, { en: "hitch", min: "hudkh" }, { en: "hitchhike", min: "hudkhhuco" },
  { en: "hitherto", min: "hudholde" }, { en: "hive", min: "hufo" }, { en: "hivemind", min: "hufonumt" }, { en: "hoagie", min: "heaguo" }, { en: "hoard", min: "healt" }, { en: "hoarfrost", min: "healvlezd" }, { en: "hoarse", min: "healzo" }, { en: "hoax", min: "heax" }, { en: "hob", min: "hep" }, { en: "hobbit", min: "heppud" },
  { en: "hobble", min: "heppro" }, { en: "hobbyhorse", min: "heppyhelzo" }, { en: "hobgoblin", min: "hepgeprum" }, { en: "hobnail", min: "hepmaur" }, { en: "hobnob", min: "hepmep" }, { en: "hobo", min: "hepe" }, { en: "hoc", min: "hek" }, { en: "hock", min: "hekc" }, { en: "hockshop", min: "hekczheb" }, { en: "hod", min: "het" },
  { en: "hodgepodge", min: "hetgobetgo" }, { en: "hoe", min: "heo" }, { en: "hoedown", min: "heotewm" }, { en: "hog", min: "heg" }, { en: "hogshead", min: "hegzhoat" }, { en: "hogwash", min: "hegwazh" }, { en: "hokum", min: "hecin" }, { en: "hold", min: "hert" }, { en: "holdout", min: "herteid" }, { en: "holdup", min: "hertib" },
  { en: "hole", min: "hero" }, { en: "hollow", min: "herrew" }, { en: "hollyhock", min: "herryhekc" }, { en: "hologram", min: "hereglan" }, { en: "holograph", min: "hereglabh" }, { en: "homage", min: "henago" }, { en: "homburg", min: "henpilg" }, { en: "home", min: "heno" }, { en: "homegrown", min: "henoglewm" }, { en: "homeland", min: "henoramt" },
  { en: "homemade", min: "henonato" }, { en: "homepage", min: "henobago" }, { en: "homeroom", min: "henoleen" }, { en: "homesick", min: "henozukc" }, { en: "homespun", min: "henozbim" }, { en: "homestead", min: "henozdoat" }, { en: "hometown", min: "henodewm" }, { en: "homework", min: "henowelc" }, { en: "homicide", min: "henukuto" }, { en: "homie", min: "henuo" },
  { en: "homogenize", min: "henegomuso" }, { en: "homograph", min: "heneglabh" }, { en: "homonym", min: "henemyn" }, { en: "homophone", min: "henebhemo" }, { en: "honcho", min: "hemkhe" }, { en: "hone", min: "hemo" }, { en: "honeybee", min: "hemoypoo" }, { en: "honeycomb", min: "hemoykenp" }, { en: "honeydew", min: "hemoytow" }, { en: "honeymoon", min: "hemoyneem" },
  { en: "honk", min: "hemc" }, { en: "honoraria", min: "hemelalua" }, { en: "honorarium", min: "hemelaluin" }, { en: "hooch", min: "heekh" }, { en: "hoodie", min: "heetuo" }, { en: "hoodlum", min: "heetrin" }, { en: "hoodoo", min: "heetee" }, { en: "hoodwink", min: "heetwumc" }, { en: "hoof", min: "heev" }, { en: "hook", min: "heec" },
  { en: "hookah", min: "heecah" }, { en: "hookup", min: "heecib" }, { en: "hookworm", min: "heecweln" }, { en: "hooligan", min: "heerugam" }, { en: "hoop", min: "heeb" }, { en: "hoopla", min: "heebra" }, { en: "hoorah", min: "heelah" }, { en: "hoot", min: "heed" }, { en: "hootch", min: "heedkh" }, { en: "hop", min: "heb" },
  { en: "hopscotch", min: "hebzkedkh" }, { en: "horde", min: "helto" }, { en: "horizon", min: "helusem" }, { en: "hormone", min: "helnemo" }, { en: "hornet", min: "helmod" }, { en: "hornpipe", min: "helmbubo" }, { en: "horrid", min: "hellut" }, { en: "horror", min: "hellel" }, { en: "horse", min: "helzo" }, { en: "horseback", min: "helzopakc" },
  { en: "horsehair", min: "helzohaul" }, { en: "horsehide", min: "helzohuto" }, { en: "horseman", min: "helzonam" }, { en: "horsemen", min: "helzonom" }, { en: "horseshoe", min: "helzozheo" }, { en: "horsetail", min: "helzodaur" }, { en: "horsewhip", min: "helzowhub" }, { en: "horsewoman", min: "helzowenam" }, { en: "horsewomen", min: "helzowenom" }, { en: "hosanna", min: "hezamma" },
  { en: "hose", min: "hezo" }, { en: "hospice", min: "hezbuko" }, { en: "host", min: "hezd" }, { en: "hostage", min: "hezdago" }, { en: "hostel", min: "hezdor" }, { en: "hostile", min: "hezduro" }, { en: "hotcake", min: "hedkaco" }, { en: "hotel", min: "hedor" }, { en: "hothead", min: "hedhoat" }, { en: "hothouse", min: "hedheizo" },
  { en: "hotlink", min: "hedrumc" }, { en: "hotshot", min: "hedzhed" }, { en: "hound", min: "heimt" }, { en: "hour", min: "heil" }, { en: "houseboat", min: "heizopead" }, { en: "housebound", min: "heizopeimt" }, { en: "housebreak", min: "heizoploac" }, { en: "housebroke", min: "heizopleco" }, { en: "houseclean", min: "heizokroam" }, { en: "housecoat", min: "heizokead" },
  { en: "household", min: "heizohert" }, { en: "housemaid", min: "heizonaut" }, { en: "houseplant", min: "heizobramd" }, { en: "housetop", min: "heizodeb" }, { en: "housewife", min: "heizowuvo" }, { en: "housework", min: "heizowelc" }, { en: "hove", min: "hefo" }, { en: "hovel", min: "hefor" }, { en: "hoverboard", min: "hefolpealt" }, { en: "hovercraft", min: "hefolklavd" },
  { en: "how", min: "hew" }, { en: "howdah", min: "hewtah" }, { en: "howl", min: "hewr" }, { en: "hub", min: "hip" }, { en: "hubbub", min: "hippip" }, { en: "hubcap", min: "hipkab" }, { en: "huddle", min: "hittro" }, { en: "hue", min: "hio" }, { en: "hug", min: "hig" }, { en: "huge", min: "higo" },
  { en: "huh", min: "hih" }, { en: "hula", min: "hira" }, { en: "hulk", min: "hirc" }, { en: "hullabaloo", min: "hirraparee" }, { en: "hum", min: "hin" }, { en: "human", min: "hinam" }, { en: "humane", min: "hinamo" }, { en: "humanize", min: "hinamuso" }, { en: "humankind", min: "hinamcumt" }, { en: "humanoid", min: "hinameut" },
  { en: "humble", min: "hinpro" }, { en: "humbug", min: "hinpig" }, { en: "humdrum", min: "hintlin" }, { en: "humeri", min: "hinolu" }, { en: "humid", min: "hinut" }, { en: "humidor", min: "hinutel" }, { en: "humiliate", min: "hinuruado" }, { en: "hummock", min: "hinnekc" }, { en: "humor", min: "hinel" }, { en: "hump", min: "hinb" },
  { en: "humpback", min: "hinbpakc" }, { en: "hunch", min: "himkh" }, { en: "hunchback", min: "himkhpakc" }, { en: "hunk", min: "himc" }, { en: "huntsman", min: "himdznam" }, { en: "huntsmen", min: "himdznom" }, { en: "hurdle", min: "hiltro" }, { en: "hurl", min: "hilr" }, { en: "hurrah", min: "hillah" }, { en: "hurricane", min: "hillukamo" },
];
