/**
 * @file Contains dictionary entries for category: phrases_common.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const phrases_common: DictionaryEntry[] = [
  { en: "i love you", min: "tulaliloo ti amo" }, { en: "i hate you", min: "tatata bala tu" }, { en: "wedding", min: "la boda" }, { en: "what is that", min: "po ka ta" }, { en: "beautiful", min: "bellisima" }, { en: "ruin", min: "lium" }, { en: "rule", min: "liro" }, { en: "rum", min: "lin" }, { en: "rumba", min: "linpa" }, { en: "rumble", min: "linpro" },
  { en: "ruminant", min: "linumamd" }, { en: "ruminate", min: "linumado" }, { en: "rummage", min: "linnago" }, { en: "rumor", min: "linel" }, { en: "rump", min: "linb" }, { en: "rumple", min: "linbro" }, { en: "runabout", min: "limapeid" }, { en: "runaround", min: "limaleimt" }, { en: "rundown", min: "limtewm" }, { en: "rune", min: "limo" },
  { en: "rung", min: "limg" }, { en: "runnel", min: "limmor" }, { en: "runoff", min: "limevv" }, { en: "runt", min: "limd" }, { en: "rupee", min: "liboo" }, { en: "rupture", min: "libdilo" }, { en: "ruse", min: "lizo" }, { en: "rusk", min: "lizc" }, { en: "russet", min: "lizzod" }, { en: "rust", min: "lizd" },
  { en: "rustle", min: "lizdro" }, { en: "rustproof", min: "lizdbleev" }, { en: "rut", min: "lid" }, { en: "rutabaga", min: "lidapaga" }, { en: "rye", min: "lyo" }, { en: "sable", min: "zapro" }, { en: "sabotage", min: "zapedago" }, { en: "saboteur", min: "zapedoil" }, { en: "sac", min: "zak" }, { en: "saccharin", min: "zakkhalum" },
  { en: "saccharine", min: "zakkhalumo" }, { en: "sachem", min: "zakhon" }, { en: "sachet", min: "zakhod" }, { en: "sack", min: "zakc" }, { en: "sacrifice", min: "zakluvuko" }, { en: "sacrilege", min: "zaklurogo" }, { en: "sacristan", min: "zakluzdam" }, { en: "sacrosanct", min: "zaklezamkd" }, { en: "sadden", min: "zattom" }, { en: "saddle", min: "zattro" },
  { en: "saddlebag", min: "zattropag" }, { en: "safari", min: "zavalu" }, { en: "safe", min: "zavo" }, { en: "safeguard", min: "zavogialt" }, { en: "saffron", min: "zavvlem" }, { en: "sag", min: "zag" }, { en: "saga", min: "zaga" }, { en: "sage", min: "zago" }, { en: "sagebrush", min: "zagoplizh" }, { en: "sago", min: "zage" },
  { en: "saguaro", min: "zagiale" }, { en: "sahib", min: "zahup" }, { en: "said", min: "zaut" }, { en: "sail", min: "zaur" }, { en: "sailboard", min: "zaurpealt" }, { en: "sailboat", min: "zaurpead" }, { en: "sailor", min: "zaurel" }, { en: "sake", min: "zaco" }, { en: "salaam", min: "zaraan" }, { en: "salad", min: "zarat" },
  { en: "salami", min: "zaranu" }, { en: "sale", min: "zaro" }, { en: "salesclerk", min: "zarozkrolc" }, { en: "salesgirl", min: "zarozgulr" }, { en: "salesman", min: "zaroznam" }, { en: "salesmen", min: "zaroznom" }, { en: "saleswoman", min: "zarozwenam" }, { en: "saleswomen", min: "zarozwenom" }, { en: "salience", min: "zaruomko" }, { en: "salient", min: "zaruomd" },
  { en: "saline", min: "zarumo" }, { en: "saliva", min: "zarufa" }, { en: "salivate", min: "zarufado" }, { en: "sallow", min: "zarrew" }, { en: "salmon", min: "zarnem" }, { en: "salmonella", min: "zarnemorra" }, { en: "salon", min: "zarem" }, { en: "saloon", min: "zareem" }, { en: "salsa", min: "zarza" }, { en: "saltine", min: "zardumo" },
  { en: "saltpetre", min: "zardbodlo" }, { en: "salute", min: "zarido" }, { en: "salvage", min: "zarfago" }, { en: "salve", min: "zarfo" }, { en: "salvo", min: "zarfe" }, { en: "samba", min: "zanpa" }, { en: "same", min: "zano" }, { en: "samizdat", min: "zanustad" }, { en: "sampan", min: "zanbam" }, { en: "sample", min: "zanbro" },
  { en: "samurai", min: "zanilau" }, { en: "sanatoria", min: "zamadelua" }, { en: "sanatorium", min: "zamadeluin" }, { en: "sancta", min: "zamkda" }, { en: "sanctum", min: "zamkdin" }, { en: "sandalwood", min: "zamtarweet" }, { en: "sandbag", min: "zamtpag" }, { en: "sandbank", min: "zamtpamc" }, { en: "sandblast", min: "zamtprazd" }, { en: "sandbox", min: "zamtpex" },
  { en: "sandcastle", min: "zamtkazdro" }, { en: "sandhog", min: "zamtheg" }, { en: "sandlot", min: "zamtred" }, { en: "sandman", min: "zamtnam" }, { en: "sandmen", min: "zamtnom" }, { en: "sandstone", min: "zamtzdemo" }, { en: "sandstorm", min: "zamtzdeln" }, { en: "sane", min: "zamo" }, { en: "sangfroid", min: "zamgvleut" }, { en: "sanguine", min: "zamgiumo" },
  { en: "sanitaria", min: "zamudalua" }, { en: "sanitarium", min: "zamudaluin" }, { en: "sanitize", min: "zamuduso" }, { en: "sank", min: "zamc" }, { en: "sanserif", min: "zamzoluv" }, { en: "sapience", min: "zabuomko" }, { en: "sapient", min: "zabuomd" }, { en: "saprophyte", min: "zablebhydo" }, { en: "sarape", min: "zalabo" }, { en: "sarcasm", min: "zalkazn" },
  { en: "sarcoma", min: "zalkena" }, { en: "sarcomata", min: "zalkenada" }, { en: "sarcophagi", min: "zalkebhagu" }, { en: "sardine", min: "zaltumo" }, { en: "sarong", min: "zalemg" }, { en: "sash", min: "zazh" }, { en: "satchel", min: "zadkhor" }, { en: "sate", min: "zado" }, { en: "sateen", min: "zadoom" }, { en: "satellite", min: "zadorrudo" },
  { en: "satiate", min: "zaduado" }, { en: "satin", min: "zadum" }, { en: "satinwood", min: "zadumweet" }, { en: "satire", min: "zadulo" }, { en: "satirize", min: "zaduluso" }, { en: "satrap", min: "zadlab" }, { en: "saturate", min: "zadilado" }, { en: "saturnine", min: "zadilmumo" }, { en: "satyr", min: "zadyl" }, { en: "sauce", min: "zaiko" },
  { en: "saucepan", min: "zaikobam" }, { en: "sauerkraut", min: "zaiolclaid" }, { en: "sauna", min: "zaima" }, { en: "sausage", min: "zaizago" }, { en: "savanna", min: "zafamma" }, { en: "savant", min: "zafamd" }, { en: "save", min: "zafo" }, { en: "saviour", min: "zafueil" }, { en: "savor", min: "zafel" }, { en: "sawdust", min: "zawtizd" },
  { en: "sawhorse", min: "zawhelzo" }, { en: "sawmill", min: "zawnurr" }, { en: "sawn", min: "zawm" }, { en: "sax", min: "zax" }, { en: "saxophone", min: "zaxebhemo" }, { en: "scab", min: "zkap" }, { en: "scabbard", min: "zkappalt" }, { en: "scad", min: "zkat" }, { en: "scaffold", min: "zkavvert" }, { en: "scag", min: "zkag" },
  { en: "scalawag", min: "zkarawag" }, { en: "scald", min: "zkart" }, { en: "scale", min: "zkaro" }, { en: "scalene", min: "zkaromo" }, { en: "scallion", min: "zkarruem" }, { en: "scallop", min: "zkarreb" }, { en: "scallywag", min: "zkarrywag" }, { en: "scalp", min: "zkarb" }, { en: "scalpel", min: "zkarbor" }, { en: "scam", min: "zkan" },
  { en: "scamp", min: "zkanb" }, { en: "scampi", min: "zkanbu" }, { en: "scan", min: "zkam" }, { en: "scandalize", min: "zkamtaruso" }, { en: "scansion", min: "zkamzuem" }, { en: "scant", min: "zkamd" }, { en: "scapegoat", min: "zkabogead" }, { en: "scapula", min: "zkabira" }, { en: "scapulae", min: "zkabirao" }, { en: "scarab", min: "zkalap" },
  { en: "scarce", min: "zkalko" }, { en: "scare", min: "zkalo" }, { en: "scarecrow", min: "zkaloklew" }, { en: "scat", min: "zkad" }, { en: "scavenge", min: "zkafomgo" }, { en: "scenario", min: "zkomalue" }, { en: "scene", min: "zkomo" }, { en: "scent", min: "zkomd" }, { en: "schedule", min: "zkhotiro" }, { en: "schema", min: "zkhona" },
  { en: "scheme", min: "zkhono" }, { en: "scherzi", min: "zkholsu" }, { en: "scherzo", min: "zkholse" }, { en: "schizoid", min: "zkhuseut" }, { en: "schlemiel", min: "zkhronuor" }, { en: "schlep", min: "zkhrob" }, { en: "schlepp", min: "zkhrobb" }, { en: "schlock", min: "zkhrekc" }, { en: "schmaltz", min: "zkhnards" }, { en: "schmalz", min: "zkhnars" },
  { en: "schmooze", min: "zkhneeso" }, { en: "schmuck", min: "zkhnikc" }, { en: "schoolbook", min: "zkheerpeec" }, { en: "schoolgirl", min: "zkheergulr" }, { en: "schoolmarm", min: "zkheernaln" }, { en: "schoolmate", min: "zkheernado" }, { en: "schoolroom", min: "zkheerleen" }, { en: "schoolwork", min: "zkheerwelc" }, { en: "schoolyard", min: "zkheeryalt" }, { en: "schrod", min: "zkhlet" },
  { en: "schtick", min: "zkhdukc" }, { en: "schwa", min: "zkhwa" }, { en: "sciatica", min: "zkuaduka" }, { en: "science", min: "zkuomko" }, { en: "scintilla", min: "zkumdurra" }, { en: "scion", min: "zkuem" }, { en: "scissor", min: "zkuzzel" }, { en: "scoff", min: "zkevv" }, { en: "scofflaw", min: "zkevvraw" }, { en: "scold", min: "zkert" },
  { en: "scollop", min: "zkerreb" }, { en: "sconce", min: "zkemko" }, { en: "scone", min: "zkemo" }, { en: "scoop", min: "zkeeb" }, { en: "scoot", min: "zkeed" }, { en: "scope", min: "zkebo" }, { en: "scorch", min: "zkelkh" }, { en: "score", min: "zkelo" }, { en: "scoreboard", min: "zkelopealt" }, { en: "scorecard", min: "zkelokalt" },
  { en: "scorn", min: "zkelm" }, { en: "scorpion", min: "zkelbuem" }, { en: "scoundrel", min: "zkeimtlor" }, { en: "scour", min: "zkeil" }, { en: "scourge", min: "zkeilgo" }, { en: "scow", min: "zkew" }, { en: "scowl", min: "zkewr" }, { en: "scram", min: "zklan" }, { en: "scramble", min: "zklanpro" }, { en: "scrap", min: "zklab" },
  { en: "scrapbook", min: "zklabpeec" }, { en: "scrape", min: "zklabo" }, { en: "scratch", min: "zkladkh" }, { en: "scrawl", min: "zklawr" }, { en: "scream", min: "zkloan" }, { en: "screech", min: "zklookh" }, { en: "screen", min: "zkloom" }, { en: "screenshot", min: "zkloomzhed" }, { en: "screwball", min: "zklowparr" }, { en: "scribble", min: "zkluppro" },
  { en: "scribe", min: "zklupo" }, { en: "scrimmage", min: "zklunnago" }, { en: "scrimp", min: "zklunb" }, { en: "scrimshaw", min: "zklunzhaw" }, { en: "scrip", min: "zklub" }, { en: "script", min: "zklubd" }, { en: "scrod", min: "zklet" }, { en: "scrofula", min: "zklevira" }, { en: "scrog", min: "zkleg" }, { en: "scroll", min: "zklerr" },
  { en: "scrota", min: "zkleda" }, { en: "scrotum", min: "zkledin" }, { en: "scrounge", min: "zkleimgo" }, { en: "scrub", min: "zklip" }, { en: "scruff", min: "zklivv" }, { en: "scrunch", min: "zklimkh" }, { en: "scrunchie", min: "zklimkhuo" }, { en: "scruple", min: "zklibro" }, { en: "scrutinize", min: "zklidumuso" }, { en: "scuba", min: "zkipa" },
  { en: "scuff", min: "zkivv" }, { en: "scuffle", min: "zkivvro" }, { en: "scull", min: "zkirr" }, { en: "scullion", min: "zkirruem" }, { en: "sculpt", min: "zkirbd" }, { en: "sculptor", min: "zkirbdel" }, { en: "sculpture", min: "zkirbdilo" }, { en: "scum", min: "zkin" }, { en: "scumbag", min: "zkinpag" }, { en: "scurf", min: "zkilv" },
  { en: "scuttle", min: "zkiddro" }, { en: "scythe", min: "zkydho" }, { en: "sea", min: "zoa" }, { en: "seabird", min: "zoapult" }, { en: "seaboard", min: "zoapealt" }, { en: "seacoast", min: "zoakeazd" }, { en: "seafood", min: "zoaveet" }, { en: "sealant", min: "zoaramd" }, { en: "sealskin", min: "zoarzcum" }, { en: "seam", min: "zoan" },
];
