/**
 * @file Contains dictionary entries for category: places_town.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const places_town: DictionaryEntry[] = [
  { en: "school", min: "escuela" }, { en: "hospital", min: "hospi" }, { en: "store", min: "tienda" }, { en: "bank", min: "banco" }, { en: "office", min: "oficina" }, { en: "inheritor", min: "umholudel" }, { en: "inhibit", min: "umhupud" }, { en: "inhuman", min: "umhinam" }, { en: "inhumane", min: "umhinamo" }, { en: "initialize", min: "umuduaruso" },
  { en: "initiate", min: "umuduado" }, { en: "initiator", min: "umuduadel" }, { en: "initio", min: "umudue" }, { en: "inject", min: "umqokd" }, { en: "injector", min: "umqokdel" }, { en: "injure", min: "umqilo" }, { en: "injustice", min: "umqizduko" }, { en: "ink", min: "umc" }, { en: "inkblot", min: "umcpred" }, { en: "inkwell", min: "umcworr" },
  { en: "inlaid", min: "umraut" }, { en: "inland", min: "umramt" }, { en: "inlet", min: "umrod" }, { en: "inline", min: "umrumo" }, { en: "inmate", min: "umnado" }, { en: "inmost", min: "umnezd" }, { en: "inn", min: "umm" }, { en: "innate", min: "ummado" }, { en: "innermost", min: "ummolnezd" }, { en: "innocence", min: "ummekomko" },
  { en: "innovate", min: "ummefado" }, { en: "innovator", min: "ummefadel" }, { en: "innuendo", min: "ummiomte" }, { en: "inoculate", min: "umekirado" }, { en: "inordinate", min: "umeltumado" }, { en: "inpatient", min: "umbaduomd" }, { en: "input", min: "umbid" }, { en: "inquietude", min: "umjiuodito" }, { en: "inquire", min: "umjiulo" }, { en: "inquisitor", min: "umjiuzudel" },
  { en: "inroad", min: "umleat" }, { en: "insane", min: "umzamo" }, { en: "inscribe", min: "umzklupo" }, { en: "inseam", min: "umzoan" }, { en: "insect", min: "umzokd" }, { en: "insecure", min: "umzokilo" }, { en: "inseminate", min: "umzonumado" }, { en: "insensate", min: "umzomzado" }, { en: "insentient", min: "umzomduomd" }, { en: "insert", min: "umzold" },
  { en: "inset", min: "umzod" }, { en: "inshore", min: "umzhelo" }, { en: "inside", min: "umzuto" }, { en: "insight", min: "umzughd" }, { en: "insigne", min: "umzugmo" }, { en: "insignia", min: "umzugmua" }, { en: "insincere", min: "umzumkolo" }, { en: "insinuate", min: "umzumiado" }, { en: "insipid", min: "umzubut" }, { en: "insistence", min: "umzuzdomko" },
  { en: "insistent", min: "umzuzdomd" }, { en: "insole", min: "umzero" }, { en: "insolence", min: "umzeromko" }, { en: "insolent", min: "umzeromd" }, { en: "insoluble", min: "umzeripro" }, { en: "insolvent", min: "umzerfomd" }, { en: "insomnia", min: "umzenmua" }, { en: "insomniac", min: "umzenmuak" }, { en: "insouciant", min: "umzeikuamd" }, { en: "inspect", min: "umzbokd" },
  { en: "inspector", min: "umzbokdel" }, { en: "inspire", min: "umzbulo" }, { en: "install", min: "umzdarr" }, { en: "instance", min: "umzdamko" }, { en: "instant", min: "umzdamd" }, { en: "instead", min: "umzdoat" }, { en: "instep", min: "umzdob" }, { en: "instigate", min: "umzdugado" }, { en: "instigator", min: "umzdugadel" }, { en: "instil", min: "umzdur" },
  { en: "instill", min: "umzdurr" }, { en: "instinct", min: "umzdumkd" }, { en: "institute", min: "umzdudido" }, { en: "instruct", min: "umzdlikd" }, { en: "instructor", min: "umzdlikdel" }, { en: "insulate", min: "umzirado" }, { en: "insulator", min: "umziradel" }, { en: "insulin", min: "umzirum" }, { en: "insult", min: "umzird" }, { en: "insurance", min: "umzilamko" },
  { en: "insure", min: "umzilo" }, { en: "insurgence", min: "umzilgomko" }, { en: "insurgent", min: "umzilgomd" }, { en: "int", min: "umd" }, { en: "intact", min: "umdakd" }, { en: "intagli", min: "umdagru" }, { en: "intaglio", min: "umdagrue" }, { en: "intake", min: "umdaco" }, { en: "integrate", min: "umdoglado" }, { en: "integrator", min: "umdogladel" },
  { en: "intellect", min: "umdorrokd" }, { en: "intend", min: "umdomt" }, { en: "intense", min: "umdomzo" }, { en: "intent", min: "umdomd" }, { en: "interim", min: "umdolun" }, { en: "interj", min: "umdolq" }, { en: "intern", min: "umdolm" }, { en: "interne", min: "umdolmo" }, { en: "intestate", min: "umdozdado" }, { en: "intestine", min: "umdozdumo" },
  { en: "intimate", min: "umdunado" }, { en: "intimidate", min: "umdunutado" }, { en: "into", min: "umde" }, { en: "intolerant", min: "umderolamd" }, { en: "intone", min: "umdemo" }, { en: "intoxicant", min: "umdexukamd" }, { en: "intoxicate", min: "umdexukado" }, { en: "intranet", min: "umdlamod" }, { en: "intrench", min: "umdlomkh" }, { en: "intrepid", min: "umdlobut" },
  { en: "intricate", min: "umdlukado" }, { en: "intrigue", min: "umdlugio" }, { en: "intro", min: "umdle" }, { en: "introduce", min: "umdletiko" }, { en: "introvert", min: "umdlefold" }, { en: "intrude", min: "umdlito" }, { en: "intrusion", min: "umdlizuem" }, { en: "intrust", min: "umdlizd" }, { en: "intuit", min: "umdiud" }, { en: "inundate", min: "umimtado" },
  { en: "inure", min: "umilo" }, { en: "invade", min: "umfato" }, { en: "invalid", min: "umfarut" }, { en: "invalidate", min: "umfarutado" }, { en: "invariant", min: "umfaluamd" }, { en: "invasion", min: "umfazuem" }, { en: "inveigh", min: "umfough" }, { en: "inveigle", min: "umfougro" }, { en: "invent", min: "umfomd" }, { en: "inventor", min: "umfomdel" },
  { en: "inverse", min: "umfolzo" }, { en: "inversion", min: "umfolzuem" }, { en: "invert", min: "umfold" }, { en: "investor", min: "umfozdel" }, { en: "inveterate", min: "umfodolado" }, { en: "invigorate", min: "umfugelado" }, { en: "inviolate", min: "umfuerado" }, { en: "invite", min: "umfudo" }, { en: "invoice", min: "umfeuko" }, { en: "invoke", min: "umfeco" },
  { en: "involve", min: "umferfo" }, { en: "ioctl", min: "uekdr" }, { en: "iodine", min: "uetumo" }, { en: "iodize", min: "uetuso" }, { en: "ion", min: "uem" }, { en: "ionize", min: "uemuso" }, { en: "ionosphere", min: "uemezbholo" }, { en: "iota", min: "ueda" }, { en: "ipecac", min: "ubokak" }, { en: "irate", min: "ulado" },
  { en: "ire", min: "ulo" }, { en: "iridescent", min: "ulutozkomd" }, { en: "iridium", min: "ulutuin" }, { en: "irk", min: "ulc" }, { en: "irksome", min: "ulczeno" }, { en: "iron", min: "ulem" }, { en: "ironclad", min: "ulemkrat" }, { en: "ironware", min: "ulemwalo" }, { en: "ironwork", min: "ulemwelc" }, { en: "irradiate", min: "ullatuado" },
  { en: "irrelevant", min: "ullorofamd" }, { en: "irresolute", min: "ullozerido" }, { en: "irreverent", min: "ullofolomd" }, { en: "irrigate", min: "ullugado" }, { en: "irritant", min: "ulludamd" }, { en: "irritate", min: "ulludado" }, { en: "islet", min: "uzrod" }, { en: "ism", min: "uzn" }, { en: "isolate", min: "uzerado" }, { en: "isotope", min: "uzedebo" },
  { en: "issuance", min: "uzziamko" }, { en: "issue", min: "uzzio" }, { en: "isthmi", min: "uzdhnu" }, { en: "italicize", min: "udarukuso" }, { en: "itch", min: "udkh" }, { en: "item", min: "udon" }, { en: "itemize", min: "udonuso" }, { en: "iterate", min: "udolado" }, { en: "iterator", min: "udoladel" }, { en: "itinerant", min: "udumolamd" },
  { en: "itself", min: "udzorv" }, { en: "jab", min: "qap" }, { en: "jabot", min: "qaped" }, { en: "jackboot", min: "qakcpeed" }, { en: "jackdaw", min: "qakctaw" }, { en: "jackknife", min: "qakccmuvo" }, { en: "jackpot", min: "qakcbed" }, { en: "jackrabbit", min: "qakclappud" }, { en: "jag", min: "qag" }, { en: "jail", min: "qaur" },
  { en: "jailbreak", min: "qaurploac" }, { en: "jailor", min: "qaurel" }, { en: "jalousie", min: "qareizuo" }, { en: "jam", min: "qan" }, { en: "jamb", min: "qanp" }, { en: "jamboree", min: "qanpeloo" }, { en: "jangle", min: "qamgro" }, { en: "janitor", min: "qamudel" }, { en: "jape", min: "qabo" }, { en: "jar", min: "qal" },
  { en: "jargon", min: "qalgem" }, { en: "jaundice", min: "qaimtuko" }, { en: "jaunt", min: "qaimd" }, { en: "javelin", min: "qaforum" }, { en: "jaw", min: "qaw" }, { en: "jawbone", min: "qawpemo" }, { en: "jaywalk", min: "qaywarc" }, { en: "jazz", min: "qass" }, { en: "jeez", min: "qoos" }, { en: "jehad", min: "qohat" },
  { en: "jejune", min: "qoqimo" }, { en: "jell", min: "qorr" }, { en: "jello", min: "qorre" }, { en: "jellybean", min: "qorrypoam" }, { en: "jeopardize", min: "qoebaltuso" }, { en: "jeremiad", min: "qolonuat" }, { en: "jerk", min: "qolc" }, { en: "jerkin", min: "qolcum" }, { en: "jest", min: "qozd" }, { en: "jet", min: "qod" },
  { en: "jetsam", min: "qodzan" }, { en: "jettison", min: "qodduzem" }, { en: "jib", min: "qup" }, { en: "jibe", min: "qupo" }, { en: "jig", min: "qug" }, { en: "jiggle", min: "quggro" }, { en: "jigsaw", min: "qugzaw" }, { en: "jigsawn", min: "qugzawm" }, { en: "jihad", min: "quhat" }, { en: "jilt", min: "qurd" },
  { en: "jingle", min: "qumgro" }, { en: "jinn", min: "qumm" }, { en: "jinni", min: "qummu" }, { en: "jinricksha", min: "qumlukczha" }, { en: "jinrikisha", min: "qumlucuzha" }, { en: "jinx", min: "qumx" }, { en: "jitterbug", min: "quddolpig" }, { en: "jiujitsu", min: "quiqudzi" }, { en: "jive", min: "qufo" }, { en: "jockstrap", min: "qekczdlab" },
  { en: "jocose", min: "qekezo" }, { en: "jocund", min: "qekimt" }, { en: "jog", min: "qeg" }, { en: "joggle", min: "qeggro" }, { en: "join", min: "qeum" }, { en: "joint", min: "qeumd" }, { en: "joke", min: "qeco" }, { en: "jolt", min: "qerd" }, { en: "jonquil", min: "qemjiur" }, { en: "jostle", min: "qezdro" },
  { en: "jot", min: "qed" }, { en: "jounce", min: "qeimko" }, { en: "journalese", min: "qeilmarozo" }, { en: "journeyman", min: "qeilmoynam" }, { en: "journeymen", min: "qeilmoynom" }, { en: "joust", min: "qeizd" }, { en: "jowl", min: "qewr" }, { en: "joyridden", min: "qeyluttom" }, { en: "joyride", min: "qeyluto" }, { en: "joyrode", min: "qeyleto" },
  { en: "joystick", min: "qeyzdukc" }, { en: "jubilant", min: "qipuramd" }, { en: "jubilee", min: "qipuroo" }, { en: "judge", min: "qitgo" }, { en: "judicature", min: "qitukadilo" }, { en: "judo", min: "qite" }, { en: "jug", min: "qig" }, { en: "juggle", min: "qiggro" }, { en: "jujitsu", min: "qiqudzi" }, { en: "jujube", min: "qiqipo" },
  { en: "jujutsu", min: "qiqidzi" }, { en: "jukebox", min: "qicopex" }, { en: "julep", min: "qirob" }, { en: "jumble", min: "qinpro" }, { en: "jumbo", min: "qinpe" }, { en: "jumpsuit", min: "qinbziud" }, { en: "junco", min: "qimke" }, { en: "juncture", min: "qimkdilo" }, { en: "jungle", min: "qimgro" }, { en: "junk", min: "qimc" },
  { en: "junket", min: "qimcod" }, { en: "junkie", min: "qimcuo" }, { en: "junkyard", min: "qimcyalt" }, { en: "junta", min: "qimda" }, { en: "juror", min: "qilel" }, { en: "just", min: "qizd" }, { en: "jut", min: "qid" }, { en: "jute", min: "qido" }, { en: "juvenile", min: "qifomuro" }, { en: "juxtapose", min: "qixdabezo" },
];
