/**
 * @file Contains dictionary entries for category: places_rooms.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const places_rooms: DictionaryEntry[] = [
  { en: "park", min: "parque" }, { en: "library", min: "biblio" }, { en: "museum", min: "museo" }, { en: "garden", min: "jardin" }, { en: "zoo", min: "zoologico" }, { en: "lemon", min: "ronem" }, { en: "lemonade", min: "ronemato" }, { en: "lemur", min: "ronil" }, { en: "lend", min: "romt" }, { en: "lengthen", min: "romgdhom" },
  { en: "lenient", min: "romuomd" }, { en: "lentil", min: "romdur" }, { en: "leonine", min: "roemumo" }, { en: "leopard", min: "roebalt" }, { en: "leotard", min: "roedalt" }, { en: "leprechaun", min: "roblokhaim" }, { en: "lept", min: "robd" }, { en: "lesbian", min: "rozpuam" }, { en: "lesion", min: "rozuem" }, { en: "lessee", min: "rozzoo" },
  { en: "lessen", min: "rozzom" }, { en: "lesson", min: "rozzem" }, { en: "lessor", min: "rozzel" }, { en: "lest", min: "rozd" }, { en: "let", min: "rod" }, { en: "letdown", min: "rodtewm" }, { en: "letterbomb", min: "roddolpenp" }, { en: "letterbox", min: "roddolpex" }, { en: "letterhead", min: "roddolhoat" }, { en: "lettuce", min: "roddiko" },
  { en: "letup", min: "rodib" }, { en: "leukemia", min: "roiconua" }, { en: "leukocyte", min: "roicekydo" }, { en: "levee", min: "rofoo" }, { en: "level", min: "rofor" }, { en: "leverage", min: "rofolago" }, { en: "levitate", min: "rofudado" }, { en: "lewd", min: "rowt" }, { en: "lexica", min: "roxuka" }, { en: "lexicon", min: "roxukem" },
  { en: "liaise", min: "ruauzo" }, { en: "liaison", min: "ruauzem" }, { en: "libel", min: "rupor" }, { en: "liberalize", min: "rupolaruso" }, { en: "liberate", min: "rupolado" }, { en: "liberator", min: "rupoladel" }, { en: "libertine", min: "rupoldumo" }, { en: "libido", min: "rupute" }, { en: "librarian", min: "ruplaluam" }, { en: "libretti", min: "ruploddu" },
  { en: "libretto", min: "ruplodde" }, { en: "lice", min: "ruko" }, { en: "licence", min: "rukomko" }, { en: "license", min: "rukomzo" }, { en: "licensee", min: "rukomzoo" }, { en: "licentiate", min: "rukomduado" }, { en: "lichee", min: "rukhoo" }, { en: "lichen", min: "rukhom" }, { en: "licit", min: "rukud" }, { en: "lick", min: "rukc" },
  { en: "licorice", min: "rukeluko" }, { en: "lid", min: "rut" }, { en: "lief", min: "ruov" }, { en: "lien", min: "ruom" }, { en: "lieu", min: "ruoi" }, { en: "lieutenant", min: "ruoidomamd" }, { en: "life", min: "ruvo" }, { en: "lifeblood", min: "ruvopreet" }, { en: "lifeboat", min: "ruvopead" }, { en: "lifeguard", min: "ruvogialt" },
  { en: "lifelike", min: "ruvoruco" }, { en: "lifeline", min: "ruvorumo" }, { en: "lifelong", min: "ruvoremg" }, { en: "lifespan", min: "ruvozbam" }, { en: "lifestyle", min: "ruvozdyro" }, { en: "lifetime", min: "ruvoduno" }, { en: "lifework", min: "ruvowelc" }, { en: "lift", min: "ruvd" }, { en: "liftoff", min: "ruvdevv" }, { en: "ligature", min: "rugadilo" },
  { en: "light", min: "rughd" }, { en: "lighten", min: "rughdom" }, { en: "lighthouse", min: "rughdheizo" }, { en: "lignite", min: "rugmudo" }, { en: "lii", min: "ruu" }, { en: "liken", min: "rucom" }, { en: "lilac", min: "rurak" }, { en: "lilt", min: "rurd" }, { en: "limb", min: "runp" }, { en: "limbo", min: "runpe" },
  { en: "lime", min: "runo" }, { en: "limeade", min: "runoato" }, { en: "limelight", min: "runorughd" }, { en: "limerick", min: "runolukc" }, { en: "limestone", min: "runozdemo" }, { en: "limit", min: "runud" }, { en: "limn", min: "runm" }, { en: "limo", min: "rune" }, { en: "limousine", min: "runeizumo" }, { en: "limp", min: "runb" },
  { en: "limpet", min: "runbod" }, { en: "limpid", min: "runbut" }, { en: "linage", min: "rumago" }, { en: "linchpin", min: "rumkhbum" }, { en: "linden", min: "rumtom" }, { en: "line", min: "rumo" }, { en: "lineage", min: "rumoago" }, { en: "lineman", min: "rumonam" }, { en: "linemen", min: "rumonom" }, { en: "linen", min: "rumom" },
  { en: "linesman", min: "rumoznam" }, { en: "linesmen", min: "rumoznom" }, { en: "lineup", min: "rumoib" }, { en: "lingerie", min: "rumgoluo" }, { en: "lingo", min: "rumge" }, { en: "link", min: "rumc" }, { en: "linkage", min: "rumcago" }, { en: "linkup", min: "rumcib" }, { en: "linoleum", min: "rumeroin" }, { en: "lint", min: "rumd" },
  { en: "lintel", min: "rumdor" }, { en: "lionize", min: "ruemuso" }, { en: "lip", min: "rub" }, { en: "lipid", min: "rubut" }, { en: "lipread", min: "rubloat" }, { en: "lipstick", min: "rubzdukc" }, { en: "liqueur", min: "rujioil" }, { en: "liquid", min: "rujiut" }, { en: "liquidate", min: "rujiutado" }, { en: "liquidator", min: "rujiutadel" },
  { en: "liquidize", min: "rujiutuso" }, { en: "liquor", min: "rujiel" }, { en: "lire", min: "rulo" }, { en: "lisle", min: "ruzro" }, { en: "lisp", min: "ruzb" }, { en: "lissom", min: "ruzzen" }, { en: "lissome", min: "ruzzeno" }, { en: "list", min: "ruzd" }, { en: "listen", min: "ruzdom" }, { en: "lit", min: "rud" },
  { en: "litchi", min: "rudkhu" }, { en: "lite", min: "rudo" }, { en: "literate", min: "rudolado" }, { en: "literati", min: "rudoladu" }, { en: "literature", min: "rudoladilo" }, { en: "lithe", min: "rudho" }, { en: "lithium", min: "rudhuin" }, { en: "lithograph", min: "rudheglabh" }, { en: "litigant", min: "rudugamd" }, { en: "litigate", min: "rudugado" },
  { en: "litterbug", min: "ruddolpig" }, { en: "live", min: "rufo" }, { en: "livelong", min: "ruforemg" }, { en: "liven", min: "rufom" }, { en: "liverwurst", min: "rufolwilzd" }, { en: "livestock", min: "rufozdekc" }, { en: "liveware", min: "rufowalo" }, { en: "livid", min: "rufut" }, { en: "lix", min: "rux" }, { en: "lizard", min: "rusalt" },
  { en: "llama", min: "rrana" }, { en: "llano", min: "rrame" }, { en: "load", min: "reat" }, { en: "loadstone", min: "reatzdemo" }, { en: "loaf", min: "reav" }, { en: "loam", min: "rean" }, { en: "loan", min: "ream" }, { en: "loanword", min: "reamwelt" }, { en: "loathe", min: "readho" }, { en: "loathsome", min: "readhzeno" },
  { en: "lob", min: "rep" }, { en: "lobe", min: "repo" }, { en: "locale", min: "rekaro" }, { en: "localize", min: "rekaruso" }, { en: "locate", min: "rekado" }, { en: "locavore", min: "rekafelo" }, { en: "loci", min: "reku" }, { en: "lock", min: "rekc" }, { en: "locket", min: "rekcod" }, { en: "lockjaw", min: "rekcqaw" },
  { en: "lockout", min: "rekceid" }, { en: "lockstep", min: "rekczdob" }, { en: "lockup", min: "rekcib" }, { en: "loco", min: "reke" }, { en: "locust", min: "rekizd" }, { en: "lode", min: "reto" }, { en: "lodestone", min: "retozdemo" }, { en: "loft", min: "revd" }, { en: "log", min: "reg" }, { en: "logarithm", min: "regaludhn" },
  { en: "logbook", min: "regpeec" }, { en: "loge", min: "rego" }, { en: "loggerhead", min: "reggolhoat" }, { en: "logician", min: "regukuam" }, { en: "login", min: "regum" }, { en: "logjam", min: "regqan" }, { en: "logo", min: "rege" }, { en: "logoff", min: "regevv" }, { en: "logon", min: "regem" }, { en: "logotype", min: "regedybo" },
  { en: "logout", min: "regeid" }, { en: "loin", min: "reum" }, { en: "lolcat", min: "rerkad" }, { en: "loll", min: "rerr" }, { en: "lollipop", min: "rerrubeb" }, { en: "lollygag", min: "rerrygag" }, { en: "lollypop", min: "rerrybeb" }, { en: "lone", min: "remo" }, { en: "lonesome", min: "remozeno" }, { en: "longboat", min: "remgpead" },
  { en: "longhair", min: "remghaul" }, { en: "longhand", min: "remghamt" }, { en: "longhorn", min: "remghelm" }, { en: "longitude", min: "remgudito" }, { en: "longtime", min: "remgduno" }, { en: "loofah", min: "reevah" }, { en: "lookalike", min: "reecaruco" }, { en: "lookout", min: "reeceid" }, { en: "lookup", min: "reecib" }, { en: "loom", min: "reen" },
  { en: "loon", min: "reem" }, { en: "loonie", min: "reemuo" }, { en: "loop", min: "reeb" }, { en: "loophole", min: "reebhero" }, { en: "loose", min: "reezo" }, { en: "loosen", min: "reezom" }, { en: "loot", min: "reed" }, { en: "lop", min: "reb" }, { en: "lope", min: "rebo" }, { en: "lore", min: "relo" },
  { en: "lorgnette", min: "relgmoddo" }, { en: "lorn", min: "relm" }, { en: "lose", min: "rezo" }, { en: "lost", min: "rezd" }, { en: "lotto", min: "redde" }, { en: "loud", min: "reit" }, { en: "lounge", min: "reimgo" }, { en: "louse", min: "reizo" }, { en: "lout", min: "reid" }, { en: "lovebird", min: "refopult" },
  { en: "lovelorn", min: "reforelm" }, { en: "lovesick", min: "refozukc" }, { en: "low", min: "rew" }, { en: "lowbrow", min: "rewplew" }, { en: "lowdown", min: "rewtewm" }, { en: "lowercase", min: "rewolkazo" }, { en: "lowland", min: "rewramt" }, { en: "lox", min: "rex" }, { en: "lozenge", min: "resomgo" }, { en: "luau", min: "riai" },
  { en: "lube", min: "ripo" }, { en: "lubricant", min: "riplukamd" }, { en: "lubricate", min: "riplukado" }, { en: "lubricator", min: "riplukadel" }, { en: "lucid", min: "rikut" }, { en: "luck", min: "rikc" }, { en: "lucre", min: "riklo" }, { en: "lug", min: "rig" }, { en: "luggage", min: "riggago" }, { en: "lukewarm", min: "ricowaln" },
  { en: "lull", min: "rirr" }, { en: "lumbago", min: "rinpage" }, { en: "lumberjack", min: "rinpolqakc" }, { en: "lumberman", min: "rinpolnam" }, { en: "lumbermen", min: "rinpolnom" }, { en: "lumberyard", min: "rinpolyalt" }, { en: "lummox", min: "rinnex" }, { en: "lump", min: "rinb" }, { en: "lunchbox", min: "rimkhpex" }, { en: "luncheon", min: "rimkhoem" },
  { en: "lunchroom", min: "rimkhleen" }, { en: "lunchtime", min: "rimkhduno" }, { en: "lung", min: "rimg" }, { en: "lunge", min: "rimgo" }, { en: "lupin", min: "ribum" }, { en: "lupine", min: "ribumo" }, { en: "lurch", min: "rilkh" }, { en: "lure", min: "rilo" }, { en: "lurid", min: "rilut" }, { en: "lurk", min: "rilc" },
  { en: "lush", min: "rizh" }, { en: "lust", min: "rizd" }, { en: "lustre", min: "rizdlo" }, { en: "lute", min: "rido" }, { en: "luxuriance", min: "rixiluamko" }, { en: "luxuriant", min: "rixiluamd" }, { en: "luxuriate", min: "rixiluado" }, { en: "lvi", min: "rfu" }, { en: "lvii", min: "rfuu" }, { en: "lxi", min: "rxu" },
  { en: "lxii", min: "rxuu" }, { en: "lxiv", min: "rxuf" }, { en: "lxix", min: "rxux" }, { en: "lxvi", min: "rxfu" }, { en: "lxvii", min: "rxfuu" }, { en: "lyceum", min: "rykoin" }, { en: "lychee", min: "rykhoo" }, { en: "lye", min: "ryo" }, { en: "lymph", min: "rynbh" }, { en: "lymphoma", min: "rynbhena" },
];
