/**
 * @file Contains dictionary entries for category: places_geo.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const places_geo: DictionaryEntry[] = [
  { en: "country", min: "pais" }, { en: "city", min: "ciudad" }, { en: "world", min: "mundo" }, { en: "state", min: "estado" }, { en: "town", min: "pueblo" }, { en: "khz", min: "chs" }, { en: "kabob", min: "capep" }, { en: "kaboom", min: "capeen" }, { en: "kaftan", min: "cavdam" }, { en: "kahuna", min: "cahima" },
  { en: "kale", min: "caro" }, { en: "kamikaze", min: "canucaso" }, { en: "kangaroo", min: "camgalee" }, { en: "kaolin", min: "caerum" }, { en: "kapok", min: "cabec" }, { en: "kaput", min: "cabid" }, { en: "karakul", min: "calacir" }, { en: "karaoke", min: "calaeco" }, { en: "karat", min: "calad" }, { en: "karate", min: "calado" },
  { en: "karma", min: "calna" }, { en: "katydid", min: "cadytut" }, { en: "kayak", min: "cayac" }, { en: "kazoo", min: "casee" }, { en: "kebab", min: "copap" }, { en: "kebob", min: "copep" }, { en: "keel", min: "coor" }, { en: "keen", min: "coom" }, { en: "keep", min: "coob" }, { en: "keepsake", min: "coobzaco" },
  { en: "keg", min: "cog" }, { en: "kelp", min: "corb" }, { en: "kennel", min: "commor" }, { en: "kept", min: "cobd" }, { en: "keratin", min: "coladum" }, { en: "kerchief", min: "colkhuov" }, { en: "kernel", min: "colmor" }, { en: "kerosene", min: "colezomo" }, { en: "kerosine", min: "colezumo" }, { en: "kestrel", min: "cozdlor" },
  { en: "ketch", min: "codkh" }, { en: "ketchup", min: "codkhib" }, { en: "keto", min: "code" }, { en: "kettle", min: "coddro" }, { en: "kettledrum", min: "coddrotlin" }, { en: "keyboard", min: "coypealt" }, { en: "keyhole", min: "coyhero" }, { en: "keynote", min: "coymedo" }, { en: "keypunch", min: "coybimkh" }, { en: "keystone", min: "coyzdemo" },
  { en: "keystroke", min: "coyzdleco" }, { en: "keyword", min: "coywelt" }, { en: "khaki", min: "chacu" }, { en: "kibbutz", min: "cuppids" }, { en: "kibbutzim", min: "cuppidsun" }, { en: "kibitz", min: "cupuds" }, { en: "kibosh", min: "cupezh" }, { en: "kick", min: "cukc" }, { en: "kickback", min: "cukcpakc" }, { en: "kickoff", min: "cukcevv" },
  { en: "kickstand", min: "cukczdamt" }, { en: "kid", min: "cut" }, { en: "kiddie", min: "cuttuo" }, { en: "kiddo", min: "cutte" }, { en: "kidnap", min: "cutmab" }, { en: "kielbasa", min: "cuorpaza" }, { en: "kill", min: "curr" }, { en: "kiln", min: "curm" }, { en: "kilo", min: "cure" }, { en: "kilobyte", min: "curepydo" },
  { en: "kilocycle", min: "curekykro" }, { en: "kilogram", min: "cureglan" }, { en: "kilohertz", min: "cureholds" }, { en: "kiloton", min: "curedem" }, { en: "kilowatt", min: "curewadd" }, { en: "kilt", min: "curd" }, { en: "kimono", min: "cuneme" }, { en: "kin", min: "cum" }, { en: "kind", min: "cumt" }, { en: "kinda", min: "cumta" },
  { en: "kindle", min: "cumtro" }, { en: "kinfolk", min: "cumverc" }, { en: "kingpin", min: "cumgbum" }, { en: "kink", min: "cumc" }, { en: "kinsman", min: "cumznam" }, { en: "kinsmen", min: "cumznom" }, { en: "kinswoman", min: "cumzwenam" }, { en: "kinswomen", min: "cumzwenom" }, { en: "kiosk", min: "cuezc" }, { en: "kismet", min: "cuznod" },
  { en: "kite", min: "cudo" }, { en: "kitsch", min: "cudzkh" }, { en: "kitten", min: "cuddom" }, { en: "kiwi", min: "cuwu" }, { en: "kludge", min: "critgo" }, { en: "kluge", min: "crigo" }, { en: "klutz", min: "crids" }, { en: "knack", min: "cmakc" }, { en: "knackwurst", min: "cmakcwilzd" }, { en: "knapsack", min: "cmabzakc" },
  { en: "knave", min: "cmafo" }, { en: "knead", min: "cmoat" }, { en: "knee", min: "cmoo" }, { en: "kneecap", min: "cmookab" }, { en: "kneel", min: "cmoor" }, { en: "knell", min: "cmorr" }, { en: "knelt", min: "cmord" }, { en: "knew", min: "cmow" }, { en: "knickknack", min: "cmukccmakc" }, { en: "knife", min: "cmuvo" },
  { en: "knit", min: "cmud" }, { en: "knob", min: "cmep" }, { en: "knock", min: "cmekc" }, { en: "knockout", min: "cmekceid" }, { en: "knockwurst", min: "cmekcwilzd" }, { en: "knoll", min: "cmerr" }, { en: "knot", min: "cmed" }, { en: "knothole", min: "cmedhero" }, { en: "knowledge", min: "cmewrotgo" }, { en: "known", min: "cmewm" },
  { en: "knuckle", min: "cmikcro" }, { en: "koala", min: "ceara" }, { en: "koan", min: "ceam" }, { en: "kohlrabi", min: "cehrlapu" }, { en: "kook", min: "ceec" }, { en: "kookaburra", min: "ceecapilla" }, { en: "kookie", min: "ceecuo" }, { en: "kopeck", min: "cebokc" }, { en: "kopek", min: "ceboc" }, { en: "kowtow", min: "cewdew" },
  { en: "krone", min: "clemo" }, { en: "kronor", min: "clemel" }, { en: "krypton", min: "clybdem" }, { en: "kudzu", min: "citsi" }, { en: "kumquat", min: "cinjiad" }, { en: "lab", min: "rap" }, { en: "label", min: "rapor" }, { en: "labia", min: "rapua" }, { en: "labium", min: "rapuin" }, { en: "labor", min: "rapel" },
  { en: "laburnum", min: "rapilmin" }, { en: "lace", min: "rako" }, { en: "lacerate", min: "rakolado" }, { en: "lachrymose", min: "rakhlynezo" }, { en: "lack", min: "rakc" }, { en: "lacrosse", min: "raklezzo" }, { en: "lactate", min: "rakdado" }, { en: "lactose", min: "rakdezo" }, { en: "lacuna", min: "rakima" }, { en: "lacunae", min: "rakimao" },
  { en: "lad", min: "rat" }, { en: "laddie", min: "rattuo" }, { en: "lade", min: "rato" }, { en: "laden", min: "ratom" }, { en: "ladle", min: "ratro" }, { en: "ladybird", min: "ratypult" }, { en: "ladybug", min: "ratypig" }, { en: "ladylike", min: "ratyruco" }, { en: "lag", min: "rag" }, { en: "laggard", min: "raggalt" },
  { en: "lagniappe", min: "ragmuabbo" }, { en: "lagoon", min: "rageem" }, { en: "laid", min: "raut" }, { en: "lain", min: "raum" }, { en: "lair", min: "raul" }, { en: "lake", min: "raco" }, { en: "lallygag", min: "rarrygag" }, { en: "lam", min: "ran" }, { en: "lama", min: "rana" }, { en: "lambast", min: "ranpazd" },
  { en: "lambaste", min: "ranpazdo" }, { en: "lambda", min: "ranpta" }, { en: "lambent", min: "ranpomd" }, { en: "lambkin", min: "ranpcum" }, { en: "lambskin", min: "ranpzcum" }, { en: "lame", min: "rano" }, { en: "lamebrain", min: "ranoplaum" }, { en: "laminate", min: "ranumado" }, { en: "lampblack", min: "ranbprakc" }, { en: "lampoon", min: "ranbeem" },
  { en: "lamppost", min: "ranbbezd" }, { en: "lampshade", min: "ranbzhato" }, { en: "lancet", min: "ramkod" }, { en: "landfall", min: "ramtvarr" }, { en: "landfill", min: "ramtvurr" }, { en: "landline", min: "ramtrumo" }, { en: "landlord", min: "ramtrelt" }, { en: "landmark", min: "ramtnalc" }, { en: "landscape", min: "ramtzkabo" }, { en: "landslid", min: "ramtzrut" },
  { en: "landslide", min: "ramtzruto" }, { en: "language", min: "ramgiago" }, { en: "languid", min: "ramgiut" }, { en: "languor", min: "ramgiel" }, { en: "lank", min: "ramc" }, { en: "lanolin", min: "ramerum" }, { en: "lantern", min: "ramdolm" }, { en: "lanyard", min: "ramyalt" }, { en: "lap", min: "rab" }, { en: "lapel", min: "rabor" },
  { en: "lapse", min: "rabzo" }, { en: "laptop", min: "rabdeb" }, { en: "larboard", min: "ralpealt" }, { en: "larch", min: "ralkh" }, { en: "lard", min: "ralt" }, { en: "large", min: "ralgo" }, { en: "largesse", min: "ralgozzo" }, { en: "largo", min: "ralge" }, { en: "lariat", min: "raluad" }, { en: "larkspur", min: "ralczbil" },
  { en: "larva", min: "ralfa" }, { en: "larvae", min: "ralfao" }, { en: "larynx", min: "ralymx" }, { en: "lasagna", min: "razagma" }, { en: "lasagne", min: "razagmo" }, { en: "lase", min: "razo" }, { en: "lash", min: "razh" }, { en: "lassitude", min: "razzudito" }, { en: "lasso", min: "razze" }, { en: "last", min: "razd" },
  { en: "lat", min: "rad" }, { en: "latch", min: "radkh" }, { en: "late", min: "rado" }, { en: "latent", min: "radomd" }, { en: "latex", min: "radox" }, { en: "lathe", min: "radho" }, { en: "latitude", min: "radudito" }, { en: "latrine", min: "radlumo" }, { en: "latte", min: "raddo" }, { en: "lattice", min: "radduko" },
  { en: "laudanum", min: "raitamin" }, { en: "laugh", min: "raigh" }, { en: "launch", min: "raimkh" }, { en: "laundryman", min: "raimtlynam" }, { en: "laundrymen", min: "raimtlynom" }, { en: "laureate", min: "railoado" }, { en: "lava", min: "rafa" }, { en: "law", min: "raw" }, { en: "lawn", min: "rawm" }, { en: "lawrencium", min: "rawlomkuin" },
  { en: "lawsuit", min: "rawziud" }, { en: "lax", min: "rax" }, { en: "layette", min: "rayoddo" }, { en: "layman", min: "raynam" }, { en: "laymen", min: "raynom" }, { en: "layoff", min: "rayevv" }, { en: "layout", min: "rayeid" }, { en: "laypeople", min: "rayboebro" }, { en: "layperson", min: "raybolzem" }, { en: "laywoman", min: "raywenam" },
  { en: "laywomen", min: "raywenom" }, { en: "laze", min: "raso" }, { en: "lead", min: "roat" }, { en: "leaden", min: "roatom" }, { en: "leaflet", min: "roavrod" }, { en: "league", min: "roagio" }, { en: "leak", min: "roac" }, { en: "leakage", min: "roacago" }, { en: "leap", min: "roab" }, { en: "leapfrog", min: "roabvleg" },
  { en: "leapt", min: "roabd" }, { en: "learn", min: "roalm" }, { en: "learnt", min: "roalmd" }, { en: "lease", min: "roazo" }, { en: "leasehold", min: "roazohert" }, { en: "leash", min: "roazh" }, { en: "least", min: "roazd" }, { en: "leave", min: "roafo" }, { en: "leaven", min: "roafom" }, { en: "lecithin", min: "rokudhum" },
  { en: "lectern", min: "rokdolm" }, { en: "lecture", min: "rokdilo" }, { en: "ledge", min: "rotgo" }, { en: "leech", min: "rookh" }, { en: "leek", min: "rooc" }, { en: "leftie", min: "rovduo" }, { en: "leftmost", min: "rovdnezd" }, { en: "legalese", min: "rogarozo" }, { en: "legalize", min: "rogaruso" }, { en: "legate", min: "rogado" },
  { en: "legatee", min: "rogadoo" }, { en: "legato", min: "rogade" }, { en: "legend", min: "rogomt" }, { en: "leggin", min: "roggum" }, { en: "legion", min: "roguem" }, { en: "legislate", min: "roguzrado" }, { en: "legislator", min: "roguzradel" }, { en: "legit", min: "rogud" }, { en: "legitimate", min: "rogudunado" }, { en: "legitimize", min: "rogudunuso" },
  { en: "legman", min: "rognam" }, { en: "legmen", min: "rognom" }, { en: "legroom", min: "rogleen" }, { en: "legume", min: "rogino" }, { en: "legwork", min: "rogwelc" }, { en: "lei", min: "rou" }, { en: "leisure", min: "rouzilo" }, { en: "leitmotif", min: "roudneduv" }, { en: "lemma", min: "ronna" }, { en: "lemme", min: "ronno" },
];
