/**
 * @file Contains dictionary entries for category: pronouns.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const pronouns: DictionaryEntry[] = [
  { en: "i", min: "me" }, { en: "you", min: "tu" }, { en: "we", min: "bee" }, { en: "they", min: "bu" }, { en: "she", min: "la" }, { en: "arequipa", min: "alojiuba" }, { en: "argentine", min: "algomdumo" }, { en: "argo", min: "alge" }, { en: "argonaut", min: "algemaid" }, { en: "argonne", min: "algemmo" },
  { en: "ariosto", min: "aluezde" }, { en: "aristotle", min: "aluzdedro" }, { en: "ariz", min: "alus" }, { en: "arizona", min: "alusema" }, { en: "arizonan", min: "alusemam" }, { en: "arizonian", min: "alusemuam" }, { en: "arjuna", min: "alqima" }, { en: "ark", min: "alc" }, { en: "arkansan", min: "alcamzam" }, { en: "arkwright", min: "alcwlughd" },
  { en: "arlington", min: "alrumgdem" }, { en: "armageddon", min: "alnagottem" }, { en: "armagnac", min: "alnagmak" }, { en: "armand", min: "alnamt" }, { en: "armando", min: "alnamte" }, { en: "armani", min: "alnamu" }, { en: "armenian", min: "alnomuam" }, { en: "armonk", min: "alnemc" }, { en: "armour", min: "alneil" }, { en: "armstrong", min: "alnzdlemg" },
  { en: "arneb", min: "almop" }, { en: "arnhem", min: "almhon" }, { en: "arno", min: "alme" }, { en: "arnold", min: "almert" }, { en: "arnulfo", min: "almirve" }, { en: "aron", min: "alem" }, { en: "arron", min: "allem" }, { en: "art", min: "ald" }, { en: "arthur", min: "aldhil" }, { en: "arthurian", min: "aldhiluam" },
  { en: "artie", min: "alduo" }, { en: "arturo", min: "aldile" }, { en: "aryan", min: "alyam" }, { en: "asama", min: "azana" }, { en: "ascella", min: "azkorra" }, { en: "asgard", min: "azgalt" }, { en: "ashanti", min: "azhamdu" }, { en: "ashcroft", min: "azhklevd" }, { en: "ashe", min: "azho" }, { en: "asheville", min: "azhofurro" },
  { en: "ashikaga", min: "azhucaga" }, { en: "ashkenazim", min: "azhcomasun" }, { en: "ashkhabad", min: "azhchapat" }, { en: "ashmolean", min: "azhneroam" }, { en: "asiago", min: "azuage" }, { en: "asian", min: "azuam" }, { en: "asimov", min: "azunef" }, { en: "asoka", min: "azeca" }, { en: "aspell", min: "azborr" }, { en: "aspen", min: "azbom" },
  { en: "aspidiske", min: "azbutuzco" }, { en: "assad", min: "azzat" }, { en: "assam", min: "azzan" }, { en: "assamese", min: "azzanozo" }, { en: "assisi", min: "azzuzu" }, { en: "assyria", min: "azzylua" }, { en: "assyrian", min: "azzyluam" }, { en: "astaire", min: "azdaulo" }, { en: "astarte", min: "azdaldo" }, { en: "aston", min: "azdem" },
  { en: "astor", min: "azdel" }, { en: "astoria", min: "azdelua" }, { en: "astrakhan", min: "azdlacham" }, { en: "astroturf", min: "azdledilv" }, { en: "aswan", min: "azwam" }, { en: "atacama", min: "adakana" }, { en: "atahualpa", min: "adahiarba" }, { en: "atari", min: "adalu" }, { en: "atascadero", min: "adazkatole" }, { en: "athabasca", min: "adhapazka" },
  { en: "athabascan", min: "adhapazkam" }, { en: "athenian", min: "adhomuam" }, { en: "atkinson", min: "adcumzem" }, { en: "atman", min: "adnam" }, { en: "atria", min: "adlua" }, { en: "attica", min: "adduka" }, { en: "attila", min: "addura" }, { en: "attlee", min: "addroo" }, { en: "atwood", min: "adweet" }, { en: "auburn", min: "aipilm" },
  { en: "auckland", min: "aikcramt" }, { en: "auden", min: "aitom" }, { en: "audion", min: "aituem" }, { en: "audubon", min: "aitipem" }, { en: "aug", min: "aig" }, { en: "augean", min: "aigoam" }, { en: "augsburg", min: "aigzpilg" }, { en: "augustan", min: "aigizdam" }, { en: "aurangzeb", min: "ailamgsop" }, { en: "aurelio", min: "ailorue" },
  { en: "aureomycin", min: "ailoenykum" }, { en: "auriga", min: "ailuga" }, { en: "auschwitz", min: "aizkhwuds" }, { en: "aussie", min: "aizzuo" }, { en: "austen", min: "aizdom" }, { en: "austerlitz", min: "aizdolruds" }, { en: "australian", min: "aizdlaruam" }, { en: "australoid", min: "aizdlareut" }, { en: "austrian", min: "aizdluam" }, { en: "autumn", min: "aidinm" },
  { en: "avalon", min: "afarem" }, { en: "ave", min: "afo" }, { en: "aventine", min: "afomdumo" }, { en: "avesta", min: "afozda" }, { en: "avicenna", min: "afukomma" }, { en: "avignon", min: "afugmem" }, { en: "avila", min: "afura" }, { en: "avior", min: "afuel" }, { en: "avogadro", min: "afegatle" }, { en: "avon", min: "afem" },
  { en: "avondale", min: "afemtaro" }, { en: "axum", min: "axin" }, { en: "ayala", min: "ayara" }, { en: "aymara", min: "aynala" }, { en: "ayrshire", min: "aylzhulo" }, { en: "ayurveda", min: "ayilfota" }, { en: "ayyubid", min: "ayyiput" }, { en: "azana", min: "asama" }, { en: "azania", min: "asamua" }, { en: "azazel", min: "asasor" },
  { en: "azov", min: "asef" }, { en: "aztec", min: "asdok" }, { en: "aztecan", min: "asdokam" }, { en: "aztlan", min: "asdram" }, { en: "bbb", min: "ppp" }, { en: "bbc", min: "ppk" }, { en: "bbq", min: "ppj" }, { en: "bff", min: "pvv" }, { en: "bitnet", min: "pudmod" }, { en: "blt", min: "prd" },
  { en: "bsd", min: "pzt" }, { en: "btu", min: "pdi" }, { en: "btw", min: "pdw" }, { en: "byob", min: "pyep" }, { en: "babbage", min: "pappago" }, { en: "babbitt", min: "pappudd" }, { en: "babel", min: "papor" }, { en: "babur", min: "papil" }, { en: "babylon", min: "papyrem" }, { en: "babylonian", min: "papyremuam" },
  { en: "bacall", min: "pakarr" }, { en: "bacardi", min: "pakaltu" }, { en: "bach", min: "pakh" }, { en: "bacon", min: "pakem" }, { en: "bactria", min: "pakdlua" }, { en: "baden", min: "patom" }, { en: "baez", min: "paos" }, { en: "baffin", min: "pavvum" }, { en: "baguio", min: "pagiue" }, { en: "bahama", min: "pahana" },
  { en: "bahamian", min: "pahanuam" }, { en: "bahia", min: "pahua" }, { en: "baidu", min: "pauti" }, { en: "baird", min: "pault" }, { en: "bakelite", min: "pacorudo" }, { en: "bakunin", min: "pacimum" }, { en: "balanchine", min: "paramkhumo" }, { en: "balaton", min: "paradem" }, { en: "balboa", min: "parpea" }, { en: "baldwin", min: "partwum" },
  { en: "balfour", min: "parveil" }, { en: "bali", min: "paru" }, { en: "balinese", min: "parumozo" }, { en: "balkan", min: "parcam" }, { en: "balkhash", min: "parchazh" }, { en: "ball", min: "parr" }, { en: "ballard", min: "parralt" }, { en: "baltimore", min: "pardunelo" }, { en: "balzac", min: "parsak" }, { en: "banach", min: "pamakh" },
  { en: "bancroft", min: "pamklevd" }, { en: "bandung", min: "pamtimg" }, { en: "bangalore", min: "pamgarelo" }, { en: "bangor", min: "pamgel" }, { en: "bantu", min: "pamdi" }, { en: "baotou", min: "paedei" }, { en: "baptiste", min: "pabduzdo" }, { en: "barack", min: "palakc" }, { en: "barbadian", min: "palpatuam" }, { en: "barbarella", min: "palpalorra" },
  { en: "barbarossa", min: "palpalezza" }, { en: "barbour", min: "palpeil" }, { en: "barcelona", min: "palkorema" }, { en: "bardeen", min: "paltoom" }, { en: "barlow", min: "palrew" }, { en: "barnard", min: "palmalt" }, { en: "barnaul", min: "palmair" }, { en: "barnett", min: "palmodd" }, { en: "barnum", min: "palmin" }, { en: "baroda", min: "paleta" },
  { en: "barr", min: "pall" }, { en: "barrera", min: "pallola" }, { en: "barrett", min: "pallodd" }, { en: "barron", min: "pallem" }, { en: "barrymore", min: "pallynelo" }, { en: "bart", min: "pald" }, { en: "bartholdi", min: "paldhertu" }, { en: "bartlett", min: "paldrodd" }, { en: "barton", min: "paldem" }, { en: "baruch", min: "palikh" },
  { en: "basel", min: "pazor" }, { en: "basho", min: "pazhe" }, { en: "basie", min: "pazuo" }, { en: "basil", min: "pazur" }, { en: "basque", min: "pazjio" }, { en: "basra", min: "pazla" }, { en: "bastille", min: "pazdurro" }, { en: "bataan", min: "padaam" }, { en: "batista", min: "paduzda" }, { en: "batman", min: "padnam" },
  { en: "battle", min: "paddro" }, { en: "batu", min: "padi" }, { en: "baudelaire", min: "paitoraulo" }, { en: "baudouin", min: "paiteium" }, { en: "baum", min: "pain" }, { en: "bavaria", min: "pafalua" }, { en: "bavarian", min: "pafaluam" }, { en: "bayesian", min: "payozuam" }, { en: "bayeux", min: "payoix" }, { en: "baylor", min: "payrel" },
  { en: "bayonne", min: "payemmo" }, { en: "baywatch", min: "paywadkh" }, { en: "beach", min: "poakh" }, { en: "beadle", min: "poatro" }, { en: "bean", min: "poam" }, { en: "beard", min: "poalt" }, { en: "beardmore", min: "poaltnelo" }, { en: "bearnaise", min: "poalmauzo" }, { en: "beau", min: "poai" }, { en: "beaufort", min: "poaiveld" },
  { en: "beaumont", min: "poainemd" }, { en: "beauregard", min: "poailogalt" }, { en: "beauvoir", min: "poaifeul" }, { en: "bechtel", min: "pokhdor" }, { en: "beck", min: "pokc" }, { en: "becket", min: "pokcod" }, { en: "beckett", min: "pokcodd" }, { en: "becquerel", min: "pokjiolor" }, { en: "bede", min: "poto" }, { en: "bedouin", min: "poteium" },
  { en: "beebe", min: "poopo" }, { en: "beefaroni", min: "poovalemu" }, { en: "beelzebub", min: "poorsopip" }, { en: "beerbohm", min: "poolpehn" }, { en: "beethoven", min: "poodhefom" }, { en: "beeton", min: "poodem" }, { en: "begin", min: "pogum" }, { en: "behan", min: "poham" }, { en: "bela", min: "pora" }, { en: "belau", min: "porai" },
  { en: "belem", min: "poron" }, { en: "belgian", min: "porguam" }, { en: "bellatrix", min: "porradlux" }, { en: "belleek", min: "porrooc" }, { en: "bellingham", min: "porrumghan" }, { en: "bellini", min: "porrumu" }, { en: "bellow", min: "porrew" }, { en: "belmont", min: "pornemd" }, { en: "beloit", min: "poreud" }, { en: "beltane", min: "pordamo" },
  { en: "belushi", min: "porizhu" }, { en: "ben", min: "pom" }, { en: "benacerraf", min: "pomakollav" }, { en: "bend", min: "pomt" }, { en: "bendix", min: "pomtux" }, { en: "benedict", min: "pomotukd" }, { en: "benelux", min: "pomorix" }, { en: "benet", min: "pomod" }, { en: "benetton", min: "pomoddem" }, { en: "benghazi", min: "pomghasu" },
  { en: "benito", min: "pomude" }, { en: "benjamin", min: "pomqanum" }, { en: "bennett", min: "pommodd" }, { en: "benson", min: "pomzem" }, { en: "bentham", min: "pomdhan" }, { en: "benton", min: "pomdem" }, { en: "benz", min: "poms" }, { en: "benzedrine", min: "pomsotlumo" }, { en: "beowulf", min: "poewirv" }, { en: "beretta", min: "polodda" },
  { en: "berg", min: "polg" }, { en: "bergen", min: "polgom" }, { en: "bergerac", min: "polgolak" }, { en: "bergman", min: "polgnam" }, { en: "bergson", min: "polgzem" }, { en: "beria", min: "polua" }, { en: "berkshire", min: "polczhulo" }, { en: "berle", min: "polro" }, { en: "berlioz", min: "polrues" }, { en: "berlitz", min: "polruds" },
];
