/**
 * @file Contains dictionary entries for category: time_relative.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const time_relative: DictionaryEntry[] = [
  { en: "today", min: "detay" }, { en: "tomorrow", min: "manana" }, { en: "yesterday", min: "ayer" }, { en: "night", min: "noche" }, { en: "morning", min: "dia" }, { en: "grim", min: "glun" }, { en: "grimace", min: "glunako" }, { en: "grime", min: "gluno" }, { en: "grin", min: "glum" }, { en: "grind", min: "glumt" },
  { en: "grindstone", min: "glumtzdemo" }, { en: "gringo", min: "glumge" }, { en: "grip", min: "glub" }, { en: "gripe", min: "glubo" }, { en: "grippe", min: "glubbo" }, { en: "gristle", min: "gluzdro" }, { en: "grit", min: "glud" }, { en: "groan", min: "gleam" }, { en: "grog", min: "gleg" }, { en: "groin", min: "gleum" },
  { en: "grok", min: "glec" }, { en: "grommet", min: "glennod" }, { en: "groom", min: "gleen" }, { en: "groove", min: "gleefo" }, { en: "grope", min: "glebo" }, { en: "grosbeak", min: "glezpoac" }, { en: "grotesque", min: "gledozjio" }, { en: "grotto", min: "gledde" }, { en: "grouch", min: "gleikh" }, { en: "ground", min: "gleimt" },
  { en: "groundhog", min: "gleimtheg" }, { en: "groundwork", min: "gleimtwelc" }, { en: "group", min: "gleib" }, { en: "groupie", min: "gleibuo" }, { en: "grouse", min: "gleizo" }, { en: "grout", min: "gleid" }, { en: "grove", min: "glefo" }, { en: "grovel", min: "glefor" }, { en: "grow", min: "glew" }, { en: "growl", min: "glewr" },
  { en: "grown", min: "glewm" }, { en: "grownup", min: "glewmib" }, { en: "grub", min: "glip" }, { en: "grubstake", min: "glipzdaco" }, { en: "grudge", min: "glitgo" }, { en: "grue", min: "glio" }, { en: "gruel", min: "glior" }, { en: "gruesome", min: "gliozeno" }, { en: "gruff", min: "glivv" }, { en: "grumble", min: "glinpro" },
  { en: "grunge", min: "glimgo" }, { en: "grunt", min: "glimd" }, { en: "gryphon", min: "glybhem" }, { en: "guacamole", min: "giakanero" }, { en: "guano", min: "giame" }, { en: "guarantee", min: "gialamdoo" }, { en: "guarantor", min: "gialamdel" }, { en: "guard", min: "gialt" }, { en: "guardhouse", min: "gialtheizo" }, { en: "guardian", min: "gialtuam" },
  { en: "guardrail", min: "gialtlaur" }, { en: "guardroom", min: "gialtleen" }, { en: "guardsman", min: "gialtznam" }, { en: "guardsmen", min: "gialtznom" }, { en: "guava", min: "giafa" }, { en: "guerilla", min: "giolurra" }, { en: "guerrilla", min: "giollurra" }, { en: "guesswork", min: "giozzwelc" }, { en: "guff", min: "givv" }, { en: "guffaw", min: "givvaw" },
  { en: "guidance", min: "giutamko" }, { en: "guide", min: "giuto" }, { en: "guidebook", min: "giutopeec" }, { en: "guideline", min: "giutorumo" }, { en: "guild", min: "giurt" }, { en: "guile", min: "giuro" }, { en: "guillotine", min: "giurredumo" }, { en: "guilt", min: "giurd" }, { en: "guise", min: "giuzo" }, { en: "gulag", min: "girag" },
  { en: "gulch", min: "girkh" }, { en: "gulf", min: "girv" }, { en: "gull", min: "girr" }, { en: "gullet", min: "girrod" }, { en: "gulp", min: "girb" }, { en: "gum", min: "gin" }, { en: "gumbo", min: "ginpe" }, { en: "gumdrop", min: "gintleb" }, { en: "gun", min: "gim" }, { en: "gunboat", min: "gimpead" },
  { en: "gunfight", min: "gimvughd" }, { en: "gunfire", min: "gimvulo" }, { en: "gunk", min: "gimc" }, { en: "gunman", min: "gimnam" }, { en: "gunmen", min: "gimnom" }, { en: "gunnysack", min: "gimmyzakc" }, { en: "gunpoint", min: "gimbeumd" }, { en: "gunshot", min: "gimzhed" }, { en: "gunwale", min: "gimwaro" }, { en: "gurgle", min: "gilgro" },
  { en: "guru", min: "gili" }, { en: "gush", min: "gizh" }, { en: "gusset", min: "gizzod" }, { en: "gust", min: "gizd" }, { en: "gusto", min: "gizde" }, { en: "gut", min: "gid" }, { en: "guzzle", min: "gissro" }, { en: "gybe", min: "gypo" }, { en: "gym", min: "gyn" }, { en: "gymnasia", min: "gynmazua" },
  { en: "gymnasium", min: "gynmazuin" }, { en: "gymnast", min: "gynmazd" }, { en: "gymnosperm", min: "gynmezboln" }, { en: "gyp", min: "gyb" }, { en: "gypsum", min: "gybzin" }, { en: "gyrate", min: "gylado" }, { en: "gyro", min: "gyle" }, { en: "habit", min: "hapud" }, { en: "habitat", min: "hapudad" }, { en: "habituate", min: "hapudiado" },
  { en: "hacienda", min: "hakuomta" }, { en: "hack", min: "hakc" }, { en: "hackle", min: "hakcro" }, { en: "hacksaw", min: "hakczaw" }, { en: "had", min: "hat" }, { en: "haddock", min: "hattekc" }, { en: "hafnium", min: "havmuin" }, { en: "haft", min: "havd" }, { en: "hag", min: "hag" }, { en: "haggard", min: "haggalt" },
  { en: "haggle", min: "haggro" }, { en: "hah", min: "hah" }, { en: "haiku", min: "hauci" }, { en: "hail", min: "haur" }, { en: "hailstone", min: "haurzdemo" }, { en: "hailstorm", min: "haurzdeln" }, { en: "hairball", min: "haulparr" }, { en: "hairbrush", min: "haulplizh" }, { en: "haircut", min: "haulkid" }, { en: "hairdo", min: "haulte" },
  { en: "hairline", min: "haulrumo" }, { en: "hairnet", min: "haulmod" }, { en: "hairpiece", min: "haulbuoko" }, { en: "hairpin", min: "haulbum" }, { en: "hairstyle", min: "haulzdyro" }, { en: "hake", min: "haco" }, { en: "halberd", min: "harpolt" }, { en: "halcyon", min: "harkyem" }, { en: "half", min: "harv" }, { en: "halfback", min: "harvpakc" },
  { en: "halfpence", min: "harvbomko" }, { en: "halftime", min: "harvduno" }, { en: "halibut", min: "harupid" }, { en: "halleluiah", min: "harroriuah" }, { en: "hallelujah", min: "harroriqah" }, { en: "hallow", min: "harrew" }, { en: "halo", min: "hare" }, { en: "halogen", min: "haregom" }, { en: "halt", min: "hard" }, { en: "halve", min: "harfo" },
  { en: "halyard", min: "haryalt" }, { en: "hammerhead", min: "hannolhoat" }, { en: "hammock", min: "hannekc" }, { en: "hamstrung", min: "hanzdlimg" }, { en: "handbag", min: "hamtpag" }, { en: "handball", min: "hamtparr" }, { en: "handbill", min: "hamtpurr" }, { en: "handbook", min: "hamtpeec" }, { en: "handcart", min: "hamtkald" }, { en: "handcraft", min: "hamtklavd" },
  { en: "handcuff", min: "hamtkivv" }, { en: "handgun", min: "hamtgim" }, { en: "handheld", min: "hamthort" }, { en: "handicap", min: "hamtukab" }, { en: "handicraft", min: "hamtuklavd" }, { en: "handiwork", min: "hamtuwelc" }, { en: "handle", min: "hamtro" }, { en: "handmade", min: "hamtnato" }, { en: "handmaid", min: "hamtnaut" }, { en: "handmaiden", min: "hamtnautom" },
  { en: "handout", min: "hamteid" }, { en: "handpick", min: "hamtbukc" }, { en: "handrail", min: "hamtlaur" }, { en: "handset", min: "hamtzod" }, { en: "handshake", min: "hamtzhaco" }, { en: "handsome", min: "hamtzeno" }, { en: "handstand", min: "hamtzdamt" }, { en: "handwork", min: "hamtwelc" }, { en: "handyman", min: "hamtynam" }, { en: "handymen", min: "hamtynom" },
  { en: "hang", min: "hamg" }, { en: "hangdog", min: "hamgteg" }, { en: "hangman", min: "hamgnam" }, { en: "hangmen", min: "hamgnom" }, { en: "hangnail", min: "hamgmaur" }, { en: "hangout", min: "hamgeid" }, { en: "hankie", min: "hamcuo" }, { en: "hansom", min: "hamzen" }, { en: "haphazard", min: "habhasalt" }, { en: "happen", min: "habbom" },
  { en: "harangue", min: "halamgio" }, { en: "harbor", min: "halpel" }, { en: "hard", min: "halt" }, { en: "hardback", min: "haltpakc" }, { en: "hardball", min: "haltparr" }, { en: "harden", min: "haltom" }, { en: "hardline", min: "haltrumo" }, { en: "hardtack", min: "haltdakc" }, { en: "hardtop", min: "haltdeb" }, { en: "hardware", min: "haltwalo" },
  { en: "hardwood", min: "haltweet" }, { en: "hare", min: "halo" }, { en: "harelip", min: "halorub" }, { en: "harem", min: "halon" }, { en: "hark", min: "halc" }, { en: "harken", min: "halcom" }, { en: "harlot", min: "halred" }, { en: "harm", min: "haln" }, { en: "harmonica", min: "halnemuka" }, { en: "harmonize", min: "halnemuso" },
  { en: "harp", min: "halb" }, { en: "harpoon", min: "halbeem" }, { en: "harridan", min: "hallutam" }, { en: "harrow", min: "hallew" }, { en: "harsh", min: "halzh" }, { en: "hash", min: "hazh" }, { en: "hasheesh", min: "hazhoozh" }, { en: "hashtag", min: "hazhdag" }, { en: "hasp", min: "hazb" }, { en: "hassle", min: "hazzro" },
  { en: "hassock", min: "hazzekc" }, { en: "haste", min: "hazdo" }, { en: "hasten", min: "hazdom" }, { en: "hatch", min: "hadkh" }, { en: "hatchback", min: "hadkhpakc" }, { en: "hatchet", min: "hadkhod" }, { en: "hate", min: "hado" }, { en: "haul", min: "hair" }, { en: "haunch", min: "haimkh" }, { en: "haunt", min: "haimd" },
  { en: "hauteur", min: "haidoil" }, { en: "have", min: "hafo" }, { en: "haven", min: "hafom" }, { en: "haversack", min: "hafolzakc" }, { en: "havoc", min: "hafek" }, { en: "haw", min: "haw" }, { en: "hawk", min: "hawc" }, { en: "hawthorn", min: "hawdhelm" }, { en: "haycock", min: "haykekc" }, { en: "hayloft", min: "hayrevd" },
  { en: "haymow", min: "haynew" }, { en: "haystack", min: "hayzdakc" }, { en: "haywire", min: "haywulo" }, { en: "hazard", min: "hasalt" }, { en: "haze", min: "haso" }, { en: "hazelnut", min: "hasormid" }, { en: "hazmat", min: "hasnad" }, { en: "headache", min: "hoatakho" }, { en: "headband", min: "hoatpamt" }, { en: "headboard", min: "hoatpealt" },
  { en: "headfirst", min: "hoatvulzd" }, { en: "headland", min: "hoatramt" }, { en: "headlight", min: "hoatrughd" }, { en: "headline", min: "hoatrumo" }, { en: "headlock", min: "hoatrekc" }, { en: "headlong", min: "hoatremg" }, { en: "headphone", min: "hoatbhemo" }, { en: "headroom", min: "hoatleen" }, { en: "headset", min: "hoatzod" }, { en: "headstone", min: "hoatzdemo" },
  { en: "headstrong", min: "hoatzdlemg" }, { en: "headwind", min: "hoatwumt" }, { en: "headword", min: "hoatwelt" }, { en: "healthcare", min: "hoardhkalo" }, { en: "heap", min: "hoab" }, { en: "hearken", min: "hoalcom" }, { en: "hearse", min: "hoalzo" }, { en: "heartache", min: "hoaldakho" }, { en: "heartbeat", min: "hoaldpoad" }, { en: "heartbreak", min: "hoaldploac" },
  { en: "heartburn", min: "hoaldpilm" }, { en: "hearten", min: "hoaldom" }, { en: "heartfelt", min: "hoaldvord" }, { en: "heartland", min: "hoaldramt" }, { en: "heartsick", min: "hoaldzukc" }, { en: "heartthrob", min: "hoalddhlep" }, { en: "heat", min: "hoad" }, { en: "heathen", min: "hoadhom" }, { en: "heatstroke", min: "hoadzdleco" }, { en: "heave", min: "hoafo" },
  { en: "heaven", min: "hoafom" }, { en: "heavyset", min: "hoafyzod" }, { en: "heck", min: "hokc" }, { en: "heckle", min: "hokcro" }, { en: "hectare", min: "hokdalo" }, { en: "hedge", min: "hotgo" }, { en: "hedgehog", min: "hotgoheg" }, { en: "hedgerow", min: "hotgolew" }, { en: "heehaw", min: "hoohaw" }, { en: "heel", min: "hoor" },
];
