/**
 * @file Contains dictionary entries for category: time_days.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const time_days: DictionaryEntry[] = [
  { en: "monday", min: "luni" }, { en: "tuesday", min: "marti" }, { en: "wednesday", min: "mierco" }, { en: "thursday", min: "juevi" }, { en: "friday", min: "vierni" }, { en: "forearm", min: "veloaln" }, { en: "forebode", min: "velopeto" }, { en: "forecast", min: "velokazd" }, { en: "forecastle", min: "velokazdro" }, { en: "foreclose", min: "velokrezo" },
  { en: "forefeet", min: "velovood" }, { en: "forefoot", min: "veloveed" }, { en: "forefront", min: "velovlemd" }, { en: "forego", min: "veloge" }, { en: "foregone", min: "velogemo" }, { en: "foreground", min: "velogleimt" }, { en: "forehand", min: "velohamt" }, { en: "forehead", min: "velohoat" }, { en: "foreign", min: "velougm" }, { en: "foreleg", min: "velorog" },
  { en: "forelock", min: "velorekc" }, { en: "foremast", min: "velonazd" }, { en: "foremen", min: "velonom" }, { en: "foremost", min: "velonezd" }, { en: "forename", min: "velomano" }, { en: "forenoon", min: "velomeem" }, { en: "foreordain", min: "veloeltaum" }, { en: "foresail", min: "velozaur" }, { en: "foresaw", min: "velozaw" }, { en: "foresee", min: "velozoo" },
  { en: "foreseen", min: "velozoom" }, { en: "foreshadow", min: "velozhatew" }, { en: "foresight", min: "velozughd" }, { en: "foreskin", min: "velozcum" }, { en: "forestall", min: "velozdarr" }, { en: "foreswore", min: "velozwelo" }, { en: "foresworn", min: "velozwelm" }, { en: "foretaste", min: "velodazdo" }, { en: "foretell", min: "velodorr" }, { en: "foretold", min: "velodert" },
  { en: "forewarn", min: "velowalm" }, { en: "forewent", min: "velowomd" }, { en: "forewoman", min: "velowenam" }, { en: "forewomen", min: "velowenom" }, { en: "foreword", min: "velowelt" }, { en: "forfeit", min: "velvoud" }, { en: "forfeiture", min: "velvoudilo" }, { en: "forgave", min: "velgafo" }, { en: "forge", min: "velgo" }, { en: "forget", min: "velgod" },
  { en: "forgiven", min: "velgufom" }, { en: "forgo", min: "velge" }, { en: "forgone", min: "velgemo" }, { en: "forgot", min: "velged" }, { en: "forgotten", min: "velgeddom" }, { en: "fork", min: "velc" }, { en: "forklift", min: "velcruvd" }, { en: "forlorn", min: "velrelm" }, { en: "form", min: "veln" }, { en: "formalize", min: "velnaruso" },
  { en: "format", min: "velnad" }, { en: "formula", min: "velnira" }, { en: "formulae", min: "velnirao" }, { en: "formulate", min: "velnirado" }, { en: "fornicate", min: "velmukado" }, { en: "forsake", min: "velzaco" }, { en: "forsaken", min: "velzacom" }, { en: "forsook", min: "velzeec" }, { en: "forswore", min: "velzwelo" }, { en: "forsworn", min: "velzwelm" },
  { en: "forsythia", min: "velzydhua" }, { en: "fort", min: "veld" }, { en: "forte", min: "veldo" }, { en: "forthright", min: "veldhlughd" }, { en: "fortissimo", min: "velduzzune" }, { en: "fortitude", min: "veldudito" }, { en: "fortnight", min: "veldmughd" }, { en: "fortunate", min: "veldimado" }, { en: "fortune", min: "veldimo" }, { en: "forum", min: "velin" },
  { en: "forwent", min: "velwomd" }, { en: "fossil", min: "vezzur" }, { en: "fossilize", min: "vezzuruso" }, { en: "fought", min: "veighd" }, { en: "foul", min: "veir" }, { en: "found", min: "veimt" }, { en: "fount", min: "veimd" }, { en: "fountain", min: "veimdaum" }, { en: "fourfold", min: "veilvert" }, { en: "fourscore", min: "veilzkelo" },
  { en: "foursome", min: "veilzeno" }, { en: "foursquare", min: "veilzjialo" }, { en: "fourteen", min: "veildoom" }, { en: "fowl", min: "vewr" }, { en: "foxglove", min: "vexgrefo" }, { en: "foxhole", min: "vexhero" }, { en: "foxhound", min: "vexheimt" }, { en: "foxtrot", min: "vexdled" }, { en: "frack", min: "vlakc" }, { en: "fracture", min: "vlakdilo" },
  { en: "frag", min: "vlag" }, { en: "fragile", min: "vlaguro" }, { en: "fragrance", min: "vlaglamko" }, { en: "fragrant", min: "vlaglamd" }, { en: "frail", min: "vlaur" }, { en: "frame", min: "vlano" }, { en: "framework", min: "vlanowelc" }, { en: "franc", min: "vlamk" }, { en: "franchise", min: "vlamkhuzo" }, { en: "franchisee", min: "vlamkhuzoo" },
  { en: "frat", min: "vlad" }, { en: "fraternize", min: "vladolmuso" }, { en: "fratricide", min: "vladlukuto" }, { en: "fraud", min: "vlait" }, { en: "fraudulent", min: "vlaitiromd" }, { en: "fraught", min: "vlaighd" }, { en: "frazzle", min: "vlassro" }, { en: "freak", min: "vloac" }, { en: "freckle", min: "vlokcro" }, { en: "free", min: "vloo" },
  { en: "freebase", min: "vloopazo" }, { en: "freebee", min: "vloopoo" }, { en: "freebie", min: "vloopuo" }, { en: "freedman", min: "vlootnam" }, { en: "freedmen", min: "vlootnom" }, { en: "freedom", min: "vlooten" }, { en: "freehand", min: "vloohamt" }, { en: "freehold", min: "vloohert" }, { en: "freelance", min: "vlooramko" }, { en: "freeload", min: "vlooreat" },
  { en: "freemen", min: "vloonom" }, { en: "freestyle", min: "vloozdyro" }, { en: "freeware", min: "vloowalo" }, { en: "freewheel", min: "vloowhoor" }, { en: "freewill", min: "vloowurr" }, { en: "freeze", min: "vlooso" }, { en: "freight", min: "vloughd" }, { en: "frequent", min: "vlojiomd" }, { en: "fresco", min: "vlozke" }, { en: "fresh", min: "vlozh" },
  { en: "freshen", min: "vlozhom" }, { en: "freshet", min: "vlozhod" }, { en: "freshman", min: "vlozhnam" }, { en: "freshmen", min: "vlozhnom" }, { en: "fret", min: "vlod" }, { en: "fretwork", min: "vlodwelc" }, { en: "fricassee", min: "vlukazzoo" }, { en: "frieze", min: "vluoso" }, { en: "frigate", min: "vlugado" }, { en: "fright", min: "vlughd" },
  { en: "frighten", min: "vlughdom" }, { en: "frigid", min: "vlugut" }, { en: "frill", min: "vlurr" }, { en: "fringe", min: "vlumgo" }, { en: "frisk", min: "vluzc" }, { en: "frizz", min: "vluss" }, { en: "frizzle", min: "vlussro" }, { en: "fro", min: "vle" }, { en: "frock", min: "vlekc" }, { en: "frog", min: "vleg" },
  { en: "frogman", min: "vlegnam" }, { en: "frogmen", min: "vlegnom" }, { en: "frolicsome", min: "vlerukzeno" }, { en: "from", min: "vlen" }, { en: "frond", min: "vlemt" }, { en: "front", min: "vlemd" }, { en: "frontage", min: "vlemdago" }, { en: "frostbit", min: "vlezdpud" }, { en: "frostbite", min: "vlezdpudo" }, { en: "frown", min: "vlewm" },
  { en: "froze", min: "vleso" }, { en: "frozen", min: "vlesom" }, { en: "fructose", min: "vlikdezo" }, { en: "fruit", min: "vliud" }, { en: "fruitcake", min: "vliudkaco" }, { en: "frump", min: "vlinb" }, { en: "frustrate", min: "vlizdlado" }, { en: "ftp", min: "vdb" }, { en: "fuchsia", min: "vikhzua" }, { en: "fuck", min: "vikc" },
  { en: "fuddle", min: "vittro" }, { en: "fudge", min: "vitgo" }, { en: "fuel", min: "vior" }, { en: "fugue", min: "vigio" }, { en: "fulcra", min: "virkla" }, { en: "fulcrum", min: "virklin" }, { en: "fulfil", min: "virvur" }, { en: "fulfill", min: "virvurr" }, { en: "full", min: "virr" }, { en: "fullback", min: "virrpakc" },
  { en: "fulminate", min: "virnumado" }, { en: "fulsome", min: "virzeno" }, { en: "fum", min: "vin" }, { en: "fumble", min: "vinpro" }, { en: "fume", min: "vino" }, { en: "fumigate", min: "vinugado" }, { en: "fumigator", min: "vinugadel" }, { en: "fun", min: "vim" }, { en: "fund", min: "vimt" }, { en: "fungi", min: "vimgu" },
  { en: "fungicide", min: "vimgukuto" }, { en: "funk", min: "vimc" }, { en: "funnel", min: "vimmor" }, { en: "fur", min: "vil" }, { en: "furbelow", min: "vilporew" }, { en: "furl", min: "vilr" }, { en: "furlong", min: "vilremg" }, { en: "furlough", min: "vilreigh" }, { en: "furnace", min: "vilmako" }, { en: "furniture", min: "vilmudilo" },
  { en: "furor", min: "vilel" }, { en: "furrow", min: "villew" }, { en: "furze", min: "vilso" }, { en: "fuse", min: "vizo" }, { en: "fuselage", min: "vizorago" }, { en: "fusillade", min: "vizurrato" }, { en: "fusion", min: "vizuem" }, { en: "fussbudget", min: "vizzpitgod" }, { en: "fustian", min: "vizduam" }, { en: "futile", min: "viduro" },
  { en: "futon", min: "videm" }, { en: "future", min: "vidilo" }, { en: "futz", min: "vids" }, { en: "fuze", min: "viso" }, { en: "fuzz", min: "viss" }, { en: "fuzzball", min: "vissparr" }, { en: "fwd", min: "vwt" }, { en: "gab", min: "gap" }, { en: "gabardine", min: "gapaltumo" }, { en: "gabble", min: "gappro" },
  { en: "gaberdine", min: "gapoltumo" }, { en: "gad", min: "gat" }, { en: "gadabout", min: "gatapeid" }, { en: "gadget", min: "gatgod" }, { en: "gaff", min: "gavv" }, { en: "gaffe", min: "gavvo" }, { en: "gag", min: "gag" }, { en: "gaggle", min: "gaggro" }, { en: "gain", min: "gaum" }, { en: "gainsaid", min: "gaumzaut" },
  { en: "gait", min: "gaud" }, { en: "gal", min: "gar" }, { en: "gala", min: "gara" }, { en: "galena", min: "garoma" }, { en: "gallant", min: "garramd" }, { en: "galleon", min: "garroem" }, { en: "gallium", min: "garruin" }, { en: "gallivant", min: "garrufamd" }, { en: "gallon", min: "garrem" }, { en: "gallop", min: "garreb" },
  { en: "gallstone", min: "garrzdemo" }, { en: "galore", min: "garelo" }, { en: "galosh", min: "garezh" }, { en: "galvanize", min: "garfamuso" }, { en: "gambit", min: "ganpud" }, { en: "gambol", min: "ganper" }, { en: "game", min: "gano" }, { en: "gamecock", min: "ganokekc" }, { en: "gamete", min: "ganodo" }, { en: "gamin", min: "ganum" },
  { en: "gamine", min: "ganumo" }, { en: "gamma", min: "ganna" }, { en: "gamut", min: "ganid" }, { en: "gang", min: "gamg" }, { en: "gangland", min: "gamgramt" }, { en: "ganglia", min: "gamgrua" }, { en: "ganglion", min: "gamgruem" }, { en: "gangplank", min: "gamgbramc" }, { en: "gangrene", min: "gamglomo" }, { en: "gannet", min: "gammod" },
  { en: "gantlet", min: "gamdrod" }, { en: "gape", min: "gabo" }, { en: "garb", min: "galp" }, { en: "garbage", min: "galpago" }, { en: "garbageman", min: "galpagonam" }, { en: "garbanzo", min: "galpamse" }, { en: "garble", min: "galpro" }, { en: "gardenia", min: "galtomua" }, { en: "gargantuan", min: "galgamdiam" }, { en: "gargle", min: "galgro" },
  { en: "gargoyle", min: "galgeyro" }, { en: "garnishee", min: "galmuzhoo" }, { en: "garote", min: "galedo" }, { en: "garotte", min: "galeddo" }, { en: "garret", min: "gallod" }, { en: "garrote", min: "galledo" }, { en: "garrotte", min: "galleddo" }, { en: "gash", min: "gazh" }, { en: "gasket", min: "gazcod" }, { en: "gaslight", min: "gazrughd" },
  { en: "gasohol", min: "gazeher" }, { en: "gasolene", min: "gazeromo" }, { en: "gasoline", min: "gazerumo" }, { en: "gasp", min: "gazb" }, { en: "gate", min: "gado" }, { en: "gatepost", min: "gadobezd" }, { en: "gauche", min: "gaikho" }, { en: "gaucho", min: "gaikhe" }, { en: "gauge", min: "gaigo" }, { en: "gaunt", min: "gaimd" },
];
