/**
 * @file Contains dictionary entries for category: verbs_communication.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const verbs_communication: DictionaryEntry[] = [
  { en: "speak", min: "boka" }, { en: "say", min: "toka" }, { en: "tell", min: "dorry" }, { en: "ask", min: "poka" }, { en: "call", min: "krilla" }, { en: "copland", min: "kebramt" }, { en: "coppertone", min: "kebboldemo" }, { en: "coppola", min: "kebbera" }, { en: "cordoba", min: "keltepa" }, { en: "cordova", min: "keltefa" },
  { en: "corfu", min: "kelvi" }, { en: "corinthian", min: "kelumdhuam" }, { en: "corleone", min: "kelroemo" }, { en: "cormack", min: "kelnakc" }, { en: "corneille", min: "kelmourro" }, { en: "cornell", min: "kelmorr" }, { en: "cornwall", min: "kelmwarr" }, { en: "coronado", min: "kelemate" }, { en: "corot", min: "keled" }, { en: "corp", min: "kelb" },
  { en: "correggio", min: "kelloggue" }, { en: "corsica", min: "kelzuka" }, { en: "corsican", min: "kelzukam" }, { en: "cortez", min: "keldos" }, { en: "cortland", min: "keldramt" }, { en: "corvette", min: "kelfoddo" }, { en: "cosmosdb", min: "kezneztp" }, { en: "cossack", min: "kezzakc" }, { en: "costello", min: "kezdorre" }, { en: "cote", min: "kedo" },
  { en: "cotonou", min: "kedemei" }, { en: "cotopaxi", min: "kedebaxu" }, { en: "cotswold", min: "kedzwert" }, { en: "cotton", min: "keddem" }, { en: "coulomb", min: "keirenp" }, { en: "couperin", min: "keibolum" }, { en: "courbet", min: "keilpod" }, { en: "cousteau", min: "keizdoai" }, { en: "covington", min: "kefumgdem" }, { en: "cox", min: "kex" },
  { en: "cozumel", min: "kesinor" }, { en: "crabbe", min: "klappo" }, { en: "craft", min: "klavd" }, { en: "craig", min: "klaug" }, { en: "cranach", min: "klamakh" }, { en: "crane", min: "klamo" }, { en: "crawford", min: "klawvelt" }, { en: "crayola", min: "klayera" }, { en: "creator", min: "kloadel" }, { en: "cree", min: "kloo" },
  { en: "creek", min: "klooc" }, { en: "creighton", min: "kloughdem" }, { en: "creole", min: "kloero" }, { en: "creon", min: "kloem" }, { en: "cressida", min: "klozzuta" }, { en: "cretan", min: "klodam" }, { en: "crete", min: "klodo" }, { en: "crichton", min: "klukhdem" }, { en: "crick", min: "klukc" }, { en: "crimea", min: "klunoa" },
  { en: "crimean", min: "klunoam" }, { en: "criollo", min: "kluerre" }, { en: "crisco", min: "kluzke" }, { en: "croat", min: "klead" }, { en: "croatian", min: "kleaduam" }, { en: "croce", min: "kleko" }, { en: "crockett", min: "klekcodd" }, { en: "cromwell", min: "klenworr" }, { en: "cronin", min: "klemum" }, { en: "cronkite", min: "klemcudo" },
  { en: "cruikshank", min: "kliuczhamc" }, { en: "cruise", min: "kliuzo" }, { en: "crusoe", min: "klizeo" }, { en: "crux", min: "klix" }, { en: "cruz", min: "klis" }, { en: "csonka", min: "kzemca" }, { en: "ctesiphon", min: "kdozubhem" }, { en: "cthulhu", min: "kdhirhi" }, { en: "cuban", min: "kipam" }, { en: "cuchulain", min: "kikhiraum" },
  { en: "cuisinart", min: "kiuzumald" }, { en: "culbertson", min: "kirpoldzem" }, { en: "cullen", min: "kirrom" }, { en: "cumberland", min: "kinpolramt" }, { en: "cunard", min: "kimalt" }, { en: "cunningham", min: "kimmumghan" }, { en: "cupid", min: "kibut" }, { en: "curacao", min: "kilakae" }, { en: "curie", min: "kiluo" }, { en: "curitiba", min: "kiludupa" },
  { en: "curt", min: "kild" }, { en: "cuzco", min: "kiske" }, { en: "cybele", min: "kyporo" }, { en: "cymbeline", min: "kynporumo" }, { en: "cyprian", min: "kybluam" }, { en: "cypriot", min: "kyblued" }, { en: "cyrano", min: "kylame" }, { en: "cyril", min: "kylur" }, { en: "czechia", min: "ksokhua" }, { en: "dat", min: "tad" },
  { en: "ddt", min: "ttd" }, { en: "dec", min: "tok" }, { en: "dmca", min: "tnka" }, { en: "dmz", min: "tns" }, { en: "dna", min: "tma" }, { en: "doa", min: "tea" }, { en: "dpt", min: "tbd" }, { en: "dst", min: "tzd" }, { en: "dtp", min: "tdb" }, { en: "dui", min: "tiu" },
  { en: "dvd", min: "tft" }, { en: "dvr", min: "tfl" }, { en: "dwi", min: "twu" }, { en: "dacca", min: "takka" }, { en: "dachau", min: "takhai" }, { en: "dacron", min: "taklem" }, { en: "dada", min: "tata" }, { en: "daguerre", min: "tagiollo" }, { en: "dagwood", min: "tagweet" }, { en: "dakota", min: "taceda" },
  { en: "dakotan", min: "tacedam" }, { en: "dalai", min: "tarau" }, { en: "dali", min: "taru" }, { en: "dalian", min: "taruam" }, { en: "dalmatian", min: "tarnaduam" }, { en: "dalton", min: "tardem" }, { en: "damian", min: "tanuam" }, { en: "damien", min: "tanuom" }, { en: "damion", min: "tanuem" }, { en: "damon", min: "tanem" },
  { en: "dan", min: "tam" }, { en: "dane", min: "tamo" }, { en: "danelaw", min: "tamoraw" }, { en: "daniel", min: "tamuor" }, { en: "danone", min: "tamemo" }, { en: "dante", min: "tamdo" }, { en: "danton", min: "tamdem" }, { en: "danubian", min: "tamipuam" }, { en: "danville", min: "tamfurro" }, { en: "dare", min: "talo" },
  { en: "daren", min: "talom" }, { en: "darfur", min: "talvil" }, { en: "darin", min: "talum" }, { en: "dario", min: "talue" }, { en: "darnell", min: "talmorr" }, { en: "darrel", min: "tallor" }, { en: "darrell", min: "tallorr" }, { en: "darren", min: "tallom" }, { en: "darrin", min: "tallum" }, { en: "darrow", min: "tallew" },
  { en: "dartmoor", min: "taldneel" }, { en: "darvon", min: "talfem" }, { en: "darwin", min: "talwum" }, { en: "darwinian", min: "talwumuam" }, { en: "davao", min: "tafae" }, { en: "davenport", min: "tafombeld" }, { en: "david", min: "tafut" }, { en: "davidson", min: "tafutzem" }, { en: "dawson", min: "tawzem" }, { en: "dayton", min: "taydem" },
  { en: "dean", min: "toam" }, { en: "dem", min: "ton" }, { en: "deng", min: "tomg" }, { en: "deon", min: "toem" }, { en: "depp", min: "tobb" }, { en: "dhaulagiri", min: "thairagulu" }, { en: "dicaprio", min: "tukablue" }, { en: "dimaggio", min: "tunaggue" }, { en: "diaghilev", min: "tuaghurof" }, { en: "diaspora", min: "tuazbela" },
  { en: "diaz", min: "tuas" }, { en: "dick", min: "tukc" }, { en: "dickerson", min: "tukcolzem" }, { en: "dickinson", min: "tukcumzem" }, { en: "dickson", min: "tukczem" }, { en: "dictaphone", min: "tukdabhemo" }, { en: "diderot", min: "tutoled" }, { en: "didrikson", min: "tutluczem" }, { en: "diego", min: "tuoge" }, { en: "diem", min: "tuon" },
  { en: "diesel", min: "tuozor" }, { en: "dietrich", min: "tuodlukh" }, { en: "dijkstra", min: "tuqczdla" }, { en: "dijon", min: "tuqem" }, { en: "dilbert", min: "turpold" }, { en: "dillard", min: "turralt" }, { en: "dillon", min: "turrem" }, { en: "dino", min: "tume" }, { en: "diocletian", min: "tuekroduam" }, { en: "dionysian", min: "tuemyzuam" },
  { en: "dior", min: "tuel" }, { en: "dirac", min: "tulak" }, { en: "dirichlet", min: "tulukhrod" }, { en: "dirk", min: "tulc" }, { en: "diwali", min: "tuwaru" }, { en: "dixiecrat", min: "tuxuoklad" }, { en: "dixieland", min: "tuxuoramt" }, { en: "dixon", min: "tuxem" }, { en: "djakarta", min: "tqacalda" }, { en: "django", min: "tqamge" },
  { en: "dmitri", min: "tnudlu" }, { en: "dobbin", min: "teppum" }, { en: "doberman", min: "tepolnam" }, { en: "dobro", min: "teple" }, { en: "doctor", min: "tekdel" }, { en: "doctorow", min: "tekdelew" }, { en: "dodge", min: "tetgo" }, { en: "dodgson", min: "tetgzem" }, { en: "dodson", min: "tetzem" }, { en: "dole", min: "tero" },
  { en: "dominguez", min: "tenumgios" }, { en: "dominick", min: "tenumukc" }, { en: "domitian", min: "tenuduam" }, { en: "don", min: "tem" }, { en: "donahue", min: "temahio" }, { en: "donald", min: "temart" }, { en: "donaldson", min: "temartzem" }, { en: "donatello", min: "temadorre" }, { en: "donetsk", min: "temodzc" }, { en: "donizetti", min: "temusoddu" },
  { en: "donn", min: "temm" }, { en: "donne", min: "temmo" }, { en: "donnell", min: "temmorr" }, { en: "donovan", min: "temefam" }, { en: "doolittle", min: "teeruddro" }, { en: "dorset", min: "telzod" }, { en: "dortmund", min: "teldnimt" }, { en: "dothan", min: "tedham" }, { en: "dotson", min: "tedzem" }, { en: "douala", min: "teiara" },
  { en: "doug", min: "teig" }, { en: "douro", min: "teile" }, { en: "dow", min: "tew" }, { en: "doyle", min: "teyro" }, { en: "draco", min: "tlake" }, { en: "draconian", min: "tlakemuam" }, { en: "dracula", min: "tlakira" }, { en: "drake", min: "tlaco" }, { en: "dramamine", min: "tlananumo" }, { en: "drambuie", min: "tlanpiuo" },
  { en: "drano", min: "tlame" }, { en: "dravidian", min: "tlafutuam" }, { en: "dresden", min: "tloztom" }, { en: "drew", min: "tlow" }, { en: "dristan", min: "tluzdam" }, { en: "dropbox", min: "tlebpex" }, { en: "drudge", min: "tlitgo" }, { en: "druid", min: "tliut" }, { en: "dryden", min: "tlytom" }, { en: "dschubba", min: "tzkhippa" },
  { en: "dupont", min: "tibemd" }, { en: "duane", min: "tiamo" }, { en: "dubai", min: "tipau" }, { en: "dubcek", min: "tipkoc" }, { en: "dubhe", min: "tipho" }, { en: "dubrovnik", min: "tiplefmuc" }, { en: "dubuque", min: "tipijio" }, { en: "duchamp", min: "tikhanb" }, { en: "duisburg", min: "tiuzpilg" }, { en: "duke", min: "tico" },
  { en: "dumbledore", min: "tinprotelo" }, { en: "dumbo", min: "tinpe" }, { en: "dunant", min: "timamd" }, { en: "duncan", min: "timkam" }, { en: "dunedin", min: "timotum" }, { en: "dunkirk", min: "timculc" }, { en: "dunlap", min: "timrab" }, { en: "dunn", min: "timm" }, { en: "dunne", min: "timmo" }, { en: "duracell", min: "tilakorr" },
  { en: "duran", min: "tilam" }, { en: "durant", min: "tilamd" }, { en: "durante", min: "tilamdo" }, { en: "durban", min: "tilpam" }, { en: "durex", min: "tilox" }, { en: "durham", min: "tilhan" }, { en: "durkheim", min: "tilchoun" }, { en: "duroc", min: "tilek" }, { en: "duse", min: "tizo" }, { en: "dustin", min: "tizdum" },
  { en: "dutchman", min: "tidkhnam" }, { en: "dutchmen", min: "tidkhnom" }, { en: "dvina", min: "tfuma" }, { en: "dwayne", min: "twaymo" }, { en: "dwight", min: "twughd" }, { en: "dylan", min: "tyram" }, { en: "dynamodb", min: "tymanetp" }, { en: "dyson", min: "tyzem" }, { en: "dzungaria", min: "tsimgalua" }, { en: "ecg", min: "okg" },
  { en: "ecmascript", min: "oknazklubd" }, { en: "edt", min: "otd" }, { en: "eec", min: "ook" }, { en: "eeg", min: "oog" }, { en: "eeo", min: "ooe" }, { en: "efl", min: "ovr" }, { en: "ekg", min: "ocg" }, { en: "emt", min: "ond" }, { en: "epa", min: "oba" }, { en: "era", min: "ola" },
];
