/**
 * @file Contains dictionary entries for category: verbs_mental.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const verbs_mental: DictionaryEntry[] = [
  { en: "know", min: "wata" }, { en: "think", min: "pensa" }, { en: "want", min: "pwede" }, { en: "like", min: "tulali" }, { en: "hope", min: "spera" }, { en: "callaghan", min: "karragham" }, { en: "callahan", min: "karraham" }, { en: "callao", min: "karrae" }, { en: "calliope", min: "karruebo" }, { en: "callisto", min: "karruzde" },
  { en: "caloocan", min: "kareekam" }, { en: "calvert", min: "karfold" }, { en: "calvin", min: "karfum" }, { en: "camacho", min: "kanakhe" }, { en: "camarillo", min: "kanalurre" }, { en: "cambodian", min: "kanpetuam" }, { en: "cambrian", min: "kanpluam" }, { en: "cambridge", min: "kanplutgo" }, { en: "camelot", min: "kanored" }, { en: "camembert", min: "kanonpold" },
  { en: "cameron", min: "kanolem" }, { en: "campanella", min: "kanbamorra" }, { en: "campbell", min: "kanbporr" }, { en: "canaan", min: "kamaam" }, { en: "canadian", min: "kamatuam" }, { en: "canaletto", min: "kamarodde" }, { en: "cancun", min: "kamkim" }, { en: "cannon", min: "kammem" }, { en: "canon", min: "kamem" }, { en: "canton", min: "kamdem" },
  { en: "cantonese", min: "kamdemozo" }, { en: "cantor", min: "kamdel" }, { en: "cantrell", min: "kamdlorr" }, { en: "cantu", min: "kamdi" }, { en: "canute", min: "kamido" }, { en: "capablanca", min: "kabapramka" }, { en: "capek", min: "kaboc" }, { en: "capella", min: "kaborra" }, { en: "capet", min: "kabod" }, { en: "capetian", min: "kaboduam" },
  { en: "capetown", min: "kabodewm" }, { en: "caph", min: "kabh" }, { en: "capistrano", min: "kabuzdlame" }, { en: "capitol", min: "kabuder" }, { en: "capitoline", min: "kabuderumo" }, { en: "capone", min: "kabemo" }, { en: "capote", min: "kabedo" }, { en: "capra", min: "kabla" }, { en: "capri", min: "kablu" }, { en: "capricorn", min: "kablukelm" },
  { en: "capt", min: "kabd" }, { en: "capuchin", min: "kabikhum" }, { en: "capulet", min: "kabirod" }, { en: "caracalla", min: "kalakarra" }, { en: "caravaggio", min: "kalafaggue" }, { en: "carbondale", min: "kalpemtaro" }, { en: "cardin", min: "kaltum" }, { en: "cardozo", min: "kaltese" }, { en: "carib", min: "kalup" }, { en: "carl", min: "kalr" },
  { en: "carlo", min: "kalre" }, { en: "carlsbad", min: "kalrzpat" }, { en: "carlson", min: "kalrzem" }, { en: "carlton", min: "kalrdem" }, { en: "carlyle", min: "kalryro" }, { en: "carmelo", min: "kalnore" }, { en: "carmichael", min: "kalnukhaor" }, { en: "carnap", min: "kalmab" }, { en: "carnegie", min: "kalmoguo" }, { en: "carnot", min: "kalmed" },
  { en: "carolinian", min: "kalerumuam" }, { en: "carpathian", min: "kalbadhuam" }, { en: "carr", min: "kall" }, { en: "carranza", min: "kallamsa" }, { en: "carrillo", min: "kallurre" }, { en: "carson", min: "kalzem" }, { en: "cartesian", min: "kaldozuam" }, { en: "carthage", min: "kaldhago" }, { en: "cartwright", min: "kaldwlughd" }, { en: "caruso", min: "kalize" },
  { en: "casablanca", min: "kazapramka" }, { en: "casanova", min: "kazamefa" }, { en: "case", min: "kazo" }, { en: "cash", min: "kazh" }, { en: "casio", min: "kazue" }, { en: "caspian", min: "kazbuam" }, { en: "cassatt", min: "kazzadd" }, { en: "cassiopeia", min: "kazzueboua" }, { en: "castaneda", min: "kazdamota" }, { en: "castillo", min: "kazdurre" },
  { en: "castor", min: "kazdel" }, { en: "castro", min: "kazdle" }, { en: "catalan", min: "kadaram" }, { en: "catalina", min: "kadaruma" }, { en: "catalonia", min: "kadaremua" }, { en: "catawba", min: "kadawpa" }, { en: "catiline", min: "kadurumo" }, { en: "cato", min: "kade" }, { en: "catskill", min: "kadzcurr" }, { en: "catt", min: "kadd" },
  { en: "caucasian", min: "kaikazuam" }, { en: "caucasoid", min: "kaikazeut" }, { en: "cavour", min: "kafeil" }, { en: "caxton", min: "kaxdem" }, { en: "cayuga", min: "kayiga" }, { en: "ceausescu", min: "koaizozki" }, { en: "cebu", min: "kopi" }, { en: "cebuano", min: "kopiame" }, { en: "celgene", min: "korgomo" }, { en: "cellini", min: "korrumu" },
  { en: "celt", min: "kord" }, { en: "centigrade", min: "komduglato" }, { en: "cepheid", min: "kobhout" }, { en: "cerenkov", min: "kolomcef" }, { en: "cerf", min: "kolv" }, { en: "cesarean", min: "kozaloam" }, { en: "cessna", min: "kozzma" }, { en: "ceylon", min: "koyrem" }, { en: "cezanne", min: "kosammo" }, { en: "chadwick", min: "khatwukc" },
  { en: "chagall", min: "khagarr" }, { en: "chaitanya", min: "khaudamya" }, { en: "chaitin", min: "khaudum" }, { en: "chaldean", min: "khartoam" }, { en: "champaign", min: "khanbaugm" }, { en: "champlain", min: "khanbraum" }, { en: "chan", min: "kham" }, { en: "chance", min: "khamko" }, { en: "chandigarh", min: "khamtugalh" }, { en: "chandon", min: "khamtem" },
  { en: "chang", min: "khamg" }, { en: "changchun", min: "khamgkhim" }, { en: "changsha", min: "khamgzha" }, { en: "chanukah", min: "khamicah" }, { en: "chaplin", min: "khabrum" }, { en: "chapman", min: "khabnam" }, { en: "charleston", min: "khalrozdem" }, { en: "charlie", min: "khalruo" }, { en: "charmin", min: "khalnum" }, { en: "charon", min: "khalem" },
  { en: "chase", min: "khazo" }, { en: "chatterton", min: "khaddoldem" }, { en: "chautauqua", min: "khaidaijia" }, { en: "chavez", min: "khafos" }, { en: "che", min: "kho" }, { en: "chechen", min: "khokhom" }, { en: "chechnya", min: "khokhmya" }, { en: "chekhov", min: "khochef" }, { en: "chen", min: "khom" }, { en: "chengdu", min: "khomgti" },
  { en: "chennai", min: "khommau" }, { en: "chernenko", min: "kholmomce" }, { en: "chernobyl", min: "kholmepyr" }, { en: "cherokee", min: "kholecoo" }, { en: "chesapeake", min: "khozaboaco" }, { en: "cheshire", min: "khozhulo" }, { en: "chesterton", min: "khozdoldem" }, { en: "cheviot", min: "khofued" }, { en: "chevrolet", min: "khoflerod" }, { en: "chevron", min: "khoflem" },
  { en: "cheyenne", min: "khoyommo" }, { en: "chi", min: "khu" }, { en: "chianti", min: "khuamdu" }, { en: "chiba", min: "khupa" }, { en: "chibcha", min: "khupkha" }, { en: "chicago", min: "khukage" }, { en: "chicagoan", min: "khukageam" }, { en: "chicana", min: "khukama" }, { en: "chicano", min: "khukame" }, { en: "chickasaw", min: "khukcazaw" },
  { en: "chico", min: "khuke" }, { en: "chihuahua", min: "khuhiahia" }, { en: "chilean", min: "khuroam" }, { en: "chimborazo", min: "khunpelase" }, { en: "chimera", min: "khunola" }, { en: "chimu", min: "khuni" }, { en: "chinatown", min: "khumadewm" }, { en: "chinook", min: "khumeec" }, { en: "chipewyan", min: "khubowyam" }, { en: "chippewa", min: "khubbowa" },
  { en: "chirico", min: "khuluke" }, { en: "chisholm", min: "khuzhern" }, { en: "chittagong", min: "khuddagemg" }, { en: "choctaw", min: "khekdaw" }, { en: "chopin", min: "khebum" }, { en: "chopra", min: "khebla" }, { en: "chou", min: "khei" }, { en: "chretien", min: "khloduom" }, { en: "chrysostom", min: "khlyzezden" }, { en: "chuck", min: "khikc" },
  { en: "chukchi", min: "khickhu" }, { en: "chumash", min: "khinazh" }, { en: "chung", min: "khimg" }, { en: "church", min: "khilkh" }, { en: "churchill", min: "khilkhurr" }, { en: "chuvash", min: "khifazh" }, { en: "cicero", min: "kukole" }, { en: "cid", min: "kut" }, { en: "cimabue", min: "kunapio" }, { en: "cincinnati", min: "kumkummadu" },
  { en: "cinerama", min: "kumolana" }, { en: "cipro", min: "kuble" }, { en: "circe", min: "kulko" }, { en: "cisco", min: "kuzke" }, { en: "citibank", min: "kudupamc" }, { en: "citigroup", min: "kudugleib" }, { en: "citroen", min: "kudleom" }, { en: "claiborne", min: "kraupelmo" }, { en: "clairol", min: "krauler" }, { en: "clapeyron", min: "kraboylem" },
  { en: "clapton", min: "krabdem" }, { en: "clarence", min: "kralomko" }, { en: "clarendon", min: "kralomtem" }, { en: "clark", min: "kralc" }, { en: "clarke", min: "kralco" }, { en: "claudio", min: "kraitue" }, { en: "clausewitz", min: "kraizowuds" }, { en: "clayton", min: "kraydem" }, { en: "clearasil", min: "kroalazur" }, { en: "clemenceau", min: "kronomkoai" },
  { en: "clemson", min: "kronzem" }, { en: "cleveland", min: "kroforamt" }, { en: "cliburn", min: "krupilm" }, { en: "cliff", min: "kruvv" }, { en: "clifford", min: "kruvvelt" }, { en: "clifton", min: "kruvdem" }, { en: "cline", min: "krumo" }, { en: "clint", min: "krumd" }, { en: "clinton", min: "krumdem" }, { en: "clojure", min: "kreqilo" },
  { en: "clorox", min: "krelex" }, { en: "closure", min: "krezilo" }, { en: "clotho", min: "kredhe" }, { en: "clouseau", min: "kreizoai" }, { en: "clyde", min: "kryto" }, { en: "clydesdale", min: "krytoztaro" }, { en: "cobain", min: "kepaum" }, { en: "cobb", min: "kepp" }, { en: "cochabamba", min: "kekhapanpa" }, { en: "cochin", min: "kekhum" },
  { en: "cochise", min: "kekhuzo" }, { en: "cochran", min: "kekhlam" }, { en: "cocteau", min: "kekdoai" }, { en: "cognac", min: "kegmak" }, { en: "cohan", min: "keham" }, { en: "cohen", min: "kehom" }, { en: "coimbatore", min: "keunpadelo" }, { en: "cointreau", min: "keumdloai" }, { en: "coke", min: "keco" }, { en: "col", min: "ker" },
  { en: "colbert", min: "kerpold" }, { en: "cole", min: "kero" }, { en: "coleman", min: "keronam" }, { en: "coleridge", min: "kerolutgo" }, { en: "colfax", min: "kervax" }, { en: "colgate", min: "kergado" }, { en: "colin", min: "kerum" }, { en: "collin", min: "kerrum" }, { en: "colo", min: "kere" }, { en: "cologne", min: "keregmo" },
  { en: "colombian", min: "kerenpuam" }, { en: "colombo", min: "kerenpe" }, { en: "colon", min: "kerem" }, { en: "colorado", min: "kerelate" }, { en: "colosseum", min: "kerezzoin" }, { en: "colt", min: "kerd" }, { en: "coltrane", min: "kerdlamo" }, { en: "columbia", min: "kerinpua" }, { en: "columbine", min: "kerinpumo" }, { en: "com", min: "ken" },
  { en: "comanche", min: "kenamkho" }, { en: "comintern", min: "kenumdolm" }, { en: "communion", min: "kennimuem" }, { en: "como", min: "kene" }, { en: "compaq", min: "kenbaj" }, { en: "compton", min: "kenbdem" }, { en: "compuserve", min: "kenbizolfo" }, { en: "comte", min: "kendo" }, { en: "conan", min: "kemam" }, { en: "concetta", min: "kemkodda" },
  { en: "concord", min: "kemkelt" }, { en: "concorde", min: "kemkelto" }, { en: "condillac", min: "kemturrak" }, { en: "condorcet", min: "kemtelkod" }, { en: "conestoga", min: "kemozdega" }, { en: "confucian", min: "kemvikuam" }, { en: "cong", min: "kemg" }, { en: "congolese", min: "kemgerozo" }, { en: "congreve", min: "kemglofo" }, { en: "conn", min: "kemm" },
  { en: "connemara", min: "kemmonala" }, { en: "conrad", min: "kemlat" }, { en: "conrail", min: "kemlaur" }, { en: "conroe", min: "kemleo" }, { en: "continent", min: "kemdumomd" }, { en: "cooke", min: "keeco" }, { en: "coolidge", min: "keerutgo" }, { en: "copacabana", min: "kebakapama" }, { en: "copeland", min: "keboramt" }, { en: "copernican", min: "kebolmukam" },
];
