/**
 * @file Contains dictionary entries for category: verbs_sensory.
 * Part of the 15,000 bijective real English words database.
 */
import type { DictionaryEntry } from "./index";

export const verbs_sensory: DictionaryEntry[] = [
  { en: "look", min: "luk" }, { en: "see", min: "luka" }, { en: "hear", min: "skucha" }, { en: "feel", min: "tokafeel" }, { en: "smell", min: "naza" }, { en: "esl", min: "ozr" }, { en: "esp", min: "ozb" }, { en: "espn", min: "ozbm" }, { en: "est", min: "ozd" }, { en: "eta", min: "oda" },
  { en: "etd", min: "odt" }, { en: "earhart", min: "oalhald" }, { en: "earl", min: "oalr" }, { en: "earle", min: "oalro" }, { en: "earlene", min: "oalromo" }, { en: "earline", min: "oalrumo" }, { en: "earnestine", min: "oalmozdumo" }, { en: "earnhardt", min: "oalmhaltd" }, { en: "earp", min: "oalb" }, { en: "eastern", min: "oazdolm" },
  { en: "eastman", min: "oazdnam" }, { en: "eastwood", min: "oazdweet" }, { en: "eaton", min: "oadem" }, { en: "eben", min: "opom" }, { en: "ebert", min: "opold" }, { en: "ebola", min: "opera" }, { en: "ebro", min: "ople" }, { en: "eco", min: "oke" }, { en: "ecuadoran", min: "okiatelam" }, { en: "ecuadorian", min: "okiateluam" },
  { en: "edam", min: "otan" }, { en: "edda", min: "otta" }, { en: "eddington", min: "ottumgdem" }, { en: "edgardo", min: "otgalte" }, { en: "edison", min: "otuzem" }, { en: "edmond", min: "otnemt" }, { en: "edmonton", min: "otnemdem" }, { en: "edmund", min: "otnimt" }, { en: "edsel", min: "otzor" }, { en: "eduardo", min: "otialte" },
  { en: "edwardian", min: "otwaltuam" }, { en: "edwardo", min: "otwalte" }, { en: "edwin", min: "otwum" }, { en: "eeyore", min: "ooyelo" }, { en: "efrain", min: "ovlaum" }, { en: "efren", min: "ovlom" }, { en: "eggo", min: "ogge" }, { en: "egyptian", min: "ogybduam" }, { en: "ehrenberg", min: "ohlompolg" }, { en: "ehrlich", min: "ohlrukh" },
  { en: "eichmann", min: "oukhnamm" }, { en: "eiffel", min: "ouvvor" }, { en: "einstein", min: "oumzdoum" }, { en: "eire", min: "oulo" }, { en: "eisenstein", min: "ouzomzdoum" }, { en: "elam", min: "oran" }, { en: "elanor", min: "oramel" }, { en: "elba", min: "orpa" }, { en: "elbe", min: "orpo" }, { en: "elbert", min: "orpold" },
  { en: "eldersburg", min: "ortolzpilg" }, { en: "eldon", min: "ortem" }, { en: "eli", min: "oru" }, { en: "elijah", min: "oruqah" }, { en: "eliot", min: "orued" }, { en: "eliseo", min: "oruzoe" }, { en: "elkhart", min: "orchald" }, { en: "ellesmere", min: "orroznolo" }, { en: "ellington", min: "orrumgdem" }, { en: "elliot", min: "orrued" },
  { en: "elliott", min: "orruedd" }, { en: "ellison", min: "orruzem" }, { en: "elma", min: "orna" }, { en: "elmo", min: "orne" }, { en: "elohim", min: "orehun" }, { en: "eltanin", min: "ordamum" }, { en: "elton", min: "ordem" }, { en: "elul", min: "orir" }, { en: "elvia", min: "orfua" }, { en: "elvin", min: "orfum" },
  { en: "elwood", min: "orweet" }, { en: "elyria", min: "orylua" }, { en: "elysian", min: "oryzuam" }, { en: "elysium", min: "oryzuin" }, { en: "emanuel", min: "onamior" }, { en: "emerson", min: "onolzem" }, { en: "emil", min: "onur" }, { en: "emile", min: "onuro" }, { en: "emilio", min: "onurue" }, { en: "eminem", min: "onumon" },
  { en: "emmanuel", min: "onnamior" }, { en: "emmett", min: "onnodd" }, { en: "encarta", min: "omkalda" }, { en: "endymion", min: "omtynuem" }, { en: "eng", min: "omg" }, { en: "englishman", min: "omgruzhnam" }, { en: "englishmen", min: "omgruzhnom" }, { en: "enif", min: "omuv" }, { en: "eniwetok", min: "omuwodec" }, { en: "enkidu", min: "omcuti" },
  { en: "enoch", min: "omekh" }, { en: "enrico", min: "omluke" }, { en: "enrique", min: "omlujio" }, { en: "enron", min: "omlem" }, { en: "enterprise", min: "omdolbluzo" }, { en: "eocene", min: "oekomo" }, { en: "epcot", min: "obked" }, { en: "ephesian", min: "obhozuam" }, { en: "ephraim", min: "obhlaun" }, { en: "epicurean", min: "obukiloam" },
  { en: "epsom", min: "obzen" }, { en: "epson", min: "obzem" }, { en: "epstein", min: "obzdoum" }, { en: "erato", min: "olade" }, { en: "erector", min: "olokdel" }, { en: "erewhon", min: "olowhem" }, { en: "erhard", min: "olhalt" }, { en: "erich", min: "olukh" }, { en: "erick", min: "olukc" }, { en: "erickson", min: "olukczem" },
  { en: "ericson", min: "olukzem" }, { en: "ericsson", min: "olukzzem" }, { en: "erie", min: "oluo" }, { en: "erik", min: "oluc" }, { en: "erlang", min: "olramg" }, { en: "ernesto", min: "olmozde" }, { en: "ernie", min: "olmuo" }, { en: "ernst", min: "olmzd" }, { en: "errol", min: "oller" }, { en: "erse", min: "olzo" },
  { en: "ervin", min: "olfum" }, { en: "erwin", min: "olwum" }, { en: "esau", min: "ozai" }, { en: "eskimo", min: "ozcune" }, { en: "esperanto", min: "ozbolamde" }, { en: "esperanza", min: "ozbolamsa" }, { en: "espinoza", min: "ozbumesa" }, { en: "esq", min: "ozj" }, { en: "essen", min: "ozzom" }, { en: "essene", min: "ozzomo" },
  { en: "essequibo", min: "ozzojiupe" }, { en: "essex", min: "ozzox" }, { en: "esteban", min: "ozdopam" }, { en: "estela", min: "ozdora" }, { en: "estonian", min: "ozdemuam" }, { en: "estrada", min: "ozdlata" }, { en: "ethan", min: "odham" }, { en: "ethernet", min: "odholmod" }, { en: "ethiopian", min: "odhuebuam" }, { en: "etna", min: "odma" },
  { en: "eton", min: "odem" }, { en: "etruria", min: "odlilua" }, { en: "etruscan", min: "odlizkam" }, { en: "euclid", min: "oikrut" }, { en: "euclidean", min: "oikrutoam" }, { en: "eugene", min: "oigomo" }, { en: "eugenio", min: "oigomue" }, { en: "eurasia", min: "oilazua" }, { en: "eurasian", min: "oilazuam" }, { en: "europa", min: "oileba" },
  { en: "european", min: "oileboam" }, { en: "eurydice", min: "oilytuko" }, { en: "eustachian", min: "oizdakhuam" }, { en: "euterpe", min: "oidolbo" }, { en: "evan", min: "ofam" }, { en: "evansville", min: "ofamzfurro" }, { en: "evenki", min: "ofomcu" }, { en: "everett", min: "ofolodd" }, { en: "everette", min: "ofoloddo" }, { en: "evert", min: "ofold" },
  { en: "evian", min: "ofuam" }, { en: "excalibur", min: "oxkarupil" }, { en: "excedrin", min: "oxkotlum" }, { en: "exercycle", min: "oxolkykro" }, { en: "exocet", min: "oxekod" }, { en: "exxon", min: "oxxem" }, { en: "eyck", min: "oykc" }, { en: "eyre", min: "oylo" }, { en: "eysenck", min: "oyzomkc" }, { en: "ezekiel", min: "osocuor" },
  { en: "ezra", min: "osla" }, { en: "faa", min: "vaa" }, { en: "faq", min: "vaj" }, { en: "fbi", min: "vpu" }, { en: "fcc", min: "vkk" }, { en: "fda", min: "vta" }, { en: "fdr", min: "vtl" }, { en: "fha", min: "vha" }, { en: "fica", min: "vuka" }, { en: "fnma", min: "vmna" },
  { en: "fofl", min: "vevr" }, { en: "fortran", min: "veldlam" }, { en: "fpo", min: "vbe" }, { en: "fsf", min: "vzv" }, { en: "ftc", min: "vdk" }, { en: "fud", min: "vit" }, { en: "fwiw", min: "vwuw" }, { en: "fyi", min: "vyu" }, { en: "fabian", min: "vapuam" }, { en: "faeroe", min: "vaoleo" },
  { en: "fafnir", min: "vavmul" }, { en: "fagin", min: "vagum" }, { en: "fahd", min: "vaht" }, { en: "fahrenheit", min: "vahlomhoud" }, { en: "fairfield", min: "vaulvuort" }, { en: "fairhope", min: "vaulhebo" }, { en: "faisalabad", min: "vauzarapat" }, { en: "fajardo", min: "vaqalte" }, { en: "falasha", min: "varazha" }, { en: "fallopian", min: "varrebuam" },
  { en: "falstaff", min: "varzdavv" }, { en: "falwell", min: "varworr" }, { en: "fargo", min: "valge" }, { en: "farmington", min: "valnumgdem" }, { en: "farragut", min: "vallagid" }, { en: "farrakhan", min: "vallacham" }, { en: "farrell", min: "vallorr" }, { en: "farrow", min: "vallew" }, { en: "farsi", min: "valzu" }, { en: "fatah", min: "vadah" },
  { en: "fatima", min: "vaduna" }, { en: "fatimid", min: "vadunut" }, { en: "faust", min: "vaizd" }, { en: "faustian", min: "vaizduam" }, { en: "faustino", min: "vaizdume" }, { en: "feb", min: "vop" }, { en: "fed", min: "vot" }, { en: "fedex", min: "votox" }, { en: "federico", min: "votoluke" }, { en: "felipe", min: "vorubo" },
  { en: "felix", min: "vorux" }, { en: "fellini", min: "vorrumu" }, { en: "fenian", min: "vomuam" }, { en: "ferdinand", min: "voltumamt" }, { en: "ferguson", min: "volgizem" }, { en: "fermat", min: "volnad" }, { en: "fermi", min: "volnu" }, { en: "fernandez", min: "volmamtos" }, { en: "fernando", min: "volmamte" }, { en: "ferrari", min: "vollalu" },
  { en: "ferraro", min: "vollale" }, { en: "ferrell", min: "vollorr" }, { en: "feynman", min: "voymnam" }, { en: "fez", min: "vos" }, { en: "fiat", min: "vuad" }, { en: "fibonacci", min: "vupemakku" }, { en: "fichte", min: "vukhdo" }, { en: "fidel", min: "vutor" }, { en: "fido", min: "vute" }, { en: "figaro", min: "vugale" },
  { en: "figueroa", min: "vugiolea" }, { en: "fijian", min: "vuquam" }, { en: "filipino", min: "vurubume" }, { en: "fillmore", min: "vurrnelo" }, { en: "filofax", min: "vurevax" }, { en: "finch", min: "vumkh" }, { en: "finn", min: "vumm" }, { en: "finnegan", min: "vummogam" }, { en: "firebase", min: "vulopazo" }, { en: "firefox", min: "vulovex" },
  { en: "firestone", min: "vulozdemo" }, { en: "fisk", min: "vuzc" }, { en: "fitch", min: "vudkh" }, { en: "fitchburg", min: "vudkhpilg" }, { en: "fitzgerald", min: "vudsgolart" }, { en: "fizeau", min: "vusoai" }, { en: "fla", min: "vra" }, { en: "flagstaff", min: "vragzdavv" }, { en: "flanagan", min: "vramagam" }, { en: "flatt", min: "vradd" },
  { en: "flaubert", min: "vraipold" }, { en: "flint", min: "vrumd" }, { en: "florentine", min: "vrelomdumo" }, { en: "floridan", min: "vrelutam" }, { en: "florine", min: "vrelumo" }, { en: "florsheim", min: "vrelzhoun" }, { en: "floyd", min: "vreyt" }, { en: "flynn", min: "vrymm" }, { en: "foch", min: "vekh" }, { en: "folsom", min: "verzen" },
  { en: "fomalhaut", min: "venarhaid" }, { en: "fonda", min: "vemta" }, { en: "foosball", min: "veezparr" }, { en: "foreman", min: "velonam" }, { en: "formica", min: "velnuka" }, { en: "formosa", min: "velneza" }, { en: "formosan", min: "velnezam" }, { en: "fortaleza", min: "veldarosa" }, { en: "fosse", min: "vezzo" }, { en: "fotomat", min: "vedenad" },
  { en: "foucault", min: "veikaird" }, { en: "fourneyron", min: "veilmoylem" }, { en: "fox", min: "vex" }, { en: "fragonard", min: "vlagemalt" }, { en: "franciscan", min: "vlamkuzkam" }, { en: "francisco", min: "vlamkuzke" }, { en: "franck", min: "vlamkc" }, { en: "franco", min: "vlamke" }, { en: "frankel", min: "vlamcor" }, { en: "frankfort", min: "vlamcveld" },
];
